### ISSUE TITLE
漫画那个的access_key是怎么弄得？

### ISSUE THREAD

**Issue by niuqudechongdong** [happy888888/BiliExp#1]
大佬，想问一下，漫画的那些access_key参数怎么得到，只有你这里看到有bilibili漫画的自动签到的代码，别的地方都没有找到类似的b站自动签到代码，如果能详细一点还是很多人需要的。但我不懂手机抓包这些，所以可以说的详细一些吗。毕竟漫画一周能白嫖两张券

**Comment by happy888888** [comment]
以下方法适用于Android7.0以下(不包含)的系统
首先电脑安装fiddler抓包工具，在软件中，工具-->选项-->HTTPS  页面，勾选所有多选框，在 连接 页面勾选允许远程计算机连接
安卓手机首先跟电脑处于同一个wifi下，在安卓手机手机上的wifi页面上长按连接的wifi名字，点击修改网络，显示高级选项，把代理设置改为手动，服务器地址写电脑的内网ip地址，服务器端口填8888。然后打开浏览器，输入"http://电脑的内网ip地址:8888"，点击"FiddlerRoot certificate"，下载证书；进入手机设置，搜索"加密与凭据"，点击“从设备安装”，安装刚才下载的证书。最后进入进入漫画app，在登录状态下随便刷新一下，就可以在电脑fiddler中的左边看到app的数据包，找到/twirp/card.v1.Card/GetUserCardInfo这个地址并点击，在软件右边点"检查器"，"RAW"，然后下面就有"access_key=xxxxxxx&appkey=xxxxxxxxx&build=xxxxxxx"字段了，第一个xxxxxxx指的就是access_key的值。

在Android7.0以及以上的系统中，系统默认不信任用户自己安装的证书，需要把证书手动安装的系统目录下，非root权限不可以访问系统目录，故上述方法失效。

**Comment by niuqudechongdong** [comment]
蟹蟹大佬，看来是没希望了，我的安卓版本已经是8.1了，不过还是蟹蟹大佬的耐心解答

**Comment by niuqudechongdong** [comment]
对了，为什么我手机Wifi修改代理后，会连不了网，就是设置代理为手动后，就连不了网了

**Comment by happy888888** [comment]
1.没有成功安装证书，那么所有https连接都会失效，app几乎都用的https协议与服务器通信，我们抓包也是https的，安卓版本8.1只能root后将证书安装到系统目录才会生效。
2.代理的ip地址或者端口号错了，手机流量并没有成功转发到电脑的fiddler软件上，也会上不了网

如果不能root的话可以试试VirtualXposed这个模拟Xposed框架的软件，配合JustTrustMe插件跳过ssl证书的认证，然后把软件装到VirtualXposed软件内就可以抓包了，不过装到VirtualXposed下的软件和直接装系统内的软件数据是不互通的，部分软件还有闪退的现象。如果能root是最好的

**Comment by niuqudechongdong** [comment]
谢谢大佬，我已经弄好了。应该是手机版本较高的原因

**Comment by niuqudechongdong** [comment]
他这个access_key大概是多久就会更新？还是永久的？

**Comment by happy888888** [comment]
只要手机app不退出就是永久的，一旦退出或者再次登录就会失效

**Comment by niuqudechongdong** [comment]
好的，谢谢大佬。这里面有没有模拟直播观看时长的？就是观看直播能得到银瓜子，银瓜子每天能换成一个硬币。那个每天自动投币的那三个参数是多久过期的？别人用cookie的好像是一段时间后就会失效。

**Comment by happy888888** [comment]
你说的是直播中的时间宝箱吗，B站靠定时发送心跳包判断用户是否在线，但网页版直播领取时间宝箱的银瓜子需要回答一道数学题，我还不会用python自动答题；至于手机版的直播我还没有试过(手机好像不用答题)。
cookie目前有效期是5个月，你用浏览器登录B站后，cookie只要不失效，浏览器的登录状态是一直在的，如果有一天B站让你重新登录，那就说明cookie失效了(这里cookie指SESSDATA和bili_jct这两个参数，DedeUserID虽然也会失效，但它的值等于账户的uid，相当于身份证号是唯一且不会改变的，所以失效一般指前两个参数失效)；手机端也是一样的，只要没有让你重新登录，那么登录状态就是有效的，让你重新登录，就说明登录失效了，目前还不知道app登录状态的有效期有多长。

**Comment by niuqudechongdong** [comment]
对，应该是时间宝箱。我之前是用电脑的网页端看b站直播，每隔3，6，9分钟有银瓜子领，我之前是用一个google插件带领的，我只要打开直播界面，时间到了，插件就会帮你解题领取瓜子(这个插件在github是开源的)，不过，就是每天都要你打开电脑网页端的b站直播界面，不能说是全自动的，感觉很麻烦。
对于常驻后台还是定时运行，我不太懂这些软件的程序，只能说一下我的想法。不过如果你说的常驻后台的是指在本地电脑后台设置开机自启程序的话，我还是偏向于能在腾讯云执行，毕竟电脑不是每天都开机，而且多了开机程序还会变卡。
如果领瓜子功能很难实现的话，就不要弄了，毕竟还是头发重要。

如果你想继续优化程序的话，我觉着可以加一下这些功能:能在参数过期时或者程序出错时，能给微信发个消息。比如，在b站漫画程序中，加入获取用户积分的程序，看程序运行后，今天的积分有没有比昨天的积分高，没有则程序运行错误，可以用service给微信报错。当不能获取用户的积分信息时，则可能是参数过期了，也可以向微信报错(这些我不知道能不能实现)。
最后，谢谢大佬

**Comment by happy888888** [comment]
目前已经完成定时执行(云函数版)获取银瓜子脚本了，已经更新了，将Biliapi.py和SilverAward.py放在云函数上，启动函数写SilverAward.main就行，用的app版的接口(因为不用答题，目前**没发现**access_key在不主动退出的情况下会失效，应该比电脑的稳定一些)，如果能有python自动答题的办法可能做网页版的接口(你说的插件是油猴的吗)。

常驻指的是脚本一旦打开后就一直在电脑中运行，并且不能结束程序或者关闭电脑，好处是3，6，9分钟时间把握得比较准，云函数有最大运行时长所以不可能常驻。定时运行就是每隔3，6，9分钟执行一次代码，但是云函数的cron很难做到这么定时执行(可以每隔3分钟执行一次，或者每隔1分钟执行一次)，但是因为网络原因时间会积累误差，假如误差积累到脚本刚好在领取时间前1s执行，那么就多浪费一个时间周期，积累下来一天也会少领取很多银瓜子。(腾讯云官方说的最大运行时间900s，不知道为什么我只能运行10多秒就超时了，如果能运行900s那么可以把3，6，9分钟合成一个15分钟当做一个周期来执行)。

云函数还有一个缺点是不能把数据保留(云函数的硬盘只读不可写，可以买持久化的数据服务比如数据库，cors什么的)，所以我那个抽奖脚本就不能在云函数上执行，因为我用了一个数据库文件保存我抽过的奖来防止脚本多次转发同一个抽奖；同理你说的将昨天的积分保留到今天是不可能的(免费的不可能)，也不需要，因为我有做登录状态检测，登录参数失效后日志里面会留下“登录验证id为DedeUserID的账户失败，原因为xxx，跳过此账户后续所有操作"这样的提示提醒你cookie已经失效了。(现在人都不喜欢看日志吗，o(╥﹏╥)o)

微信推送这个功能我还没有想过，还不知道如何实现，学python之前学php的时候学过用邮件推送的，用邮件推送的话倒是不难实现(自己给自己制造垃圾邮件？)。

最后。看了一下你说的Server酱，发现看起来真的简单，接口都封装好了，公众号也是现成的，我还在想需不需要用这个来替代日志，Server酱写的消息记录可以保存一周但是没给获取消息记录的接口，云函数不能保存数据，只有获取消息记录才能避免同样的消息被多次发送(不然access_key失效了每隔3分钟发送一次失效消息那不是刷屏了吗)。还有自动答题那个应该有现成的接口可以直接拿来用的，如果是油猴的插件拿到js代码就能看出插件调用的接口，crx的插件就只能反编译(我不会o(╥﹏╥)o)或者抓包了。

**Comment by niuqudechongdong** [comment]
那个插件叫做BILIBILI HELPER，在谷歌的网上应用店就能下载，哔哩哔哩助手官网已经更新为：https://bilibili-helper.github.io/，忘记了这个插件还有每天自动把银瓜子换成硬币。（毕竟用你的自动投硬币的程序，硬币很快用完了，所以我之前才问你有没有银瓜子换的，这样每天能登录获得一个硬币+银瓜子兑换），现在如果有获取银瓜子脚本，那么可以加一下自动兑换硬币的功能。
哈哈哈，之前我接触的程序都是很少日志的（可能也是我接触的代码比较少吧，毕竟不是学计算机、代码那些的），我都是直接看软件报错的提醒。

我也是昨天才看到别人的程序，才知道有service酱（可以用service酱来给微信推送消息），他们用Python调用代码（python发送消息脚本）：
import requests
sckey = 'your sckey'#在发送消息页面可以找到
url = 'https://sc.ftqq.com/%s.send?text=程序完成了'%sckey
#text为推送的title,desp为推送的描述
url = 'https://sc.ftqq.com/%s.send?text=程序完成了&desp=好玩吧'%sckey
requests.get(url)

确实，如果不能避免同样的消息被多次发送的话，那一旦程序不能运行，微信刷屏了（service酱获取消息记录的接口我也不知道有没有）。能实现推送消息的还有：1.service酱（有免费额度）。2.pushplus.(没仔细看)
3.望风塔wangfengta.com(要钱的)

**Comment by niuqudechongdong** [comment]
B站客户端access_keys是哪个地址对应下的数据包？

**Comment by happy888888** [comment]
api.live.bilibili.com这个域名下的访问几乎都要access_keys，有access_keys的数据包太多了，随便抓几个就有

**Comment by niuqudechongdong** [comment]
我抓到了，换了一个抓包程序。
在云函数里，获取银瓜子脚本的程序里设置触发器的周期是每3分钟触发一次吗？还是一天一次就行。
这些函数是只能两个放在一起挂在云函数里吗？是当第1个函数+第4个函数实现b漫画签到，第1个+第2个实现自动投币。
不能在云函数里直接把第1个函数+第2个函数+第4个函数放在一起，来实现自动签到和投币是吧？

**Comment by happy888888** [comment]
目前在BiliExp.py脚本中添加了Server酱的消息推送服务
更新了直播获取银瓜子的脚本SilverAward.py，云函数触发器的cron表达式可以参照README.md里写的
增加了银瓜子兑换硬币的脚本silver2coin.py

B站函数模块Biliapi.py和微信推送模块PushMessage.py整理到了models文件夹下面，建议将这个文件夹打包上传到云函数的"层"里面，只要其他函数引用这个层就可以共享这两个文件(“层”功能就是方面多个函数使用相同模块用的，不用每个函数都放相同的东西，方便添加依赖)
BiliExp.py，SilverAward.py，silver2coin.py，mangaClockIn.py这四个脚本都分别新建个python3.6的函数就行(一共四个函数)，直接文件内容复制到新建的云函数的模板内就行(默认有个index.py文件)，然后把启动函数设为index.main保存就行了(参数要先写到脚本里)。
触发器BiliExp.py，silver2coin.py，mangaClockIn.py这三个函数每天执行一次就行，SilverAward.py这个函数需要自定义cron表达式，参见README.md里写的

**Comment by happy888888** [comment]
BiliExp.py，silver2coin.py，mangaClockIn.py这三个脚本都是每天执行一次，其实可以都复制到同一个脚本内一起执行的，除了main函数其他函数都可以放在一个文件里面，只要修改一下main函数就可以实现一个脚本执行三个脚本的功能了，我分开是因为不一定每个人都同时需要这些功能，同时也方便自己看起来舒服点，我也是新手，不怎么会码代码哈，只是为了练练抓包而已，代码多了就看着头大。

**Comment by niuqudechongdong** [comment]
好的，谢谢大佬。
一键抽奖的只能放在本地后台运行。
这个BiliExp程序有判断三个参数有没失效的功能，那B漫签到有能判断Assess_key失效的函数吗？b漫签到的那个程序，好像参数过期了也能正常执行，不会报错。

**Comment by happy888888** [comment]
日志保留有每次签到的信息，每次执行成功或者失败的原因都有，有日志就能定位大部分问题。云函数一旦报错，可能就不会记录日志了，不方便定位错误位置，必须要避免云函数的直接报错。

漫画签到的脚本结构和逻辑比较简单，每次日志就一行，签到成功还是失败一眼能看出来的，你可以用正确的access key运行一次在用错误的运行一次，或者一天签到两次，运行结果从日志就能明显看出来不一样。

如果每天都要用app的话access key失效了也能及时发现，目前还没发现失效的情况，感觉不需要每天微信推送。如果你发现经常失效的话我也可以把微信推送的功能加在漫画签到的脚本里。

**Comment by niuqudechongdong** [comment]
为什么经验脚本那个程序，测试时会发送两条信息到微信，今天自动运行时，会发送3条信息到微信？第二条信息里面的内容有重复的（里面的内容有两个直播签到那些），正常的话，不是一条信息吗？
其实，我觉得如果程序能自动运行的话（参数那些没有失效），应该不需要向微信发送信息，不然，能正常运行的话，发送的信息你也不会点开看（也不太需要点开看），而且时间久了，就会想公众号消息免打扰。我觉得只有当参数失效了，或者遇到其他问题，需要你去腾讯云函数里改一下脚本时，才需要发个消息提醒你。不过，可能也有人希望每天都能看到运行结果的，哈哈哈。
如果不麻烦的话，可以在漫画脚本里加一下，当assess_key参数失效时，或者遇到其他问题时，能向微信推送一下消息吗？这样可以提醒我们去改一下参数那些。（可能有些人是用老版本的手机来抓包的，这样的话，就不会很经常打开老版本手机上的APP，这样在腾讯云上参数失效你也不知道）
谢谢大佬，感觉你好有耐心O(∩_∩)O

**Comment by niuqudechongdong** [comment]
对了，动态抽奖的那个脚本是不是只能在本地win计划运行，不能放在腾讯云函数里？但是本地win的触发器的最小时间间隔不是只能设置为每天吗？怎么能设成每隔10分钟运行。

**Comment by happy888888** [comment]
没有遇到你说的问题，经验脚本那个程序不管是单账户还是多账户每运行一次只会发送一条消息，你在日志里看看是不是同一时间运行了两次。

目前推送的消息有直播签到，视频的观看和分享，脚本执行前后硬币数量等，推送目的除了判断用户登录状态是否有效外，还有判断B站接口是否有效。日志的话可以调节日志记录的等级来区分一般消息，警告消息，错误消息等，微信推送要确定发送哪一类消息的话就要自己实现消息内容分级了(可以通过参数调节具体推送的消息??)。

win计划任务里面创建基本任务确实最短间隔为每天执行，但是创建后可以在任务的右键--属性--触发器--新建--高级设置下面的重复任务间隔和时间设置，在这里就可以实现每隔10分钟运行，持续1天，然后每天执行就相当于每隔10分钟运行一次了。我一般是挂在linux crontab下面跑的，crontab配置文件添加一行 */10 * * * * /etc/Sign/BiliLottery.py 再重启cron进程就行(脚本放在/etc/Sign文件夹下)。

抽奖那个脚本我已经写好不需要数据库版本的了(就是说可以云函数执行)，目前正在测试还没有提交。

**Comment by niuqudechongdong** [comment]
好像是运行了好几次，运行时间是1500多ms，不知道为什么持续了那么长，现在是不是要在腾讯云函数的函数配置那里修改一下超时时间?（我现在设置的是3s）

好的，那我研究一下，怎么在用户登录状态失效和B站接口失效时才推送信息。O(∩_∩)O

**Comment by happy888888** [comment]
我将所有的脚本用户登录信息单独放到了userData文件夹下的userData.py文件中，并在这个文件夹下添加了check.py脚本单独用来检查所有用户信息是否失效，只有至少一个用户信息失效了才会推送微信消息，云函数上每天执行一次check.py就行。

抽奖脚本取消了用数据库保存转发信息，可以用于云函数运行。

不知道为什么我现在腾讯云函数进去就强制要我实名，我转用阿里云函数了。

**Comment by niuqudechongdong** [comment]
腾讯云函数我昨天也是强制实名，实名有什么害处吗？害怕，看来我也要转了

**Comment by niuqudechongdong** [comment]
为什么我在阿里云里开通函数计算（这个应该是云函数）时，也要我实名验证，不然不给开通云函数功能

**Comment by happy888888** [comment]
不知道，我支付宝账号登陆的，没有让我实名，可能支付宝已经是实名的吧。
腾讯云我是微信登录的，明明微信是实名的不知道为什么还要我实名。

**Comment by niuqudechongdong** [comment]
大佬，能问一下，为什么在云函数里不用最后一行main()？这一行不是启动函数的吗？其他行都是定义函数的类？可能我之前微信一次推送两条信息就跟这个有关。

**Comment by niuqudechongdong** [comment]
大佬，你知道为什么在云函数最后一行不用main()吗？

**Comment by happy888888** [comment]
main()是用来调用def main(*args)这个方法的，云函数会自己调用main方法并传一些参数进去，不需要再调用main方法了，python的执行顺序是从上到下，遇到xxx=xxx就是定义了变量，遇到def 就是定义方法(函数)，遇到方法名加括号就是执行方法，云函数会自己执行main方法，所以前面才要填写一个BiliExp.main，就是让云函数调用BiliExp文件的main方法作为脚本的入口

**Comment by niuqudechongdong** [comment]
哦，原来是main(*args)这个方法，明白了，谢谢大佬

**Comment by niuqudechongdong** [comment]
想问一下，为什么youtube下载的视频好像是没有声音的。
上传到B站时也会出错，因为下载时，命名（/@等等）会直接忽略，这样就会导致上传的名字与下载的视频的名字对不上，会报错。

**Comment by happy888888** [comment]
默认视频流可能是不带音频的，一共有多少的视频流可以用print(video.streams)打印出来，或者直接用video.streams.get_by_itag(22).download()下载，22指的是720p 30hz 带音频的mp4视频(如果youtube视频本身就没有这个格式会出错)

下载文件的命名是pytube库进行命名的，我并不知道下载的文件名是什么，直接把video.title(video.title是pytube库解析youtube视频的标题)加上mp4后缀当做文件名，video.title也当做上传到B站的标题。pytube库可能对特殊字符进行了转义，pytube库的使用方法可以参照官方文档，我做的部分只是提供一个用来发布视频和专栏的库而已，主要是让别人二次开发用的，我只是提供一个使用的例子而已。

我不知道pytube库怎么修改下载文件名，如果可以的话可以改成下载时用一个随机文件名来保存，上传后把标题设置为video.title就行了，视频文件的名字不重要(上传到B站后也会变成纯数字的随机文件名)

如果可以的话也可以把你下载视频的链接给我看一下

**Comment by niuqudechongdong** [comment]
昨天我只是测试一下，链接：https://www.youtube.com/watch?v=Rr63xigwPMM
下载下来是没有声音的，下载的命名为：UK Has Socially Distanced Concerts & Trump Battles Showerheads  The Daily Social Distancing Show.mp4
但上传时是（命令行显示的）：
     开始下载youtube视频
     开始将U.K. Has Socially Distanced Concerts & Trump Battles Showerheads | The Daily Social Distancing Show.mp4上传至B 
     站，请耐心等待
所以，两个名字对不上，下载下来的视频没有特殊字符：|

**Comment by happy888888** [comment]
目前把文件名不同步的问题解决了，下载的视频流改为手动选择来避免下载到没有音频的视频，B站发布标题改为手动输入(默认为文件名)，tag和视频分区也改为手动输入

**Comment by niuqudechongdong** [comment]
好的，谢谢大佬

**Comment by niuqudechongdong** [comment]
大佬，我看了下，下载的视频还是没有声音。看了下网上的介绍，他们说1080P的是音频分开的，但我下载的480p的也是没有声音，好像现在全部都是音频跟视频分开了。网上别人用的方法是youtube-dl+ffmpeg来下载和合并音频。

**Comment by happy888888** [comment]
选择有acodec字段的视频就是有声音的，当然视频和音频可以分开下再合并，moviepy库就是封装的ffmpeg进行视频处理，我也用来进行图片和音频转单一背景视频过，视频和音频合并当然没问题，不过默认没有GPU加速所以速度感人。总之下载有声音的视频选择有acodec和type="video"的流就行。确实高分辨率的视频音频和视频是分开的，我还没找到效率比较高的一键下载合并的用python实现的方法。
只想下载youtube视频的话现成的Gihosoft TubeGet下载器倒是挺好用的，下载的视频都是带音频的还可以顺便下载机翻字幕，网上也有破解版的可以下载1080P。

**Comment by niuqudechongdong** [comment]
好的，谢谢大佬

**Comment by niuqudechongdong** [comment]
想问一下，如果是用苹果系统的客户端获取的assess_key，是要改一下Biliapi.py中（下面这一部分）的即  def __init__(self, access_key, platform="android"):）中的“android”吗？是把它改成ios?


class BiliAppApi(object):
    "B站app的api接口"
    __headers = {
            "User-Agent": "Mozilla/5.0 BiliDroid/6.4.0 (bbcallen@gmail.com) os/android",
            }
    def __init__(self, access_key, platform="android"):
        "初始化app操作类,B站客户端和漫画客户端通用一个access_key"
        self.__access_key = access_key
        self.__platform = platform
        if not self.isValid(access_key, platform):
            raise Exception("参数验证失败，登录状态失效")

**Comment by happy888888** [comment]
说实话这个我也想知道，可惜我没有苹果手机，拿不到数据。

这些接口并不是官方提供的，没有详细的说明文档，实际上这些接口需要的参数远不止access_key和platform两个，只是经过测试这两个参数是必须的，使用尽量少的参数也避免了参数泄露，毕竟只有access_key操作权限极低，连账号的昵称都拿不到。

猜想的话platform这个参数只是官方用来统计不同平台的使用人数的，应该没做过多的验证，苹果的access_key说不定也能直接用，但是我目前没办法证实这个猜想。

要替换platform参数也不能直接在Biliapi.py里改，应该在mangaClockIn.py等用到BiliAppApi(access_key)的地方加参数，比如BiliAppApi(access_key, "android")这样，只是在不提供第二个参数的情况下默认第二个参数是"android"，把Biliapi.py改了相当于在不提供第二个参数时默认第二个参数是"ios"了，实际上这个参数应该在调用biliapi = BiliAppApi(access_key)时提供

**Comment by niuqudechongdong** [comment]
好的，我明白了，谢谢。
一般查一些APP的接口是在哪里查的，也是在github吗？（之前我就很好奇）

**Comment by happy888888** [comment]
用Fiddler抓包分析网站或者app访问了哪些地址，发了哪些数据，收到了哪些数据，再自己构造符合规则的数据提交就行了。就是因为接口不是现成的才要自己去找啊。github上确实也有人收集了一些网站的接口的，但是没有的就得自己找了

**Comment by niuqudechongdong** [comment]
好的，明白了。

**Comment by niuqudechongdong** [comment]
大佬，想问一下，可以增加一下Bilibili漫画每月自动领取大会员的10个劵吗？

还有没有自动领取5个B币，以及每月自动把领到的5B币投到站友日活动得到15个券？（有可能站友日活动的链接每月都是不同的，所以有很能实现不了这个功能）。

以及可以实现自动购买漫画吗？比如每周自动签到得到的券，可能一周没上B漫（或者更久），就过期了。（还有每月固定多出来的漫券也希望可以去补一些漫画）

**Comment by happy888888** [comment]
可以试试，但是这个功能测试起来可就麻烦了，毕竟一个月就一次机会。

**Comment by niuqudechongdong** [comment]
这确实是个问题吗，每月只有一次尝试的机会

**Comment by happy888888** [comment]
购买漫画的接口已经实现了，关键是购买逻辑，每次执行要购买哪些漫画？每次执行搜索账号的追漫列表吗，是把劵均匀分布到追漫列表里的漫画还是有优先级这些都是问题。

还有这个issues太长了，我觉得可以另开一个，看着有点费劲了。
