### ISSUE TITLE
Frok后没有Actions

### ISSUE THREAD

**Issue by 2498966969** [happy888888/BiliExp#10]
![QQ截图20200829205021](https://user-images.githubusercontent.com/57282666/91637338-50a1b880-ea3a-11ea-946c-f0e0612a923f.png)
如图，今天上午Fork的，晚上弄的时候没有Actions

**Comment by happy888888** [comment]
"New workflow" -》 "set up a workflow yourself" -》 在输入框里把/.github/workflows/deploy_for_aliyun.yml文件里面的内容原封不动地粘贴进去，然后点右上的绿色按钮"Start commit"提交

github fork后并不能直接使用源项目的workflow actions，但文件还在，你照上面的方法新建一个workflow就行

**Comment by 2498966969** [comment]
良心作者




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "星辰"<notifications@github.com&gt;; 
发送时间: 2020年8月29日(星期六) 晚上11:53
收件人: "happy888888/BiliExp"<BiliExp@noreply.github.com&gt;; 
抄送: " "<2498966969@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [happy888888/BiliExp] Frok后没有Actions (#10)





 
"New workflow" -》 "set up a workflow yourself" -》 在输入框里把/.github/workflows/deploy_for_aliyun.yml文件里面的内容原封不动地粘贴进去，然后点右上的绿色按钮"Start commit"提交
 
github fork后并不能直接使用源项目的workflow actions，但文件还在，你照上面的方法新建一个workflow就行
