### ISSUE TITLE
收到了B站的风控警告，有出现一样情况的吗

### ISSUE THREAD

**Issue by BlueTea3** [happy888888/BiliExp#102]
账号安全通知
系统检测到您的账号有异常使用，建议及时更改密码，确保账号安全。
若有使用第三方工具，请立即停止使用。
恶意使用第三方工具造成数据安全问题，将导致账号封停。

**Comment by BlueTea3** [comment]
![屏幕截图 2020-12-01 193204](https://user-images.githubusercontent.com/61354802/100735574-672a2800-340c-11eb-8ef0-3befd351d303.jpg)

**Comment by happy888888** [comment]
我4个三级号，2个四级号(其中一个是我的up主账号)，1个五级号(年度大会员)都没有收到这个消息

**Comment by BlueTea3** [comment]
哦哦，我之前用的是另一个项目，最近几天才转用这个项目的，可能是之前项目的问题

**Comment by happy888888** [comment]
先置顶，看看其他人有无发现这个情况

**Comment by stockce** [comment]
同样收到消息，我今天才部署，腾讯云还报错呢   我也是之前使用其他的项目提示的  不是本项目

**Comment by happy888888** [comment]
1. 此类情况无法复现
2. 目前此类情况波及范围小(并没有更多人提供更多消息)
3. 没有直接或间接表明此类情况由本项目导致
4. 无法明确定位原因

综上所述，认定本类情况为个别极端情况而不做更多处理，如果使用本项目期间出现这种情况，请立即停止使用。同时我会使用更多账号对本项目进行测试，观察是否出现类似情况，然后再做处理，目前先关闭此issue

本人使用状态一切正常，23个账号包括2-5级，大会员账号，up主账号，抽奖工具号等均未发现有B站封禁迹象(近一个月)，后期会继续追踪此类问题。

**Comment by if1y** [comment]
两个号，同类工具长期使用未出现报警。
之前辣条还在的时候有经常被列入风控的情况，不知道是后来辣条没有了导致解除报警，还是说长期使用就不认为风控了。
