### ISSUE TITLE
在腾讯云函数运行出现异常

### ISSUE THREAD

**Issue by 2498966969** [happy888888/BiliExp#103]
![45d0e08268c713d478af29e764da6648](https://user-images.githubusercontent.com/57282666/100746428-a744d700-341b-11eb-9a88-42a2f590d1a7.png)
![575a2c59f08f49060f090e3a24ec4745](https://user-images.githubusercontent.com/57282666/100746420-a449e680-341b-11eb-9afe-2c430a175fd4.png)
如图，腾讯云运行报错

**Comment by happy888888** [comment]
配置文件有问题，检查是否把配置文件格式改错了

**Comment by stockce** [comment]
遇到同样的问题

**Comment by stockce** [comment]
START RequestId: b976681d-0960-4df8-87d2-5ec45e58563a

Event RequestId: b976681d-0960-4df8-87d2-5ec45e58563a

配置加载异常，原因为Expecting ',' delimiter: line 159 column 27 (char 3921)，退出程序

 

ERROR RequestId:b976681d-0960-4df8-87d2-5ec45e58563a Result:{"errorCode":-1,"errorMessage":"User process exit when running"} 

END RequestId: b976681d-0960-4df8-87d2-5ec45e58563a

Report RequestId: b976681d-0960-4df8-87d2-5ec45e58563a Duration:40ms Memory:128MB MemUsage:30.351562MB

**Comment by happy888888** [comment]
你们部署后改过config/config.json文件吗

**Comment by stockce** [comment]
> 你们部署后改过config/config.json文件吗

没有动过。name为”biliconfig” value为B站账号登录信息，格式参照config/config.json文件是不是这个错了。


{
     "cookieDatas":[
		{
			"SESSDATA": "",
			"bili_jct": "",
			"DedeUserID": ""
		}
	],
	"email": "",
	"SCKEY": "",
	"说明":"cookieDatas由浏览器获取，获取详情见首页说明；email用于邮件消息推送，SCKEY用于微信消息推送，详情见http://sc.ftqq.com/，这两项不用请留空"
}
按照这个格式填写的

**Comment by happy888888** [comment]
按这个格式，那个格式是好几个月以前的了
![](https://user-images.githubusercontent.com/67217225/95849036-77654580-0d81-11eb-8125-9adcd23ec25a.png)

**Comment by happy888888** [comment]
直接放
```
SESSDATA
bili_jct
uid
```

**Comment by 2498966969** [comment]
sckey怎么添加，同问

**Comment by happy888888** [comment]
![image](https://user-images.githubusercontent.com/67217225/100750940-ad3db680-3421-11eb-9a78-3544393e833f.png)

**Comment by happy888888** [comment]
云函数里有config/config.json文件里面有更详细的配置，在那里填写sckey，也可以进行其他配置，看上图

**Comment by happy888888** [comment]
![image](https://user-images.githubusercontent.com/67217225/100752677-d4958300-3423-11eb-93fc-3376b4e754cb.png)
