### ISSUE TITLE
机器人up主 创建稿件失败

### ISSUE THREAD

**Issue by speaknowpotato** [happy888888/BiliExp#104]
我使用了
https://github.com/happy888888/BiliExp/blob/master/%E6%9C%BA%E5%99%A8%E4%BA%BAup%E4%B8%BB/youtube%E8%A7%86%E9%A2%91%E6%90%AC%E8%BF%90%E5%B7%A5.py
中的视频上传代码，
运行了几次之后发现，有些视频上传没有问题，有些视频会显示如下的error code。

**上传完成,即将发布，请等待最多30s
{'code': 21015, 'message': '第(1)个视频可能上传过程出现问题，导致创建稿件失败，建议重新上传', 'ttl': 1}**

重复试了几次之后，也还是不行。
手动通过bilibili官网上传是没有问题的。

有大佬可以解答下，为啥会出这个错误吗？

感谢。

**Comment by happy888888** [comment]
能否提供一下视频，暂时无法重现这个问题

**Comment by speaknowpotato** [comment]
google drive可以吗？

**Comment by happy888888** [comment]
可以的

**Comment by speaknowpotato** [comment]
https://drive.google.com/file/d/1lR543IJfgLpBUFirrmZnmtzcXjFbIcUq/view?usp=sharing
另外补充一个信息，我在美国，不知道有没有影响。
但是有些视频是可以上传成功的。
谢谢大佬！

**Comment by happy888888** [comment]
更新一下[BiliClient/Video.py](https://github.com/happy888888/BiliExp/blob/master/BiliClient/Video.py) 这个文件，然后重新运行视频上传

**Comment by speaknowpotato** [comment]
正在重新上传中，不知道为啥速度这么慢，这个100多m的视频，传了半小多小时还没完成。

**Comment by happy888888** [comment]
B站在国外没有cdn所以上传速度慢，国内单线程上传就可以达到满速，嫌慢可以尝试把
第20行的`vd = bilivideo.uploadFileOneThread(filename)` 改为 `vd = bilivideo.uploadFile(filename, ThreadNum=3)` 使用三线程上传，浏览器默认使用的三线程上传

**Comment by speaknowpotato** [comment]
好的，我试试，谢谢大佬！

**Comment by speaknowpotato** [comment]
验证成功。修改了rname之后，可以成功上传视频。
另外我还发现一个typo error，这里面的splitext多了一个t。
https://github.com/happy888888/BiliExp/blob/master/BiliClient/Video.py#L161

**Comment by happy888888** [comment]
> 验证成功。修改了rname之后，可以成功上传视频。谢谢大佬！
> 另外我还发现一个typo error，这里面的splitext多了一个t。
> https://github.com/happy888888/BiliExp/blob/master/BiliClient/Video.py#L161

感谢指正，视频封面只需要提供一个url就行，但网址必须是站内的，更建议用专栏Article类里的图片上传方法，浏览器上传视频封面的时候默认对图片进行了一次压缩(甚至有裁剪)，我这个图片上传方法只能上传原图
