### ISSUE TITLE
如何让server酱反馈更多的消息

### ISSUE THREAD

**Issue by stockce** [happy888888/BiliExp#105]
B站经验脚本消息推送
明晚一定会早睡:直播签到失败

明晚一定会早睡:瓜子转硬币失败

目前推送只有这么多消息，如何设置反馈全部信息，比如投币信息，是否观看视频

**Comment by happy888888** [comment]
默认推送简化消息，即不出错不推送，推送完整消息如下设置


![image](https://user-images.githubusercontent.com/67217225/100957731-f98a1300-3555-11eb-82b6-98cbdc311ab6.png)

**Comment by happy888888** [comment]
本项目支持多账号，当同时执行大量账号任务时，完整日志消息的量会很大，故默认只推送简化消息，也可通过上图设置推送完整日志消息

**Comment by happy888888** [comment]
每次运行的完整日志也可通过如下方式查看
![image](https://user-images.githubusercontent.com/67217225/100958303-1246f880-3557-11eb-8a87-4154f9dd5aec.png)

**Comment by happy888888** [comment]
![image](https://user-images.githubusercontent.com/67217225/100958723-cfd1eb80-3557-11eb-9736-137d7a1b42f7.png)
