### ISSUE TITLE
可以做一个自动发布p站图片到哔哩专栏的腾讯云函数或者action脚本吗?

### ISSUE THREAD

**Issue by FairyWorld** [happy888888/BiliExp#108]
可以做一个自动发布p站图片到哔哩专栏的腾讯云函数或者action脚本吗? 手动执行太累了

**Comment by FairyWorld** [comment]
反馈一个问题, 每日一图专栏脚本执行出错, 我把读取config改成了直接输入cookie，和替换了p站的cookie, 其他代码没有动. 第一次执行太久没有反应, 我ctrl+c终止了, 但是好像成功了, 成功生成草稿(内容不知道有没有, 没有进去看), 然后删掉草稿后, 重新执行了4次, 正常执行没有手动终止, 显示错误如图
![image](https://user-images.githubusercontent.com/32956212/101274651-ec318a80-37da-11eb-827a-97393bff61ef.png)

**Comment by happy888888** [comment]
国内访问不了P站所以会卡住

看图上错误是ssl验证失败导致的，如果多次出现就只有关闭ssl验证了

**Comment by FairyWorld** [comment]
> 国内访问不了P站所以会卡住
> 
> 看图上错误是ssl验证失败导致的，如果多次出现就只有关闭ssl验证了
我都是开着全局小飞机运行的，网页版可以直接上p站，命令行应该也能上吧

**Comment by happy888888** [comment]
那ssl验证失败这个错误很可能是shadowsocksR造成的

**Comment by FairyWorld** [comment]
> 那ssl验证失败这个错误很可能是shadowsocksR造成的

这个用该就是fq的原因，我把图片接口改成必应图片就可以用了

**Comment by FairyWorld** [comment]
大佬，可以帮我看下腾讯云函数这段报错怎么解决吗? 我在腾讯云函数使用py3.6的环境的hello world的函数格式模板，改了下入口文件名和包了一层函数名: def main_handler(event, context), 并且在本地执行成功了。但是把项目和依赖上传的云函数就像是下面的错误，不知道怎么解决

{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 4, in \u003cmodule\u003e\n    from BiliClient import Article\n  File \"/var/user/BiliClient/__init__.py\", line 4, in \u003cmodule\u003e\n    from .asyncBiliApi import asyncBiliApi as asyncbili\n  File \"/var/user/BiliClient/asyncBiliApi.py\", line 2, in \u003cmodule\u003e\n    from aiohttp import ClientSession\n  File \"/var/user/aiohttp/__init__.py\", line 5, in \u003cmodule\u003e\n    from . import hdrs as hdrs\n  File \"/var/user/aiohttp/hdrs.py\", line 6, in \u003cmodule\u003e\n    from multidict import istr\nModuleNotFoundError: No module named 'multidict'"}

日志:

START RequestId: 5c0ec5e2-dc65-4405-b0da-9b9998e8f2df

Event RequestId: 5c0ec5e2-dc65-4405-b0da-9b9998e8f2df

 

ERROR RequestId:5c0ec5e2-dc65-4405-b0da-9b9998e8f2df Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 4, in \u003cmodule\u003e\n    from BiliClient import Article\n  File \"/var/user/BiliClient/__init__.py\", line 4, in \u003cmodule\u003e\n    from .asyncBiliApi import asyncBiliApi as asyncbili\n  File \"/var/user/BiliClient/asyncBiliApi.py\", line 2, in \u003cmodule\u003e\n    from aiohttp import ClientSession\n  File \"/var/user/aiohttp/__init__.py\", line 5, in \u003cmodule\u003e\n    from . import hdrs as hdrs\n  File \"/var/user/aiohttp/hdrs.py\", line 6, in \u003cmodule\u003e\n    from multidict import istr\nModuleNotFoundError: No module named 'multidict'"} 

END RequestId: 5c0ec5e2-dc65-4405-b0da-9b9998e8f2df

Report RequestId: 5c0ec5e2-dc65-4405-b0da-9b9998e8f2df Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by happy888888** [comment]
依赖少了 `multidict`

**Comment by FairyWorld** [comment]
> 依赖少了 `multidict`

终于解决了所有问题, 昨晚解决完multidict后，又出现 idna_ssl 模块找不到的现象
好像是 `pipreqs ./ --encoding=utf-8` 命令生成的依赖列表不全导致的
后来通过 `pip freeze > requirements.txt` 生成依赖文件列表就可以了.
每日一图模板的` ret = article.articleUpcover(res.content)`, 好像哔站做了限制, 频繁上传会报错, 我网上查了下用time.sleep(1)可以解决

**Comment by happy888888** [comment]
我这里还没发现过频繁上传图片会报错的情况

如果要使用Actions执行的话，在`.github/workflows/run_BiliExp.yml`文件把
```
      run: python3 BiliExp.py
```
改为
```
      run: |
          python3 BiliExp.py
          python3 './机器人up主/“每日美图”专栏发表机器人.py'
```
这样就会执行两个了

**Comment by FairyWorld** [comment]
> 我这里还没发现过频繁上传图片会报错的情况
> 
> 如果要使用Actions执行的话，在`.github/workflows/run_BiliExp.yml`文件把
> 
> ```
>       run: python3 BiliExp.py
> ```
> 
> 改为
> 
> ```
>       run: |
>           python3 BiliExp.py
>           python3 './机器人up主/“每日美图”专栏发表机器人.py'
> ```
> 
> 这样就会执行两个了，注意对齐缩进，空格一个也不能少

大佬可以帮我看下: https://github.com/FairyWorld/BiliBot 我这个有什么问题吗?
![image](https://user-images.githubusercontent.com/32956212/101333867-199d3780-38b2-11eb-8575-654fbe25080a.png)
今天尝试了很多次都不行, 腾讯云函数和本地是可以运行成功的, 只有action不行
1. 如果和BiliExp-action分支一起运行, uses: actions/checkout@v2 会报错, 所以我弄了个简单版本
2. 删掉步骤一: uses: actions/checkout@v2, 步骤二安装依赖失败, 好像requirements.txt文件不能打开, 不知道什么原因 `Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt`
3. 在本地安装好依赖, 吧依赖和项目一起传到github, 直接 `run: python3 Article.py`, 和上面一样无法打开Bot.py文件
4. `run: |` 后面的 | 有没有写都是打开不了文件, 应该不是这里的语法问题
5. 放到公有和私有仓库还是 `Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt`

**Comment by happy888888** [comment]
uses: actions/checkout@v2
这个是用来把代码下载到actions环境用的，你删了就没有代码了actions还执行什么

**Comment by FairyWorld** [comment]
> uses: actions/checkout@v2
> 这个是用来把代码下载到actions环境用的，你删了就没有代码了actions还执行什么

视频和专栏已上车

**Comment by FairyWorld** [comment]
我想问下我fork你的项目后，master分支怎么自动更新到和你的一样? 
1. 目前用的是BiliExp-Action分支用于跑签到等内容, 在action有个auto_merge的任务可以定时更新BiliExp-Action分支, 但是master分支没有和你的代码同步, 我看到master分支的.github文件夹里有一个pull.yml描述是增加自动同步上游代码, 但是好像没有执行, 现在我的master分支落后你的一个版本
2. 后来我想试一下master的.github文件夹里pull.yml是不是以action的形式执行, 发现切换的master分之后action依旧是BiliExp-Action分支的action. 很久之前的第一次配置漏了一步先切换BiliExp-Action分支再开启action, 结果action是腾讯云和阿里云的任务。当时是删除了仓库重新fork解决的
3. 我想问下有没有办法在不创建两个一样的仓库的情况下，既可以执行master的action又能切换到BiliExp-Action分支的action执行？

**Comment by happy888888** [comment]
1. 默认分支只有一个，只有默认分支的Actions能执行，包括代码同步的actions
2.切换到master分支后BiliExp-Action分支的actions是不可执行的
3.不可能，参见第一条，只能创建另一个仓库

**Comment by FairyWorld** [comment]
> 1. 仓库



> 1. 默认分支只有一个，只有默认分支的Actions能执行，包括代码同步的actions
>    2.切换到master分支后BiliExp-Action分支的actions是不可执行的
>    3.不可能，参见第一条，只能创建另一个仓库

刚刚试了下在setting修改默认分支为master后，在action看到的任务还是BiliExp-Action的两个任务，并没有显示master的任务. 不确定默认分支设置为master后BiliExp-Action的任务会不会执行, 从界面显示来看执行到一半的任务修改默认分支后不会停止执行, 如果执行完了就不确定了

**Comment by happy888888** [comment]
确实还看得到，但是"Run workflow"这个按钮没有了，没办法启动另一个分支的actions，因为master分支根本没有run BiliExp.yml这个文件

**Comment by happy888888** [comment]
目前除了视频和专栏，还支持上传音频稿件了，你是做up主的吗

**Comment by FairyWorld** [comment]
> 目前除了视频和专栏，还支持上传音频稿件了，你是做up主的吗

不算是up, 几年前缺少硬币账号升级太慢了，搬运过一些视频赚硬币升级。后来在掘金看到腾讯云函数的文章好像记得是腾讯官方团队发的文章，就发现了你这个项目的合作者github@tinafangkunding, 然后就过来尝试一下，感觉挺好玩的之前没怎么搞过复杂的服务器部署。
