### ISSUE TITLE
【enhancement】通过server酱向微信推送中奖成功信息，可行吗？

### ISSUE THREAD

**Issue by lance52587** [happy888888/BiliExp#11]

**Comment by happy888888** [comment]
up主抽奖，用的官方的互动抽奖是可行的，非官方的互动抽奖up主口头说谁中谁就中没办法判断抽奖结果，连截至时间都没办法判断。互动抽奖中了一般up主会通知的。

如果是官方的活动抽奖就更不需要通知了，一般最多中几个硬币或者大会员什么的没必要通知。

总结一下就是不论可不可行都没必要。

**Comment by lance52587** [comment]
> up主抽奖，用的官方的互动抽奖是可行的，非官方的互动抽奖up主口头说谁中谁就中没办法判断抽奖结果，连截至时间都没办法判断。互动抽奖中了一般up主会通知的。
> 
> 如果是官方的活动抽奖就更不需要通知了，一般最多中几个硬币或者大会员什么的没必要通知。
> 
> 总结一下就是不论可不可行都没必要。

我发现同一个账号，Chrome上的bili_jct和SESSDATA和edge上的bili_jct和SESSDATA不一样。。。

**Comment by lance52587** [comment]
> up主抽奖，用的官方的互动抽奖是可行的，非官方的互动抽奖up主口头说谁中谁就中没办法判断抽奖结果，连截至时间都没办法判断。互动抽奖中了一般up主会通知的。
> 
> 如果是官方的活动抽奖就更不需要通知了，一般最多中几个硬币或者大会员什么的没必要通知。
> 
> 总结一下就是不论可不可行都没必要。

气死了
edge上的bili_jct和SESSDATA挂了一天没反应
刚换成Chrome上的bili_jct和SESSDATA就有转发
难道是人品问题？

**Comment by happy888888** [comment]
肯定不一样啊，每登录一次就会获得一个bili_jct和SESSDATA，你换个浏览器登录又不一样了。

**Comment by happy888888** [comment]
脚本每天有登录检查的，失效了有server酱推送消息
