### ISSUE TITLE
win32_64版的计划任务bat缺少填写activities.json配置文件

### ISSUE THREAD

**Issue by dtpoi** [happy888888/BiliExp#111]
win32_64版的计划任务"setup_for_windows.bat"因缺少activities.json项
导致计划任务执行时提示找不到activities.json
如图：
![](https://i.loli.net/2020/12/08/XL3brJg48VmxHpn.png)

**Comment by happy888888** [comment]
activities.json路径在config.json里面的

**Comment by happy888888** [comment]
是程序出现报错了吗

**Comment by dtpoi** [comment]
> 是程序出现报错了吗

`[WARNING]: 蛋挞poi: 读取活动列表异常,原因为([Errno 2] No such file or directory: './config/activities.json')`
![notepad++_KRdWbJCaUe.png](https://i.loli.net/2020/12/08/Rwe6rWaqStdPOfC.png)

**Comment by happy888888** [comment]
把配置文件里的`./config/activities.json`改为activities.json文件的实际路径，比如`D:\\BiliExp\\config\\activities.json`(`D:/BiliExp/config/activities.json`)
