### ISSUE TITLE
有没有arm64的docker

### ISSUE THREAD

**Issue by 1525249038** [happy888888/BiliExp#112]
rt

**Comment by happy888888** [comment]
没有，主要是x86平台上没有制作arm的docker镜像的方法，需要有arm环境才行

**Comment by happy888888** [comment]
直接运行`docker run -v /etc/BiliExp:/etc/BiliExp happy888888/biliexp:arm64-latest`就行了
`/etc/BiliExp`是`config.json`配置文件所在文件夹

**Comment by 1525249038** [comment]
> 直接运行`docker run -v /etc/BiliExp:/etc/BiliExp happy888888/biliexp:arm64-latest`就行了
> `/etc/BiliExp`是`config.json`配置文件所在文件夹
standard_init_linux.go:211: exec user process caused "exec format error"
还是不兼容啊

**Comment by happy888888** [comment]
你重新试一下 [镜像地址](https://registry.hub.docker.com/repository/docker/happy888888/biliexp)

**Comment by 1525249038** [comment]
容器运行完成后直接关闭了,然后直播心跳不知道是不是我没搞对，没有在线20多分钟就显示完成了，小心心没领全

**Comment by happy888888** [comment]
> 容器运行完成后直接关闭了,然后直播心跳不知道是不是我没搞对，没有在线20多分钟就显示完成了，小心心没领全

目前容器需要每天定时启动，直播心跳次数和时间可以在配置文件里面修改，把次数num和时间time都修改为120能确保小心心领完

**Comment by happy888888** [comment]
现在提供runner版本docker镜像，每次执行时向github下载代码，支持通过指定参数运行程序的指定版本以及常驻后台不退出和指定运行频率而不需要外部定时执行

```
docker run -d -v /home/user/Biliexp:/BiliExp happy888888/biliexp:runner-arm64-latest -t latest -d -c "0 8 * * *"
```
这样就可以每天8点执行，但是如果docker因为外部原因(手动关闭,断电等)关闭，会每次都下载代码，建议指定版本号而不是用latest
```
docker run -d -v /home/user/Biliexp:/BiliExp happy888888/biliexp:runner-arm64-latest -t 1.1.8 -d -c "0 8 * * *"
```
指定版本号可以缓存代码到挂载的目录
直接执行`docker run -d -v /home/user/Biliexp:/BiliExp happy888888/biliexp:runner-arm64-latest`不带`-d`参数也会运行一次后退出
