### ISSUE TITLE
无法发送直播间弹幕

### ISSUE THREAD

**Issue by 136585816** [happy888888/BiliExp#113]
只有第一次运行时成功发送了弹幕，但是并没有往全部的直播间发送弹幕，之后再运行的话，就一条弹幕也发不出去了

**Comment by 136585816** [comment]
linux和Windows版都试过，弹幕发不出去，日志上也什么都没有显示

**Comment by happy888888** [comment]
[#75](https://github.com/happy888888/BiliExp/issues/75#issuecomment-727501623)
参考这个issue，只有没点亮粉丝牌的直播间会发送消息

**Comment by 136585816** [comment]
好的，感谢
