### ISSUE TITLE
为什么我的脚本会风怒执行

### ISSUE THREAD

**Issue by Shhhhhy** [happy888888/BiliExp#114]
看了crontab配置文件，只有一条定时命令，去掉这条命令不会自动运行，但是加上就风怒执行
具体表现包括但不限于server酱推送两次，转发评论抽奖两次

**Comment by Shhhhhy** [comment]
log文件里基本都是两行连着一样的返回消息

**Comment by happy888888** [comment]
手动执行`BiliExp -c /etc/BiliExp/config.json`会执行两遍吗

**Comment by Shhhhhy** [comment]
不会，只会执行一遍

星辰 <notifications@github.com> 于2020年12月10日周四 下午1:29写道：

**Comment by happy888888** [comment]
你查一下是不是启动了两个crond进程

**Comment by happy888888** [comment]
一般是crontab的配置问题，非本项目问题，无法深入解决

**Comment by Shhhhhy** [comment]
> 你查一下是不是启动了两个crond进程

对的对的，多谢了
