### ISSUE TITLE
本地Linux部署运行报错

### ISSUE THREAD

**Issue by LxDebug** [happy888888/BiliExp#115]
Error loading Python lib '/tmp/_MEI9QeOzf/libpython3.6m.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEI9QeOzf/libpython3.6m.so.1.0)
貌似是glibc版本太低了？但是本人更新不了centos7.6的glibc目前是2.17

**Comment by happy888888** [comment]
确实是glibc的版本问题，我的打包环境glibc的版本太高了在低版本的环境下跑不起来

不建议升级glibc，可以直接安装python3，python3-pip和aiohttp依赖库或者直接使用docker版（集成所有运行环境依赖）

**Comment by LxDebug** [comment]
能不能教教我打包这个项目？十分感谢

**Comment by happy888888** [comment]
安装python3，依赖库aiohttp，打包工具pyinstaller(这个工具打的包不能跨平台，win上打包win上运行，linux-x64上打包linux-x64上运行，macos上打包macos运行)。aiohttp和pyinstaller都用python3-pip安装所以还要先装pip，不推荐使用源码安装

然后下载本项目代码，进入代码目录执行`pyinstaller -F BiliExp.py`就能在`dist`文件夹下生成可执行文件，`-F`参数是打包成单文件，`BiliExp.py`是入口文件

**Comment by LxDebug** [comment]
非常感谢！
