### ISSUE TITLE
未发现有效账户Cookies

### ISSUE THREAD

**Issue by SadPull** [happy888888/BiliExp#117]
secret中填写好了uid bilijct sessdata 是单用户

**Comment by SadPull** [comment]
![Uploading QQ截图20201212131802.png…]()

**Comment by SadPull** [comment]
![QQ截图20201212131802](https://user-images.githubusercontent.com/51036486/101976085-bda12d00-3c7c-11eb-90c9-df72e6900252.png)

**Comment by happy888888** [comment]
三行，每行一个cookie
uid的格式是`纯整数`
bilijct的格式是`31位数字和小写字母`
sessdata的格式是 `8位数字和小写字母`+`%2C`+`10位数字和小写字母`+`%2C`+`5位数字和小写字母`+`*`+`2位数字和小写字母`

**Comment by happy888888** [comment]
例子
```
451154519
cf28bac01cd7d443646907a5c4da8cf1
4a5f1c63%2C1617173721%2Cdf9fc*a1
```

**Comment by SadPull** [comment]
是三十二位吧？不过我这边重新获取好几次了，还是不行，我佛了

**Comment by happy888888** [comment]
是三十二位

**Comment by happy888888** [comment]
或者你把cookie复制到这里我看看，先在浏览器中把账号退出cookie就会失效

**Comment by SadPull** [comment]
感谢大佬，现在已经解决啦
提个小建议，推送的消息能不能加上账号经验 硬币等日常状况？仅推送成功与否有点不够看啊...

**Comment by happy888888** [comment]
目前消息推送仅有简化消息和完整日志两种选项，默认推送的简化消息，完整日志就是actions中显示的。

简化部署方式没有提供完整日志的推送，使用复杂配置修改config.json配置文件里webhook选项，可以推送完整日志。

由于本项目支持多账号，有时候能产生几千行的巨量日志会导致推送失败才默认提供简化的消息推送的，完整日志推送必须修改配置文件

**Comment by happy888888** [comment]
你的意思是每次还要推送当前经验和剩余硬币吗

**Comment by SadPull** [comment]
> 你的意思是每次还要推送当前经验和剩余硬币吗

是的，这样也方便调试一点，简化的信息太少了，反应不出太多情况

**Comment by SadPull** [comment]
这排版我感觉也有点破碎。。。
![Screenshot_20201226_172928](https://user-images.githubusercontent.com/51036486/103148963-43a29500-47a0-11eb-8a3a-b61ed876ce88.jpg)

**Comment by happy888888** [comment]
已修复此问题，并把默认推送消息改为推送完整日志，可通过设置secrets(SIMPLIFIED)为1改为简化消息
3个账号以上推荐使用简化消息，某些消息推送方式每次发送的信息量有上限
