### ISSUE TITLE
多个账号如何查看是否中奖（互动抽奖）

### ISSUE THREAD

**Issue by yun-Tong** [happy888888/BiliExp#119]
请问一下dalao你是怎么解决的

**Comment by happy888888** [comment]
目前还没有实现中奖消息的推送，最开始是打算加一个捕获`"@"消息`或`"回复"消息`和判断关键字然后进行推送的功能的，但是几乎没中过奖，这个功能就一直推迟了并没有实现

结论:目前只能自己***手动登陆账号***查看..........

**Comment by yun-Tong** [comment]
好的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "happy888888/BiliExp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月15日(星期二) 晚上9:10
收件人:&nbsp;"happy888888/BiliExp"<BiliExp@noreply.github.com&gt;;
抄送:&nbsp;"云彤"<1640516241@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [happy888888/BiliExp] 多个账号如何查看是否中奖（互动抽奖） (#119)





 
目前还没有实现中奖消息的推送，最开始是打算加一个捕获"@"消息或"回复"消息和判断关键字然后进行推送的功能的，但是几乎没中过奖，这个功能就一直推迟了并没有实现
 
结论:目前只能自己手动登陆账号查看..........

**Comment by if1y** [comment]
获奖内容是通过`直播小喇叭`这个账号，以卡片消息的形式进行推送的。

另外在`直播中心`的`获奖记录`里也可以查询到。

如果能抓的话应该可以实现。

**Comment by yun-Tong** [comment]
直播小喇叭里面的是天选的中奖信息，而互动抽奖的基本上是靠up艾特你。你在互动抽奖上的中奖信息是没有任何记录的，至少是我以前那一次中奖就只有up主@我这我才知道，其他地方都没任何记录。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;if1y&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月21日(星期一) 下午2:59
收件人:&nbsp;&quot;happy888888/BiliExp&quot;<BiliExp@noreply.github.com&gt;;
抄送:&nbsp;&quot;Cloud&quot;<1640516241@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [happy888888/BiliExp] 多个账号如何查看是否中奖（互动抽奖） (#119)

**Comment by if1y** [comment]
> 直播小喇叭里面的是天选的中奖信息，而互动抽奖的基本上是靠up艾特你。你在互动抽奖上的中奖信息是没有任何记录的，至少是我以前那一次中奖就只有up主@我这我才知道，其他地方都没任何记录。

没注意是互动抽奖（主站），那确实是没有的

**Comment by happy888888** [comment]
目前已增加主站@消息和私信消息的提醒，可用于辅助判断多个账号是否中奖

直播天选时刻的中奖是在直播间轮询的，大部分直播间抽奖程序都是采用的websocket进行实时监听，本程序由于最开始并不是用于直播间的，且不是常驻型的程序所以采用的轮询的方式。以后可能会采用websocket方式已增加其他直播间功能，但是本人最近开始着手准备毕设了没时间上github，其他功能无限期延期

此issues终止
