### ISSUE TITLE
按照教程github一键部署到阿里云后执行报错

### ISSUE THREAD

**Issue by Chillily** [happy888888/BiliExp#12]
Response
{
    "errorMessage": "Extra data: line 1 column 15 (char 14)",
    "errorType": "JSONDecodeError",
    "stackTrace": [
        [
            "File \"/code/BiliExp.py\"",
            "line 109",
            "in main",
            "configData = json.load(fp)"
        ],
        [
            "File \"/usr/local/lib/python3.6/json/__init__.py\"",
            "line 299",
            "in load",
            "parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)"
        ],
        [
            "File \"/usr/local/lib/python3.6/json/__init__.py\"",
            "line 354",
            "in loads",
            "return _default_decoder.decode(s)"
        ],
        [
            "File \"/usr/local/lib/python3.6/json/decoder.py\"",
            "line 342",
            "in decode",
            "raise JSONDecodeError(\"Extra data\", s, end)"
        ]
    ]
}
Function Logs
FC Invoke Start RequestId: 3744cab7-b689-44a4-8486-b07cdde8be29
2020-09-14T01:30:26.428Z 3744cab7-b689-44a4-8486-b07cdde8be29 [ERROR] {
    "errorMessage": "Extra data: line 1 column 15 (char 14)",
    "errorType": "JSONDecodeError",
    "stackTrace": [
        [
            "File \"/code/BiliExp.py\"",
            "line 109",
            "in main",
            "configData = json.load(fp)"
        ],
        [
            "File \"/usr/local/lib/python3.6/json/__init__.py\"",
            "line 299",
            "in load",
            "parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)"
        ],
        [
            "File \"/usr/local/lib/python3.6/json/__init__.py\"",
            "line 354",
            "in loads",
            "return _default_decoder.decode(s)"
        ],
        [
            "File \"/usr/local/lib/python3.6/json/decoder.py\"",
            "line 342",
            "in decode",
            "raise JSONDecodeError(\"Extra data\", s, end)"
        ]
    ]
}
FC Invoke End RequestId: 3744cab7-b689-44a4-8486-b07cdde8be29, Error: Unhandled function error

Duration: 121.62 ms, Billed Duration: 200 ms, Memory Size: 128 MB, Max Memory Used: 19.11 MB
Request ID
3744cab7-b689-44a4-8486-b07cdde8be29

以上是执行结果帮忙看看是哪里出了问题

**Comment by Chillily** [comment]
![FireShot Capture 003 - 函数计算控制台 - fc console aliyun com](https://user-images.githubusercontent.com/39014836/93034691-7bf8ea00-f66d-11ea-8d59-5dd66df35488.png)
![FireShot Capture 006 - 函数计算控制台 - fc console aliyun com](https://user-images.githubusercontent.com/39014836/93034695-7dc2ad80-f66d-11ea-9a41-bed20f723c5d.png)

**Comment by happy888888** [comment]
可能是config/config.json文件的编码或者格式有问题，请使用utf-8编码。
其他脚本有运行出错吗？？

**Comment by Chillily** [comment]
> 可能是config / config.json文件的编码或格式有问题，请使用utf-8编码。
> 其他脚本有运行出错吗？？

所有的脚本都是报一样错，阿里云函数在哪里改UTF-8

**Comment by Chillily** [comment]
> > 可能是config / config.json文件的编码或格式有问题，请使用utf-8编码。
> > 其他脚本有运行出错吗？？
> 
> 所有的脚本都是报一样错，阿里云函数在哪里改UTF-8

好了 找到问题所在了 是config.json的格式问题，谢谢了
