### ISSUE TITLE
港澳台代理怎么判断视频是不是港澳台进行相应的处理

### ISSUE THREAD

**Issue by FairyWorld** [happy888888/BiliExp#120]
在配置云函数代理遇到如下问题:
1. 可以正常代理up主的视频, 但是服务器用腾讯云函数香港地区就会导致大陆的番剧类视频代理失败 (可能识别到香港ip导致大陆番剧无法解析), 但是腾讯云函数香港地区代理港澳台番剧也是同样的错误, 代理失败
2.  如果把腾讯云函数改为广州地区, 那么大陆的番剧类视频代理成功, 港澳台番剧代理失败. (如果哔哩识别ip, 理论上这里港澳台应该代理成功)
3. 我测试了你部署的 http://biliapi.8box.top/playerproxy?avid=796300564&cid=231786190, 是可以代理港澳台，但是大陆会失败. (你用的是阿里云, 前面两点的错误是腾讯云函数搞鬼?)
4. 使用 https://api.bilibili.com/x/player/playurl?avid=796300564&cid=231786190, 发现fq时可以获取大陆番剧(港澳台失败)，使用港澳台fq时，港澳台成功大陆失败。(猜测真的和ip有关? 腾讯云函数香港地区代理失败是腾讯云在搞事?)

其他问题:
1. 有没有获取cid,bid,aid的方法或者接口?控制台获取太麻烦了, 港澳台地区还要fq一下控制台才能执行

**Comment by FairyWorld** [comment]
补充: 有没有办法大陆不代理, 港澳台番剧才代理, 没有找到分辨番剧是否是港澳台的接口

**Comment by happy888888** [comment]
B站是通过ip判断是否在港澳台的，理论上只要ip在港澳台就能观看港澳台番剧，但大陆番剧受限
ip在大陆比如广州就无法观看港澳台番剧

视频地址接口开头有个code字段，只有是0才是解析成功，是其他值就有错误，可以通过这个值判断是否是港澳台番剧

视频网址里面不是就自带了av号和bv号吗还要怎么自动获取？番剧是ep号和ss号

**Comment by FairyWorld** [comment]
> B站是通过ip判断是否在港澳台的，理论上只要ip在港澳台就能观看港澳台番剧，但大陆番剧受限
> ip在大陆比如广州就无法观看港澳台番剧
> 
> 视频地址接口开头有个code字段，只有是0才是解析成功，是其他值就有错误，可以通过这个值判断是否是港澳台番剧
> 
> 视频网址里面不是就自带了av号和bv号吗还要怎么自动获取？番剧是ep号和ss号

我再研究下你下载功能的代码吧, py刚入门看起来有点累，我没有直接跑你的项目，只是想部署一个接口玩一下没有打算使用，参数都是手动输入的。应该实现方式是一样的，参考了你的node代码和api参数, 只是没有使用cookie, 好像非会员低画质不需要cookie就懒得弄了
![image](https://user-images.githubusercontent.com/32956212/102325319-f95e2e80-3fbd-11eb-99a5-1d493318256e.png)

腾讯云函数部署在香港地区，大陆和港澳台番剧的都失败了 {"code":-404,"message":"啥都木有","ttl":1,"data":null}, 我再研究就一下原因, 刚刚查了下腾讯云函数用的是保留地址, 不知道是香港的还是广州的或者腾讯做了什么东西，待会在本地环境搭个服务器试一下

**Comment by happy888888** [comment]
在云函数内访问这个接口看看ip是不是香港的`https://api.ipify.org/?format=json` 获得ip后百度一下就行

我也是py新手，代码写得比较辣鸡可能看起来比较费劲.....

**Comment by FairyWorld** [comment]
> https://api.ipify.org/?format=json

101.32.36.192 确实是香港的, 之前用其他方式查到的是内部的ip，今晚再排查下是什么原因代理失败

**Comment by happy888888** [comment]
不用`https://api.bilibili.com/x/player/playurl`改用`https://api.bilibili.com/pgc/player/web/playurl`呢，后者才是用来解析番剧的，有些非会员未购买的视频(一般是电影之类的)用前者是解析不出的，但后者能解析出试看5分钟的视频(前提是支持试看)，当然有会员能直接解析

**Comment by FairyWorld** [comment]
> 不用`https://api.bilibili.com/x/player/playurl`改用`https://api.bilibili.com/pgc/player/web/playurl`呢，后者才是用来解析番剧的，有些非会员未购买的视频(一般是电影之类的)用前者是解析不出的，但后者能解析出试看5分钟的视频(前提是支持试看)，当然有会员能直接解析

换了第二个接口后确实可以访问成功了.
现在只是想不明白为什么第一个接口在腾讯云函数上会失败，如果第一个接口不在腾讯云函数运行的话，只在本地是配合港澳台节点可以访问到数据的, postman等也可以成功，只是放到腾讯云函数就 {"code":-404,"message":"啥都木有","ttl":1,"data":null}了。我看了下 player_proxy.js 文件中你把第二个接口注释了，所以和你的配置一样，但是我访问你部署的 http://biliapi.8box.top/playerproxy 确实是可以成功的, 只是我用第一个接口不行

**Comment by happy888888** [comment]
我用的是阿里云函数部署的，但是应该没有什么区别才对，毕竟都是香港的ip，除非腾讯云访问大陆的ip地址直接走的腾讯内部线路，出口ip是大陆的

访问`https://2021.ip138.com/`这个网址试试，这个返回的是个包含ip的网页不是json，上面那个接口是国外的，这个是大陆的地址

**Comment by FairyWorld** [comment]
> 我用的是阿里云函数部署的，但是应该没有什么区别才对，毕竟都是香港的ip，除非腾讯云访问大陆的ip地址直接走的腾讯内部线路，出口ip是大陆的
> 
> 访问`https://2021.ip138.com/`这个网址试试，这个返回的是个包含ip的网页不是json，上面那个接口是国外的，这个是大陆的地址

![image](https://user-images.githubusercontent.com/32956212/102362388-48708780-3fef-11eb-94b3-ad42f8ff6423.png)
好像确实是香港的，两个接口返回ip都是香港的, 云函数居然不是固定ip，好像比服务器牛逼。现在还是搞不懂第一个接口会失败，现在不管了只是玩一下

**Comment by happy888888** [comment]
云函数只是弹性计费而已，比服务器便宜，性能限制比较大，用处还是非常有局限性的

你这么说我也搞不懂为什么会失败，难道是B站特地限制了腾讯云的ip，我没有香港服务器可以测试

**Comment by FairyWorld** [comment]
> 云函数只是弹性计费而已，比服务器便宜，性能限制比较大，用处还是非常有局限性的
> 
> 你这么说我也搞不懂为什么会失败，难道是B站特地限制了腾讯云的ip，我没有香港服务器可以测试

有可能是限制了腾讯云的ip，中午本来想用阿里云函数试一下，发现每次都是上海的ip，好像不能更改地区(或者我没有找到按钮, 感觉阿里云控制台界面太乱了), 云函数好像是免费的，我连1/10都用不完，等学会了linux基础就搞个国外的服务器

**Comment by if1y** [comment]
B站之前对各种云进行过限制，后来放开了。
但是考虑到第二个接口可以，那应该还是没有限制的。

腾讯云香港有些IP是从大陆广播过去的，所以我觉得应该是b站的ip数据库把它列入了大陆范围。

**Comment by if1y** [comment]
对了，另外你可以在函数配置里勾选`固定出口IP`，每地域最多5个，免费，也许能够解决问题

**Comment by FairyWorld** [comment]
> 对了，另外你可以在函数配置里勾选`固定出口IP`，每地域最多5个，免费，也许能够解决问题

改为固定ip，第一个接口真的可以成功。
顺便反馈一个使用github action发送直播小心心的bug:
   1. 我用的是github action的方式运行, 使用复杂配置, 总共两个账号, 因为风纪委员任务判断有任务才执行, 所以为了保证能够完成20次, 我修改了定时功能, 每天10点开始, 一小时一次直到23点(应该执行了有10次)
   2. 很久我的配置是 每执行一次action 就获取 24个小心心并发送大概2小时执行完一次, 晚上的结果是大号和小号都获取到了24个, 但是只有第一个配置的账号发送完了24颗, 第二个配置的账号也发送了但是没有发送完24颗
   3. 后来我优化了下配置文件, 每次执行获取6颗小心心, 大概一次就半小时左右, 结果晚上查看两个号都获取了24个，但是两个号都是只有部分小心心发送了.
   4. 理论上配置24颗一次和配置6颗一次(获取小心心时长配置也改为对应的了), 每天执行10多轮应该圆满的, 但是实际上有部分小心心没有发送出去

**Comment by FairyWorld** [comment]
> > 对了，另外你可以在函数配置里勾选`固定出口IP`，每地域最多5个，免费，也许能够解决问题
> 
> 改为固定ip，第一个接口真的可以成功。
> 顺便反馈一个使用github action发送直播小心心的bug:
> 
> 1. 我用的是github action的方式运行, 使用复杂配置, 总共两个账号, 因为风纪委员任务判断有任务才执行, 所以为了保证能够完成20次, 我修改了定时功能, 每天10点开始, 一小时一次直到23点(应该执行了有10次)
> 2. 很久我的配置是 每执行一次action 就获取 24个小心心并发送大概2小时执行完一次, 晚上的结果是大号和小号都获取到了24个, 但是只有第一个配置的账号发送完了24颗, 第二个配置的账号也发送了但是没有发送完24颗
> 3. 后来我优化了下配置文件, 每次执行获取6颗小心心, 大概一次就半小时左右, 结果晚上查看两个号都获取了24个，但是两个号都是只有部分小心心发送了.
> 4. 理论上配置24颗一次和配置6颗一次(获取小心心时长配置也改为对应的了), 每天执行10多轮应该圆满的, 但是实际上有部分小心心没有发送出去

修正一下: 
       我后来的配置是8-23点, 每次3个心心或者15分钟终止, 一般看结果的时间是晚上8-12点

**Comment by FairyWorld** [comment]
> 对了，另外你可以在函数配置里勾选`固定出口IP`，每地域最多5个，免费，也许能够解决问题

还想问下为什么固定ip就行了, 动态ip之前测试过了也是香港的腾讯云，固定也是。但是只有固定ip使用第一个接口才能成功

**Comment by happy888888** [comment]
> > > 对了，另外你可以在函数配置里勾选`固定出口IP`，每地域最多5个，免费，也许能够解决问题
> > 
> > 
> > 改为固定ip，第一个接口真的可以成功。
> > 顺便反馈一个使用github action发送直播小心心的bug:
> > 
> > 1. 我用的是github action的方式运行, 使用复杂配置, 总共两个账号, 因为风纪委员任务判断有任务才执行, 所以为了保证能够完成20次, 我修改了定时功能, 每天10点开始, 一小时一次直到23点(应该执行了有10次)
> > 2. 很久我的配置是 每执行一次action 就获取 24个小心心并发送大概2小时执行完一次, 晚上的结果是大号和小号都获取到了24个, 但是只有第一个配置的账号发送完了24颗, 第二个配置的账号也发送了但是没有发送完24颗
> > 3. 后来我优化了下配置文件, 每次执行获取6颗小心心, 大概一次就半小时左右, 结果晚上查看两个号都获取了24个，但是两个号都是只有部分小心心发送了.
> > 4. 理论上配置24颗一次和配置6颗一次(获取小心心时长配置也改为对应的了), 每天执行10多轮应该圆满的, 但是实际上有部分小心心没有发送出去
> 
> 修正一下:
> 我后来的配置是8-23点, 每次3个心心或者15分钟终止, 一般看结果的时间是晚上8-12点

小心心是5分钟获得1个，获取24个需要2个小时，获取小心心个数与心跳次数没有关系只与心跳时间有关系，每发送一次心跳官方都会统计一次时间，但是每个心跳的间隔是官方指定的(每次执行程序的第一个心跳不计时，从第二个心跳开始计时)，小心心个数不够只有可能是心跳时间不够，还有在没有开播的直播间心跳好像是无效的，而且心跳间隔要比正常情况下短
