### ISSUE TITLE
通用券快要过期了不能自动购买

### ISSUE THREAD

**Issue by niuqudechongdong** [happy888888/BiliExp#124]
发现通用券明天就没了，今天还没有用出去。理论上应该几天前就自动购买了

**Comment by happy888888** [comment]
通用券可能跟漫读劵不是一个东西

**Comment by niuqudechongdong** [comment]
应该是，我看日志里面直接说：没有即将过期的券

**Comment by happy888888** [comment]
最近B站漫画改版了，网页上看漫画都提示在app上观看，而且网页上根本就看不到通用卷数量，估计B站后面要把漫画网页版给砍掉

**Comment by niuqudechongdong** [comment]
哈哈哈，好像是的，我看很多人都在苹果B站app下载页骂B站，说网页端看不了漫画，充的钱都用不来了，而ios账户app又与安卓、电脑端账户不通用。
现在战友日没了，只能把B站送的B币券换成10张漫读券。。。好垃圾

**Comment by happy888888** [comment]
B漫店大欺客真的垃圾，积分兑换漫读劵也很快没库存了，我几乎都没兑换成功过

**Comment by niuqudechongdong** [comment]
上两个月可以兑换，我那时每天12点执行一次，一满100积分就兑换。但这两天不行，好像要连续点两次才行。我设成12点30秒触发一次，这两天没有兑换，今天看日志才发现多了以下信息：
兑换福利劵失败，原因为:现在抢票的人太多啦，再点一下有机会优先上车喔 ε=ε=(ノ≧∇≦)ノ
我觉得应该要短时间内触发两次才能领到票
