### ISSUE TITLE
多账号差异化配置的问题

### ISSUE THREAD

**Issue by if1y** [happy888888/BiliExp#125]
看了 config，使用 task 参数可以实现多账号差异化配置~

想问：
**是只能把 default 中的差异项复制到 task 中么？**

个人感觉，称 default 是配置模板1，那么平行设置另一套配置模板2，命名为 config2，然后在 task中指定 config2为小号的配置模板，看起来更美观和便捷，不知道目前是否可行

**Comment by happy888888** [comment]
改动太大了，目前配置文件需要向下保持兼容，因为使用actions运行的人会自动同步代码

当时想的是大部分账号用一个模板就够了，只有一两个账号在少数功能上需要改变所以才这样设计的

**Comment by if1y** [comment]
好的，感谢！
