### ISSUE TITLE
修改脚本触发时间的问题

### ISSUE THREAD

**Issue by if1y** [happy888888/BiliExp#126]
因为想让天选时刻和小心心长时间运行，但是云函数又有免费额度限制，考虑到**直播高峰期主要在晚上**，所以想着把执行时间改改，使之控制在17:00-2:00。

查看触发配置，Github Actions 处标注`时间与其他脚本有依赖关系如无必要请勿修改`。

所以想问：
如果确实需要修改触发时间，除了更改各自的触发时间（Actions 为 `run_BiliExp.yml`，腾讯云为`触发管理`）以外，**还有哪里需要联动更改么？**

**Comment by happy888888** [comment]
主站互动抽奖动态转发和漫画的积分兑换福利卷部分是依赖时间的，不启用这俩功能都没事，直接修改云函数触发时间就行。

需要长时间运行的功能不适合云函数运行，每获取一个小心心需要直播心跳5分钟，每天能获取24个需要2个小时，假如一次云函数脚本运行时长5分钟，心跳间隔3分钟，那么运行一次只有两次心跳增加3分钟的时长，另外2分钟不足以一次心跳所以时间其实浪费了，同理下一次云函数触发后也只能得到3分钟时长，时间浪费很严重

**Comment by if1y** [comment]
虽然资源确实有浪费，不过单纯跑这一个项目，云函数的资源量还是够 30d * 24h 的~
当然，一直跑并不合适，所以我就在想让它每天只跑七八个小时。

所以也想请教，要实现上述17:00-2:00持续获取小星星、动态抽奖、天选时刻：
> 小心心：心跳参数因为是可选，所以不填
> 动态抽奖：不作时间方面的调整
> 天选时刻：设置 delay = 60秒，times = 540次，从而满足 60*540 = 9小时

我这个方案有没有毛病？ 😂

**Comment by happy888888** [comment]
其实调整配置文件几乎没用，云函数每次最多运行900s就会强制关闭，你把心跳次数和时间调大一点，天选次数调大一点，然后云函数设置为每15分钟运行一次就行

动态抽奖每次抽的一整天的，今天中午12点到昨天中午12点，所以每天中午运行一次就行

**Comment by if1y** [comment]
好的，懂了。

那如果不用云函数，哪种方案能比较好地实现长期服务呢？
Actions 也是定时触发的，每月有额度限制。感觉 VPS 自建可行？

**Comment by happy888888** [comment]
Actions每次运行最长6个小时，就按照你上面的配置运行就行，小心心(心跳)的次数加大一些，time改为120(2个小时)就行
