### ISSUE TITLE
关于直播间心跳支持多个直播间问题

### ISSUE THREAD

**Issue by TWOBUG31** [happy888888/BiliExp#128]
问题：挂取小心心好像没有实现在多个直播间同时获取。

脚本地址：https://github.com/pjy612/Bilibili-LRHH

上述脚本在开发调试工具运行日志为在不同直播间同时获取小心心，且是否开播不会影响能否获取。如图
![image](https://user-images.githubusercontent.com/66819503/103069878-4ca63180-45fb-11eb-947c-22b7b8b4e80c.png)

按照官方获取小心心的描述为在开播且已有勋章的直播间挂机5分钟可以获取一个小心心，每天上限24个，需要2h挂满。
对于上述脚本，如果已有勋章大于等于24个，那么同时在24个直播间获取小心心，可以在5分钟获取到24个。如果有12个勋章，则可以在12个直播间同时获取，需要每个直播间获取2个，耗时10分钟。

对于本程序在ac中运行日志显示如下图，设置参数为心跳1200次，时间60分钟。在达到60分钟后程序停止，显示运行时间59分钟多，获取到小心心11个。猜测心跳在1分钟1次左右，而且获取小心心目前还是在单个直播间进行获取，并没有同时在不同直播间获取。

![image](https://user-images.githubusercontent.com/66819503/103070326-3cdb1d00-45fc-11eb-9a99-253369a7394c.png)

不知是否存在这个问题？

**Comment by TWOBUG31** [comment]
> 问题：挂取小心心好像没有实现在多个直播间同时获取。
> 
> 脚本地址：https://github.com/pjy612/Bilibili-LRHH
> 
> 上述脚本在开发调试工具运行日志为在不同直播间同时获取小心心，且是否开播不会影响能否获取。如图
> ![image](https://user-images.githubusercontent.com/66819503/103069878-4ca63180-45fb-11eb-947c-22b7b8b4e80c.png)
> 
> 按照官方获取小心心的描述为在开播且已有勋章的直播间挂机5分钟可以获取一个小心心，每天上限24个，需要2h挂满。
> 对于上述脚本，如果已有勋章大于等于24个，那么同时在24个直播间获取小心心，可以在5分钟获取到24个。如果有12个勋章，则可以在12个直播间同时获取，需要每个直播间获取2个，耗时10分钟。
> 
> 对于本程序在ac中运行日志显示如下图，设置参数为心跳1200次，时间60分钟。在达到60分钟后程序停止，显示运行时间59分钟多，获取到小心心11个。猜测心跳在1分钟1次左右，而且获取小心心目前还是在单个直播间进行获取，并没有同时在不同直播间获取。
> 
> ![image](https://user-images.githubusercontent.com/66819503/103070326-3cdb1d00-45fc-11eb-9a99-253369a7394c.png)
> 
> 不知是否存在这个问题？

主要是现在如果挂满小心心需要连续运行120分钟以上才可以，参考之前issue时间过长可能会出现其他错误，而且会因为占用ac太长时长从而被封。麻烦大佬看下是否存在此问题。

**Comment by happy888888** [comment]
多直播间心跳目前只支持手动指定多个直播间，不指定默认只选取一个等级高的

**Comment by happy888888** [comment]
你的意思是改为默认在所有获得过勋章的直播间同时心跳吗？目前是自定义直播间为主

**Comment by TWOBUG31** [comment]
> 你的意思是改为默认在所有获得过勋章的直播间同时心跳吗？目前是自定义直播间为主

是的，默认在所有直播间同时心跳，尽快获取满全部小心心。

目前配置文件中对于指定直播间的描述为“ 直播间id，取空会自动获取拥有勋章的直播间(在线的，勋章等级高的，等级亲密度高的优先)，建议手动指定”

没有提示多个直播间的格式，我一直认为是只支持单个直播间，而且也不清楚在非直播情况下能否获取小心心，所以都是默认没有填写的状态。

如果现在可以手动指定多个直播间的话，房间号是以逗号隔开吗？

**Comment by happy888888** [comment]
对的，以逗号隔开`[4563, 478962, 47895]`这样表示三个直播间的房间号

我也不清楚在非直播情况下能否获取小心心，但这样确实能同时在三个直播间保持在线

**Comment by TWOBUG31** [comment]
> 对的，以逗号隔开`[4563, 478962, 47895]`这样表示三个直播间的房间号
> 
> 我也不清楚在非直播情况下能否获取小心心，但这样确实能同时在三个直播间保持在线

我刚才测试了下，上午获取到14个小心心，将心跳时间设置为7分钟，将直播间添加了25个，在日志中显示运行时间6m48s，每个直播间心跳7，现在24个小心心是满的。应该是可以实现非直播情况下的小心心获取。
