### ISSUE TITLE
关于在云服务器上报错的问题

### ISSUE THREAD

**Issue by T1573** [happy888888/BiliExp#129]
我在我的win10系统电脑上使用没问题，但是挂到阿里云服务器win10系统上就运行不了exe，一开始我怀疑是cookieDatas的问题，但我用了我电脑和服务器上Edge浏览器抓的cookieDatas都试了一下，都是在运行exe时显示这个“配置加载异常，原因为Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0) ,退出程序                                     注：“column”这个单词看不太清，u这个字母后面的字母有点模糊。

**Comment by happy888888** [comment]
文件编码用utf8而不是utf8 bom

**Comment by happy888888** [comment]
文件编码用utf8而不是utf8 bom

**Comment by T1573** [comment]
> 8]utf8 bom

请问要怎么改，只懂一点c语言的基础，不会改这个QAQ

**Comment by happy888888** [comment]
win下的话编辑器用notepad++，别用记事本。
c语言的话打开文件，读入文件后不要前三个字节保存回源文件就行

**Comment by T1573** [comment]
> win [笔记板]，]
> c]，=

谢谢，用了notepad++改了一下编译后解决了问题，顺便问一下设置多个账号的cookieDatas有更精确示例图吗？文字叙述琢磨里半天，直接剪切了示例2，换了一下里面的数据，括号也对齐了，还是报错。

**Comment by happy888888** [comment]
注释必须被/*   */包裹，直接去除原来第二个示例的注释符号，需要把汉字用注释符合包裹或直接删除

**Comment by T1573** [comment]
好的，谢谢
