### ISSUE TITLE
部署阿里云失败，

### ISSUE THREAD

**Issue by FunkyPantsSa** [happy888888/BiliExp#13]
部署到阿里云的时候总是失败，已经检查了阿里云的账号和config文件，都没问题。
![image](https://user-images.githubusercontent.com/34020994/93568292-7e877680-f9c2-11ea-9f1d-0c0eb08323f8.png)

还有下图
![image](https://user-images.githubusercontent.com/34020994/93568316-8ba46580-f9c2-11ea-897f-7be20abaa9cc.png)

**Comment by happy888888** [comment]
ACCESS_KEY_ID和ACCESS_KEY_SECRET这两个参数需要主账户的，不能使用子账户。
第一次使用云函数可能需要在这里开通https://www.aliyun.com/product/fc

**Comment by FunkyPantsSa** [comment]
这两个参数确实是主账户，也开通了函数计算的，
![image](https://user-images.githubusercontent.com/34020994/93731475-bb8c7c80-fbff-11ea-87b2-8433f2afdc17.png)
![image](https://user-images.githubusercontent.com/34020994/93731491-cba45c00-fbff-11ea-8f70-33a42c0a26b7.png)

**Comment by FunkyPantsSa** [comment]
已经解决，id填写错误
