### ISSUE TITLE
大佬，求助，刚刚用这个下载视频，批量下载因为速度过快被B站识别为爬虫了，这种需要多久才能解除呀？

### ISSUE THREAD

**Issue by smalloneSAMA** [happy888888/BiliExp#131]
大佬，求助，刚刚用这个下载视频，批量下载因为速度过快被B站识别为爬虫了，这种需要多久才能解除呀？

**Comment by happy888888** [comment]
没遇到过这种情况，是收到B站官方的信息了吗？还是程序报错了？

**Comment by smalloneSAMA** [comment]
谢谢，没关系了，几个小时后解封了
不过有一个问题想问下大佬
这个什么时候可以支持mac呀

**Comment by happy888888** [comment]
在mac上装好环境（python3，requests，aiohttp）后克隆代码到本地运行就行

**Comment by smalloneSAMA** [comment]
好的 感谢:)
