### ISSUE TITLE
天选时刻有办法选择性参加了吗

### ISSUE THREAD

**Issue by if1y** [happy888888/BiliExp#132]
用小号测试发现有些天选时刻提示“余额不足”，看起来是参加了需要投喂的那种。
大号上面有一些余额，但是并不希望被自动用于抽奖，所以想问问能不能过滤掉……

**Comment by happy888888** [comment]
请问那些直播间经常出现***需要投喂的那种***的天选时刻呢，我需要先收集数据才能做过滤

**Comment by if1y** [comment]
哪些经常出现，我没法给出定论，相对无需投喂的而言、投喂还是少数，且取决于主播意愿，完全没有规律可循。

我最近的执行日志中，以下直播间是出现过的（按从多到少排序）：8009467、22349804、22361714、22599134

保证获取到数据，可能还是需要大佬花时间长期监控。
明天跨年夜，有不少直播活动，多看看那些热门大主播，遇到投喂的概率应该会大一些。

**Comment by if1y** [comment]
另外 https://github.com/lkeme/BiliHelper-personal 是我之前用过的同类程序，可以选择性过滤各种条件的天选时刻（无限制/关注主播/粉丝勋章/大航海/用户等级/主站等级，**实际使用没有出现过投喂**），也许有参考意义~

**Comment by if1y** [comment]
此刻 34348 在投喂天选时刻

**Comment by if1y** [comment]
今晚有投喂“冲鸭”的投票活动，大佬有空的话可以蹲一下，比如 82178 6103516

**Comment by happy888888** [comment]
目前已增加金瓜子投喂上限限制，需要金瓜子超过上限则跳过参与天选时刻，可不修改配置文件直接合并更新代码，默认上限是0

**Comment by if1y** [comment]
辛苦了！

**Comment by happy888888** [comment]
除了天选时刻，直播间还有其他形式的抽奖吗，我想收集一些直播间用来获取数据扩展更多功能

**Comment by if1y** [comment]
> 除了天选时刻，直播间还有其他形式的抽奖吗，我想收集一些直播间用来获取数据扩展更多功能

- 大型活动、赞助商类直播有个宝箱，不确定是不是单纯整合的天选时刻。
- 另外遇到过几次“节奏风暴”，但没有仔细了解，不确定是否存在抽奖性质，可能只是单纯的弹幕“跟风”（但即使如此，算作一个拓展功能也可吧）
- 其它应该没了，或者我不知道
