### ISSUE TITLE
ep视频无法下载，大佬我看解析出来的epList为空

### ISSUE THREAD

**Issue by smalloneSAMA** [happy888888/BiliExp#134]
刚刚看了下，现在B站的ep视频 eplist是空的，bvid，cid，title 等数据在epInfo下了，大佬有时间修改下吧~
例如这个就无法下载：https://www.bilibili.com/bangumi/play/ep374805

**Comment by happy888888** [comment]
ep默认解析的是***正片***，没有解析pv，额外的总集篇，小剧场，广播节目，声优访谈这些东西(虽然ep可能包含这些但不是每个ep都包含所以忽略了)

直接解析bv号链接也行，比如你这个例子[https://www.bilibili.com/video/BV1Mo4y1Z7KS](https://www.bilibili.com/video/BV1Mo4y1Z7KS)

**Comment by happy888888** [comment]
目前最新代码已支持解析ep号时解析正片，pv，额外的总集篇，小剧场，广播节目，声优访谈等所有内容，release版本将在下个版本开始支持
