### ISSUE TITLE
漫画购买

### ISSUE THREAD

**Issue by niuqudechongdong** [happy888888/BiliExp#14]
我觉得可以用漫画的mc号（可以设置你要购买第几话到第几话），或者你说的追漫列表也行。

战友日是可以用5B币得到15张券，平时只能兑换10张券，不过，就是好像每个月都会有新的链接。（在B漫的“活动中心”里可以看到之前的站友日活动）

**Comment by happy888888** [comment]
貌似站友日的页面链接虽然不一样但是接口是一样的。站友日的日期都是同一天吗？

购买漫画其实是按照epid(每一章/话一个)来购买的不是mc号。输入多个mc号，按照mc号的顺序进行购买吗？排在前面的购买到最新话再买后面的这样？

**Comment by niuqudechongdong** [comment]
战友日之前改过好几次，现在是每月初的好几天，不止一天。

之前我是这样想的，如果可以的，可以设置章节数（购买第几章到第几章，不过，这样工作量有点大了）

**Comment by happy888888** [comment]
感觉没必要指定多少章啊，直接购买后续话数不行吗，比如已经买到20话了，还剩2章劵，就把21和22话买了，如果只更新到21话，就购买漫画列表里下一个漫画的章节。我现在按照指定mc号和章节数实现试试。

**Comment by niuqudechongdong** [comment]
我觉得也可以。之前我想指定章节是因为我想到，可能有人想买章节数很多的漫画，比如海贼王（当然我不看海贼王，举例一下），可能前面很多章节不想买，也太多章节了，只想从某个章节买起。或者，第一部漫画从头买起需要太多券了，这样很难轮到第二部漫画。不过，确实，番外（这些不确定因素）会影响到章节，如果太多细节要弄，就忽略我这个奇思妙想吧

**Comment by happy888888** [comment]
已增加mangaAutoBuy.py文件用于自动花费即将过期的漫读劵购买指定漫画，采用的是手动指定漫画mc号和章节序号的方式，参数在脚本文件内修改，因为没有经过大量的测试(没有劵啊😂)，暂时没有添加到自动部署到云函数的脚本中。

你有即将过期的劵的话可以测试一下，没有即将过期的劵就不会自动购买。

**Comment by niuqudechongdong** [comment]
哈哈哈，我前几天刚要过期的券也被我用完了。

**Comment by happy888888** [comment]
目前默认购买追漫列表里面的漫画来应对懒得配置的人，手动指定购买列表可以在mangaAutoBuy.py里改。

自动领取大会员的5B币添加到BiliExp.py里了，但没有经过测试。

**Comment by niuqudechongdong** [comment]
想到一个问题，自动购买漫画的脚本，当你追漫列表里的第一个漫画要用通用券才能购买时，而你只有漫读券时，会不会跳过这个漫画购买下一个漫画用漫读券可以购买的漫画？

**Comment by happy888888** [comment]
会的，购买失败自动跳到下一个，日志里应该会有"本漫画不允许漫读劵购买"的记录。

我考虑过购买失败的情况，但是目前没遇到过你说的这种情况，理论上应该能达到你说的效果，但是在遇到这种情况前我不能打包票。

**Comment by niuqudechongdong** [comment]
好的，明白了，谢谢大佬

**Comment by happy888888** [comment]
目前把漫画签到的脚本也合并在一起了，添加了自动用积分兑换福利劵的功能(这个福利劵要每天中午12点抢，默认是关闭的功能)。

**Comment by niuqudechongdong** [comment]
“合并”的意思是说已经支持阿里云函数自动部署吗？

**Comment by happy888888** [comment]
现在是支持了

**Comment by niuqudechongdong** [comment]
"8507742": "25900|"
25900|后面什么都不写，是指从第一张开始购买mc25900的漫画直到最后一张吗？

**Comment by happy888888** [comment]
请使用
25900|1-
1-指的才是从第一章到最后一章，同理3-就是三章到最后一章，也可以写1-1000指的是一章到一千章

**Comment by niuqudechongdong** [comment]
![Uploading image.png…]()
为什么我更新不了你的代码，在pull requests里更新不了。是不是因为有新分支了？

**Comment by happy888888** [comment]
README.md
aliyun-serverless-template.yml
这两个文件有冲突无法合并，需要git命令来解决冲突

**Comment by niuqudechongdong** [comment]
具体是怎么弄的，git没有用过，或者说有教程吗？(百度没找到类似的回答)
好奇怪，前天还更新了你的代码，今天就不行了。

**Comment by happy888888** [comment]
我已经去你的仓库把冲突消除了。

**Comment by niuqudechongdong** [comment]
为什么我这里看不到你图上的这个按钮？
![Uploading github2.png…]()

**Comment by happy888888** [comment]
这个链接是按钮的链接，能进去吗https://github.com/niuqudechongdong/BiliExp/pull/4/conflicts

**Comment by niuqudechongdong** [comment]
我点进去是404

**Comment by niuqudechongdong** [comment]
应该只能这样了，我估计是因为你那里有两个分支了，然后pull request就会出现问题。不知道别人会不会出现这个问题

**Comment by happy888888** [comment]
pull request一次只能拉取一个分支啊，应该是我覆盖更改了一些文件，你在我更改前同步了代码，就会出现这种问题。

**Comment by happy888888** [comment]
网页上只能我这里才能解决冲突，但是需要向仓库提交两个修改与我本地不同步了。
你如果可以用git的话可以先把你的仓库git clone到本地，再执行下面的代码解决冲突

git checkout -b happy888888-master master
git pull https://github.com/happy888888/BiliExp.git master

git checkout master
git merge --no-ff happy888888-master
git push origin master

不能用git的话就你pull的时候创建一个新分支，把BiliExp-Actions这个分支同步过去，放弃原来的主分支

**Comment by happy888888** [comment]
最好 把仓库删除了 重新fork，这几天有几次覆盖提交(push --force)导致在第一次覆盖提交后同步过的代码有冲突。覆盖提交确实有大坑........

**Comment by niuqudechongdong** [comment]
运行第一行代码后：fatal: 'master' is not a commit and a branch 'happy888888-master' cannot be created from it
运行第二行代码无报错
第三行代码出现 ：Already on 'master'

**Comment by happy888888** [comment]
git reset --hard 73b43b1
git push -f
用上面两行命令强制回退再到网页上pull

**Comment by niuqudechongdong** [comment]
还是报错fatal: ambiguous argument '73b43b1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

我删除库，在重新FORK把

**Comment by happy888888** [comment]
删除库不是删除文件，在"Settings"的最下面有删除仓库的选项。

**Comment by niuqudechongdong** [comment]
我刚才是想，把我库里的文件全都删除了，可能pull request就不会报错了，发现还是不行。
不过，我库里不知怎么多了一个新分支patch,好像跟你最新的master分支是一样的

**Comment by happy888888** [comment]
在"Settings"的最下面删除仓库

**Comment by niuqudechongdong** [comment]
终于可以了，还是要删除库。
想问一下，如果是直接用github Actions的话，是如何修改代码的（之前可以想部署在阿里云上，然后在阿里云上修改代码）

**Comment by happy888888** [comment]
直接在仓库里改吧，因为是直接执行的仓库里的代码。

**Comment by niuqudechongdong** [comment]
好的，谢谢大佬
