### ISSUE TITLE
想在每条抽奖后面自己发一条动态（[狗头]或者一段文字），避免被动态抽奖工具检测到是机器人，怎么添加？

### ISSUE THREAD

**Issue by zyz183** [happy888888/BiliExp#140]
https://www.bilibili.com/read/cv5720739中提到如果你发的5条连续的动态与“抽奖”相关，则判定为抽奖号。我想先在每条转发抽奖后，自己发条动态，可以是表情，可以是图片，可以是一段文字，这样避免被检测到。但我在BiliApi没有找到相关的东西，能指点一下嘛？谢谢

**Comment by happy888888** [comment]
目前没有自动发动态的功能，后续会添加

没有在你给的链接里找到连发5条抽奖动态就判定抽奖号的说明

**Comment by zyz183** [comment]
抽奖号阈值：最新10条动态中与“抽奖”有关的动态条数(1≤x≤10)。 UP主打开默认值就是5，我想了一下将config.json中关键词转发的里面加上一些关键字如“二次元”，“装机”，“直播”等，可以避免被发现。

**Comment by happy888888** [comment]
后续会添加主动发动态的功能，目前只能转发动态

**Comment by zyz183** [comment]
那一定要学习一下

**Comment by happy888888** [comment]
您认为如何控制动态发送比较好呢，在配置文件里增加一个动态内容和每转发多少个动态就发一次自定义动态的选项吗

**Comment by if1y** [comment]
> 您认为如何控制动态发送比较好呢，在配置文件里增加一个动态内容和每转发多少个动态就发一次自定义动态的2个选项吗

定时，或者定量，最好提供随机空间，最大可能避免呈现“特征”

**Comment by happy888888** [comment]
> > 您认为如何控制动态发送比较好呢，在配置文件里增加一个动态内容和每转发多少个动态就发一次自定义动态的2个选项吗
> 
> 定时，或者定量，最好提供随机空间，最大可能避免呈现“特征”

官方抽奖关键是要把转发时间分散开，第三方的抽奖你是不是抽奖号直接由up主说了算，已经碰到一位B站粉丝(与本项目无关)反馈手动转发的第三方抽奖被up主列为抽奖号，这类第三方抽奖工具判断抽奖号的方式过于简单暴力了

**Comment by happy888888** [comment]
目前已实现
