### ISSUE TITLE
清理动态任务获取用户动态时出错

### ISSUE THREAD

**Issue by FairyWorld** [happy888888/BiliExp#144]
![image](https://user-images.githubusercontent.com/32956212/103742858-6d787900-5036-11eb-96df-ce9e52961c4d.png)

好像是字符串和整数类型不一致

我的配置如下:
"clean_dynamic_task": {/* 清理自己的动态，包括过期抽奖，失效动态 */
            "enable": true,
            "black_keywords": ["从未中奖", "支持支持"], /* 黑名单关键字 */
            "unfollowed": true /* 删除未关注的up主的动态(本账号已转发的) */
}

**Comment by happy888888** [comment]
已修复

**Comment by FairyWorld** [comment]
> 已修复

这个可以在config.json的参数列表加一个参数控制删除多久之前的动态, 昨晚删除动态后好像很多抽奖转发的也清空了. 比如加个参数只删除3天或者七天之前命中关键词的动态, 这样好像才能抽奖成功，不然需要手动配置关闭和开启清理动态

**Comment by happy888888** [comment]
已添加
