### ISSUE TITLE
希望有人能查看我的config.json修改是否出错

### ISSUE THREAD

**Issue by MrSuna** [happy888888/BiliExp#145]
运行了很多遍一直在报错，到了错误的行数也没有看到哪里出问题，所以希望有人能帮忙看一下……
P.S.  "SESSDATA": "","bili_jct": "","DedeUserID": ""
都填了，这里省略了……貌似报错原因也不在这儿
advconfig也加了，如能解决，感激不尽

{
    "version": "1.1.9", /* 配置文件版本,严禁修改 */
    "default": { /* 注意！！下列任何一项任务配置，值设置为true才为启用(enable参数)，将值设置为false或者直接删除就可以关闭任务*/
        "vip_task": { /* 1号领取大会员B币劵优惠券，28号花费剩余B币劵 */
            "enable": false,
            "BpCharge": { /* 花费B币劵的方式 */
                "charge": 2, /* 给自己充电，花费劵的数量为2 */
                "Bp2Gold": 3 /* 兑换金瓜子，花费劵的数量为3 */
                /* 劵不够时会按照剩余劵数量进行花费，
                请合理设置花费方式的数量和顺序(上述配置是先给自己充电后兑换金瓜子，可交换顺序)，
                如果要B币劵兑换漫画漫读劵请使用站友日任务 */
            }
        },
        "group_sign_task": true, /* 应援团签到 */
        "xliveSign_task": true, /* 直播签到 */
        "xlive_bag_send_task": { /* 送出即将到期的礼物 */
            "enable": true,
            "room_id": 4088200 ,22315516,  /* 送礼物的直播间,0为随机取直播间 */
            "expire": 172800 /* 距离过期的时间(s),172800为两天 */
        },
        "xlive_heartbeat_task": { /* 发送直播心跳，获得小心心(费时，不建议在云函数使用，多账户同时开启用时不叠加) */
            "enable": true,
            "room_id": [], /* 直播间id，取空会自动获取拥有勋章的直播间(在线的，勋章等级高的，等级亲密度高的优先)，建议手动指定 */
            "num": 5, /* 心跳次数，每次(第1次除外)需要5分钟并获得1个小心心(每天最高24个小心心)，与time参数满足任一条件都会停止心跳 */
            "time": 25, /* 心跳分钟数(允许带小数)，心跳的时间，与num参数满足任一条件都会停止心跳 */
            "send_msg": "" /* 每次执行向所有带勋章的直播间发送消息，为空则不发送 */
        },
        "xlive_anchor_task": { /* 参与直播天选时刻，目前还没有条件过滤 */
            "enable": true,
            "rooms_id": [3742025, 5441], /* 直播间id，只支持长id，请不要用短id */
            "times": 10, /* 每个直播间查询天选时刻次数，超过次数退出 */
            "delay": 300, /* 每次查询间隔秒数，存在天选时刻时将会在结束时查询结果，否则按本项间隔不断轮询是否有天选存在 */
            "price_limit": 0 /* 金瓜子上限,参与天选需要的金瓜子数量超过此配置则不会参加 */
        },
        "coin_task": { /* 投币任务，启动此项请注意BiliExp同一时间只允许运行一个，否则可能额外投币 */
       /*--------- 必填项------------ */
            "enable": true, /* 功能开关 */
       /*--------------------------- */

       /*--------- enable为true必填项(为false则为无效项,可删除本区域)------------ */
            "num": 2, /* 投币数量，如果当天已经投币超过这个数量则不会继续投币，取值范围为0-5，投币数量自动受到剩余硬币数量限制 */
            "target_exp": 28800, /* 达到目标经验值停止投币，如果当天投币后达到经验值第二天及以后就不会投币 */
            "do_task": [2],
       /*  do_task为模式执行顺序(此项不存在等同于取[1])
           模式1:随机抽取视频投币
           模式2:从账号的关注列表或下面up参数获取up主，对up主视频(专栏)投币
           模式3:搜索特定关键字得到视频进行投币

           取值例子:[3, 2, 1]
           含义，先执行模式3，当币没有投够，执行模式2，还没有投够，执行模式1,推荐将模式1放最后(多账户模式推荐只使用模式1)
        */
       /*-----------------------------end-------------------------------------- */

       /*--------- do_task存在2时的必填项(不存在则为无效项,可删除本区域)------------- */
            "coin": { /* 抽取up主后投币顺序 */
                "article": 1, /* 从抽取的up中选最新最新的5个专栏投币投币，已经投过则执行下面一行 */
                "video": 0 /* 从抽取的up中选最新最新的5个视频投币，已经投过则再抽下一个up主执行上面一行 */
                /* 这两个参数也可以颠倒顺序，且至少存在一个(即另一个可直接删除)，实际数量自动受到up主实际稿件数量限制 */
            },
       /*--------- do_task存在2时的可选项(不需要请删除本区域)----------------------------------------- */
            "groupTag": "特别关注",  /* 此项提供后(不指定一定要删除本项)，只会投此用户组里的up主,与up参数不兼容 */
            "up": [102984190,490505561 ,43645887],  /* 此项提供后(不指定一定要删除本项)，只会投此参数里的up主(按顺序尝试)而不会投其他关注的up主,不兼容groupTag参数 */
       /*-----------------------------end---------------------------------------- */

       /*--------- do_task存在3时的必填项(不存在则为无效项,可删除本区域)------------ */
            "search": { /* 视频关键字 */
                "马保国": { /* 搜索关键字为马保国的视频 */
                    "num": 5, /* 搜索数量上限(默认取值) */
                    "order": 0, /* 排序规则,0综合排序(默认取值),1最多点击,2最新发布,3最多弹幕,4最多收藏 */
                    "duration": 0, /* 时长规则,0全部时长(默认取值),1十分钟以下,2三十分钟以下,3六十分钟以下,4以上 */
                    "tids": 0 /* 分区规则,0全部分区(默认取值),1动画,13番剧,167国创,3音乐,129舞蹈(分区太多篇幅有限不列举了) */
                }, 
                "特朗普": {} /* 这里括号为空,是因为括号里的参数全为可选参数，均可以不填写，值参照上面默认取值 */
            /* 以此类推后面添加更多关键字，前面的关键字视频投币数量不够才会搜索后面的(保证至少有一个关键字) */
            }
       /*-----------------------------end--------------------------------------- */
        },
        "watch_task": true,/* 模拟观看一个随机视频 */
        "share_task": true,/* 模拟分享一个随机视频 */
        "silver2coin_task": true,/* 银瓜子兑换硬币 */
        "lottery_task": {/* 互动抽奖转发，范围是当天中午12点到昨天中午12点自己动态中的互动抽奖 */
            "enable": true,
            "reply": ["从未中奖，从未放弃[doge]", "支持支持"],/* 回复原动态评论，随机抽一个 */
            "repost": ["从未中奖，从未放弃[doge]", "支持支持"],/* 转到自己动态的评论，随机抽一个 */
            "keywords": ["#互动抽奖#", "#抽奖#", ".*(转|抽|评).*(转|抽|评).*(转|抽|评).*"], /* 关键字转发，支持正则表达式匹配 */
            "repost_with_tag": { /* 带着标签转发,有的动态转发需要带标签 */
                "fix": 1, /* 取0为将标签加在首部,取1为加在尾部 */
                "except": ["抽奖"], /* 排除条件,符合本条件的标签不会携带 */
                "reply_with_tag": false /* 回复是否带上标签 */
            },
            "delay": [4, 6], /* 随机延时4-6秒转发 */
       /*----------------- 跟踪转发模式------------------- */
            "repost_by_others": [],
            "force_follow": false /* 是否强制关注抽奖up主 */
       /* 当repost_by_others参数指定大于等于1个B站用户id时
          启用跟踪转发模式(与原模式不兼容)，复制转发指定用户转发的动态
          此模式用于:
          1. 大号转发了抽奖动态，小号使用此模式跟着转
          2. 跟着其他大量抽奖的用户转
          不建议跟踪多个用户
           */
       /*----------------------end----------------------- */
        },
        "msg_notify_task": true,/* 主站@消息,私聊消息推送,配合互动抽奖任务使用便于得到中奖消息 */
        "clean_dynamic_task": {/* 清理自己的动态，包括过期抽奖，失效动态 */
            "enable": true,
            "black_keywords": [], /* 黑名单关键字 */
            "unfollowed": false /* 删除未关注的up主的动态(本账号已转发的) */
        },
        "manga_sign_task": true,/* 漫画签到 */
        "exchangeCoupons_task": {/* 漫画积分兑换福利券，请保证程序在中午12点整启动 */
            "enable": false,
            "num": 0/* 兑换数量 */
        },
        "manga_vip_reward_task": {/* 领取每月大会员漫画权益(漫读劵) */
            "enable": false,
            "days": [1]/* 每月尝试领取的日期 */
        },
        "manga_auto_buy_task": {/* 自动花费即将过期的漫读劵 */
            "enable": false,
            "mode": 1,
            /* mode为1，自动购买追漫列表的漫画，mode为2，购买filter参数中的指定漫画 */
            "filter": "25900|1-30,35,55;25966|5,15,35-"
        },
        "judgement_task": { /*  风纪委员投票(每次运行头当前所有案件) */
            "enable": true, /*  对风纪委员投票不了解的请不要开启本功能 */
            "baiduNLP": { /*  百度语言情感分析，直接影响params参数中vote值 */
                "confidence": 0.6, /*  置信系数门限 */
                "negative_prob": 0.6, /*  积极概率门限 */
                "positive_prob": 0.7  /*  消极概率门限 */
            },
            "params": {    /* 投票参数 */
                "vote": 4,
                "attr": 0
            }
        },
        "activity_task": { /* B站转盘抽奖活动 */
            "enable": true,
            "path": "./config/activities.json", /* B站转盘抽奖列表文件 */
            "activities": [] /* B站转盘抽奖列表 */
        }
    },
    "webhook": { /* 用于自定义消息推送,server酱消息推送只需填写下面SCKEY参数和在hooks参数中enable设置为true，另外提供邮箱推送和telegram推送模板,其他推送可自行添加 */
        "http_header": {"User-Agent":"Mozilla/5.0"}, /* 定义http头部 */
        "variable": { /* 声明任意变量,在hooks参数中的url参数和params参数中使用大括号{}可直接引用在此声明的变量 */
            "msg_simple": null, /* 简化的日志消息，下面msg_raw为完整日志消息，用于下面hooks消息推送接口引用 */
         /*   "msg_raw": null, */
            "title": "B站经验脚本消息推送",
            "SCKEY": "SCU143860Tb931d18dc314d2c1a65330cc71eb806a5ff085cdaa3f2" /*,
            "email": "",
            "telegram_bot_token": "",
            "telegram_bot_chatid": "" */
        },
        "hooks": [ /* 在这里定义所有消息推送回调接口 */
            {
                "enable": true, /* 开关，需要开启请直接把本项删除或设置为true */
                "name": "server酱消息推送", /* webhook名称 */
                "msg_separ": "\n\n", /* 消息分隔符 */
                "method": 1, /* 请求方式,0为get,1为post,2为以json方式post */
                "url": "https://sc.ftqq.com/{SCKEY}.send", /* 请求地址,{SCKEY}为对上面variable变量中的SCKEY的引用 */
                "params": { /* 请求参数 */
                    "text": "{title}",
                    "desp": "{msg_simple}" 
                } 
            }/*,
            {
            	"enable": false,
                "name": "邮箱消息推送",
                "msg_separ": "<br>",
                "method": 0,
                "url": "http://liuxingw.com/api/mail/api.php",
                "params": {
                    "address": "{email}",
                    "name": "{title}",
                    "certno": "{msg_simple}" 
                }
            },
            {
            	"enable": false,
                "name": "telegram_bot消息推送",
                "method": 1,
                "url": "https://api.telegram.org/bot{telegram_bot_token}/sendMessage",
                "params": {
                    "chat_id": "{telegram_bot_chatid}",
                    "text": "{msg_simple}"
                }
            }*/
        ]
    },
    "log_file": "BiliExp.log",/* 日志文件，不输出请留空 */
    "log_console": true,/* 是否把日志输出到控制台 */
    "users": [{/* users为用户数组，每个账户包含一个cookieDatas和tasks参数 */
        "cookieDatas": {/* 下面三项参数为必填参数(DedeUserID在但账户情况下选填，仅用于区分账户)，获取方式见说明 */
            "SESSDATA": "",
            "bili_jct": "",
            "DedeUserID": ""
        },
        "show_name": "", /* 昵称，用于日志，消息推送，填空则默认使用账号昵称 */
        /* 下面tasks参数与最上面default参数作用相同，但优先级更高，用于定制每个账号的参数，
             default中未出现的参数在tasks参数中出现则无效 */
        "tasks": {}
    }/*, { 下面注释掉的是第二个账号的参数例子，以此类推多个账号，单账号仅填写上面内容
        "cookieDatas": {
            "SESSDATA": "4a5f1c63%2C1785313721%2Cdf9fc*a1",
            "bili_jct": "cf28ba45824d443646907a5c4da8cf1",
            "DedeUserID": "914624742"
        },
        "show_name": "",
        "tasks": {}
    }*/]
}

**Comment by happy888888** [comment]
送出直播礼物，指定直播间只能指定一个

**Comment by happy888888** [comment]
只有带中括号`[ ]`的项代表数组，才能传入多个值。

投币任务，模式2指定了up主后，还要指定上面的`coin`参数，代表每次抽取up的专栏和视频数量(每个稿件投一个币)，若第一个up主没有投够币才会投第二个up主以此类推

**Comment by happy888888** [comment]
advconfig只存放配置文件的任务自定义部分，配置文件里面的账号cookie和消息推送不用修改，账号cookie和消息推送可以放到另外两个secrets里面，执行actions时会自动合并为一个完整的配置文件，一定程度上能防止这两个配置错误

**Comment by MrSuna** [comment]
您好，根据来信我只修改了部分，并把这部分复制到advconfig中，但是仍运行报错，能否看看是哪里不对？谢谢！






&nbsp; &nbsp;"vip_task": { /* 1号领取大会员B币劵优惠券，28号花费剩余B币劵 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "enable": false,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "BpCharge": { /* 花费B币劵的方式 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "charge": 2, /* 给自己充电，花费劵的数量为2 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "Bp2Gold": 3 /* 兑换金瓜子，花费劵的数量为3 */




&nbsp; &nbsp; &nbsp;"xlive_bag_send_task": { /* 送出即将到期的礼物 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "enable": true,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "room_id": 4088200 ,  /* 送礼物的直播间,0为随机取直播间 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "expire": 172800 /* 距离过期的时间(s),172800为两天 */
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; "xlive_heartbeat_task": { /* 发送直播心跳，获得小心心(费时，不建议在云函数使用，多账户同时开启用时不叠加) */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "enable": true,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "room_id": [], /* 直播间id，取空会自动获取拥有勋章的直播间(在线的，勋章等级高的，等级亲密度高的优先)，建议手动指定 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "num": 5, /* 心跳次数，每次(第1次除外)需要5分钟并获得1个小心心(每天最高24个小心心)，与time参数满足任一条件都会停止心跳 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "time": 25, /* 心跳分钟数(允许带小数)，心跳的时间，与num参数满足任一条件都会停止心跳 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "send_msg": "" /* 每次执行向所有带勋章的直播间发送消息，为空则不发送 */
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; "xlive_anchor_task": { /* 参与直播天选时刻，目前还没有条件过滤 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "enable": true,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "rooms_id": [4088200 ,22315516], /* 直播间id，只支持长id，请不要用短id */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "times": 10, /* 每个直播间查询天选时刻次数，超过次数退出 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "delay": 300, /* 每次查询间隔秒数，存在天选时刻时将会在结束时查询结果，否则按本项间隔不断轮询是否有天选存在 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "price_limit": 0 /* 金瓜子上限,参与天选需要的金瓜子数量超过此配置则不会参加 */
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; "coin_task": { /* 投币任务，启动此项请注意BiliExp同一时间只允许运行一个，否则可能额外投币 */
&nbsp; &nbsp; &nbsp; &nbsp;/*--------- 必填项------------ */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "enable": false, /* 功能开关 */






&nbsp; &nbsp;"webhook": { /* 用于自定义消息推送,server酱消息推送只需填写下面SCKEY参数和在hooks参数中enable设置为true，另外提供邮箱推送和telegram推送模板,其他推送可自行添加 */
&nbsp; &nbsp; &nbsp; &nbsp; "http_header": {"User-Agent":"Mozilla/5.0"}, /* 定义http头部 */
&nbsp; &nbsp; &nbsp; &nbsp; "variable": { /* 声明任意变量,在hooks参数中的url参数和params参数中使用大括号{}可直接引用在此声明的变量 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "msg_simple": null, /* 简化的日志消息，下面msg_raw为完整日志消息，用于下面hooks消息推送接口引用 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;/*   "msg_raw": null, */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "title": "B站经验脚本消息推送",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "SCKEY": "SCU143860Tb931d18dc314d2c1a65330cc71eb806a5ff085cdaa3f2" /*,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "email": "",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "telegram_bot_token": "",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "telegram_bot_chatid": "" */
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; "hooks": [ /* 在这里定义所有消息推送回调接口 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "enable": true, /* 开关，需要开启请直接把本项删除或设置为true */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "name": "server酱消息推送", /* webhook名称 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "msg_separ": "\n\n", /* 消息分隔符 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "method": 1, /* 请求方式,0为get,1为post,2为以json方式post */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "url": "https://sc.ftqq.com/{SCKEY}.send", /* 请求地址,{SCKEY}为对上面variable变量中的SCKEY的引用 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "params": { /* 请求参数 */
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "text": "{title}",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "desp": "{msg_simple}"&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }

**Comment by happy888888** [comment]
```
{
    "version": "1.1.9",
    "default": {
        "group_sign_task": true,
        "xliveSign_task": true,
        "xlive_bag_send_task": {
            "enable": true,
            "room_id": 4088200,
            "expire": 172800
        },
        "xlive_heartbeat_task": {
            "enable": true,
            "room_id": [],
            "num": 24,
            "time": 25,
            "send_msg": ""
        },
        "xlive_anchor_task": {
            "enable": true,
            "rooms_id": [4088200 ,22315516],
            "times": 10,
            "delay": 300,
            "price_limit": 0
        },
        "watch_task": true,
        "share_task": true,
        "silver2coin_task": true,
        "lottery_task": {
            "enable": true,
            "reply": ["从未中奖，从未放弃[doge]", "支持支持"],
            "repost": ["从未中奖，从未放弃[doge]", "支持支持"],
            "keywords": ["#互动抽奖#", "#抽奖#", ".*(转|抽|评).*(转|抽|评).*(转|抽|评).*"],
            "repost_with_tag": {
                "fix": 1,
                "except": ["抽奖"],
                "reply_with_tag": false
            },
            "delay": [6, 8],
            "repost_by_others": [],
            "force_follow": false
        },
        "msg_notify_task": true,
        "clean_dynamic_task": {
            "enable": true,
            "black_keywords": [],
            "unfollowed": false
        },
        "manga_sign_task": true,
        "judgement_task": {
            "enable": true,
            "baiduNLP": {
                "confidence": 0.6,
                "negative_prob": 0.6,
                "positive_prob": 0.9
            },
            "params": {
                "vote": 4,
                "attr": 0
            }
        },
        "activity_task": {
            "enable": true,
            "path": "./config/activities.json",
            "activities": []
        }
    },
    "log_file": "BiliExp.log",
    "log_console": true,
    "users": []
}
```

**Comment by MrSuna** [comment]
我现在才看到邮件。
非常感谢！



---Original---
