### ISSUE TITLE
今天自动同步的action突然报错了

### ISSUE THREAD

**Issue by awei4287** [happy888888/BiliExp#146]
![QQ截图20210108123234](https://user-images.githubusercontent.com/23376999/103974984-0087ef00-51ae-11eb-8a02-1592a8203fde.png)

**Comment by RouRouX** [comment]
看上去感觉是run_BiliExp.yml触发的action无法更新自己的原因。

我在github页面上手动合并了一波，后续应该只要run_BiliExp.yml这个文件不更新，不会报错。

只是我的理解，等权威答案吧。

**Comment by happy888888** [comment]
> 看上去感觉是run_BiliExp.yml触发的action无法更新自己的原因。
> 
> 我在github页面上手动合并了一波，后续应该只要run_BiliExp.yml这个文件不更新，不会报错。
> 
> 只是我的理解，等权威答案吧。

完全正确，workflow文件夹里的文件改变后无法自动同步，需要手动同步一次
