### ISSUE TITLE
关于风记委员执行问题

### ISSUE THREAD

**Issue by wangmanv2** [happy888888/BiliExp#147]
风纪委员一年如果完整做完每天的20个审核（可以缺少150个左右），可以获取到一整年的大会员和一些硬币。
但是我发现本软件每日只运行一次每次处理的案件太少（大概天只能处理6-13个左右）反正肯定是满不了20个的。虽然也能获得一定期限的大会员奖励但是能白嫖一年为什么不呢？
想问能否单独增加风纪委员脚本的执行次数呢？尽量保证能达到每日20个案件？

**Comment by happy888888** [comment]
我看已经有人修改actions，把执行周期从每隔一天执行一次改为每隔一小时执行一次..........

理论上每隔半小时执行一次能100%覆盖所有案件

**Comment by wangmanv2** [comment]
其实我也想修改的，但是修改了以后就有一个问题。

因为设置了主仓库更新，分支仓库也跟着更新的服务。就会导致修改过后如果主仓库更新，分支就会被覆盖掉，所以最好就是您这边能进行修改...

**Comment by happy888888** [comment]
更新到最新代码，目前配置文件支持指定期望案件数量和超时时间，如果超时时间内没办法获得足够的案件数量就退出

**Comment by happy888888** [comment]
投弃权票有效吗

**Comment by wangmanv2** [comment]
问了一下客服娘，客服娘回复说无效。。

**Comment by happy888888** [comment]
那投票正确率有影响吗？没投对有效吗？目前没有太好的办法协助判断，也不知道投票前可否获取"众议观点"来协助判断。每次想测试时都找不到案件........

**Comment by wangmanv2** [comment]
投票前好像是可以看观点的，我也不太清楚投票正确率对奖励的影响。应该不要太低就好吧，（如果我是风控的话设定应该是在80左右吧）太低应该还是会有影响的。

**Comment by happy888888** [comment]
百度的识别对阴阳怪气的评论识别正确度很低，很多时候还不如全部投删除票，如果可以投票前看观点的话那我可能改成依靠别人的观点(或者别人对观点的点踩)来判断

**Comment by LetMeDecay** [comment]
不知道你是哪知道的消息
今年我只拿到3个月带会员，4k多案件
去年是送的7个月，6k多快7k案件

**Comment by wangmanv2** [comment]
私聊客服娘就可以了解了，去年案件完全解决是可以拿到一整年的（可以缺少150左右个案件），这个是最高的奖励。

如果没有做到就是另外的算法即每一千案件约等于一个月大会员。

阴阳怪气的评论在NLP上是蛮难识别的，我也没什么特别好的建议。遇到那些没多少人评判的，多等一段时间，观察评判结果再进行评判？（每个案件可以等待30分钟）

**Comment by happy888888** [comment]
> 不知道你是哪知道的消息
> 今年我只拿到3个月带会员，4k多案件
> 去年是送的7个月，6k多快7k案件

平均每天完成20个一年也才7300个，这奖励太难拿了
目前还没有做等待，在昨天改为了直接观察投票人数，什么票投票人数高就投啥

**Comment by happy888888** [comment]
程序里在投票前能查到案件的投票人数，然后再投票，网页上并不能，而且网页上如果查看案件不投票离开查看下一个案件直接算做弃权，并不知道程序有没有这样的限制(猜测是没有的)，确实如果能获取投票数再依靠延时后判断几乎能100%正确了

**Comment by happy888888** [comment]
想完全覆盖所有案件，使用云函数作为运行环境是比较好的，把案件投票超时时间设置短一些，再每隔半小时运行一次(最好关闭除风纪委投票的其他功能)

再actions里可以通过将超时时间设置长一些来增大单次运行获取的案件数量。

当然本地或服务器运行的不管是增加运行次数(频率)还是增加运行时间来增大案件的覆盖率都是可行的

**Comment by wangmanv2** [comment]
BTW 有个问题就是，即使我已经完成了今天的案件审查但是还是需要等待预设时间，才能结束程序。应该逻辑判断上还能再优化一下，感谢了。

表现如下： 
```
[WARNING***: 帐号1: 风纪委员案件已审满
[INFO***: 帐号1: 风纪委员投票等待300s后继续获取案件
```

**Comment by happy888888** [comment]
已将判断任务是否完成的逻辑放到了延时前面

**Comment by LetMeDecay** [comment]
`真给力 , 移交众裁的举报案件已经被处理完了`
好像今天不推案件了

看了下action记录
`[WARNING***: xxxxx: 风纪委员没有新案件了`

**Comment by wangmanv2** [comment]
还有一个问题就是如果一天内多次运行程序，会存在重复执行小心心的心跳任务过程。

能否设置达到每日上限后不执行小心心获取呢？网页端的话会提示已经达到小心心的最大值了，不清楚API的话是否有相应的获取方式。

**Comment by happy888888** [comment]
在哪里看小心心是否最大值了？网页能看程序就没理由不能看，如果真的能看就可以设计成同时在所有勋章房间心跳，直到获得足够小心心后退出了，也能大大节约时间

**Comment by wangmanv2** [comment]
网页是达到最大的时候有个对话框弹出提示已达到最大值了，查看的话我没找到。

**Comment by happy888888** [comment]
啥样的对话框，最好网页截个图，网址也要

**Comment by wangmanv2** [comment]
这个不太好截图，它只是一个在观看直播的时候跳出来的蓝色框框，一两秒就没了（而且好像一天只提示一次）。提示语是 今日获取小心心已达上限 ，仅此而已。

**Comment by wangmanv2** [comment]
或者换个思路？ 检测到包裹内有24个7天的小心心 就停止获取？

**Comment by loststar** [comment]
> 更新到最新代码，目前配置文件支持指定期望案件数量和超时时间，如果超时时间内没办法获得足够的案件数量就退出

我有个想法，或许可以把风纪投票独立成一个任务？每天多次执行这个就行

**Comment by wangmanv2** [comment]
目前我采用的是将风纪委员的投票抽离出来，单独做一个config，然后用一个单独的action去执行（每半个小时一次一次持续一分钟）。比较折中的方案。

**Comment by happy888888** [comment]
改workflow的话其实一个就够了，可以生成`config.json`文件后`mv`命令改名为`config1.json`和`config2.json`，再执行`python3 BiliExp.py -c config1.json && python3 BiliExp.py -c config2.json`，目前可以设置每次风纪委员投票只判断一次，本来是为了兼容云函数这种运行时间受限的环境使用的，云函数的定时比较精确不像actions启动都要花费很长时间
