### ISSUE TITLE
执行完最后一个任务，推送消息时报错

### ISSUE THREAD

**Issue by FairyWorld** [happy888888/BiliExp#148]
![image](https://user-images.githubusercontent.com/32956212/104085216-9132fd80-5288-11eb-8936-ebdb5f48205f.png)
好像是从昨天的版本开始，控制台多了一条报错信息。应该是推送时出现问题, 但是在使用过程中任务确实已经完成，并且通过server酱成功推送到微信一切正常，只是不明白控制台的这条报错是什么原因

**Comment by happy888888** [comment]
已修复，是私信消息不存在时导致的错误，还真有账号消息中心里一条消息都没有的吗。

这个功能是获取别人对你的@消息和私信消息用的，比如互动抽奖抽中了别人联系你什么的可以获得通知，不需要可以关闭这个功能

**Comment by FairyWorld** [comment]
> 已修复，是私信消息不存在时导致的错误，还真有账号消息中心里一条消息都没有的吗。
> 
> 这个功能是获取别人对你的@消息和私信消息用的，比如互动抽奖抽中了别人联系你什么的可以获得通知，不需要可以关闭这个功能

1-13的最新版本，天选时刻和获取小心心是不是串行任务? 很久之前的版本我开启两个账号执行任务总时长基本等于单个账号小心心任务的时长，应该两个号的小心心任务是并行的(我记得之前config.json的注释也是这样说的)。昨晚12点多更新了下版本，天选保持默认参数，小心心个数改为25，时长改为125，结果两个号执行了6个多小时。
暂时没有遇到什么bug, 只是想了解一下大概执行的总时长，方便观察数据，总时长是不是就是: (单个账号) 天选 + 小心心。昨晚的推送消息太多了，我又是选择了完整消息推送，超出长度导致电报请求失败，下次我要把参数调小一点再测试。

**Comment by happy888888** [comment]
每个账号的每个任务都是并行的，整个程序运行时间几乎等于单个账号花费时间最长的任务。

当然我用的协程模型并不是完全并行的，同一时间只有一个任务在执行，只是利用每个任务的执行间隙来执行其他任务，比如心跳任务（）每个心跳花费的时间是毫秒级的，但是每个心跳要间隔1-5分钟左右，那么在这个间隔就可以去执行其他任务

所以账号数量的增加和任务数量的增加对执行时间也是会增加的

**Comment by FairyWorld** [comment]
> 每个账号的每个任务都是并行的，整个程序运行时间几乎等于单个账号花费时间最长的任务。
> 
> 当然我用的协程模型并不是完全并行的，同一时间只有一个任务在执行，只是利用每个任务的执行间隙来执行其他任务，比如心跳任务（其他任务也是如此）每个心跳花费的时间是毫秒级的，但是每个心跳要间隔1-5分钟左右，那么在这个间隔就可以去执行其他任务
> 
> 所以账号数量的增加和任务数量的增加对执行时间也是会增加的
刚刚发现了一个天选时刻取关的问题(还不能确定是不是问题)，我看了下控制台确实有显示取关成功，但实际上我的关注列表是不断变多的，今天两个账号都加了40多个关注。因为现在还没有确定是不是多个action同时导致的，因为我设置的参数比较大执行的比较久然后定时器1小时一次，这时上次action没完成下次就执行了。所以今晚回宿舍进行单个action测试再确定这个问题

**Comment by happy888888** [comment]
> > 每个账号的每个任务都是并行的，整个程序运行时间几乎等于单个账号花费时间最长的任务。
> > 当然我用的协程模型并不是完全并行的，同一时间只有一个任务在执行，只是利用每个任务的执行间隙来执行其他任务，比如心跳任务（其他任务也是如此）每个心跳花费的时间是毫秒级的，但是每个心跳要间隔1-5分钟左右，那么在这个间隔就可以去执行其他任务
> > 所以账号数量的增加和任务数量的增加对执行时间也是会增加的
> > 刚刚发现了一个天选时刻取关的问题(还不能确定是不是问题)，我看了下控制台确实有显示取关成功，但实际上我的关注列表是不断变多的，今天两个账号都加了40多个关注。因为现在还没有确定是不是多个action同时导致的，因为我设置的参数比较大执行的比较久然后定时器1小时一次，这时上次action没完成下次就执行了。所以今晚回宿舍进行单个action测试再确定这个问题

我看了一下确实有这个bug
我想象的执行流程：
程序参与天选时刻-->B站关注主播-->B站回应程序参加天选时刻成功-->程序取关up主-->B站回应程序取关成功

测试流程：
程序参与天选时刻-->B站回应程序参加天选时刻成功-->程序获取与主播的关系-->B站回应程序(未关注)-->程序取关up主-->B站回应程序取关成功-->程序休眠-->程序获取与主播的关系-->B站回应程序(已关注)

由此猜测实际的执行流程应该为：
程序参与天选时刻-->B站回应程序参加天选时刻成功-->程序取关up主-->B站回应程序取关成功-->B站关注主播
这样取关操作就是无效的...........

**Comment by FairyWorld** [comment]
> > > 每个账号的每个任务都是并行的，整个程序运行时间几乎等于单个账号花费时间最长的任务。
> > > 当然我用的协程模型并不是完全并行的，同一时间只有一个任务在执行，只是利用每个任务的执行间隙来执行其他任务，比如心跳任务（其他任务也是如此）每个心跳花费的时间是毫秒级的，但是每个心跳要间隔1-5分钟左右，那么在这个间隔就可以去执行其他任务
> > > 所以账号数量的增加和任务数量的增加对执行时间也是会增加的
> > > 刚刚发现了一个天选时刻取关的问题(还不能确定是不是问题)，我看了下控制台确实有显示取关成功，但实际上我的关注列表是不断变多的，今天两个账号都加了40多个关注。因为现在还没有确定是不是多个action同时导致的，因为我设置的参数比较大执行的比较久然后定时器1小时一次，这时上次action没完成下次就执行了。所以今晚回宿舍进行单个action测试再确定这个问题
> 
> 我看了一下确实有这个bug
> 我想象的执行流程：
> 程序参与天选时刻-->B站关注主播-->B站回应程序参加天选时刻成功-->程序取关up主-->B站回应程序取关成功
> 
> 测试流程：
> 程序参与天选时刻-->B站回应程序参加天选时刻成功-->程序获取与主播的关系-->B站回应程序(未关注)-->程序取关up主-->B站回应程序取关成功-->程序休眠-->程序获取与主播的关系-->B站回应程序(已关注)
> 
> 由此猜测实际的执行流程应该为：
> 程序参与天选时刻-->B站回应程序参加天选时刻成功-->程序取关up主-->B站回应程序取关成功-->B站关注主播
> 这样取关操作就是无效的...........

> 原来是这样，刚刚我看了下应该只有部分取关成功，不是全部没取关。
> 因为5点多中了一次天选，我点进去主播哪里发现我没有关注，之前没有玩过天选这东西，不知道先关注中奖了然后取关，接着关注回去领取奖励会不会被发现。
> 今天一天中了5次，好像3张舰长优惠卷，还有一个游戏物品之类的和一个cos自拍，不过有点尴尬中奖之后不知道是实物还是虚拟货品有些还不知道中的是什么东西要google搜索一下..

**Comment by happy888888** [comment]
可以通过配置文件过滤一些天选时刻不参与的

**Comment by FairyWorld** [comment]
> 可以通过配置文件过滤一些天选时刻不参与的

- 我好像知道为什么脚本有时会执行几个小时有时却执行30分钟了，我觉得很大可能是同时执行了天选时刻和获取小心心这些耗时的任务。因为我设置的参数比较大理论上单个action执行会有点久，然而我的cron是每隔一小时执行, 只要第一个action没有在一小时执行完，那么第二个action还是会启动, 因为这两个action相当于在两个不同docker并发运行，而且用的是同一个账号。

- 今天无意中试了一下，全程单个action大概1小时左右。如果在运行时同时跑了2-3个action。所有action在控制台的日志在某个地方都会卡住很久不动(有些地方甚至半个多小时也不动), 然后大概要跑3-6小时才能完成，今天好像有一次超过6小时被github取消了，还有2次3个多小时卡住了我手动取消，感觉就是某一次时间点重叠导致多个action一起运行导致的, 然后一直这样重复到晚上我关闭执行

**Comment by happy888888** [comment]
你天选时刻超时时间是设置的多久？如果超时是强制结束任务的

**Comment by FairyWorld** [comment]
> 你天选时刻超时时间是设置的多久？如果超时是强制结束任务的

天选时刻和小心心都是一个小时，忽略其他任务最多就两小时。但是不知道为什么有时会半小时结束了，是不是小心心任务如果我今天获取完24颗了，下一次执行action就会跳过(但是我在控制台看到，即使我已经获取并发送完毕，下一次action还是会打印出获取小心心和发送小心心的日志)。卡住的时候一般就是有一个action在天选，其他几个action可能是天选可能是小心心
