### ISSUE TITLE
fork最新云函数版本运行错误

### ISSUE THREAD

**Issue by LxDebug** [happy888888/BiliExp#151]
两种方式都报错
![B9621253-BF85-457D-B707-9255ABEABCD6](https://user-images.githubusercontent.com/27006147/104096035-13491380-52d5-11eb-8853-cfffcf791149.png)
![7E95ACFB-A02E-47A1-BD37-069A706E8322](https://user-images.githubusercontent.com/27006147/104096037-16440400-52d5-11eb-9173-01fd16aa0e2c.png)

**Comment by happy888888** [comment]
config.json文件第81和82行，数组应该用英文逗号分隔，你用的中文逗号，不符合json规范

**Comment by LxDebug** [comment]
已经解决，正如你所说，十分感谢
