### ISSUE TITLE
有粉丝牌的直播间不会自动发送弹幕

### ISSUE THREAD

**Issue by Gensokyo1995** [happy888888/BiliExp#152]
"xlive_heartbeat_task": { // 任务:发送直播心跳，可用于获得小心心(每5分钟1个)和大老爷在线时长加经验(费时，不建议在云函数使用)
        	                      // 删除22行-29行可关闭本任务，下面为本功能详细配置
            "enable": true,      //任务开关，值为true或false分别代表开启和关闭
            "room_id": [这里我填写了16个直播间id],       // 直播间id，值为整数数组，若值为空数组会自动获取拥有勋章的直播间(在线的，勋章等级高的，等级亲密度高的优先)，建议手动指定
            "num": 12,            // 心跳次数，值为整数，心跳达到次数退出
            "time": 17,          // 心跳分钟数，值为数字(单位分钟,允许小数),心跳的时间，达到时间退出
            "send_msg": "1"       // 向所有未点亮粉丝牌的房间发送消息(作用是点亮粉丝牌)，值为字符串，为空字符串则不发送
        },

这样填写了，能自动获取24个小心心了，但是不会在相应直播间发送1的弹幕，执行任务后去直播间看了没有看到相应的弹幕，粉丝牌经验没有增加，能麻烦看看是什么问题吗

**Comment by Gensokyo1995** [comment]
是不是只会向未点亮粉丝牌的直播间发送弹幕？可以设置成有粉丝牌的直播间每天都会发送一条弹幕吗？每天都能获取100的亲密度呢

**Comment by happy888888** [comment]
已改为想所有拥有粉丝牌的房间发送消息

**Comment by happy888888** [comment]
请不要直接在仓库config.json中存放cookie，可以使用专门存放cookie的secrets biliconfig或者能存放整个配置文件的secrets advconfig

**Comment by Gensokyo1995** [comment]
多谢提醒，复制配置的时候忘记删除了
