### ISSUE TITLE
BiliExp-Actions配置完后没有发现runbiliEXP

### ISSUE THREAD

**Issue by pofang** [happy888888/BiliExp#156]
点了star弹出了这两个，我佛了
![20210113095612](https://user-images.githubusercontent.com/77334379/104397340-972a2680-5587-11eb-8b5d-f4a13124d937.png)

**Comment by happy888888** [comment]
你要先切换到actions分支，首页有切换分支的说明

**Comment by pofang** [comment]
> 你要先切换到actions分支，首页有切换分支的说明
> 
> 图片加载不出来参考这个issue #100

好的谢谢，再请问一下投币数在哪修改成每天只投两个?

**Comment by happy888888** [comment]
改config/config.json文件第60行，修改后可以把整个文件放secrets（advconfig）中防止同步时配置被覆盖

**Comment by pofang** [comment]
> 改config/config.json文件第60行，修改后可以把整个文件放secrets（advconfig）中防止同步时配置被覆盖

没看明白，修改完是放在哪个文件夹里吗还是放其他地方
能具体说说怎么设置吗？谢谢

**Comment by happy888888** [comment]
修改完config.json，整个文件，复制粘贴放进secrets里面，一共有三个secrets可用于配置，一个放账号cookie，一个放消息推送key，一个放配置文件，当然配置文件也可以包含前两个secrets的内容

**Comment by pofang** [comment]
> 修改完config.json，整个文件，复制粘贴放进secrets里面，一共有三个secrets可用于配置，一个放账号cookie，一个放消息推送key，一个放配置文件，当然配置文件也可以包含前两个secrets的内容

![20210113150935](https://user-images.githubusercontent.com/77334379/104418240-90b0a480-55b1-11eb-87e6-df62b6d28efe.png)
是这样吗老哥?，名字用原名还是用其他名字

**Comment by pofang** [comment]
> 修改完config.json，整个文件，复制粘贴放进secrets里面，一共有三个secrets可用于配置，一个放账号cookie，一个放消息推送key，一个放配置文件，当然配置文件也可以包含前两个secrets的内容

大哥我求求你回回我吧😭😭😭😭😭😭
你只要点个头就行了😭😭😭😭😭😭
![20210114195219](https://user-images.githubusercontent.com/77334379/104587693-3fcca900-56a2-11eb-966d-e769cc076df4.png)

**Comment by happy888888** [comment]
![image](https://user-images.githubusercontent.com/67217225/104588788-dea5d500-56a3-11eb-8183-d0390e50760c.png)

**Comment by pofang** [comment]
> 修改完config.json，整个文件，复制粘贴放进secrets里面，一共有三个secrets可用于配置，一个放账号cookie，一个放消息推送key，一个放配置文件，当然配置文件也可以包含前两个secrets的内容

感谢感谢，还有个问题请问脚本运行了一会就这样是正常的吗?
![IMG_20210114_203854](https://user-images.githubusercontent.com/77334379/104592293-e9af3400-56a8-11eb-8704-417e21a940da.jpg)

**Comment by happy888888** [comment]
那看你超时设置的多少了

**Comment by pofang** [comment]
> 那看你超时设置的多少了

超时是在哪一行，最佳设置多少?求解

**Comment by happy888888** [comment]
配置文件内都有详细说明，默认850秒，要获得24个小心心需要单个直播间心跳两小时，两个直播间就只要一小时

**Comment by pofang** [comment]
> 配置文件内都有详细说明，默认850秒，要获得24个小心心需要单个直播间心跳两小时，两个直播间就只要一小时

![IMG_20210115_000920](https://user-images.githubusercontent.com/77334379/104617864-f17dd100-56c6-11eb-97ff-888edbad6cf8.jpg)
找到了，大哥我能修改成24个小时🐴?如果修改成其他时间，哪些代码还需修改?

**Comment by pofang** [comment]
> 配置文件内都有详细说明，默认850秒，要获得24个小心心需要单个直播间心跳两小时，两个直播间就只要一小时

大哥我只想问一下这个最多能设置多少秒，修改最长时间后其他的设置是否需要改，求解😭

**Comment by happy888888** [comment]
并没有运行时间规定上限，修改时间后其他设置不用改

**Comment by pofang** [comment]
> 并没有运行时间规定上限，修改时间后其他设置不用改，每个模块的运行都是相对独立的

 以后更新需要怎么做?代码会自动更新吗?
cookies以后失效了可以在secrets中的biliconfig点击update更新吗？

**Comment by happy888888** [comment]
cookie失效可以update biliconfig，一般浏览器不主动退出的话有效期是半年(主动退出立即失效)，具体有效期可以在浏览器上查看，就是复制cookie那个地方右边有cookie的过期日期

有个auto_merge的actions可以手动运行或者设置定时运行，详细配置actions分支的主页有说明，要稳定运行可以不用更新代码，不然可能导致代码更新了配置文件没更新导致错误

**Comment by pofang** [comment]
> cookie失效可以update biliconfig，一般浏览器不主动退出的话有效期是半年(主动退出立即失效)，具体有效期可以在浏览器上查看，就是复制cookie那个地方右边有cookie的过期日期
> 
> 有个auto_merge的actions可以手动运行或者设置定时运行，详细配置actions分支的主页有说明，要稳定运行可以不用更新代码，不然可能导致代码更新了配置文件没更新导致错误

好的，非常非常感谢，意思就是说不更新代码也行是这个意思吧?
应该是最后的一个问题了:我的两个账号现在都没有在手机上使用，如果下次再手机app上登录会刷新cookies吗?还有个问题比如电脑浏览器登录了账号，我在手机上的网页版也登录了账号这样会导致cookies刷新吗？
害，说简单点就是一个账号在三个不同的环境运行下是否会导致cookies刷新😓

**Comment by happy888888** [comment]
理论上只要不退出就不会刷新，实际没测试过

**Comment by pofang** [comment]
> 理论上只要不退出就不会刷新，实际没测试过，账号失效也会消息推送的

好的

**Comment by pofang** [comment]
> 理论上只要不退出就不会刷新，实际没测试过，账号失效也会消息推送的

- [ ] 大哥这是什么情况，是action每次任务最多只能让我跑6个小时吗?

> 理论上只要不退出就不会刷新，实际没测试过，账号失效也会消息推送的
大哥这是什么情况，是action每次任务最多只能让我跑6个小时吗?
![IMG_20210116_072138](https://user-images.githubusercontent.com/77334379/104788125-553df200-57cc-11eb-9653-48993d422ed3.jpg)

**Comment by happy888888** [comment]
对，单次actions上限是6个小时

**Comment by pofang** [comment]
> 对，单次actions上限是6个小时

感谢感谢

**Comment by pofang** [comment]
> 对，单次actions上限是6个小时

哥我又来了😅，有个小问题请问一下，一开始还能中几块低保，现在就只能中加速器和舰长代金券了，是运气问题🐴?

**Comment by happy888888** [comment]
不太清楚B站的抽奖逻辑，但从经验来看中奖少的账号中奖几率会高一些，哪怕是1、2级账号，所以那些不想要的奖品就建议不抽，而且一般大奖主播都是设置需要投喂或者有粉丝勋章等级要求的，过滤掉这些后能抽的奖就比较少了。当然也可以取消粉丝勋章等级的限制在日志里看哪些主播是经常抽奖的去获得一个主播的粉丝勋章参与那些限制条件更高的抽奖。

这里仅代表个人意见，你也可以另开一个issue看看其他人的有没有什么其他看法。

**Comment by pofang** [comment]
> 不太清楚B站的抽奖逻辑，但从经验来看中奖少的账号中奖几率会高一些，哪怕是1、2级账号，所以那些不想要的奖品就建议不抽，而且一般大奖主播都是设置需要投喂或者有粉丝勋章等级要求的，过滤掉这些后能抽的奖就比较少了。当然也可以取消粉丝勋章等级的限制在日志里看哪些主播是经常抽奖的去获得一个主播的粉丝勋章参与那些限制条件更高的抽奖。
> 
> 这里仅代表个人意见，你也可以另开一个issue看看其他人的有没有什么其他看法。

好的，非常感谢
