### ISSUE TITLE
auto merge会报错

### ISSUE THREAD

**Issue by chaixin25** [happy888888/BiliExp#157]
在push commits里会报如下错误：
Run git push origin $DOWNSTREAM_BRANCH
To https://github.com/chaixin25/BiliExp
 ! [remote rejected] BiliExp-Actions -> BiliExp-Actions (refusing to allow a GitHub App to create or update workflow `.github/workflows/run_BiliExp.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/chaixin25/BiliExp'
Error: Process completed with exit code 1.

**Comment by happy888888** [comment]
auto merge没有权限同步workflows文件夹里的变更，需要手动同步

**Comment by chaixin25** [comment]
手动怎么弄

**Comment by happy888888** [comment]
访问这个链接创建一个反向的pull request https://github.com/chaixin25/BiliExp/compare/BiliExp-Actions...happy888888:BiliExp-Actions
