### ISSUE TITLE
天选时刻自动取关功能有待优化

### ISSUE THREAD

**Issue by if1y** [happy888888/BiliExp#160]
天选时刻的 `unfollow` 参数能在参与天选后立即取消关注。
实际操作中，若账号**原本已经关注主播**，抽奖时要求条件为“关注”，则程序在参加天选时刻后**依然会自动取关，导致“被迫”取关**。

理想优化：
- 对于已经抽奖时**已经关注的主播，直接参与抽奖，且不执行取关操作**
- 对于**取关行为，最好改在抽奖结束、结果公布后再进行**，避免算法上可能因此判断为“未关注”而不予发奖

**Comment by happy888888** [comment]
这两个问题我曾经都想过
1. 存在第一个问题，是因为我想的是***避免关系判断可能因为请求次数过多出错***，我并没有对关系判断的接口做过并发测试，目前我做过并发测试的接口有***关注取关***的接口(这个接口有很多个，但是目前只有一个能稳定使用(2分钟内成功关注2000个用户并取关重复多次都能成功)，其他的在关注取关操作***100次***左右就会出错)，***搜索天选时刻***的接口(5个账号每间隔5分钟搜索5个不同的分区的前40页不会报错，目前没发现并发上限)等等，最严格的接口是***转盘活动抽奖***的接口，5s内只允许请求一次，哪怕家里有两台电脑用两个账号也不能在5s内请求两次。***目前对没经过测试但请求频繁的接口的使用采取保守态度***
2. 取关这个问题是为了***避免程序被打断导致的没有取关***的问题，目前这种模式程序遭到突然打断(任务timeout超时打断，云函数和actions本身也有执行时间上限导致强制打断)时最坏的情况是有一个关注的主播没有被取关，***延后取关行为将导致这种情况恶化***。

第一个问题将在后续解决，第二个正在探索解决方法(目前探索过的方法有使用关注用户分组区分主播)

**Comment by if1y** [comment]
1. 第一个，不知道关注数量的接口有没有试过，感觉限制可能会宽松一些？我的想法是**在发送参与天选时刻的请求前后分别对比关注的数量，如果没有变化，说明本次的主播是已经关注的，于是不执行取关**。不过这种间接实现的方法，针对极限状态下应该会出现误差。（结合下一条，使用分组应该会更好）

2. 第二个，分组应该是不错的方案。之前也看过其它项目使用分组，专门用一个独特的分组名。这样应该还能**顺便解决前一个问题**。只需设定**每隔一段时间** _（比如，每天凌晨4点，没有正在等待结果的天选时刻，则运行取关，否则待结果出来后执行）_ **针对分组成员全部取关，而不是每次参与抽奖后就取关**，因此也不用担心程序超时造成错过取关。

**Comment by if1y** [comment]
另寻求帮助：

今天升级到了最新版，就是重写后的天选时刻。

超时设定为 `"timeout": 20000`，按理说应该能持续执行5个半小时左右。但**实际两轮执行，分别只运行了2小时和1小时，Actions 就退出了**，报错为
```
天选时刻抽奖任务异常，原因为('NoneType' object is not subscriptable)，退出任务
```
看不出来具体是什么原因。

同时发现参加的天选时刻，在日志中**均没有监测到中奖结果**。

**Comment by happy888888** [comment]
天选时刻的关注是在默认分组里的改不了，想用关注分组只能在参加天选时刻前提前关注，又会回到关注接口的问题

目前中奖结果由一个名为直播小喇叭的账号通过私信来推送，由项目里的msg_notify_task进行私信的推送，同时推送@消息，因为有的动态抽奖中了会有人@你

**Comment by if1y** [comment]
那看来还是需要测试了关注/取关的接口才好做后续。

---

抽奖结果通报，这个我此前也有启用，记得当时在日志里也会写 `天选时刻XXXX没有中奖` 的。
其实现在**主要问题是配置升级上来之后，总是没达到超时设定就提前结束了**，就把二者关联起来考虑会不会有相关性。

**Comment by happy888888** [comment]
以前采用的一直在同一个直播间参加天选时刻，不断在同一个房间轮询，判断房间里是否有天选时刻的接口与抽奖结果的接口是同一个，参与后自然可以判断结果，现在为了参加更多天选，参加完成后就跑其他房间去了，并不会在房间里等待天选的抽奖结果，抽中了直播小喇叭会通知的
![image](https://user-images.githubusercontent.com/67217225/104541531-be065c80-565c-11eb-95eb-4efd9691ff23.png)
这个通知只要没有把状态转换成"已读" msg_notify_task都会推送

**Comment by happy888888** [comment]
由于有些事非实物奖品，故没有添加自动填写奖品收货地址的功能，只做消息推送

**Comment by happy888888** [comment]
改为 搜索直播间-->参加天选-->搜索下一个-->休眠一个周期-->取关已经结束的天选主播-->任务超时-->取关所有主播
                   ↑                  ↑-----------<--↓                                                               ↓
                   ↑---------------------------------------------------------------------<--↓
改为这样的执行顺序呢

**Comment by happy888888** [comment]
目前取关前会判断是否是参加天选时刻以前就关注过的

取关动作尽量延后到天选结束(任务超时会立即取关不会等待天选结束)

**Comment by if1y** [comment]
好

所以接口的频率限制是测速出来了吗？还会考虑以分组的形式实现么

**Comment by if1y** [comment]
可能有bug？

1. 天选时刻有个账号设置**只参与无限制、勋章1级**，结果收到了关注的私信，对应主播也出现在了关注分组和直播列表里。
    根据实际推断查找对应的log，结果并无相关记录。
    但我个人确实是没有关注过该主播的，只有可能是程序行为。

2. 最近执行发现，脚本快6小时也没退出，而当时天选时刻的超时是9999s（不到3小时），目前一共遇到2次

**Comment by happy888888** [comment]
只参与无限制就不要填关注分组那个参数

超时失败只是天选时刻吗，其他有超时功能的模块是否正常退出(日志里会显示超时退出)

**Comment by if1y** [comment]
> 只参与无限制就不要填关注分组那个参数
> 
> 超时失败只是天选时刻吗，其他有超时功能的模块是否正常退出(日志里会显示超时退出)

日志我清理掉了，记得有个 lottery_task，然后报错是类似于 python 那种，不是BiliExp定义的日志。
这两天也确实没有转发任何抽奖动态。
天选时刻的超时日志在这之前就执行完并输出了一条。

**Comment by happy888888** [comment]
就是超时了还不知道哪个模块在运行占用时间吗

**Comment by if1y** [comment]
差不多是这个意思。
如果目前不好排错的话，我再多观察几天，下次遇到补log。

**Comment by if1y** [comment]
目前暂未复现 lottery_task 的问题。 @happy888888 
不过发现了另一个问题：天选时刻超时设置为20202s（小于6h），理论上到达这个时候就会结束脚本。使用两个账号同时运行，当账户A已经超时退出，账户B报错`获取直播间列表异常,原因为()`，随后继续参与天选时刻，直到超出 Actions 最大时长。

具体可参见我的 Actions 第113、第114

**Comment by happy888888** [comment]
lottery_task 的问题目前已修复

获取直播间列表异常是因为B站服务器强制把程序连接断开了并没有给出回复，根据日志来看貌似只要有这个异常出现就不会触发超时了

**Comment by happy888888** [comment]
我去查看了一下超时器的源码 https://github.com/aio-libs/async-timeout 并没有找到超时会失效的原因，也没在issue中发现相关问题，但是几乎可以肯定是发生了服务器断开的异常后才会发生这种情况
最新版本会打印出天选发生异常的详细信息辅助解决问题

**Comment by happy888888** [comment]
超时问题已修复

**Comment by if1y** [comment]
> 超时问题已修复

好的。

话说这里的注释是不是有点矛盾。
https://github.com/happy888888/BiliExp/blob/e1a4237c3559e7fea2240a82cf8fc4850c0391cd/config/config.json#L43
https://github.com/happy888888/BiliExp/blob/e1a4237c3559e7fea2240a82cf8fc4850c0391cd/config/config.json#L57

`unfollow=true` 到底是 参与立即取关 还是 出结果后取关

**Comment by happy888888** [comment]
没超时前等待出结果后取关，超时了就不可能等待出结果只能立即取关啊，这很难理解吗

**Comment by if1y** [comment]
本来我是这么认为的，包括之前的 https://github.com/happy888888/BiliExp/issues/160#issuecomment-759976334 也让我认为是这么回事

但是看了这俩注释：

> 前一条注释是 **结束后**取消关注
> 后一条注释是 **不等待**天选**结束**直接取关 （也就是立即取关）

这两条注释都是针对 `unfollow = true` 来解释的，那么二者就冲突了。

----

你应该是想表示 ：

> 超时参数在 unfollow = true 的情况下还多了一个取消关注的功能，即超时立即取关

目前的表述有点歧义……

个人觉得改成 `unfollow 为 true 时**发生超时**则会立即取消关注，不再等待结果` 可能不容易产生歧义吧……

**Comment by happy888888** [comment]
unfollow参数是等待天选结束的，但是仔细想想就会发现超时后任务退出了就没办法等待了呀，这是逻辑上的常识吧。

有没有歧义还要看位置的，如果`不等待天选结束直接取关主播`是注释在`unfollow`参数旁边的，那么确实应该把注释改成你说的这样，但是注释在`timeout`参数旁边就不需要了，因为这个注释是写给`timeout`参数用的
