### ISSUE TITLE
互动抽奖如何排除关键词

### ISSUE THREAD

**Issue by if1y** [happy888888/BiliExp#161]
目前已有的互动抽奖字段`keywords`是**存在关键词即转发、评论、点赞**，但根据实际使用中发现，经常有抽奖结果的动态被误判为抽奖，而纳入转发（原因是恰好包含了“抽奖”等关键词）。

我的想法是排除掉某些关键词，比如“恭喜”。

尝试使用正则`^((?!恭喜).)*$`，使用测试器似乎并无问题，但实际执行却把动态里的所有不包含“恭喜”的动态都转发了……

**所以应该如何编写正则进行排除？或者能否增加一个字段，直接排除关键词。**

**Comment by happy888888** [comment]
包含 `#抽奖#` 标签但不包含`恭喜`关键字，可以这样表示 `^((?!恭喜).)*#抽奖#((?!恭喜).)*$`
