### ISSUE TITLE
给 msg_notify_task 加个过滤条件？

### ISSUE THREAD

**Issue by if1y** [happy888888/BiliExp#163]
很多主播都设置了**关注时的自动私聊欢迎，这导致最终的推送结果会计入这些无意义的条目**。
如果能有关键词过滤功能，对 `欢迎`、`感谢`、`关注` 等几个关键词进行过滤，应该会好很多。

**Comment by happy888888** [comment]
被过滤掉还需要设置消息已读吗

**Comment by happy888888** [comment]
目前增加了设置过滤关键字的功能

**Comment by if1y** [comment]
应该可以已读
