### ISSUE TITLE
个人使用后的一些感受和情况

### ISSUE THREAD

**Issue by tlj218** [happy888888/BiliExp#165]
我没有学过编程，用的是树莓派，纯属个人兴趣捣鼓。
按照作者的教程方式五、linux本地部署，我操作了，但是第二天没看到运行，也许是我根本看不懂吧。
在crontab我也发现了定时任务。然后，我想起以前玩树莓派的操作方式，我就把作者的所有文件都下载了下来，并且设置好参数，然后用命令直接运行BiliExp.py，成功运行。然后又发现风纪委投票，没有案件。打算让他一整天都运行，可是我不会。于是找来一个可以定时的PY文件，设置成一小时运行一次BiliExp.py，俗称套娃。也成功了。
下面说一下我发现的一些情况。
B站每天会在早晨六点，下午两点，晚上十点这三个时间段集中放出需要投票的案件，所以建议第一次运行没有案件的，可以多运行一段时间。
作者程序里面的小心心代码，貌似没有作用，这也许是和B站对直播区监管越来越严格有关，但是可以自动给所有拥有勋章的直播间发个弹幕点亮勋章，白嫖100经验是可以运行成功的。
以上是我发现的一些情况，希望对大家有用。

**Comment by happy888888** [comment]
方式5是给x64 linux使用的，树莓派是arm的当然跑不起来。

小心心不可用，但是心跳日志是否是正常的？

**Comment by tlj218** [comment]
> 方式5是给x64 linux使用的,树莓派是手臂的当然跑不起来。
> 
> 小心心不可用,但是心跳日志是否是正常的？目前我还没有发现小心心的接口发生变动,应该是能成功的
[INFO]: 当前程序版本为v1.1.9,配置文件版本为v1.1.9
[INFO]: 左天都: 等级5,经验17945,剩余硬币1576.5
[INFO]: 左天都: 成功分享av号为246022723的视频
[INFO]: 左天都: 漫画今天已经签到过了
[INFO]: 左天都: 直播签到失败，信息为：今日已签到过,无法重复签到
[WARNING]: 左天都: 风纪委员投票失败，案件已审满，当前裁决正确率为：98%
[INFO]: 左天都: 成功模拟观看av号为246022723的视频
[INFO]: 左天都: 给大福李的小可爱们！应援成功
[INFO]: 左天都: 给穆子老弟的应援团①应援成功
[INFO]: 左天都: 给这个桃子甜到掉牙了w应援成功
[INFO]: 左天都: 没有2天内过期的直播礼物，跳过赠送
[INFO]: 左天都: 给慵懒君清的应援团①应援成功
[INFO]: 左天都: 给清严君的应援团①应援成功
[INFO]: 左天都: 给紫雨carol的应援团④应援成功
[INFO]: 左天都: 给沈南溪的秘密花园应援成功
[INFO]: 左天都: 给左天都的应援团应援成功
[INFO]: 左天都: 成功在id为3869194的直播间发送第1次心跳
[INFO]: 左天都: 给万年老痞子的应援团①应援成功
[INFO]: 左天都: 给我愿似一块扣肉呀的应援团应援成功
[INFO]: 左天都: 给豆花天下第一(一条五毛)应援成功
[INFO]: 左天都: 给八宝酱的小饼干们应援成功
[INFO]: 左天都: 给冰阔落了解一哈的应援团①应援成功
[INFO]: 左天都: 给老田儿吖的应援团应援成功
[INFO]: 左天都: 成功在id为3869194的直播间发送第2次心跳
[INFO]: 左天都: 成功在id为3869194的直播间发送第3次心跳
[INFO]: 左天都: 成功在id为3869194的直播间发送第4次心跳
[INFO]: 左天都: 成功在id为3869194的直播间发送完5次心跳，退出直播心跳(达到最大心跳次数)
[INFO]: 未定义消息推送

**Comment by tlj218** [comment]
关于小心心获取，
这个心跳时间，经过我自己的测算，是每隔一分钟出现一次，然后跳五次结束
经过我查看，没有获得小心心

**Comment by happy888888** [comment]
增加心跳次数和心跳时间，你可以试试都改成120来保证心跳时间达到2小时，如果填写多个有小心心的直播间也可以，两个直播间需要1个小时心跳，三个直播间需要40分钟心跳

**Comment by tlj218** [comment]
> 增加心跳次数和心跳时间，你可以试试都改成120来保证心跳时间达到2小时，如果填写多个有小心心的直播间也可以，两个直播间需要1个小时心跳，三个直播间需要40分钟心跳

好的，我试试

**Comment by tlj218** [comment]
继续汇报情况
小心心问题已经解决，可以通过增加心跳次数和时间，还有我当时设置的直播间并不是我拥有勋章的直播间，导致自己没有小心心。
关于风纪委投票，更正一下，之前分享的时间点，有可能是我恰好碰上了，我还是建议大家能够把程序设置成多次运行，例如我现在改成两小时运行一次。

**Comment by hunter8605** [comment]
> 继续汇报情况
> 小心心问题已经解决，可以通过增加心跳次数和时间，还有我当时设置的直播间并不是我拥有勋章的直播间，导致自己没有小心心。
> 关于风纪委投票，更正一下，之前分享的时间点，有可能是我恰好碰上了，我还是建议大家能够把程序设置成多次运行，例如我现在改成两小时运行一次。

如果不是风纪委员,多久运行一次比较合适
