### ISSUE TITLE
直播小心心有没有办法判断任务完成后下次执行的时候自动跳过?

### ISSUE THREAD

**Issue by FairyWorld** [happy888888/BiliExp#166]
1. 经过测试每次执行一次action，小心心任务当前不管有没有完成都会重新执行一次, 没有判断今天完成了24颗就跳过这个任务, 只有等到超时才会结束, 控制台的日志里会显示发送成功(不太清楚原因, 应该上次action已经发送完了)。

2. 希望能够和投币任务一样,  如果24颗满了,  当前如果再执行action就会跳过小心心。

3. 希望能够加入一个执行总时间超时的参数(action默认好像6小时)，超时直接推送消息或者终止程序，如不超过3小时或4小时。昨天半夜有个action导致被封号了，听说就是在滥用action，所以希望加入这个超时的参数。

**Comment by FairyWorld** [comment]
补充一张今天单个action(不是第一次执行, 前面执行了几次没有执行完我手动关闭了)的小心心的图片，感觉有点奇怪，为什么会发送第30次心跳(理论只有24次)，而且日志输出了多次"第30次心跳"(我只开了2个号, 应该最多2次), 然后后面一直在输出心跳超时退出(应该也只有2次才对)
![image](https://user-images.githubusercontent.com/32956212/104686220-b2d42f00-5737-11eb-8882-60d69b065878.png)

**Comment by happy888888** [comment]
目前为了加快小心心获取速度，默认在所有有粉丝牌的房间心跳，说明你一个账号有很多个粉丝牌，如果你有12个粉丝牌理论上只要心跳10分钟就能获得24个小心心

目前并没有找到比较准确的判断小心心任务是否完成的方法

**Comment by FairyWorld** [comment]
> 目前为了加快小心心获取速度，默认在所有有粉丝牌的房间心跳，说明你一个账号有很多个粉丝牌，如果你有12个粉丝牌理论上只要心跳10分钟就能获得24个小心心
> 
> 目前并没有找到比较准确的判断小心心任务是否完成的方法

12个粉丝勋章是不是相当于一个浏览器打开了12个标签去同时观看12个直播间，然后10分钟后每个直播间两个小心心一共24。天选的时候也是这样吗? 同时开着几个直播间

**Comment by happy888888** [comment]
可以这样理解，天选目前是不断搜索直播间然后依次参与，光呆在一个直播间里根本就参加不了多少

**Comment by FairyWorld** [comment]
> 可以这样理解，天选目前是不断搜索直播间然后依次参与，光呆在一个直播间里根本就参加不了多少
> 
> 心跳目前只有超时退出，次数限制被取消了

- 感觉这个超时退出没有强制关闭成功。
- 我设置了天选奖2000s超时，我看到控制台大概从20-30分钟之间把小心心任务执行完了，然后一直执行天选结果2个小时20分还在执行，而且控制台没有新的日志输出，这是不是因为主播设置了“几个小时后才开奖”导致我一直在等待抽奖结果的返回才能结束。
- 昨天发现小心心任务好像有时也会卡住，但是一般就比超时多了10-20分钟就完成了没有天选这么久。刚刚也测试了下最新版本，小心心超时设为12分钟，实际执行到30分钟时还在发送第28颗小心心，即使减去action配置环境(2分钟左右)和一些其他任务(应该很快, 我关了风纪委员)的时间感觉还是超出一点，对整体来说感觉影响不大。只是觉得好像超时了没有强制终止当前任务，应该天选也是这样导致没有被终止

**Comment by happy888888** [comment]
我看了一下你的actions日志，设置了2200s超时，程序执行大概37分钟，没有什么问题啊

**Comment by FairyWorld** [comment]
> 我看了一下你的actions日志，设置了2200s超时，程序执行大概37分钟，没有什么问题啊

- 你看到的这个是我下班前最后一次配置，我把天选的分区和页数减少了很多，超时改为了2000，这次一共执行了37分钟。你可以参考下我这条action前面几个被取消的，就是卡在了抽奖。
- 6-9点现在有3个action同时进行，一个执行了一个小时，一个执行了两个小时，配置和6点左右37分钟完成那个配置是一样的，我没有修改。所以我感觉每次action执行时间差别相差较大有可能是3个原因
- 一是超时了终止执行当前任务但是没有彻底终止
- 二是主播设置了30分钟后开奖之类的导致一直在等待开奖。
- 三是同时执行了多个action, 37分钟那个是单独执行的，大概6.05结束。定时任务是每个小时55分的时候执行，也就是说第二个action和37分钟那个冲突了10分钟，然后卡了2小时。极有可能是B站的接口限制了每分钟请求的次数，然后多个action执行到达了上限，然后卡住了，超时的时候可能没有完全终止
![image](https://user-images.githubusercontent.com/32956212/104728582-111e0380-5772-11eb-92bf-6fa7f03c6df8.png)
![image](https://user-images.githubusercontent.com/32956212/104728644-2b57e180-5772-11eb-92b6-5c109c15de6a.png)

**Comment by happy888888** [comment]
不会等待开奖，超时后会在日志中显示，如果日志中没有出现超时那就说明任务确实被卡住了，除了天选时刻任务超时后会把天选时刻关注的up主全部取关，其他任务超时后都是打印日志后直接退出

**Comment by FairyWorld** [comment]
> 不会等待开奖，超时后会在日志中显示，如果日志中没有出现超时那就说明任务确实被卡住了，除了天选时刻任务超时后会把天选时刻关注的up主全部取关，其他任务超时后都是打印日志后直接退出

刚刚3个同时执行的任务完成了一个用时31分(天选确实超时了)，另外两个还在天选抽奖(没有超时)。看了下日志，感觉超时确实是有效的，可以终止执行。只是在某些条件会进入不了超时这个方法里面，然后继续抽奖，也就是卡住
![image](https://user-images.githubusercontent.com/32956212/104730369-e3868980-5774-11eb-87c1-ac406a3c5b7e.png)

**Comment by gy39830** [comment]
都是一个task，我就在这里反馈吧，多账号发弹幕好像只有一个账号完成

**Comment by gy39830** [comment]
> 目前为了加快小心心获取速度，默认在所有有粉丝牌的房间心跳，说明你一个账号有很多个粉丝牌，如果你有12个粉丝牌理论上只要心跳10分钟就能获得24个小心心
> 
> 目前并没有找到比较准确的判断小心心任务是否完成的方法

这个功能需求主要是因为风纪天选这类需要长时间运行的任务，现在实现了同时心跳，或许可以通过设定时间条件限制任务运行，比如设定每隔2小时就运行一次脚本，0、2、4、6....20、22  ，那么第一次的0 和最后一次的22都心跳发弹幕，其他时间不心跳

**Comment by happy888888** [comment]
> > 目前为了加快小心心获取速度，默认在所有有粉丝牌的房间心跳，说明你一个账号有很多个粉丝牌，如果你有12个粉丝牌理论上只要心跳10分钟就能获得24个小心心
> > 目前并没有找到比较准确的判断小心心任务是否完成的方法
> 
> 这个功能需求主要是因为风纪天选这类需要长时间运行的任务，现在实现了同时心跳，或许可以通过设定时间条件限制任务运行，比如设定每隔2小时就运行一次脚本，0、2、4、6....20、22 ，那么第一次的0 和最后一次的22都心跳发弹幕，其他时间不心跳

可以通过命令行参数传入不同的配置文件来达到这个目的，云函数可以直接多开，actions workflow可以先在shell里判断时间加载不同的配置文件，linux和windows中直接通过crontab和任务计划在不同时间传入不同的配置文件就行

**Comment by happy888888** [comment]
> > 不会等待开奖，超时后会在日志中显示，如果日志中没有出现超时那就说明任务确实被卡住了，除了天选时刻任务超时后会把天选时刻关注的up主全部取关，其他任务超时后都是打印日志后直接退出
> 
> 刚刚3个同时执行的任务完成了一个用时31分(天选确实超时了)，另外两个还在天选抽奖(没有超时)。看了下日志，感觉超时确实是有效的，可以终止执行。只是在某些条件会进入不了超时这个方法里面，然后继续抽奖，也就是卡住
> ![image](https://user-images.githubusercontent.com/32956212/104730369-e3868980-5774-11eb-87c1-ac406a3c5b7e.png)

超时失效的问题应该已经解决
