### ISSUE TITLE
自动合并后程序出错

### ISSUE THREAD

**Issue by wangmanv2** [happy888888/BiliExp#167]
报错日志：
https://github.com/wangmanv2/BiliExp/actions/runs/487107168/workflow
主要错误：
msg_notify_task() missing 1 required positional argument: 'task_config'
也许是这个修改导致的问题？
https://github.com/happy888888/BiliExp/commit/1a07557d679a19b619c56bd0407ed39f9c4b27cd

**Comment by happy888888** [comment]
嗯，直接更新配置文件

**Comment by happy888888** [comment]
目前心跳改为了默认同时在所有有粉丝牌的房间心跳用于加快小心心获取速度，如果有12个粉丝牌只需要心跳10分钟就够了

**Comment by wangmanv2** [comment]
我有70几个牌牌。
https://github.com/wangmanv2/BiliExp/runs/1707734958
这个日志还是按照越来的设置70个房间发送20次心跳，是否设置里面也只需要修改成发送一次？

**Comment by happy888888** [comment]
目前取消了心跳的次数设置，只能设置超时时间，设置个6分钟就差不多了

**Comment by wangmanv2** [comment]
OK

**Comment by happy888888** [comment]
另外如果有粉丝牌但是没有直播间那么怎么点亮粉丝牌呢，虽然这是很久以前解决的一个bug了，当时发现有的粉丝牌没有对应直播间id导致程序出错

这种粉丝牌是不是只能一直灰色下去了？

**Comment by wangmanv2** [comment]
没遇到这种情况，不太了解应该怎么办
