### ISSUE TITLE
关于风纪委员的一个问题

### ISSUE THREAD

**Issue by mengdiao** [happy888888/BiliExp#169]
能增加风纪委员失效后能自动申请新资格的功能吗

**Comment by happy888888** [comment]
我目前没有过期的风纪委员账号，而且每天都投票是自动续期的

**Comment by mengdiao** [comment]
https://i.loli.net/2021/01/16/EvO7iHust9n3oA1.png  如图

**Comment by happy888888** [comment]
可能每个月投票数量不够就不会续期，我现在没有失效账号不清楚怎么重新申请

**Comment by tlj218** [comment]
这个你可以自己去点一下申请，除非你是很多很多账号，但是知道你每天都有投票就不会出现过期的现象

**Comment by catlair** [comment]
即使有投票都会续期,甚至一个月都没几次投票,如果过期还是自己申请吧
