### ISSUE TITLE
lottery_task 的 time_quantum 没太看懂

### ISSUE THREAD

**Issue by if1y** [happy888888/BiliExp#170]
`[-43200, 43200]` 是**基于12:00执行脚本**，从而表示转发 _前一天0:00-24:00_ 的动态吗？
那么 `[0, 1800]` 应该也是**基于脚本执行时间起**的30m来分段的？
但是为什么前者不写为 `[0, 86400]` 呢……

---

计划每6小时执行一次，具体时间是 1:00 7:00 13:00 19:00，直接使用 `[0, 21600]`？
考虑到不是单纯地平分一天24小时（有整体偏移），不确定这样对不对。

**Comment by happy888888** [comment]
`[-43200, 43200]`是从昨天12:00到今天12:00划分一个时间段，`[0, 86400]`是从今天0:00到今天24:00划分一个时间段
程序应该尽量保证在每个时间段的开头启动，且在每个时间段内不重复运行来保证不会转发相同的动态。

时间段平移一个周期是等价的，比如`[0, 1800]`与`[1800, 3600]`是等价的，唯一的区别是时间段序号不同，前者把今天0:00-0:30当做第0个时间段，0:30-1:00是第1个时间段，后者把0:00-0:30当做第-1个时间段，0:30-1:00当做第0个时间段，1:00-1:30当做第1个时间段。因为程序在每个时间段内运行，都只会转发前一个时间段发出的动态，所以时间段平移一个周期是等价的。

**Comment by happy888888** [comment]
在时间段的末尾启动是不合理的，假设时间段为`[0, 86400]`，每次都转发前1天的动态，但是在今天23:59运行程序，程序就会把今天的所有动态都跳过一遍才能到达昨天的动态

**Comment by if1y** [comment]
好像……懂了
学废了！
