### ISSUE TITLE
关于cron表达式和实际不符合的问题

### ISSUE THREAD

**Issue by FairyWorld** [happy888888/BiliExp#173]
1. 因为没有用过action中cron表达式的5位，所以参考了下腾讯云7位数cron的语法。顺序应该是：分，时，日，月，星期几。在书写时github也给出了提示，正如我猜测的一样
![image](https://user-images.githubusercontent.com/32956212/104888607-ed440300-59a7-11eb-8103-b035bb9fe4ea.png)

2. 根据你的注释中10点执行猜测, 0 2 * * * 表示10点执行是因为采用了UTC时间, 中国时间晚8小时就刚刚好。本来想设置为: xx小时55分开始执行action, 使用: - cron: 55 1,4,7,10,13,16,19 * * *, 但是实际发现却是在 xx小时28分执行, 有点意外。

3. 之前开到你auto_merge.yml代码里有个TZ参数比较好奇是不是梯子的意思, 后来搜索到的结果是用来修改时区的而不是梯子。你的auto_merge.yml比run_BiliExp.yml多设置了这个参数，理论上就是上海时区了，这样就和你的注释的10点对不上了。
![image](https://user-images.githubusercontent.com/32956212/104890033-f7670100-59a9-11eb-8b8c-bf36a5fbadca.png)
 
4. 测试结果
    - run_BiliExp设置 55分时, 是在28分执行。
    -  auto_merge.yml在有TZ的情况下，设置了 - cron: 55 1,4,7,10,13,16,19 * * *，理论在15点和18点才会执行，结果在16:22执行, 不管是时钟还是分钟都对不上。
  
5. 不知道这个时间的设置是不是以action所在ip对应地区的时间为标准？主要是想设置每小时55分钟执行，然后等到action环境什么的配置好了就可以在整点进入天选时刻，一般主播都是在整点才抽奖的

**Comment by happy888888** [comment]
1. actions的cron是用的utc时间没发现例外
2. TZ只是一个环境变量，只对其作用域(按照图上是Push Commits)内用到这个环境变量的程序有效(按照图上这个程序是git)
3. actions的cron是任务进入排队的时间，并不是启动时间，使用actions的任务数量不一定比actions的服务器数量低，人多了就要排队，想精确控制启动时间是不可能的，当然也可以提前启动，计算离目标时间相差的时间然后sleep延时

**Comment by FairyWorld** [comment]
> 1. actions的cron是用的utc时间没发现例外
> 2. TZ只是一个环境变量，只对其作用域(按照图上是Push Commits)内用到这个环境变量的程序有效(按照图上这个程序是git)
> 3. actions的cron是任务进入排队的时间，并不是启动时间，使用actions的任务数量不一定比actions的服务器数量低，人多了就要排队，想精确控制启动时间是不可能的，当然也可以提前启动，计算离目标时间相差的时间然后sleep延时

原来是这样，我之前一直以为cron是定时器，只要到达特定的时间就开始运行action和手动执行一样，只是省去人工点击，原来还要排队。和云函数单人使用的模式想成一样了

**Comment by happy888888** [comment]
这么理解没有错，cron就是计划任务，按照计划的时间执行计划的任务。即使手动启动actions有时候也会等待几分钟才会启动，有个status会显示为queued就说明在排队等待。

linux上crontab就是一项系统服务，启动一个进程很快，云函数这类弹性云计算也能快速分配资源来启动程序，actions是实实在在分配一台物理机，性能比云函数不是一个数量级的，其实光用actions执行一个签到程序是很浪费的，反正微软财大气粗低调用就行了
