### ISSUE TITLE
一个关于风纪投票的问题

### ISSUE THREAD

**Issue by dbwuac** [happy888888/BiliExp#174]
我使用的是win部署，我只开启了风纪这一个功能，这个程序是一直执行完毕吗？我运行的结果是假如还没投够20票且当时没有票了，程序就会结束，我想问的是此时结束了，就不会再执行了吧？
![image](https://user-images.githubusercontent.com/77618659/104910741-bb8d6500-59c4-11eb-819d-164bf7a3de63.png)

**Comment by happy888888** [comment]
如果用的当前最新的exe版本那么是这样的，你可以用Windows任务计划每半个小时执行一次。

如果使用actions分支的代码（无exe版需要安装python环境才行运行），支持指定等待时间，在等待时间内不会退出而是一直等待新的案件出现

**Comment by dbwuac** [comment]
好的，感谢~~~
