### ISSUE TITLE
当风纪委员案件已审满时，建议不再等待

### ISSUE THREAD

**Issue by zhongfly** [happy888888/BiliExp#176]
提示 `[WARNING***: 用户名: 风纪委员案件已审满` 后，无法再获取新案件，因此也不需要等待

**Comment by happy888888** [comment]
你可以修改配置文件

**Comment by zhongfly** [comment]
> 你可以修改配置文件

https://github.com/happy888888/BiliExp/blob/master/config/config.json#L158
这里吗？这里的意思是没有获取到案件退出，我的意思是发现审满就不再获取(等待)，不是同一情况吧

**Comment by happy888888** [comment]
这个`审满`的意思是今天整天都不会有新案件了吗？

**Comment by zhongfly** [comment]
> 这个`审满`的意思是今天整天都不会有新案件了吗？

对的，在网页端的提示就是如此`今日案件已审满，感谢您对社区的贡献！ 明天再来看看吧 ~`

**Comment by happy888888** [comment]
已完成
