### ISSUE TITLE
关于多账户cookie失效的问题

### ISSUE THREAD

**Issue by TTNTO** [happy888888/BiliExp#177]
推送消息是：
id为43***300的账户cookie失效，跳过此账户后续操作

然后我按F12检查发现除了uid其他两个参数都变了
请问是因为我退了账号再重新登录它的原因嘛？
我不太懂它的刷新机制

**Comment by happy888888** [comment]
F12里面有cookie的有效期(一般是半年)，但是退出登录肯定是立即失效

**Comment by TTNTO** [comment]
退出就立即失效的话，那怎么保证所有账号（其实就俩）的cookie同时是有效的呢

**Comment by happy888888** [comment]
不退出不就行了，没有两个浏览器还不能开个隐身模式了？

**Comment by TTNTO** [comment]
有道理，我是傻子0v0 感谢大佬

**Comment by if1y** [comment]
主动注销 或 修改密码 一般均会触发刷新 Cookie。
可以使用无痕模式，或手动在 F12 中清空 Cookie。
