### ISSUE TITLE
天选时刻异常('search_areas')

### ISSUE THREAD

**Issue by FairyWorld** [happy888888/BiliExp#179]
天选时刻抽奖任务异常，异常为('search_areas')，这个是指当前没有天选还是搜索失败?
![image](https://user-images.githubusercontent.com/32956212/105272780-ffef4f80-5bd4-11eb-82b4-4f36227f542c.png)

**Comment by happy888888** [comment]
配置文件中这个字段需要填写，重新复制一下配置文件就好了

**Comment by FairyWorld** [comment]
> 配置文件中这个字段需要填写，重新复制一下配置文件就好了

明天我在重新配置一个新的config.json吧，这个字段我早上确实是填了，刚刚我也复制粘贴了一遍昨晚最新备份的config, 我看到search_areas字段是有的，有可能是其他字段导致的，明天我再测试一次

**Comment by FairyWorld** [comment]
> 配置文件中这个字段需要填写，重新复制一下配置文件就好了

现在可以了，search_areas没有看到有问题，可能是config不兼容旧版的问题或者其他原因，我拷贝最新的config.json重新填了一遍就可以了

**Comment by FairyWorld** [comment]
> 配置文件中这个字段需要填写，重新复制一下配置文件就好了

大佬，我想问下auto_merge这个任务的写法是不是可能会被别人覆盖代码, 并删除自己的提交记录。我拷贝了这个文件只改了需要同步的仓库，运行的时候确实成功了，但是有时别人提交了代码导致了版本的回退, 我提交的代码不见了，比如我新加了一个自己的文件，这个文件别人没有理论上别人不管怎么修改都不会冲突，但是有时执行完auto_merge后这个文件就不见了, 而且我提交的记录也没了(不是每次都会, 只有在某种条件下才会)

**Comment by happy888888** [comment]
没发现这种情况，auto_merge正常是不可能删除你创建的文件的，而且如果有两个人同时修改了同一个文件或者workflow文件夹被改变(actions没有token时没有权限修改workflow文件夹)，auto_merge是会执行失败的(一把红叉而不是绿勾)

**Comment by FairyWorld** [comment]
> 没发现这种情况，auto_merge正常是不可能删除你创建的文件的，而且如果有两个人同时修改了同一个文件或者workflow文件夹被改变(actions没有token时没有权限修改workflow文件夹)，auto_merge是会执行失败的(一把红叉而不是绿勾)

确实和你说的一样，auto_merge没有权限会导致合并失败是一把红叉。之前看到过没有权限的错误，然后没有怎么关注这个问题，一般我都是通过仓库上面的手动pull拉去fork最新的代码(文件和提交记录没有丢失)，然后auto_merge)就可以正常更新了。这样看来auto_merge和手动pull都不会导致文件和提交记录没有丢失。
![image](https://user-images.githubusercontent.com/32956212/105569580-98c0cf00-5d7d-11eb-8950-a1d564efa76e.png)
我其实用了了3个同步方式，一个是auto_merge, 失败了就手动pull，还有一个是安装github机器人自动拉取。我感觉文件和提交记录丢失应该github机器人(可能权限比较大)同步代码导致的, 而且是fork源应该回滚了版本，因为机器人大概6-8小时才触发，而丢失文件的时间有可能是几天后也有可能是最近几个小时内，原fork一般一天几十次commit，可能是他们回滚了
