### ISSUE TITLE
腾讯云适用吗

### ISSUE THREAD

**Issue by rua-aaa** [happy888888/BiliExp#18]
没有阿里云函数，可以用腾讯云么

**Comment by happy888888** [comment]
可以的，原来我就是用的腾讯云，后来8月初的时候强制弹出实名认证的框后就用不了了，转向了阿里云。只要能提供python3.6环境不管什么云函数都行。

**Comment by rua-aaa** [comment]
ok

**Comment by happy888888** [comment]
或者使用纯github actions版本的分支，不需要云函数就能执行
