### ISSUE TITLE
下载最新更新的全部文件后，开始报错

### ISSUE THREAD

**Issue by tlj218** [happy888888/BiliExp#180]
![QQ截图20210121174337](https://user-images.githubusercontent.com/43595611/105333163-5d54c200-5c10-11eb-95a8-80dd057cc1d0.png)
直接运行，没有进行任何设置，账号啥都没设置，就报错

**Comment by tlj218** [comment]
一开始我发现你的代码更新了，我就想着用新的，而且我发现你的代码有很多地方和旧的不一样，我就下载了全部代码文件，然后按照之前的设置，把各种配置都配置了一遍，运行之后就开始报错，然后我用重新下载了一遍用另一个树莓派，并且不进行任何设置，直接运行，还是显示配置加载异常。

**Comment by happy888888** [comment]
安装模块`json5`(`pip install json5`)或者删除配置文件中所有注释，因为只有json5支持读取带注释的json文件
