### ISSUE TITLE
向当前佩戴的粉丝牌房间发送消息异常

### ISSUE THREAD

**Issue by GOOD-AN** [happy888888/BiliExp#181]
刚刚在查看亲密度时，发现当前佩戴的粉丝牌并未增加发送消息的亲密度，aciton内报错
信息为![image](https://user-images.githubusercontent.com/53306377/105343637-d6f2ad00-5c1c-11eb-9279-9b0b73e20df9.png)

**Comment by happy888888** [comment]
已解决，更新代码就好，这个54房间的真实id是910884

**Comment by GOOD-AN** [comment]
好的，非常感谢。

**Comment by GOOD-AN** [comment]
似乎还是有问题，运行报错信息为
![image](https://user-images.githubusercontent.com/53306377/105486984-5f8b4f00-5cea-11eb-8c25-8e6c6efa1416.png)

**Comment by happy888888** [comment]
`msg repeat`说明发送的消息重复了，你确定消息没发出去吗，你现在重试运行一下看看能不能发出消息

**Comment by GOOD-AN** [comment]
提示一样的错误信息，粉丝牌的100经验并未增加。

**Comment by happy888888** [comment]
手动发消息会增加经验吗

**Comment by GOOD-AN** [comment]
会的，手动发送可以。
发送前
![image](https://user-images.githubusercontent.com/53306377/105510934-3da1c480-5d0a-11eb-91ea-73976cc02de6.png)
发送后
![image](https://user-images.githubusercontent.com/53306377/105511015-5f9b4700-5d0a-11eb-9b04-11a459e8ca52.png)

**Comment by happy888888** [comment]
目前我发现有的房间手动发消息也发不出去，无论app还是网页都与程序返回相同错误，暂时无法解决此问题
