### ISSUE TITLE
运行出问题

### ISSUE THREAD

**Issue by cjuwen** [happy888888/BiliExp#183]
作者大大，打扰了，帮我看看出了什么问题。
![image](https://user-images.githubusercontent.com/20887192/105474645-72e1ee80-5cd9-11eb-8cb7-93d47e310f86.png)

**Comment by cjuwen** [comment]
我用部分功能推荐配置可以使用但一起运行就不行了

**Comment by happy888888** [comment]
配置文件格式有问题，贴出来看看

**Comment by cjuwen** [comment]
{
    "version": "1.2.0",
    "default": {
        "group_sign_task": true,
        "xliveSign_task": true,
        "xlive_bag_send_task": {
            "enable": true,
            "room_id": 236672,
            "expire": 86400
        },
        "xlive_heartbeat_task": {
            "enable": true,
            "medal_room": true,
            "room_id": [],
            "send_msg": "打卡",
            "timeout": 66,
        },
        "xlive_anchor_task": {
        	"enable": true,
        	"anchor_type": [[0, 0], [1, 0]],
            "delay": 6,
            "room_filter": [],
            "gift_filter": ["代金卷","优惠券","上船","抵扣卷","1毛","0.233元","0.52元","0.1"],
            "danmu_filter": [],
            "price_limit": 0,
            "unfollow": true,
            "follow_group": "天选",
            "clean_group_interval": 0,
            "search_interval": 500,
        	"search_areas": [
        		{"paid": 1,"aid": 0,"sort": "","ps": 50},
        		{"paid": 2,"aid": 0,"sort": "","ps": 50},
                {"paid": 9,"aid": 0,"sort": "","ps": 50},
        		{"paid": 3,"aid": 0,"sort": "","ps": 50},
                {"paid": 6,"aid": 0,"sort": "","ps": 50},
                {"paid": 10,"aid": 0,"sort": "","ps": 50}
        	],
        	"timeout": 3300,
            "run_once": false
        },
        "watch_task": true,),
        "share_task": true, ),
        "silver2coin_task": true,
        "lottery_task": {
            "enable": true,
            "reply": ["冲冲冲[doge]", "加油"],
            "repost": ["冲冲冲[doge]", "加油"],
            "keywords": ["^((?!恭喜).)*#互动抽奖#((?!恭喜).)*$", "^((?!恭喜).)*#抽奖#((?!恭喜).)*$", ".*(转|抽|评).*(转|抽|评).*(转|抽|评).*"],
            "repost_with_tag": {
                "fix": 1,
                "except": ["抽奖"],
                "reply_with_tag": false
            }, 
            "time_quantum": [0, 3600],
            "create_dynamics_interval": [4, 6],
            "create_dynamics": ["今天天气不错", "又是美好的一天"],
            "create_dynamics_end": 0,
            "delay": [6, 8],
        },
        "msg_notify_task": {
            "enable": false,
            "black_keywords": ["欢迎", "感谢", "关注"]
        },
        "clean_dynamic_task": {
            "enable": false,
            "black_keywords": [],
            "unfollowed": false,
            "days_range": [7, 30]
        },
        "manga_sign_task": true,
        "exchangeCoupons_task": {
            "enable": false,
            "num": 0
        },
        "manga_vip_reward_task": {
            "enable": false,
            "days": [1]
        },
        "manga_auto_buy_task": {
            "enable": false,
            "mode": 1,
            "filter": "25900|1-30,35,55;25966|5,15,35-"
        },
        "judgement_task": {
            "enable": true,
            "run_once": false,
            "params": {
                "vote": 4,
                "attr": 0
            },
            "vote_num": 20,
            "check_interval": 480,
            "timeout":850
        },
        "activity_task": {
            "enable": true,
            "path": "./config/activities.json",
            "activities": []
        }
    },
    "log_file": "BiliExp.log",
    "log_console": false,
    "users": []
}

**Comment by happy888888** [comment]
```
{
	"version": "1.2.0",
	"default": {
		"group_sign_task": true,
		"xliveSign_task": true,
		"xlive_bag_send_task": {
			"enable": true,
			"room_id": 236672,
			"expire": 86400
		},
		"xlive_heartbeat_task": {
			"enable": true,
			"medal_room": true,
			"room_id": [],
			"send_msg": "打卡",
			"timeout": 66
		},
		"xlive_anchor_task": {
			"enable": true,
			"anchor_type": [[0, 0],[1, 0]],
			"delay": 6,
			"room_filter": [],
			"gift_filter": ["代金卷", "优惠券", "上船", "抵扣卷", "1毛", "0.233元", "0.52元", "0.1"],
			"danmu_filter": [],
			"price_limit": 0,
			"unfollow": true,
			"follow_group": "天选",
			"clean_group_interval": 0,
			"search_interval": 500,
			"search_areas": [
			  {"paid": 1,"aid": 0,"sort": "","ps": 50},
			  {"paid": 2,"aid": 0,"sort": "","ps": 50},
			  {"paid": 9,"aid": 0,"sort": "","ps": 50},
			  {"paid": 3,"aid": 0,"sort": "","ps": 50},
			  {"paid": 6,"aid": 0,"sort": "","ps": 50},
			  {"paid": 10,"aid": 0,"sort": "","ps": 50}
			],
			"timeout": 3300,
			"run_once": false
		},
		"watch_task": true,
		"share_task": true,
		"silver2coin_task": true,
		"lottery_task": {
			"enable": true,
			"reply": ["冲冲冲[doge]", "加油"],
			"repost": ["冲冲冲[doge]", "加油"],
			"keywords": ["^((?!恭喜).)#互动抽奖#((?!恭喜).)$", "^((?!恭喜).)#抽奖#((?!恭喜).)$", ".(转|抽|评).(转|抽|评).(转|抽|评)."],
			"repost_with_tag": {
				"fix": 1,
				"except": ["抽奖"],
				"reply_with_tag": false
			},
			"time_quantum": [0, 3600],
			"create_dynamics_interval": [4, 6],
			"create_dynamics": ["今天天气不错", "又是美好的一天"],
			"create_dynamics_end": 0,
			"delay": [6, 8]
		},
		"manga_sign_task": true,
		"judgement_task": {
			"enable": true,
			"run_once": false,
			"params": {
				"vote": 4,
				"attr": 0
			},
			"vote_num": 20,
			"check_interval": 480,
			"timeout": 850
		},
		"activity_task": {
			"enable": true,
			"path": "./config/activities.json",
			"activities": []
		}
	},
	"log_file": "BiliExp.log",
	"log_console": true,
	"users": []
}
```

**Comment by cjuwen** [comment]
可以了，谢谢🙏，可以问一下是什么问题吗？

**Comment by happy888888** [comment]
就是json格式不正确，去https://www.sojson.com/ 排查一下格式问题就行了

**Comment by cjuwen** [comment]
好的，麻烦大大了，打扰到您了，不好意思

**Comment by cjuwen** [comment]
打扰了
