### ISSUE TITLE
动态抽奖问题

### ISSUE THREAD

**Issue by SadPull** [happy888888/BiliExp#185]
![QQ截图20210123121312](https://user-images.githubusercontent.com/51036486/105568467-77a7b080-5d74-11eb-9d12-065cf3ae863b.png)

如图，我这几个小号互相关注，然后疯狂给对方点赞+转动态。
现在搞得每天要重复转发几十次动态

建议加个抽奖是否过期的检测
再排除一下重复转发

**Comment by happy888888** [comment]
建议只使用官抽，而不是关键字匹配的非官抽。
官抽是明确开奖时间的。
非官抽由关键字匹配得到，并不明确开奖时间，原up主发布动态a，路人1转发一次变成动态b，路人2转发一次变成动态c，那么a，b，c是不同的三个动态不算重复转发。

**Comment by happy888888** [comment]
把配置文件修改为
https://github.com/SadPull/BiliExp/blob/fc721c81d70b64cda746b514a42627643e07e022/config/config.json#L87-L92
```
            "keywords": [],
```
即删除88-92行

**Comment by happy888888** [comment]
也可以直接更改84行 `"enable": true,`为`"enable": false,`关闭动态转发
