### ISSUE TITLE
可能需要注意 Actions 存在的风险

### ISSUE THREAD

**Issue by if1y** [happy888888/BiliExp#187]
目前已知有类似仓库调用 Actions 被封。

Github 给出的理由是
> violates our Terms of Service limitations on using GitHub Actions to promote inauthentic activity on other platforms: https://docs.github.com/en/github/site-policy/github-terms-of-service

**Comment by happy888888** [comment]
这个在其他平台上不真实的活动就看官方怎么解释了，Actions本质还是一个CI/CD工具，本项目大部分workflows文件也没有超出这个使用范畴。

这个封禁是封禁整个仓库的Actions功能吗，还是封禁账号？有fork关系的仓库也会受连带影响？

**Comment by if1y** [comment]
对应**作者账号**被锁定成**非公开可见**了。
导致 fork 仓库无法进行后续更新，已 fork 的部分还是可以正常使用的。

**Comment by happy888888** [comment]
我这个号Actions用得很少再怎么也轮不到来封我........

**Comment by if1y** [comment]
我的理解是，从源头解决问题，所以封作者？

**Comment by if1y** [comment]
本 issue 主要还是提个醒，封不封确实是很玄乎的事情，可供官方发挥的余地太大，谁也说不清楚

**Comment by happy888888** [comment]
主要是这个提醒没有什么实际用处，没有什么实际的解决方法还是只有保持现状。

其实新建一个非fork的仓库也是可以的，可以切断分支上的关联，自动合并用的actions也还是能用，不知道对应封禁有没有效果

**Comment by if1y** [comment]
按目前的情况来看，应该只针对 owner，而不影响 maintainer。
**所以单独注册一个账号作为仓库 owner 是否可行？**
万一被封，也能通过维护号找到新仓库。
另外我看你这账号还有些其他内容，如果一并封了可能得不偿失。

**Comment by if1y** [comment]
你说的方法也可以。

可以继续在这里维护更新，但我觉得 Actions 执行的部分还是放在另一个账号上会比较保险。

**Comment by rewag01** [comment]
二手东的羊毛脚本好像就这么没的。那么吓人-0-

**Comment by happy888888** [comment]
目前支持将`.github/workflows/run_BiliExp.yml`放到其他仓库运行，但需要额外添加两个secrets `repository`和`ref` 来指定代码来源，也就是代码和`run_BiliExp.yml`可以不放在一个仓库

**Comment by if1y** [comment]
不错的方案，我抽空试试，先 close 了
