### ISSUE TITLE
关于多账号的问题

### ISSUE THREAD

**Issue by zyz183** [happy888888/BiliExp#189]
你好：
        现在的多账号模式是A账号执行一下，B账号执行一下，再A账号执行一下，B账号执行一下，被判断为操作异常。其中一个号被封禁。
        建议将操作改为A账号全部执行完成后，休息较长一段时间，再进行B账号的操作。其他几个账号全部是用定时脚本设置好时间（40分钟间隔，实际执行大概10-30分钟），并未出现相应的问题。

**Comment by happy888888** [comment]
使用的环境？版本？开启了哪些功能？

目前为了节约时间，多账号多任务都是并行执行而不是串行，每个账号的执行空间是完全独立的，类似于模拟同时开两个不同的浏览器或者同一路由器下两台电脑同时执行任务，并行任务本身不是太大的问题，同一个ip用的人这么多不可能让所有人都错开时间上B站吧。

目前已知3级以下的号使用投币，模拟观看视频等任务可能出现封禁现象，是因为目前并没有完整地模拟视频观看的整个流程而是直接向服务器上传观看记录。除这种情况外并没有发现可能导致封禁的现象。

你的这个建议可以通过把两个账号分别放进两个配置文件config1.json和config2.json
windows:
```
python BiliExp.py -c config1.json
timeout /T 1800 /NOBREAK
python BiliExp.py -c config2.json
```
exe版
```
BiliExp.exe -c config1.json
timeout /T 1800 /NOBREAK
BiliExp.exe -c config2.json
```

linux:
```
python BiliExp.py -c /etc/BiliExp/config1.json
sleep 1800
python BiliExp.py -c /etc/BiliExp/config2.json
```

这样就可以在一个账号执行完成后等待半个小时(1800秒)后在执行另一个账号的任务

**Comment by zyz183** [comment]
好的 谢谢
