### ISSUE TITLE
风纪委员会和一般命令同时存在导致一般命令不执行

### ISSUE THREAD

**Issue by ychen3edu** [happy888888/BiliExp#192]
Actions secrets
里面有三个scrects，其中ADVCONFIG（只有风纪其余删除了）
BILICONFIG
但目前只执行ADVCONFIG而不执行BILICONFIG，只有把ADVCONFIG删除后才能执行BILICONFIG，请问有什么方法可以同时执行两个呢？把所有命令全部都写到ADVCONFIG里吗？

**Comment by happy888888** [comment]
BILICONFIG是用来存放cookie的，ADVCONFIG是用来存放配置文件的，如果ADVCONFIG不存在加载的就是默认的配置。

配置文件参见/config/config.json，配置文件里没有启用的功能就不会加载，你只放了风纪委员的配置其他任务就不会执行
