### ISSUE TITLE
auto_merge.yml怎么在新版本取消了?

### ISSUE THREAD

**Issue by FairyWorld** [happy888888/BiliExp#194]
1. auto_merge.yml怎么在新版本取消了? 还是说用了其他方法去自动同步上游分支
2. 现在是不是不在按照分支去区分了, 之前BiliExp和master分支合并了

**Comment by happy888888** [comment]
因为不需要同步，Actions执行需要`run_BiliExp.yml`文件和指定代码源，你可以使用secrets `repository`来指定Actions运行时从哪个仓库获取代码，也可以使用secrets `ref`来指定从仓库的哪个分支或者哪一次提交来获取代码。

如果上面两个secrets都没有，Actions执行时默认从`run_BiliExp.yml`文件所在仓库的最新一次提交获取代码，也就是以前默认的模式。

**Comment by happy888888** [comment]
比如如果你在 secrets `repository` 里填写 `happy888888/BiliExp` ，Actions执行时就会从我的仓库默认分支(master)的最新一次提交中获得代码。当然更建议同时使用`ref`来指定从哪一次提交中获得代码以保证代码和配置文件的统一性

**Comment by FairyWorld** [comment]
> 当然更建议同时使用`ref`来指定从哪一次提交中获得代码以保证代

1. 我看了下yml的代码好像和你说的一样, 我想问下 secrets ref这个的值是不是就是commit的6位字母的版本号?

2. 还有一个问题是yml中下面这个条件判断中的"github"是不是github自己内置的全局变量, 还是说这个变量是你定义的? 
```
if: github.repository != 'happy888888/BiliExp' || github.event_name == 'workflow_dispatch'
```

3. 根据你上面的说法，action是可以从别人仓库获取代码，这个仓库是不是只能是github仓库，能不能是gitee仓库或者别的仓库。其实github新建仓库的时候是可以导入其他平台仓库的，最近我又想运行gitee的代码，就想问下能不能实现?

4. 大佬有没有哪个网站推荐学习一下github action和action yml的配置? 看了你的项目后有了点兴趣，主体部分能看懂一些，但是自己还是不会写，想自己学习玩一下

**Comment by happy888888** [comment]
1. commit版本号是32位的，你看到的只是前面6位
2. github是workflow内置变量，secrets也是，当然还有其他的，最关键内置变量里有个token可以获取当前仓库的读写权限（包括仓库代码，issues，pull request的权限，但为了安全没有workflow文件夹的权限），不然actions也没办法访问仓库，就像你的浏览器没有登录一样（公共仓库任何人都有读取权限，但没有其他权限）
3. actions的运行环境就可以当做一台电脑，你的电脑能干的事actions也能干，你能获取gitee仓库的代码actions也能，但是我用的actions/checkout@v2来拉取代码，这个是github官方实现的，不提供拉取非github仓库的功能，拉取其他仓库直接使用git命令就行，就跟在你自己电脑上一样，唯一与普通电脑不同的就是actions的操作只能靠workflow文件指定
4. github有自己的官方文档，而且有中文文档，虽然中文文档不一定比英文文档易懂

**Comment by happy888888** [comment]
actions/checkout@v2是如何拉取代码的，可以直接去看它的代码，仓库名称就跟他名字一样actions/checkout，后面的v2是它的分支名称

同样你自己也可以实现一个actions，别人在workflow文件里直接use你的仓库名称就能使用，但仅限于github仓库，因为workflow是github独有的
