### ISSUE TITLE
希望能添加一个qq推送

### ISSUE THREAD

**Issue by a840900544** [happy888888/BiliExp#195]
我平时都是qq用的比较多，所以希望能添加个qq推送
现在我只发现两个qq推送的
一个是酷推https://cp.xuthus.cc/
一个是qmsg  https://qmsg.zendee.cn/

**Comment by if1y** [comment]
参照 Webhook 部分改改就好了

**Comment by a840900544** [comment]
我自己搞了搞，虽然推送成功了，但是却没有url解码...

**Comment by a840900544** [comment]
哥，弄好了，我把post改成get就行了

**Comment by happy888888** [comment]
也可以分享一下配置方便后来人使用

**Comment by a840900544** [comment]
"msg_simple": null, // msg_simple为简化的日志消息，用于下面hooks消息推送接口引用
         //   "msg_raw": null,    // msg_raw为完整的日志消息，用于下面hooks消息推送接口引用，若不引用最好注释掉，否则占用内存空间

        //    "title": "B站经验脚本消息推送", // 此为自定义变量，用于下面hooks消息推送接口引用
            "SCKEY": "填上你酷推的sckey" ,
        /*  "email": "",
            "telegram_bot_token": "",
            "telegram_bot_chatid": "" */
        },
        "hooks": [ // 在这里以数组的形式定义所有消息推送回调接口
            {
                "enable": true, // 开关，需要开启请直接把本项删除或设置为true
                "name": "server酱消息推送", // webhook名称，仅用于日志显示不用于实际消息推送
                "msg_separ": "\n\n",       // 消息分隔符，推送消息时将每一条消息用两个换行符(\n)隔开
                "method": 0,               // 请求方式,0为get,1为post,2为以json方式post
                "url": "https://push.xuthus.cc/send/{SCKEY}", // 请求地址,{SCKEY}为对上面variable变量中的SCKEY的引用，当然也可以直接把SCKEY的值放在url里面
                "params": {                                // 请求参数,server酱推送需要text和desp两个参数，分别把变量里title和msg_simple(简化消息)赋值进去
                    "c": "{msg_simple}" 
                }
            }/*, //若要实现其他消息推送接口，需要自己查阅相关文档构建method，url和params三个参数，下面是邮箱推送和telegram_bot推送的例子，其他平台自行探索

在config/config.json中
从179行复制到198行

**Comment by happy888888** [comment]
url编码的问题我看了一下，你应该把`"method": 1`改为`"method": 3`，这玩意儿的post格式是json的，同时这个接口支持直接post原始文本，但本项目不支持这样post，直接使用`"method": 3`就不会有任何问题
