### ISSUE TITLE
run BiliExp的cookie没错但是解析不到SESSDATA

### ISSUE THREAD

**Issue by z844911398** [happy888888/BiliExp#197]
Run bash ./run_in_Actions/run_BiliExp.sh
  bash ./run_in_Actions/run_BiliExp.sh
  shell: /bin/bash -e {0}
  env:
    ADVCONFIG: 
    BILICONFIG: ***
    PUSH_MESSAGE: ***
  Failed building wheel for idna-ssl
  Failed building wheel for yarl
发现biliconfig，开始映射cookie
biliconfig第1行解析为DedeUserID
biliconfig第2行解析为DedeUserID
biliconfig第3行解析为bili_jct
虽然配置了BILICONFIG，但并没有发现有效账户cookie
[INFO]: 当前程序版本为v1.2.0,配置文件版本为v1.2.0
Warning: : id为账号uid的账户cookie失效，跳过此账户后续操作
[INFO]: 未定义消息推送

**Comment by happy888888** [comment]
sessdata格式为 `8位数字字母+"%2C"+10位数字字母+"%2C""+5位数字字母+单个任意字符+2位数字字母`
类似`36e71d56%2C1617545513%2C367d6*a1`

当然也可以在按照config.json文件格式填写然后保存到secrets advconfig中

**Comment by z844911398** [comment]
> sessdata格式为`8位数字字母+"%2C"+10位数字字母+"%2C""+5位数字字母+单个任意字符+2位数字字母`
> 类似`36e71d56%2C1617545513%2C367d6*a1`
> 
> 当然也可以在遵循config.json文件格式填充然后保存到秘密advconfig中

用advconfig解决了谢谢大佬

**Comment by happy888888** [comment]
你的sessdata格式不符合上面写的吗？

**Comment by z844911398** [comment]
> 你的sessdata格式不符合上面写的吗？
4a5f1c63%2C1785313721%2Cdf9fc*a1  我看起来是符合的😂

**Comment by cq535454518** [comment]
我也出现了这个问题
********%2C1627555899%2C02740%2A11
大佬好像后面不符合规则，前8位我拿星号替换了

**Comment by happy888888** [comment]
@cq535454518  `********%2C1627555899%2C02740*11`  把那个`%2A`改成`*` 星号呢，%2A在url编码里就是星号

**Comment by cq535454518** [comment]
牛皮  嗯嗯 改了以后正常了

**Comment by happy888888** [comment]
@cq535454518 config.json文件如果要修改，应该复制到secrets advconfig里面，不建议直接在仓库修改

**Comment by cq535454518** [comment]
绝了 刚刚我还在纠结 怎么改了配置 没有生效。。哈哈  对哦这样改了不仅生效慢 而且别人也能看到 欧克欧克！谢谢老哥提醒

**Comment by cq535454518** [comment]
- cron: '*/30 20-23,0-1 * * *' #中午12:00执行，修改时注意时区
- 大佬这个时区是按照那个算的

**Comment by happy888888** [comment]
> * cron: '*/30 20-23,0-1 * * *' #中午12:00执行，修改时注意时区
> * 大佬这个时区是按照那个算的

utc时间，0点等于我们北京时间的8点
