### ISSUE TITLE
如何取得B站客户端access_keys

### ISSUE THREAD

**Issue by Chillily** [happy888888/BiliExp#2]

**Comment by happy888888** [comment]
以下方法适用于Android7.0以下(不包含)的系统
首先电脑安装fiddler抓包工具，在软件中，工具-->选项-->HTTPS 页面，勾选所有多选框，在 连接 页面勾选允许远程计算机连接
安卓手机首先跟电脑处于同一个wifi下，在安卓手机手机上的wifi页面上长按连接的wifi名字，点击修改网络，显示高级选项，把代理设置改为手动，服务器地址写电脑的内网ip地址，服务器端口填8888。然后打开浏览器，输入"http://电脑的内网ip地址:8888"，点击"FiddlerRoot certificate"，下载证书；进入手机设置，搜索"加密与凭据"，点击“从设备安装”，安装刚才下载的证书。最后进入进入漫画app，在登录状态下随便刷新一下，就可以在电脑fiddler中的左边看到app的数据包，找到/twirp/card.v1.Card/GetUserCardInfo这个地址并点击，在软件右边点"检查器"，"RAW"，然后下面就有"access_key=xxxxxxx&appkey=xxxxxxxxx&build=xxxxxxx"字段了，第一个xxxxxxx指的就是access_key的值。
