### ISSUE TITLE
关于转盘抽奖

### ISSUE THREAD

**Issue by dbwuac** [happy888888/BiliExp#201]
我记得之前有如何获得转盘抽奖sid的图片教程，现在找不到了，是删除了吗？还是我没找到。

**Comment by dbwuac** [comment]
我记得有个获取转盘抽奖sid的演示，现在找不到了

**Comment by happy888888** [comment]
https://github.com/happy888888/BiliExp/tree/66cd38b20b7ab5ec68308cc4bda141bea6c2c367/config#activities活动列表必选

**Comment by dbwuac** [comment]
收到，感谢
