### ISSUE TITLE
小心心没有发送成功

### ISSUE THREAD

**Issue by FairyWorld** [happy888888/BiliExp#203]
1. 开了2个号，2个号直播都可以获取到小心心，但是并没有发送出去。

2. action日志是有显示发送小心心成功的，但是实际上一个都没有发送出去。这个问题应该几天前的版本也有，因为昨晚我看到我的背包里有一大堆小心心，然后手动一波发送完毕。然后今天下午重新fork了一份最新的仓库进行部署，大概今天下午跑了5-6轮action，我发现小心心还是24颗。

3. 小号关注的up是没有开播的，大号关注的up今天基本一直在直播(而且我拥有粉丝勋章)，理论上大号应该是可以发送小心心的，结果大小号都没有发出去1颗小心心

4. 配置如下:
```
 "xlive_heartbeat_task": { // 任务:发送直播心跳，可用于获得小心心(每5分钟1个)和大老爷在线时长加经验(费时，不建议在云函数使用)
            "enable": true,      //任务开关，值为true或false分别代表开启和关闭
            "medal_room": true,   //在所有拥有粉丝牌的直播间心跳，值为true或false分别代表开启和关闭，只有在有粉丝牌的房间心跳才能获取小心心(时间累加多个房间,没有开播也累加)
            "room_id": [],       // 直播间id，值为整数数组，除了上面的拥有粉丝牌的直播间还可以在其他直播间心跳
            "send_msg": "我来打卡了",  // 向所有有粉丝牌的房间发送消息(作用是点亮粉丝牌和增加其密度)，值为字符串，为空字符串则不发送
            "timeout": 11       // 心跳分钟数，值为数字(单位分钟,允许小数),心跳的时间，达到时间退出
        }
```

**Comment by happy888888** [comment]
我这里是可以获得小心心的，你昨天把小心心全部送出了，今天有24个不是正常的吗

**Comment by FairyWorld** [comment]
> 我这里是可以获得小心心的，你昨天把小心心全部送出了，今天有24个不是正常的吗

昨天应该囤了200多个小心心，应该是几天都没有发出去(我的关注有人直播, 带勋章)，昨晚10点多是我手动全部发送出去。今天重新拉取了一次仓库，然后大概执行了5-6轮action，我看到日志显示有发送的，但是背包里实际还有24个(今天获取的24个)

**Comment by happy888888** [comment]
你的意思是没有把小心心当做礼物送出去吗？心跳任务只能获取小心心不负责送出礼物的

**Comment by FairyWorld** [comment]
> 你的意思是没有把小心心当做礼物送出去吗？心跳任务只能获取小心心不负责送出礼物的

1. 我好像理解为什么失败了，这个任务应该是只获取24颗小心心。而小心心发送任务是在"xlive_bag_send_task"这个发送快要过期礼物里配置的, 所以按照下面的配置，只有在过期2天内我才会发出小心心?

2. 因为看到日志显示"成功在id为11367的直播间发送第10次心跳", 所以我以为是获取并发送。而"xlive_bag_send_task"配置里的礼物是指辣条之类(不包含小心心)的礼物

```
"xlive_bag_send_task": {   // 任务:送出即将到期的直播间背包里的礼物，值为true或false分别代表开启和关闭，下面为本功能详细配置
            "enable": true,       //任务开关，值为true或false分别代表开启和关闭
            "room_id": 1314,         // 值为整数，送礼物的直播间，0为随机取直播间
            "expire": 172800      // 值为整数，距离过期的时间(单位为秒),172800为两天，若礼物将在这个时间内过期则会被随机送出
        }
```

**Comment by happy888888** [comment]
B站获取小心心的方式是要你要在有粉丝勋章的直播间里面，而判断你是否在线的方式是你每隔一段时间发送一次加密心跳，如果一段时间内B站没有收到你发送的心跳就说明你退出了直播间或者掉线了，就获取不到小心心。心跳是一种检测是否在线的方式，就是定时发送特定的数据包。

**Comment by FairyWorld** [comment]
> B站获取小心心的方式是要你要在有粉丝勋章的直播间里面，而判断你是否在线的方式是你每隔一段时间发送一次加密心跳，如果一段时间内B站没有收到你发送的心跳就说明你退出了直播间或者掉线了，就获取不到小心心。心跳是一种检测是否在线的方式，就是定时发送特定的数据包。

原来这样，我把心跳的含义理解为了小心心。所以修改下"xlive_bag_send_task"这里的时间配置应该就可以了

**Comment by happy888888** [comment]
对，关于"心跳"可以参考百度百科
https://baike.baidu.com/item/%E5%BF%83%E8%B7%B3/1946723
https://baike.baidu.com/item/%E5%BF%83%E8%B7%B3%E5%8C%85/1219901
