### ISSUE TITLE
最新的版本在哪可以设置指定up投币还有投币数量呢

### ISSUE THREAD

**Issue by sandglasstu** [happy888888/BiliExp#205]
今天更新到最新的了，发现原来的配置文件发现用不了了。。  最新的版本没找到地方

**Comment by sandglasstu** [comment]
一直用的是action，之前所有参数都是放到ADVCONFIG里的

**Comment by happy888888** [comment]
config/config.json 文件，修改后新建一个secrets advconfig，把文件内容全部复制进去

**Comment by sandglasstu** [comment]
我改了下config.json放到ADVCONFIG  但是没成功，帮忙看下是啥问题
![image](https://user-images.githubusercontent.com/12029190/106446188-e5fa1a80-64ba-11eb-9177-90a93f418e72.png)

**Comment by happy888888** [comment]
你什么信息都没有我怎么判断，是投币数量没设置成功吗还是其他问题
