### ISSUE TITLE
互动抽奖需再优化

### ISSUE THREAD

**Issue by if1y** [happy888888/BiliExp#206]
1. **过滤问题**，看动态评论区 https://t.bilibili.com/486632877110206075
  使用[在线正则测试器](https://c.runoob.com/front-end/854)测试，预制的3条规则都没有触发匹配。似乎唯一可能的是`转`这个字。
  有点离谱……

2. **部分联合抽奖**，Up1转发Up2的动态，在转发时加码奖品，这时往往需要关注二者，但很有可能出现未关注Up2，导致抽奖参与无效。
   举例 https://t.bilibili.com/486657349832919859

**Comment by happy888888** [comment]
1. 这就需要用户改用更好的正则表达式了，不然也不会把正则表达式放配置文件中而不是直接扔代码里
2. 关注操作需要用户自己进行

**Comment by if1y** [comment]
🤔 因为那种联动抽奖，一般会在里面写 `关注 @某某某 和 @某某某`，所以我觉得可以设计得智能一点，不然就是无用转发了。
避免争议，可以把联动转发**作为一个选项，不默认开启**。
