### ISSUE TITLE
可更新配置文件

### ISSUE THREAD

**Issue by 9k001** [happy888888/BiliExp#208]
当前程序版本为v1.1.9,配置文件版本为v1.2.0,可更新配置文件

读取活动列表异常,原因为([Errno 2] No such file or directory: './config/activities.json')

第一个问题，是不是docker源 镜像没有更新？
第二个问题，这没说要填写这个呀。

**Comment by happy888888** [comment]
docker默认每次执行拉取最新release版本代码，目前最新release版本代码是1.1.9，master分支的当前版本是1.2.0。你应该使用1.1.9版本的配置文件https://github.com/happy888888/BiliExp/blob/1.1.9/config/config.json

/config/activities.json这是转盘抽奖的活动列表文件，实际上目前很多活动都已经过期了，直接不管就行。

**Comment by 9k001** [comment]
> docker默认每次执行拉取最新release版本代码，目前最新release版本代码是1.1.9，master分支的当前版本是1.2.0。你应该使用1.1.9版本的配置文件https://github.com/happy888888/BiliExp/blob/1.1.9/config/config.json
> 
> /config/activities.json这是转盘抽奖的活动列表文件，实际上目前很多活动都已经过期了，直接不管就行。

那实际上 我是执行成功了 是这个意思吧

**Comment by happy888888** [comment]
docker已支持v1.2.0版本的执行直接拉取最新镜像就行，但不包括转盘抽奖活动列表文件，因为这个抽奖活动官方一直在更新所以活动列表文件也需要用户不断更新才能参与新活动，中奖率也不高没必要启用这个功能
