### ISSUE TITLE
能否添加一个Server酱的推送通知

### ISSUE THREAD

**Issue by xwb2000** [happy888888/BiliExp#210]
添加一个推送能够清楚看到加了多少经验什么的😜😜

**Comment by 1076764805** [comment]
如果不发视频，每日最多也就65经验

**Comment by xwb2000** [comment]
好滴




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "happy888888/BiliExp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月3日(星期三) 下午5:38
收件人:&nbsp;"happy888888/BiliExp"<BiliExp@noreply.github.com&gt;;
抄送:&nbsp;"淺笑丶厝ㄖ凊"<1205895054@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [happy888888/BiliExp] 能否添加一个Server酱的推送通知 (#210)





 
如果不发视频，每日最多也就65经验

**Comment by happy888888** [comment]
主要是B站经验信息更新不及时，并不是操作了经验马上就能加上的，可能要延迟几分钟或十几分钟才会更新，那时候程序已经退出了。

每次运行都会显示当前经验的，只要看两次运行的经验差就能知道涨了多少经验了
