### ISSUE TITLE
关于tg消息推送

### ISSUE THREAD

**Issue by wzwcc** [happy888888/BiliExp#211]
![image](https://user-images.githubusercontent.com/76573126/106717497-c5f16500-663a-11eb-9d2e-c4f17b2a6421.png)
当消息过长时导致tg返回400错误
执行环境:Actions

**Comment by if1y** [comment]
不要推送 msg_raw，一定会超出长度的。
msg_simple 没出现此类问题

**Comment by wzwcc** [comment]
![image](https://user-images.githubusercontent.com/76573126/107119203-0feb7c80-68c1-11eb-942c-13dffce55dda.png)
原来默认是msg_raw 啊 行吧我改好了

**Comment by if1y** [comment]
默认是 msg_simple
