### ISSUE TITLE
大佬能增加一个天选过滤的功能吗？

### ISSUE THREAD

**Issue by mengdiao** [happy888888/BiliExp#213]
RT对含关键词的天选进行过滤 ，
一天天的不是空气就是自拍.

**Comment by happy888888** [comment]
天选有比较完善的过滤机制，可以使用secrets advconfig内复制配置文件/config

**Comment by TTNTO** [comment]
https://github.com/happy888888/BiliExp/issues/178
天选时刻的过滤写法在这里写着呀

**Comment by if1y** [comment]
典型的不看实际光提需求，天选过滤的配置项都出来很久了
