### ISSUE TITLE
wasmtime现在只支持64bit系统

### ISSUE THREAD

**Issue by sxx1314** [happy888888/BiliExp#215]
- wasmtime._error.WasmtimeError: wasmtime only works on 64-bit platforms right now

### 部分32bit的路由器(如部分高通的soc)/32bit开发板（如全志h系列/老树莓派）/基于32bit的docker 注意了！
- 由于wasmtime现在只支持64bit系统 因此最新代码肯定无法使用。
- 解决办法  git checkout 3dff0c25c6e22cec45e22efa601e2fa46aa6f8f6

**Comment by happy888888** [comment]
wasmtime是本地直播心跳加密模块用的，如果不需要直播心跳，可以把这个模块删除。如果删除模块后仍要使用直播心跳功能，会把心跳数据包发送到我搭建的加密服务器进行加密。

也就是说直播心跳功能既可以使用依赖于wasmtime的本地加密模块，也可以直接使用远程服务器进行加密

**Comment by dirrory** [comment]
@happy888888  

> wasmtime是本地直播心跳加密模块用的，如果不需要直播心跳，可以把这个模块删除。如果删除模块后仍要使用直播心跳功能，会把心跳数据包发送到我搭建的加密服务器进行加密。
> 
> 也就是说直播心跳功能既可以使用依赖于wasmtime的本地加密模块，也可以直接使用远程服务器进行加密

请问如何删除模块，我尝试注释掉 config 里面关于直播心跳的代码并删除tasks/xlive_heartbeat_task.py文件，但是依旧会报错提示wasmtime only works on 64-bit platforms right now

**Comment by happy888888** [comment]
> @happy888888
> 
> > wasmtime是本地直播心跳加密模块用的，如果不需要直播心跳，可以把这个模块删除。如果删除模块后仍要使用直播心跳功能，会把心跳数据包发送到我搭建的加密服务器进行加密。
> > 也就是说直播心跳功能既可以使用依赖于wasmtime的本地加密模块，也可以直接使用远程服务器进行加密
> 
> 请问如何删除模块，我尝试注释掉 config 里面关于直播心跳的代码并删除tasks/xlive_heartbeat_task.py文件，但是依旧会报错提示wasmtime only works on 64-bit platforms right now

`BiliClient/wasm_enc`文件夹删除就好

**Comment by dirrory** [comment]
> > @happy888888
> > > wasmtime是本地直播心跳加密模块用的，如果不需要直播心跳，可以把这个模块删除。如果删除模块后仍要使用直播心跳功能，会把心跳数据包发送到我搭建的加密服务器进行加密。
> > > 也就是说直播心跳功能既可以使用依赖于wasmtime的本地加密模块，也可以直接使用远程服务器进行加密
> > 
> > 
> > 请问如何删除模块，我尝试注释掉 config 里面关于直播心跳的代码并删除tasks/xlive_heartbeat_task.py文件，但是依旧会报错提示wasmtime only works on 64-bit platforms right now
> 
> `BiliClient/wasm_enc`文件夹删除就好

尝试了一下，换了个报错 :(  不知道是哪里有问题，于是试过重新下载，删除BiliClient/wasm_enc文件夹也是一样显示：  
配置加载异常，原因为Expecting value:line1 column1(char 0)
请教一下具体应该如何正确操作

**Comment by happy888888** [comment]
> > > @happy888888
> > > > wasmtime是本地直播心跳加密模块用的，如果不需要直播心跳，可以把这个模块删除。如果删除模块后仍要使用直播心跳功能，会把心跳数据包发送到我搭建的加密服务器进行加密。
> > > > 也就是说直播心跳功能既可以使用依赖于wasmtime的本地加密模块，也可以直接使用远程服务器进行加密
> > > 
> > > 
> > > 请问如何删除模块，我尝试注释掉 config 里面关于直播心跳的代码并删除tasks/xlive_heartbeat_task.py文件，但是依旧会报错提示wasmtime only works on 64-bit platforms right now
> > 
> > 
> > `BiliClient/wasm_enc`文件夹删除就好
> 
> 尝试了一下，换了个报错 :( 不知道是哪里有问题，于是试过重新下载，删除BiliClient/wasm_enc文件夹也是一样显示：
> 配置加载异常，原因为Expecting value:line1 column1(char 0)
> 请教一下具体应该如何正确操作

requirements.txt文件里有本项目需要安装的模块，请在命令行下用`pip install -r requirements.txt`命令安装
