### ISSUE TITLE
DOCKER运行不成功

### ISSUE THREAD

**Issue by Mark2T** [happy888888/BiliExp#216]
# docker run \
> -v /home/user/Biliexp:/BiliExp \
> happy888888/biliexp:runner-latest 
Connecting to api.github.com (192.30.255.117:443)
Connecting to codeload.github.com (192.30.255.120:443)
saving to '/tmp/BiliExp.zip'
BiliExp.zip          100% |********************************|  129k  0:00:00 ETA
'/tmp/BiliExp.zip' saved
Archive:  /tmp/BiliExp.zip
   creating: happy888888-BiliExp-cc009b0/
   creating: happy888888-BiliExp-cc009b0/.github/
  inflating: happy888888-BiliExp-cc009b0/.github/pull.yml
   creating: happy888888-BiliExp-cc009b0/.github/workflows/
  inflating: happy888888-BiliExp-cc009b0/.github/workflows/deploy_for_aliyun.yml
  inflating: happy888888-BiliExp-cc009b0/.github/workflows/deploy_for_tencentyun.yml
   creating: happy888888-BiliExp-cc009b0/BiliClient/
  inflating: happy888888-BiliExp-cc009b0/BiliClient/Article.py
  inflating: happy888888-BiliExp-cc009b0/BiliClient/Audio.py
  inflating: happy888888-BiliExp-cc009b0/BiliClient/BiliApi.py
  inflating: happy888888-BiliExp-cc009b0/BiliClient/Danmu2Ass.py
  inflating: happy888888-BiliExp-cc009b0/BiliClient/Downloader.py
  inflating: happy888888-BiliExp-cc009b0/BiliClient/Manga.py
  inflating: happy888888-BiliExp-cc009b0/BiliClient/Video.py
  inflating: happy888888-BiliExp-cc009b0/BiliClient/__init__.py
  inflating: happy888888-BiliExp-cc009b0/BiliClient/asyncBiliApi.py
  inflating: happy888888-BiliExp-cc009b0/BiliExp.py
   creating: happy888888-BiliExp-cc009b0/Docker/
  inflating: happy888888-BiliExp-cc009b0/Docker/Dockerfile
  inflating: happy888888-BiliExp-cc009b0/Docker/entrypoint.sh
  inflating: happy888888-BiliExp-cc009b0/LICENSE
  inflating: happy888888-BiliExp-cc009b0/README.md
   creating: happy888888-BiliExp-cc009b0/browser_assist/
  inflating: happy888888-BiliExp-cc009b0/browser_assist/README.md
   creating: happy888888-BiliExp-cc009b0/config/
  inflating: happy888888-BiliExp-cc009b0/config/README.md
  inflating: happy888888-BiliExp-cc009b0/config/activities.json
  inflating: happy888888-BiliExp-cc009b0/config/config.json
  inflating: happy888888-BiliExp-cc009b0/mangaDownloader.py
   creating: happy888888-BiliExp-cc009b0/player_proxy/
  inflating: happy888888-BiliExp-cc009b0/player_proxy/README.md
  inflating: happy888888-BiliExp-cc009b0/player_proxy/player_proxy.js
  inflating: happy888888-BiliExp-cc009b0/requirements.txt
   creating: happy888888-BiliExp-cc009b0/serverless/
  inflating: happy888888-BiliExp-cc009b0/serverless/aliyun_serverless.yml
  inflating: happy888888-BiliExp-cc009b0/serverless/serverless.yml
   creating: happy888888-BiliExp-cc009b0/tasks/
  inflating: happy888888-BiliExp-cc009b0/tasks/__init__.py
  inflating: happy888888-BiliExp-cc009b0/tasks/activity_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/clean_dynamic_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/coin_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/exchangeCoupons_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/group_sign_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/import_once.py
  inflating: happy888888-BiliExp-cc009b0/tasks/judgement_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/lottery_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/manga_auto_buy_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/manga_comrade_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/manga_sign_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/manga_vip_reward_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/msg_notify_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/push_message_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/share_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/silver2coin_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/vip_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/watch_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/xliveSign_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/xlive_anchor_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/xlive_bag_send_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/xlive_heartbeat_task.py
  inflating: happy888888-BiliExp-cc009b0/topicRepost.py
  inflating: happy888888-BiliExp-cc009b0/videoDownloader.py
  inflating: happy888888-BiliExp-cc009b0/videoUploader.py
   creating: happy888888-BiliExp-cc009b0/?????????up???/
  inflating: happy888888-BiliExp-cc009b0/?????????up???/README.md
  inflating: happy888888-BiliExp-cc009b0/?????????up???/youtube???????????????.py
  inflating: happy888888-BiliExp-cc009b0/?????????up???/???????????????????????????????????????.py
  inflating: happy888888-BiliExp-cc009b0/?????????up???/???????????????????????????????????????.py
配置加载异常，原因为Expecting property name enclosed in double quotes: line 3 column 25 (char 27)，退出程序

这是日志 不清楚什么原因

**Comment by happy888888** [comment]
配置文件格式不正确

**Comment by solodarker** [comment]
配置加载异常，原因为Expecting property name enclosed in double quotes: line 2 column 25 (char 26)，退出程序

同样是这个问题。无法运行

**Comment by happy888888** [comment]
使用这个配置文件
https://github.com/happy888888/BiliExp/blob/1.1.9/config/config.json

**Comment by 9k001** [comment]
注意把中文去掉。。
