### ISSUE TITLE
天选时刻中奖概率的问题

### ISSUE THREAD

**Issue by TTNTO** [happy888888/BiliExp#221]
同时运行了5个号，有两个号抽奖信息满了两页（40条）之后就再也抽不到一个了，另外两个号还没抽到40条，想问一下大家有没有这个状况，怀疑是b站的源码里对这个设置了限制条件？0v0

**Comment by happy888888** [comment]
与本项目代码无关的内容最好别发"issue"，"讨论"可以放到"Discussions"里。

现在几乎可以确定中奖数量越多的账号中奖几率越低了，应该是有吸引新人的目的，但这无法证实，本项目只是代替手动参与抽奖，你可以试试纯手抽看看能否突破这个限制以反证本项目对中奖率的影响。

**Comment by if1y** [comment]
风控肯定有，见怪不怪。
抽奖就图一乐，真指望中，不现实。
