### ISSUE TITLE
提交一个最新的转盘抽奖活动（2月4日-2月16日）

### ISSUE THREAD

**Issue by GJF2015** [happy888888/BiliExp#222]
[招商银行小招喵豪送20年大会员](https://www.bilibili.com/blackboard/activity-cmbchina2021.html?i_transfer_match=e5b0cc62-e45b-4958-b416-ad4ecc4a35c2&native.theme=1)

`sid="c9363300-5fb3-11eb-8597-246e966235d8"`

抽奖时间：**2月4日-2月16日**

**Comment by GJF2015** [comment]
能否更新一下activities.json

**Comment by if1y** [comment]
sid 是怎么抓的来着……我忘了，教程也没找着
