### ISSUE TITLE
 配置加载异常，原因为Expecting value: line 1 column 1 (char 0)，退出程序

### ISSUE THREAD

**Issue by Azurlane-a** [happy888888/BiliExp#226]
**配置加载异常，原因为Expecting value: line 1 column 1 (char 0)，退出程序**

只改了cookie 其他默认 已是最新版

Windows 已安装python 源代码启动。

**Comment by happy888888** [comment]
安装json5
`pip install json5`

**Comment by Azurlane-a** [comment]
> 安装json5
> `pip install json5`

啊这，，又来了新问题，
C:\Users\Desktop\BiliExp-master>python BiliExp.py
C:\Users\Desktop\BiliExp-master\BiliExp.py:83: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
  await asyncio.wait([run_user_tasks(user, configData["default"]) for user in configData["users"]]) #执行任务
C:\Users\Desktop\BiliExp-master\BiliExp.py:137: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
  await asyncio.wait(task_array)        #异步等待所有任务完成

**Comment by happy888888** [comment]
不能正常运行吗？这个警告应该不会影响正常运行的，直到python3.11版本之前

**Comment by Azurlane-a** [comment]
> 不能正常运行吗？这个警告应该不会影响正常运行的，直到python3.11版本之前

好像是运行了，刚才天选中奖了，2.33元，但是命令框没显示文字输出

**Comment by happy888888** [comment]
配置文件有个配置项"log_console"，把false改为true就可以在控制台输出，或者直接看日志文件

**Comment by Azurlane-a** [comment]
> 配置文件有个配置项"log_console"，把false改为true就可以在控制台输出，或者直接看日志文件

啊这，我是个瞎子，这都没看到，添麻烦了，解决了。
