### ISSUE TITLE
docker 定时启动命令执行问题

### ISSUE THREAD

**Issue by 9k001** [happy888888/BiliExp#228]
执行环境：openwrt(docker)
执行经过：

任意路径执行
docker run --name=biliexp -v /opt/data/openwrt_scripts/docker_config/biliexp:/BiliExp happy888888/biliexp:runner-latest -t 1.1.9 -d -c "0 8 * * *"
执行结果：
卡住，程序不跳出

**Comment by happy888888** [comment]
`docker run --name=biliexp -d -v /opt/data/openwrt_scripts/docker_config/biliexp:/BiliExp happy888888/biliexp:runner-latest -t 1.1.9 -d -c "0 8 * * *"`
这样可以让docker后台运行

**Comment by 9k001** [comment]
> `docker run --name=biliexp -d -v /opt/data/openwrt_scripts/docker_config/biliexp:/BiliExp happy888888/biliexp:runner-latest -t 1.1.9 -d -c "0 8 * * *"`
> 这样可以让docker后台运行

我理解-d 后台运行，问题是。。。我的跳出执行程序呀 不能关闭xshell来解决问题吧

**Comment by happy888888** [comment]
`docker run --name=biliexp -v /opt/data/openwrt_scripts/docker_config/biliexp:/BiliExp happy888888/biliexp:runner-latest -t 1.1.9`
这样就会运行一次后退出

**Comment by 9k001** [comment]
> `docker run --name=biliexp -v /opt/data/openwrt_scripts/docker_config/biliexp:/BiliExp happy888888/biliexp:runner-latest -t 1.1.9`
> 这样就会运行一次后退出

。。。这不成头疼医头脚疼医脚的解决办法了么
那就编成crond配合脚本来解决问题。

**Comment by happy888888** [comment]
> > `docker run --name=biliexp -v /opt/data/openwrt_scripts/docker_config/biliexp:/BiliExp happy888888/biliexp:runner-latest -t 1.1.9`
> > 这样就会运行一次后退出
> 
> 。。。这不成头疼医头脚疼医脚的解决办法了么
> 那就编成crond配合脚本来解决问题。

要么docker不退出不断运行，要么外部定时执行docker，你难道还能找出其他执行方案吗？
