### ISSUE TITLE
部署腾讯云出现问题

### ISSUE THREAD

**Issue by brad214** [happy888888/BiliExp#23]
sls deploy --debug || (echo '检查到部署程序异常退出，请检查腾讯云函数参数是否配置正确(key名带下划线)，请不要使用子账户，并确认云函数功能已开启(云函数控制台 https://console.cloud.tencent.com/scf)' && exit -1)
  shell: /bin/bash -e ***0***

**Comment by happy888888** [comment]
没有设置secretId/Key吧，脚本没权限访问你的腾讯云函数，这个腾讯云的部署程序是[tinafangkunding](https://github.com/tinafangkunding)提交到我的仓库里的，我并没有测试过这个部署程序。

**Comment by brad214** [comment]
我用的是那个访问管理里面的，可以出个教程吗，嘻嘻

**Comment by tinafangkunding** [comment]
hi @brad214 请问有报错的详细信息吗？建议从这个地址获取主账号的 sid 和 key

https://console.cloud.tencent.com/cam/capi

**Comment by tinafangkunding** [comment]
我可以出个详细一点的教程附上

**Comment by brad214** [comment]
我就是从这里获取的

**Comment by brad214** [comment]
sls deploy --debug || (echo '检查到部署程序异常退出，请检查腾讯云函数参数是否配置正确(key名带下划线)，请不要使用子账户，并确认云函数功能已开启(云函数控制台 https://console.cloud.tencent.com/scf)' && exit -1)
  shell: /bin/bash -e ***0***
  env:
    SERVERLESS_PLATFORM_VENDOR: tencent
    TENCENT_SECRET_ID: ***
    TENCENT_SECRET_KEY: ***
25lInitializing...
Deploying...
the code will be uploaded to https://sp-gins-prod-1300963013.cos.na-siliconvalley.myqcloud.com/7e4baa8b-d035-492f-9a6d-c084d3c07881.zip?q-sign-algorithm=sha1&q-ak=AKID1qcBe1cVaOwSmtn67y7pJJIAVj4jftBE&q-sign-time=1601347143;1601347743&q-key-time=1601347143;1601347743&q-header-list=&q-url-param-list=&q-signature=c981a88dd3c73a4c70736e6a6636113dbf945373
the code will be uploaded to https://sp-gins-prod-1300963013.cos.na-siliconvalley.myqcloud.com/8250a1e5-b4eb-4412-833a-072d959cf5c3.zip?q-sign-algorithm=sha1&q-ak=AKID1qcBe1cVaOwSmtn67y7pJJIAVj4jftBE&q-sign-time=1601347143;1601347743&q-key-time=1601347143;1601347743&q-header-list=&q-url-param-list=&q-signature=991541f487948b42662cb0bfc566aa93e41210ed
the code will be uploaded to https://sp-gins-prod-1300963013.cos.na-siliconvalley.myqcloud.com/a040ee8a-35b0-43ef-81ef-f0ee822c188d.zip?q-sign-algorithm=sha1&q-ak=AKID1qcBe1cVaOwSmtn67y7pJJIAVj4jftBE&q-sign-time=1601347143;1601347743&q-key-time=1601347143;1601347743&q-header-list=&q-url-param-list=&q-signature=f757e4b04918d8b2199e6d8affcfb5389f35e12e
the code will be uploaded to https://sp-gins-prod-1300963013.cos.na-siliconvalley.myqcloud.com/e6e9a652-5b15-422e-8dc4-80f2eb1f00a5.zip?q-sign-algorithm=sha1&q-ak=AKID1qcBe1cVaOwSmtn67y7pJJIAVj4jftBE&q-sign-time=1601347143;1601347743&q-key-time=1601347143;1601347743&q-header-list=&q-url-param-list=&q-signature=9a7e7a70d393e32c9d0cf0fa2de4dfc496227e58
the code will be uploaded to https://sp-gins-prod-1300963013.cos.na-siliconvalley.myqcloud.com/86068559-6fad-4fb0-ae31-300eb394270c.zip?q-sign-algorithm=sha1&q-ak=AKID1qcBe1cVaOwSmtn67y7pJJIAVj4jftBE&q-sign-time=1601347143;1601347743&q-key-time=1601347143;1601347743&q-header-list=&q-url-param-list=&q-signature=c655252d158759daa02f63ca7bc9eaafc3ccf784
the code will be uploaded to https://sp-gins-prod-1300963013.cos.na-siliconvalley.myqcloud.com/78b1c919-0362-4199-b71b-39471f8cc59c.zip?q-sign-algorithm=sha1&q-ak=AKID1qcBe1cVaOwSmtn67y7pJJIAVj4jftBE&q-sign-time=1601347143;1601347743&q-key-time=1601347143;1601347743&q-header-list=&q-url-param-list=&q-signature=eab0bc96d89e2ba9e1facd57645166ac63355e96
Deploying Tencent SCF...
Deploying Tencent SCF...
Deploying Tencent SCF...
Deploying Tencent SCF...

 Error: Cannot get secretId/Key, your account could be sub-account and does not have the access to use SLS_QcsRole, please make sure the role exists first, then visit https://cloud.tencent.com/document/product/1154/43006, follow the instructions to bind the role to your account.
    at new TypeError (/var/user/node_modules/tencent-component-toolkit/src/utils/error.js:2:15)
    at ServerlessComponent.getCredentials (/var/user/serverless.js:12:13)
    at ServerlessComponent.deploy (/var/user/serverless.js:32:30)
    at Runtime.module.exports [as handler] (/opt/node_modules/@serverless/core/handler.js:306:53)
    at process._tickCallback (internal/process/next_tick.js:68:7)

BiliLottery: Cannot get secretId/Key, your account could be sub-account and does not have the access to use SLS_QcsRole, please make sure the role exists first, then visit https://cloud.tencent.com/document/product/1154/43006, follow the instructions to bind the role to your account. 

  帮助文档: https://cloud.tencent.com/document/product/1154/39270 
  获取支持: https://cloud.tencent.com/act/event/Online_service 
  问答社区: https://cloud.tencent.com/developer/ask 

 Error: Cannot get secretId/Key, your account could be sub-account and does not have the access to use SLS_QcsRole, please make sure the role exists first, then visit https://cloud.tencent.com/document/product/1154/43006, follow the instructions to bind the role to your account.
    at new TypeError (/var/user/node_modules/tencent-component-toolkit/src/utils/error.js:2:15)
    at ServerlessComponent.getCredentials (/var/user/serverless.js:12:13)
    at ServerlessComponent.deploy (/var/user/serverless.js:32:30)
    at Runtime.module.exports [as handler] (/opt/node_modules/@serverless/core/handler.js:306:53)
    at process._tickCallback (internal/process/next_tick.js:68:7)

silver2coin: Cannot get secretId/Key, your account could be sub-account and does not have the access to use SLS_QcsRole, please make sure the role exists first, then visit https://cloud.tencent.com/document/product/1154/43006, follow the instructions to bind the role to your account. 

  帮助文档: https://cloud.tencent.com/document/product/1154/39270 
  获取支持: https://cloud.tencent.com/act/event/Online_service 
  问答社区: https://cloud.tencent.com/developer/ask 
Deploying Tencent SCF...
Deploying Tencent SCF...

 Error: Cannot get secretId/Key, your account could be sub-account and does not have the access to use SLS_QcsRole, please make sure the role exists first, then visit https://cloud.tencent.com/document/product/1154/43006, follow the instructions to bind the role to your account.
    at new TypeError (/var/user/node_modules/tencent-component-toolkit/src/utils/error.js:2:15)
    at ServerlessComponent.getCredentials (/var/user/serverless.js:12:13)
    at ServerlessComponent.deploy (/var/user/serverless.js:32:30)
    at Runtime.module.exports [as handler] (/opt/node_modules/@serverless/core/handler.js:306:53)
    at process._tickCallback (internal/process/next_tick.js:68:7)

check: Cannot get secretId/Key, your account could be sub-account and does not have the access to use SLS_QcsRole, please make sure the role exists first, then visit https://cloud.tencent.com/document/product/1154/43006, follow the instructions to bind the role to your account. 

  帮助文档: https://cloud.tencent.com/document/product/1154/39270 
  获取支持: https://cloud.tencent.com/act/event/Online_service 
  问答社区: https://cloud.tencent.com/developer/ask 

 Error: Cannot get secretId/Key, your account could be sub-account and does not have the access to use SLS_QcsRole, please make sure the role exists first, then visit https://cloud.tencent.com/document/product/1154/43006, follow the instructions to bind the role to your account.
    at new TypeError (/var/user/node_modules/tencent-component-toolkit/src/utils/error.js:2:15)
    at ServerlessComponent.getCredentials (/var/user/serverless.js:12:13)
    at ServerlessComponent.deploy (/var/user/serverless.js:32:30)
    at Runtime.module.exports [as handler] (/opt/node_modules/@serverless/core/handler.js:306:53)
    at process._tickCallback (internal/process/next_tick.js:68:7)

BiliExp: Cannot get secretId/Key, your account could be sub-account and does not have the access to use SLS_QcsRole, please make sure the role exists first, then visit https://cloud.tencent.com/document/product/1154/43006, follow the instructions to bind the role to your account. 

  帮助文档: https://cloud.tencent.com/document/product/1154/39270 
  获取支持: https://cloud.tencent.com/act/event/Online_service 
  问答社区: https://cloud.tencent.com/developer/ask 

 Error: Cannot get secretId/Key, your account could be sub-account and does not have the access to use SLS_QcsRole, please make sure the role exists first, then visit https://cloud.tencent.com/document/product/1154/43006, follow the instructions to bind the role to your account.
    at new TypeError (/var/user/node_modules/tencent-component-toolkit/src/utils/error.js:2:15)
    at ServerlessComponent.getCredentials (/var/user/serverless.js:12:13)
    at ServerlessComponent.deploy (/var/user/serverless.js:32:30)
    at Runtime.module.exports [as handler] (/opt/node_modules/@serverless/core/handler.js:306:53)
    at process._tickCallback (internal/process/next_tick.js:68:7)

cleanDynamic: Cannot get secretId/Key, your account could be sub-account and does not have the access to use SLS_QcsRole, please make sure the role exists first, then visit https://cloud.tencent.com/document/product/1154/43006, follow the instructions to bind the role to your account. 

  帮助文档: https://cloud.tencent.com/document/product/1154/39270 
  获取支持: https://cloud.tencent.com/act/event/Online_service 
  问答社区: https://cloud.tencent.com/developer/ask 

 Error: Cannot get secretId/Key, your account could be sub-account and does not have the access to use SLS_QcsRole, please make sure the role exists first, then visit https://cloud.tencent.com/document/product/1154/43006, follow the instructions to bind the role to your account.
    at new TypeError (/var/user/node_modules/tencent-component-toolkit/src/utils/error.js:2:15)
    at ServerlessComponent.getCredentials (/var/user/serverless.js:12:13)
    at ServerlessComponent.deploy (/var/user/serverless.js:32:30)
    at Runtime.module.exports [as handler] (/opt/node_modules/@serverless/core/handler.js:306:53)
    at process._tickCallback (internal/process/next_tick.js:68:7)

mangaTask: Cannot get secretId/Key, your account could be sub-account and does not have the access to use SLS_QcsRole, please make sure the role exists first, then visit https://cloud.tencent.com/document/product/1154/43006, follow the instructions to bind the role to your account. 

  帮助文档: https://cloud.tencent.com/document/product/1154/39270 
  获取支持: https://cloud.tencent.com/act/event/Online_service 
  问答社区: https://cloud.tencent.com/developer/ask 
BiliExp:      undefined
BiliLottery:  undefined
check:        undefined
cleanDynamic: undefined
mangaTask:    undefined
silver2coin:  undefined
23s › BiliExp › Success

25h

**Comment by happy888888** [comment]
@tinafangkunding 我想请问一下出现这种情况怎么办
```
Your have not verified your identity in account center, please verify. (reqId: NWY3MzQyMTFfMzhiY2IxMDlfMzM0OTdfMWMzMjU4OQ==) 
```
好像是身份认证的问题，账号没实名强制用不了吗，SERVERLESS_PLATFORM_VENDOR改为aws会不会可以不用实名。

**Comment by tinafangkunding** [comment]
@happy888888 这种情况确实可能因为几种 引起
1. 子账户，缺乏权限
2. 未实名，或者账户欠费等，没有资格创建资源

目前确实使用对应的函数资源要强制实名了···

**Comment by happy888888** [comment]
@tinafangkunding 没用子账号，secretId/Key用的主账户的，因为我的dnspod也是用的这个secretId/Key来访问域名，我记得今年7月份以前SCF是不用实名的(使用api网关用http方式触发才需要实名)，现在别说创建资源了，想进入https://console.cloud.tencent.com/scf/list?rid=1&ns=default 删除以前创建的云函数退坑都做不到了....

**Comment by tinafangkunding** [comment]
对的···现在平台限制要全部实名才可以操作资源了 > <

**Comment by tinafangkunding** [comment]
@brad214 部署教程可以参考 https://my-hexo-bucket-1251971143.cos-website.ap-guangzhou.myqcloud.com/2020/09/30/bilibili/

**Comment by brad214** [comment]
@tinafangkunding 我按照教程，还是提示原来那个，还是部署不了，我账户实名了也是主账户，用微信登陆的

**Comment by brad214** [comment]
@tinafangkunding Cannot get secretId/Key, your account could be sub-account and does not have the access to use SLS_QcsRole, please make sure the role exists first
是不是这个问题

**Comment by tinafangkunding** [comment]
@brad214 怀疑是没有sls权限问题 可以试试进入到serverless framework控制台 然后授权加一下角色。这块忽略了

**Comment by Zd036** [comment]
我也是同样的问题，已确认
1.用的主账号
2.账号已授权sls
3.账号已实名

**Comment by tinafangkunding** [comment]
奇怪，方便发我一下 appid 来查一下到底哪里的问题吗 @Zd036 @brad214

**Comment by AprilJC** [comment]
@Zd036 这边可以辛苦确认一下在云函数 **“访问管理”** 控制台 -  **“角色”**  处看一下是否有 SLS_QcsRole 角色呢？
部署权限前提：
主账户：
1. 账号已实名
2. 开通 sls 服务，并成功创建 SLS_QcsRole 角色

子账户：
1. 主账户已开通 sls 服务，并成功创建 SLS_QcsRole 角色
2. 主账户给子账户 SLS_QcsRole 调用权限，参考文档：https://cloud.tencent.com/document/product/1154/43006#.E5.AD.90.E8.B4.A6.E5.8F.B7.E6.9D.83.E9.99.90.E9.85.8D.E7.BD.AE

**Comment by brad214** [comment]
@tinafangkunding 1300548678您看看

**Comment by brad214** [comment]
@tinafangkunding 而且我在Serverless Framework里面可以看到bilibili应用，但是云函数里面确实没有，还是一样报错

**Comment by viko-so** [comment]
我也出现了这个问题，目前解决了。

操作步骤如下：
1）删除 “**访问管理**” 控制台 - “**角色**”中的全部角色（因为没其他的项目，所以我全删了）
2）重新开通云函数的权限，确保刷新页面后，没有权限提示[https://console.cloud.tencent.com/scf](url)
3）重新开通sls服务的权限，确保刷新页面后，没有权限提示[https://console.cloud.tencent.com/sls](url)
4）删除Serverless Framework里面的bilibili应用，大概会剩一个删不掉
5）回到github，重新执行workflow

主账号状态：
1）已实名
2）角色只有两个：SLS_QcsRole、SCF_QcsRole

**Comment by brad214** [comment]
@viko-so 按照你这个方法，会不会把原来的腾讯云函数删除了

**Comment by tinafangkunding** [comment]
和 @brad214 联系了一下，确认了有云函数和 SLS 权限之后可以部署了~

**Comment by Nsking-xs** [comment]
@happy888888 建议在教程里面加一下  腾讯云主账号除了要有云函数的角色权限还要有 Serverless Framework 的角色权限，获取权限的方法也很简单，分别打开[https://console.cloud.tencent.com/sls](https://console.cloud.tencent.com/sls) 和[https://console.cloud.tencent.com/scf/list?rid=1&ns=default](https://console.cloud.tencent.com/scf/list?rid=1&ns=default) 按照提示开通就好

**Comment by tinafangkunding** [comment]
Get 我来加一下

**Comment by Phil-tung** [comment]
Run sls deploy --debug || (echo '检查到部署程序异常退出，请检查腾讯云函数参数是否配置正确(key名带下划线)，请不要使用子账户，并确认云函数功能已开启(云函数控制台 https://console.cloud.tencent.com/scf)' && exit -1)
8
25lInitializing...
9

10
 Error: The provided credentials could not be validated. Please check your signature is correct.
11
    at /usr/local/lib/node_modules/serverless/node_modules/@serverless/utils-china/library/common/abstract_client.js:102:31
12
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/@serverless/utils-china/library/common/http/http_connection.js:71:9)
13
    at IncomingMessage.emit (events.js:327:22)
14
    at endReadableNT (_stream_readable.js:1220:12)
15
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
16

17
1s › Serverless › The provided credentials could not be validated. Please check your signature is correct. 
18

19
  帮助文档: https://cloud.tencent.com/document/product/1154/39270 
20
  获取支持: https://cloud.tencent.com/act/event/Online_service 
21
  问答社区: https://cloud.tencent.com/developer/ask 
22

23

24
25h检查到部署程序异常退出，请检查腾讯云函数参数是否配置正确(key名带下划线)，请不要使用子账户，并确认云函数功能已开启(云函数控制台 https://console.cloud.tencent.com/scf)
25
Error: Process completed with exit code 255.
可以麻烦大牛们帮我看一下吗 小白一个 appID 1303834587
