### ISSUE TITLE
action的日志文件或者临时文件在哪里可以查看

### ISSUE THREAD

**Issue by FairyWorld** [happy888888/BiliExp#230]
我看到biliexp的配置里有个输出日志文件的功能还有很久之前有个auto_merge.yml也有个临时merge信息的文件，突然很好奇这种在action运行时生成的文件如何查看。
我看了下action页面并没有发现查看生成文件的地方，而且每次action的执行应该是在不同的环境，理论每次输出的日志都在单独的一个容器环境里，不知道哪里可以找到这些文件。

**Comment by if1y** [comment]
一般是在控制台直接看，就是 Actions 的执行日志
Actions 本身就是一个 vps 容器，可以连上ssh去找找，推测应该是 `$workdir/BiliExp.log`
如果想把文件导出来的话，可以看看 https://github.com/actions/upload-artifact ，或者在运行过程中增加脚本传到其他第三方平台

**Comment by happy888888** [comment]
所有临时文件如果没有缓存都会在actions执行结束时释放（更准确的说是job结束时释放，每个workflow文件可以并发多个job，每个job相当于一个vps实例，而job中的每个step相当于一个进程实例）

所以要获得临时文件只能使用其他方法在一次actions结束前保存到其他地方。
