### ISSUE TITLE
第四十一行  "danmu_filter": [] 输入中文后会运行失败

### ISSUE THREAD

**Issue by Azurlane-a** [happy888888/BiliExp#231]
第41行  "danmu_filter": [],  //弹幕过滤关键字，值为字符串数组，弹幕包含此值会被过滤
输入中文后会运行失败：配置加载异常，原因为<string>:5 Unexpected """ at column 5，退出程序

2021年2月8日22:05:02
补充问题：
第三十九行  "room_filter": [3],   //直播间黑名单，值为整数数组，指定直播间的天选将不会参与
设置房号后天选出现异常：天选时刻抽奖任务异常，异常为('in <string>' requires string as left operand, not int)
 
Windows

**Comment by happy888888** [comment]
尝试已修复此问题，请使用最新的代码

**Comment by Azurlane-a** [comment]
> 已尝试修复此问题，请使用最新的代码
> 
> 字符串记得两端要加英文引号

已测试，OKK了。

**Comment by Azurlane-a** [comment]
> 已尝试修复此问题，请使用最新的代码
> 
> 字符串记得两端要加英文引号

天选关键词过滤无效，添加了关键词仍然会参与抽奖。
