### ISSUE TITLE
视频投稿功能希望添加上传多P视频

### ISSUE THREAD

**Issue by cibimo** [happy888888/BiliExp#232]
多P视频在网页端不能上传，但在windows客户端可以上传，如果命令行能实现多P上传，我就不用开着虚拟机在win下上传了

**Comment by happy888888** [comment]
已收到建议，目前命令行暂时不支持上传多P视频，但本项目的库文件当前是支持上传多P视频的，如果是python开发者可以直接参考
[python发布视频稿件](https://github.com/happy888888/BiliExp/tree/master/%E6%9C%BA%E5%99%A8%E4%BA%BAup%E4%B8%BB#发布视频稿件)

**Comment by happy888888** [comment]
最新版已改为使用app方式投稿，支持多P视频上传
