### ISSUE TITLE
运行默认的配置，转发动态抽奖的功能正常吗

### ISSUE THREAD

**Issue by b9735** [happy888888/BiliExp#233]
secret设置的跑大佬的仓库代码，感觉貌似没有进行动态抽奖

**Comment by happy888888** [comment]
你得先关注其他抽奖up主

**Comment by b9735** [comment]
我关注了，我感觉从四号开始就不会发动态了，我调整过yml，想问下这个功能对时间有依赖吗，是不是必须中午12点才会执行

**Comment by happy888888** [comment]
默认配置是每天中午12点触发一次，每次转发今天中午12点到昨天中午12点之间你关注的所有人发出的抽奖动态。

这个转发的时间区间是可以改的，主要是为了防止重复转发

**Comment by asd987467104** [comment]
我也是一样的问题，空间里最新动态转发抽奖还在2月1号，还是大佬以前Actions分支好用，已经好多天没抽奖了，感觉亏了一个亿

**Comment by happy888888** [comment]
@asd987467104 @b9735 其实就是配置文件变了一下，本来想让你们自己调整执行周期将抽奖的时间分散化的，顺便加入一些随机自定义动态，这种每天中午集中转发容易被官方认为抽奖号。

没想到你们都不喜欢调整配置文件，我又把配置文件调整回原来的转发模式了，***直接更新代码***或者***使用secrets “repository”设置值为"happy888888/BiliExp"将我的仓库设置为代码源***二选一就行。

**Comment by T1573** [comment]
> @asd987467104 @b9735 其实就是配置文件变了一下，本来想让你们自己调整执行周期将抽奖的时间分散化的，顺便加入一些随机自定义动态，这种每天中午集中转发容易被官方认为抽奖号。
> 
> 没想到你们都不喜欢调整配置文件，我又把配置文件调整回原来的转发模式了，_**直接更新代码**_或者_**使用secrets “repository”设置值为"happy888888/BiliExp"将我的仓库设置为代码源**_二选一就行。

我也是，1.2.0版本无论是默认配置还是secrets “ADVCONFIG”设置运行都不会运行转发抽奖

**Comment by happy888888** [comment]
> > @asd987467104 @b9735 其实就是配置文件变了一下，本来想让你们自己调整执行周期将抽奖的时间分散化的，顺便加入一些随机自定义动态，这种每天中午集中转发容易被官方认为抽奖号。
> > 没想到你们都不喜欢调整配置文件，我又把配置文件调整回原来的转发模式了，_**直接更新代码**_或者_**使用secrets “repository”设置值为"happy888888/BiliExp"将我的仓库设置为代码源**_二选一就行。
> 
> 我也是，1.2.0版本无论是默认配置还是secrets “ADVCONFIG”设置运行都不会运行转发抽奖，已经删掉重新for过了，是最新版。

如果只每天中午12点运行一次，把配置文件112行修改一下`"time_quantum": [-43200, 43200],`

**Comment by T1573** [comment]
> > > @asd987467104 @b9735 其实就是配置文件变了一下，本来想让你们自己调整执行周期将抽奖的时间分散化的，顺便加入一些随机自定义动态，这种每天中午集中转发容易被官方认为抽奖号。
> > > 没想到你们都不喜欢调整配置文件，我又把配置文件调整回原来的转发模式了，_**直接更新代码**_或者_**使用secrets “repository”设置值为"happy888888/BiliExp"将我的仓库设置为代码源**_二选一就行。
> > 
> > 
> > 我也是，1.2.0版本无论是默认配置还是secrets “ADVCONFIG”设置运行都不会运行转发抽奖，已经删掉重新for过了，是最新版。
> 
> 如果只每天中午12点运行一次，把配置文件112行修改一下`"time_quantum": [-43200, 43200],`

我手动运行都不会抽奖

**Comment by happy888888** [comment]
目前actions默认已经修改为上述配置了，如果是`"time_quantum": [0, 600],`则应该每隔10分钟执行一次

有的人会一天执行多次，为防止重复转发增加了此项设置

**Comment by happy888888** [comment]
> > > > @asd987467104 @b9735 其实就是配置文件变了一下，本来想让你们自己调整执行周期将抽奖的时间分散化的，顺便加入一些随机自定义动态，这种每天中午集中转发容易被官方认为抽奖号。
> > > > 没想到你们都不喜欢调整配置文件，我又把配置文件调整回原来的转发模式了，_**直接更新代码**_或者_**使用secrets “repository”设置值为"happy888888/BiliExp"将我的仓库设置为代码源**_二选一就行。
> > > 
> > > 
> > > 我也是，1.2.0版本无论是默认配置还是secrets “ADVCONFIG”设置运行都不会运行转发抽奖，已经删掉重新for过了，是最新版。
> > 
> > 
> > 如果只每天中午12点运行一次，把配置文件112行修改一下`"time_quantum": [-43200, 43200],`
> 
> 我手动运行都不会抽奖

time_quantum 参数是怎么配置的？

**Comment by T1573** [comment]
> > > > > @asd987467104 @b9735 其实就是配置文件变了一下，本来想让你们自己调整执行周期将抽奖的时间分散化的，顺便加入一些随机自定义动态，这种每天中午集中转发容易被官方认为抽奖号。
> > > > > 没想到你们都不喜欢调整配置文件，我又把配置文件调整回原来的转发模式了，_**直接更新代码**_或者_**使用secrets “repository”设置值为"happy888888/BiliExp"将我的仓库设置为代码源**_二选一就行。
> > > > 
> > > > 
> > > > 我也是，1.2.0版本无论是默认配置还是secrets “ADVCONFIG”设置运行都不会运行转发抽奖，已经删掉重新for过了，是最新版。
> > > 
> > > 
> > > 如果只每天中午12点运行一次，把配置文件112行修改一下`"time_quantum": [-43200, 43200],`
> > 
> > 
> > 我手动运行都不会抽奖
> 
> time_quantum 参数是怎么配置的？

用的ADVCONFIG，默认[0, 600]

**Comment by happy888888** [comment]
> > > > > > @asd987467104 @b9735 其实就是配置文件变了一下，本来想让你们自己调整执行周期将抽奖的时间分散化的，顺便加入一些随机自定义动态，这种每天中午集中转发容易被官方认为抽奖号。
> > > > > > 没想到你们都不喜欢调整配置文件，我又把配置文件调整回原来的转发模式了，_**直接更新代码**_或者_**使用secrets “repository”设置值为"happy888888/BiliExp"将我的仓库设置为代码源**_二选一就行。
> > > > > 
> > > > > 
> > > > > 我也是，1.2.0版本无论是默认配置还是secrets “ADVCONFIG”设置运行都不会运行转发抽奖，已经删掉重新for过了，是最新版。
> > > > 
> > > > 
> > > > 如果只每天中午12点运行一次，把配置文件112行修改一下`"time_quantum": [-43200, 43200],`
> > > 
> > > 
> > > 我手动运行都不会抽奖
> > 
> > 
> > time_quantum 参数是怎么配置的？
> 
> 用的ADVCONFIG，默认[0, 600]

如果这样配置，需要每隔10分钟执行一次
[-43200, 43200]就需要每天中午12点后执行一次

**Comment by happy888888** [comment]
参考这个 https://github.com/happy888888/BiliExp/issues/178

**Comment by T1573** [comment]
> > > > > > > @asd987467104 @b9735 其实就是配置文件变了一下，本来想让你们自己调整执行周期将抽奖的时间分散化的，顺便加入一些随机自定义动态，这种每天中午集中转发容易被官方认为抽奖号。
> > > > > > > 没想到你们都不喜欢调整配置文件，我又把配置文件调整回原来的转发模式了，_**直接更新代码**_或者_**使用secrets “repository”设置值为"happy888888/BiliExp"将我的仓库设置为代码源**_二选一就行。
> > > > > > 
> > > > > > 
> > > > > > 我也是，1.2.0版本无论是默认配置还是secrets “ADVCONFIG”设置运行都不会运行转发抽奖，已经删掉重新for过了，是最新版。
> > > > > 
> > > > > 
> > > > > 如果只每天中午12点运行一次，把配置文件112行修改一下`"time_quantum": [-43200, 43200],`
> > > > 
> > > > 
> > > > 我手动运行都不会抽奖
> > > 
> > > 
> > > time_quantum 参数是怎么配置的？
> > 
> > 
> > 用的ADVCONFIG，默认[0, 600]
> 
> 如果这样配置，需要每隔10分钟执行一次
> [-43200, 43200]就需要每天中午12点后执行一次

但这会影响手动执行吗？现在已经过了10分钟我又手动执行了一次，日志里并没有抽奖相关的文字

**Comment by happy888888** [comment]
> > > > > > > > @asd987467104 @b9735 其实就是配置文件变了一下，本来想让你们自己调整执行周期将抽奖的时间分散化的，顺便加入一些随机自定义动态，这种每天中午集中转发容易被官方认为抽奖号。
> > > > > > > > 没想到你们都不喜欢调整配置文件，我又把配置文件调整回原来的转发模式了，_**直接更新代码**_或者_**使用secrets “repository”设置值为"happy888888/BiliExp"将我的仓库设置为代码源**_二选一就行。
> > > > > > > 
> > > > > > > 
> > > > > > > 我也是，1.2.0版本无论是默认配置还是secrets “ADVCONFIG”设置运行都不会运行转发抽奖，已经删掉重新for过了，是最新版。
> > > > > > 
> > > > > > 
> > > > > > 如果只每天中午12点运行一次，把配置文件112行修改一下`"time_quantum": [-43200, 43200],`
> > > > > 
> > > > > 
> > > > > 我手动运行都不会抽奖
> > > > 
> > > > 
> > > > time_quantum 参数是怎么配置的？
> > > 
> > > 
> > > 用的ADVCONFIG，默认[0, 600]
> > 
> > 
> > 如果这样配置，需要每隔10分钟执行一次
> > [-43200, 43200]就需要每天中午12点后执行一次
> 
> 但这会影响手动执行吗？现在已经过了10分钟我又手动执行了一次，日志里并没有抽奖相关的文字

那只说明这10分钟内你关注的所有up主都没有发布抽奖动态

**Comment by happy888888** [comment]
如果修改为[-43200, 43200]，手动执行也没有转发，就说明今天中午12点回到昨天中午12点之间你关注的所有up主没有发布抽奖动态

**Comment by T1573** [comment]
> [-43200, 43200]

多谢，我大概明白原因了

**Comment by T1573** [comment]
> 如果修改为[-43200, 43200]，手动执行也没有转发，就说明今天中午12点回到昨天中午12点之间你关注的所有up主没有发布抽奖动态

对了能加个每日转发抽奖次数限制吗？有时候转发过多会导致账号异常（不能关注，评论会被隐藏），且无法解封

**Comment by happy888888** [comment]
> > 如果修改为[-43200, 43200]，手动执行也没有转发，就说明今天中午12点回到昨天中午12点之间你关注的所有up主没有发布抽奖动态
> 
> 对了能加个每日转发抽奖次数限制吗？有时候转发过多会导致账号异常（不能关注，评论会被隐藏），且无法解封

那是因为短时间内转发大量动态导致的，你可以试试把`"delay": [6, 8],`参数调大，比如`"delay": [10, 20],`每转发一次动态就会延时10到20秒才会进行下一次转发。把`"time_quantum": [-43200, 43200],`改为`"time_quantum": [0, 3600],`然后每隔1个小时执行一次，这样每次运行都只转发过去1小时的动态抽奖

总之最好避免短时间内转发大量动态，尽量分散转发

**Comment by T1573** [comment]
> > > 如果修改为[-43200, 43200]，手动执行也没有转发，就说明今天中午12点回到昨天中午12点之间你关注的所有up主没有发布抽奖动态
> > 
> > 
> > 对了能加个每日转发抽奖次数限制吗？有时候转发过多会导致账号异常（不能关注，评论会被隐藏），且无法解封
> 
> 那是因为短时间内转发大量动态导致的，你可以试试把`"delay": [6, 8],`参数调大，比如`"delay": [10, 20],`每转发一次动态就会延时10到20秒才会进行下一次转发。把`"time_quantum": [-43200, 43200],`改为`"time_quantum": [0, 3600],`然后每隔1个小时执行一次，这样每次运行都只转发过去1小时的动态抽奖
> 
> 总之最好避免短时间内转发大量动态，尽量分散转发

懂了

**Comment by windCloud152** [comment]
> 
> 
> > > 如果修改为[-43200, 43200]，手动执行也没有转发，就说明今天中午12点回到昨天中午12点之间你关注的所有up主没有发布抽奖动态
> > 
> > 
> > 对了能加个每日转发抽奖次数限制吗？有时候转发过多会导致账号异常（不能关注，评论会被隐藏），且无法解封
> 
> 那是因为短时间内转发大量动态导致的，你可以试试把`"delay": [6, 8],`参数调大，比如`"delay": [10, 20],`每转发一次动态就会延时10到20秒才会进行下一次转发。把`"time_quantum": [-43200, 43200],`改为`"time_quantum": [0, 3600],`然后每隔1个小时执行一次，这样每次运行都只转发过去1小时的动态抽奖
> 
> 总之最好避免短时间内转发大量动态，尽量分散转发

`"time_quantum": [-43200, 43200],改为"time_quantum": [0, 3600],`
这个是指无须载设置运行时间，只需要挑战这个就会在这个区间再次运行吗

**Comment by windCloud152** [comment]
> 
> 
> > > 如果修改为[-43200, 43200]，手动执行也没有转发，就说明今天中午12点回到昨天中午12点之间你关注的所有up主没有发布抽奖动态
> > 
> > 
> > 对了能加个每日转发抽奖次数限制吗？有时候转发过多会导致账号异常（不能关注，评论会被隐藏），且无法解封
> 
> 那是因为短时间内转发大量动态导致的，你可以试试把`"delay": [6, 8],`参数调大，比如`"delay": [10, 20],`每转发一次动态就会延时10到20秒才会进行下一次转发。把`"time_quantum": [-43200, 43200],`改为`"time_quantum": [0, 3600],`然后每隔1个小时执行一次，这样每次运行都只转发过去1小时的动态抽奖
> 
> 总之最好避免短时间内转发大量动态，尽量分散转发

`"time_quantum": [-43200, 43200],改为"time_quantum": [0, 3600],`
这个是指只需要调整这个就能在不改动`run_BiliExp.yml`的情况下再次运行吗

**Comment by happy888888** [comment]
> > > > 如果修改为[-43200, 43200]，手动执行也没有转发，就说明今天中午12点回到昨天中午12点之间你关注的所有up主没有发布抽奖动态
> > > 
> > > 
> > > 对了能加个每日转发抽奖次数限制吗？有时候转发过多会导致账号异常（不能关注，评论会被隐藏），且无法解封
> > 
> > 
> > 那是因为短时间内转发大量动态导致的，你可以试试把`"delay": [6, 8],`参数调大，比如`"delay": [10, 20],`每转发一次动态就会延时10到20秒才会进行下一次转发。把`"time_quantum": [-43200, 43200],`改为`"time_quantum": [0, 3600],`然后每隔1个小时执行一次，这样每次运行都只转发过去1小时的动态抽奖
> > 总之最好避免短时间内转发大量动态，尽量分散转发
> 
> `"time_quantum": [-43200, 43200],改为"time_quantum": [0, 3600],`
> 这个是指只需要调整这个就能在不改动`run_BiliExp.yml`的情况下再次运行吗

不能，实际在什么时间执行是`run_BiliExp.yml`决定的，默认是每天中午12点执行所以对应的参数应该是`"time_quantum": [-43200, 43200],`
