### ISSUE TITLE
运行出错File "/home/bili/BiliExp/BiliExp.py", line 169, in <module> main(**kwargs)

### ISSUE THREAD

**Issue by Sonniferi** [happy888888/BiliExp#236]
运行环境 ubuntu 18.04.5 lts  python3
报错方式 宝塔的定时计划任务 启动会报错   用系统自带的cron启动也是报错 但是手动的python3 BiliExp.py不会报错
报错提示如下
Traceback (most recent call last):
  File "/home/bili/BiliExp/BiliExp.py", line 169, in &lt;module&gt;
    main(**kwargs)
  File "/home/bili/BiliExp/BiliExp.py", line 149, in main
    init_message(configData) #初始化消息推送
  File "/home/bili/BiliExp/BiliExp.py", line 60, in init_message
    initlog(configData["log_file"], configData["log_console"])
KeyError: 'log_file'

**Comment by happy888888** [comment]
`Ubuntu 18.04 LTS`自带的cron未发现此问题
`0 * * * * /usr/bin/python3 /home/bili/BiliExp/BiliExp.py`
如果不清楚cron默认工作目录，建议把配置文件放到`/etc/BiliExp/config.json`，当然放到`cron工作目录/config/config.json`也是可以的，手动执行的话工作目录就是shell环境的当前目录

**Comment by Sonniferi** [comment]
感谢 确定是无法读取到config.json 看了下releases的sh文件 手动指定了一下config.json 问题解决
