### ISSUE TITLE
Actions上不会推送消息到Server酱

### ISSUE THREAD

**Issue by kangyabawutuandui1** [happy888888/BiliExp#237]
push_message也填了Server酱的key，第一次任务完成后推送过一次，之后就不会推送了

**Comment by kangyabawutuandui1** [comment]
Actions上Server酱不会推送消息到
微信，说错了

**Comment by happy888888** [comment]
把配置文件235行log_console改为true把日志信息显示出来，现在什么信息都没有我也没办法判断
https://github.com/happy888888/BiliExp/blob/d168a40944b726d2ae16ca173639b9cd18e3fcdd/config/config.json#L234-L235
