### ISSUE TITLE
天选时刻抽奖并没有参与

### ISSUE THREAD

**Issue by nightlight02** [happy888888/BiliExp#238]
关注列表确实在变多，但是点进直播间之后，发现并没有参与天选时刻抽奖。

**Comment by nightlight02** [comment]
环境（action）

**Comment by happy888888** [comment]
每次抽奖只有十分钟 可能你点进去时已经结束了，你看看日志显示抽奖的时间与你进入直播间的时间有没有差太远

**Comment by Mark2T** [comment]
天选时刻 中奖是否能跟中奖的直播间主播发一条私信“UP我中天选了，请问怎么领奖 
”之类的。

**Comment by happy888888** [comment]
> 天选时刻 中奖是否能跟中奖的直播间主播发一条私信“UP我中天选了，请问怎么领奖
> ”之类的。

可以
