### ISSUE TITLE
为什么一直在不停地关注别人？

### ISSUE THREAD

**Issue by licksk** [happy888888/BiliExp#247]
第一次用这个不太明白，为啥运行了以后就开始不停地关注别人。

**Comment by dirrory** [comment]
请检查config里面是否开启了天选抽奖以及转发抽奖

**Comment by if1y** [comment]
建议先把配置项逐个弄明白了再使用，以免产生不必要的误会

**Comment by CaoMeiYouRen** [comment]
> 请检查config里面是否开启了天选抽奖以及转发抽奖

请问这个配置项是存在缓存吗？为什么修改配置后重新运行还是会执行某些操作

**Comment by happy888888** [comment]
> > 请检查config里面是否开启了天选抽奖以及转发抽奖
> 
> 请问这个配置项是存在缓存吗？为什么修改配置后重新运行还是会执行某些操作

自定义配置需要使用secrets ADVCONFIG

**Comment by CaoMeiYouRen** [comment]
> > > 请检查config里面是否开启了天选抽奖以及转发抽奖
> > 
> > 
> > 请问这个配置项是存在缓存吗？为什么修改配置后重新运行还是会执行某些操作
> 
> 自定义配置需要使用secrets ADVCONFIG

好的，谢谢，我以为直接改 config.json 也能生效
