### ISSUE TITLE
请提供VPS运行是crontab的配置文件

### ISSUE THREAD

**Issue by kaze-kaze** [happy888888/BiliExp#248]
就是输入crontab -e之添加的内容

**Comment by kaze-kaze** [comment]
环境 CentOS7

**Comment by kaze-kaze** [comment]
你好？能看下issue吗？

**Comment by happy888888** [comment]
你是直接使用的源码还是release包？
如果使用release包可使用如下cron
`0 12 * * * /home/BiliExp/BiliExp -c /etc/BiliExp/config.json`
`0 12 * * *`代表每天中午12点执行1次，可改为你需要执行的时间，`/home/BiliExp/BiliExp`是主程序路径，改为你下载release解压后的主程序BiliExp的存放路径，`/etc/BiliExp/config.json`为配置文件路径，改为你下载release解压后config.json文件的存放路径

**Comment by kaze-kaze** [comment]
已解决，非常感谢！
