### ISSUE TITLE
天选可以只搜索关注列表的直播间吗

### ISSUE THREAD

**Issue by a145600** [happy888888/BiliExp#250]
我只想在已关注的人的直播间参与天选，看配置好像不能这样设置

**Comment by if1y** [comment]
1.1.9版本可以指定直播间

**Comment by happy888888** [comment]
1.1.9版本只能手动指定直播间，搜索直播间的功能是1.2.0版本加入的。退回使用1.1.9版本就行

**Comment by if1y** [comment]
> 1.1.9版本只能手动指定直播间，搜索直播间的功能是1.2.0版本加入的。退回使用1.1.9版本就行

说起来，能不能在1.2.0的配置里使用1.1.9版的天选时刻那一段？（还是说头部版本号决定后续全部配置结构）

**Comment by happy888888** [comment]
> > 1.1.9版本只能手动指定直播间，搜索直播间的功能是1.2.0版本加入的。退回使用1.1.9版本就行
> 
> 说起来，能不能在1.2.0的配置里使用1.1.9版的天选时刻那一段？（还是说头部版本号决定后续全部配置结构）
> 
> 起因是今天发现一个搜索模式的“漏洞”：
> 因为已关注的主播，也经常发布要求关注的天选时刻，本来这种天选是可以无干扰直接参加。
> 但在搜索模式中，这类天选时刻也不会参与，除非在参与类型中选上“关注”，但我又不想关注（欢迎消息气泡残留略烦人），就挺矛盾。
> 如果能直接混用，或者直接同时支持两种参数设定，就太好了。

把1.1.9版本的task文件夹下的xlive_anchor_task.py替换掉1.2.0版本的task文件夹下的同名文件，然后就可以像你说的那样修改配置文件了

配置文件里每项任务配置都对应task文件夹下的名字相同的模块，想使用老版本模块直接替换掉就行，同时使用两个版本的模块只需要修改名称
