### ISSUE TITLE
漫画下载失败

### ISSUE THREAD

**Issue by niuqudechongdong** [happy888888/BiliExp#251]
在下载《天宫赐福》漫画的第25章《同席共眠》时出错，不能下载，报错如下（其他章节正常）：
在./天官赐福\25-同席共眠 下写入01.jpg时异常 FileNotFoundError(2, 'No such file or directory')

**Comment by happy888888** [comment]
应该是遇到特殊符号，windows创建目录时失败了，我去看看

**Comment by happy888888** [comment]
你试试使用命令行执行
`mangaDownloader -m 26769 -e 25 -p D:\download`这样指定下载到`D:\download`目录可以成功吗

**Comment by niuqudechongdong** [comment]
你这样实际下载的是第24章，应该要写26实际上下载的才是第25章

**Comment by happy888888** [comment]
我的意思是要你指定一个下载目录

**Comment by niuqudechongdong** [comment]
![image](https://user-images.githubusercontent.com/64181801/108470031-457e6580-72c4-11eb-8eb6-714cbb048ce9.png)

**Comment by happy888888** [comment]
25章名称末尾有个空格，windows上名称末尾不允许有空格.....................

**Comment by niuqudechongdong** [comment]
那应该是要怎么弄来下载这个章节？
有这个文件《25-同席共眠》，但就是下载不来图片

**Comment by happy888888** [comment]
使用命令行
`MD "D:\download\25-同席共眠 \ "`
强制创建一个末尾带空格的文件夹(上面的命令一个空格都不能丢)然后再使用下载器。不过这在windows中是属于非法文件夹，以后可能在资源管理器中使用鼠标右键删除时删除不掉。

**Comment by niuqudechongdong** [comment]
好的，大佬以后会在更新漫画下载程序时加入可以下载这个章节的代码吗？
如果可以的话，我就等到以后再来下载这个章节

**Comment by happy888888** [comment]
后续会更新中会把文件名默认首尾空格删除来解决这个问题

**Comment by niuqudechongdong** [comment]
好的，谢谢大佬

**Comment by happy888888** [comment]
你如果安装有python的话也可以直接修改代码
https://github.com/happy888888/BiliExp/blob/d168a40944b726d2ae16ca173639b9cd18e3fcdd/BiliClient/Manga.py#L91
https://github.com/happy888888/BiliExp/blob/d168a40944b726d2ae16ca173639b9cd18e3fcdd/BiliClient/Manga.py#L101
https://github.com/happy888888/BiliExp/blob/d168a40944b726d2ae16ca173639b9cd18e3fcdd/BiliClient/Manga.py#L122

这三行后面分别都加一个`.strip()`
```
name = re.sub('[\/:*?"<>|]','', mlist[x]["title"]).strip()
```

**Comment by niuqudechongdong** [comment]
为什么会有这个报错？

E:\bilibili漫画下载器\Downloader\BiliExp-master\BiliExp-master>mangaDownloader -m 26769 -e 26
Traceback (most recent call last):
  File "E:\bilibili漫画下载器\Downloader\BiliExp-master\BiliExp-master\mangaDownloader.py", line 11, in <module>
    configData = json.loads(re.sub(r'\/\*[\s\S]*?\/', '', fp.read()))
  File "E:\python3.8.7\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "E:\python3.8.7\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\python3.8.7\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 3 column 25 (char 27)

**Comment by happy888888** [comment]
貌似是配置文件第三行有错

**Comment by niuqudechongdong** [comment]
原来要把config.json放在mangaDownloader.py同一个文件夹里，并且config.json跟现在的是不一样的，要跟release包里的config.json格式一样才行

**Comment by niuqudechongdong** [comment]
顺便问一下，大佬，可以添加一个每月自动用大会员领取的5b币券兑换10张漫读券吗？

**Comment by niuqudechongdong** [comment]
我刚才看到一个有趣的功能，每天自动阅读漫画一个章节，这好像对22卡有用（虽然我用不上），链接地址为https://github.com/JunzhouLiu/BILIBILI-HELPER/issues/267


用到的代码：
String mangaView = "https://manga.bilibili.com/twirp/bookshelf.v1.Bookshelf/AddHistory?device=pc&platform=web";
String requestBodyForMangaView = "comic_id=24742&ep_id=218087";
HttpUtil.doPost(mangaView, requestBodyForMangaView);

**Comment by happy888888** [comment]
这个接口是用于添加阅读历史记录的，并不知道B站对阅读的判定是如何进行的，并不是只要添加了历史记录就一定能判定完成任务的，还可能要带上app版本号请求什么的（就像新人限免活动那样），你说的什么阅读排位赛我要实际参加一下才能实现这个功能

**Comment by niuqudechongdong** [comment]
阅读排位赛这个活动还是算了，我刚才看了下，好像用漫币来解锁才行。
不过每天阅读一个章节对22卡用户还是有用，这个功能好像在这个github项目上已经实现了https://github.com/JunzhouLiu/BILIBILI-HELPER

**Comment by happy888888** [comment]
光是接口的话本项目早就已经有了
https://github.com/happy888888/BiliExp/blob/d168a40944b726d2ae16ca173639b9cd18e3fcdd/BiliClient/asyncBiliApi.py#L1217-L1233

只是没有22卡进行测试，就没有在此基础上实现其他功能

**Comment by niuqudechongdong** [comment]
确实没有22卡就只能等以后在说了。
那就麻烦大佬下一次修改，添加一下b币券兑换漫读券的脚本，每月10张有点不够用了，哈哈哈

**Comment by schlusss** [comment]
@happy888888 能给个群号吗😭
