### ISSUE TITLE
下载器功能建议

### ISSUE THREAD

**Issue by O2C14** [happy888888/BiliExp#252]
可以做到下载新人限免（就是不购买不解锁，但是可以免费观看）的漫画章节吗

**Comment by niuqudechongdong** [comment]
好像不行，网页端看不了新人限免的漫画，只能在APP上看。除非这个程序下载的是app上的资源。

**Comment by O2C14** [comment]
> 好像不行，我记得电脑端看不了新人限免的漫画，只能在APP上看。你看一下电脑端能不能看新人限免(不太确定)？

我知道怎么从APP中提取解密，但我就是不知道怎么用py脚本解密，网上找的脚本在运行后输出的文件是损坏的。
所以我就是想知道怎么用py脚本解密

**Comment by niuqudechongdong** [comment]
我不太懂代码，但我觉得这个代码应该是类似于爬虫，爬取网页端的漫画图片，你说的用py脚本解密的应该是另外一个大佬的代码，转成webp格式的？以前用过。

**Comment by O2C14** [comment]
可以发那个脚本的网址来吗，非常感谢。
昨天写了一天的代码，从c++到c#再到python。绕了好多弯路也没有解决。最后是用notepad++录制了一个宏才解决，而且效率也没有py高

**Comment by niuqudechongdong** [comment]
新版客户端3.7.0之后，缓存文件需要root后才可以访问，并且图片未加密，不再需要使用该工具解密，只需要改文件后缀为webp即可

**Comment by niuqudechongdong** [comment]
应该是这个？https://github.com/zhongfly/view2webp

**Comment by O2C14** [comment]
这个我试过，没有用

**Comment by happy888888** [comment]
我的账号不是新人，也没看到有新人限免类的漫画，目前我知道的app向服务器请求图片数据是没有加密的，如果手机缓存是加密的也可能是app先下载后加的密，直接模拟app向服务器请求图片数据应该是可行的。本工具是使用的网页版接口，下载前判断了漫画是否被锁定，不清楚移出这个判断直接下载是否可能下载新人限免漫画

**Comment by niuqudechongdong** [comment]
你有没有试过老版本的哔哩哔哩漫画app？
用老本版的缓存来转换，我记得这个是可以用的，我电脑上还有以前的缓存文件，我试了一下，可以用

**Comment by niuqudechongdong** [comment]
我记得新人限免的漫画有：《鬼灭之刃》
还有新人限免比较好看的漫画吗？

**Comment by O2C14** [comment]
可能是我的问题
看过但没解锁（新人限免）的缓存路径：/data/data/com.bilibili.comic/files/.cache/
我觉得你会用到

**Comment by O2C14** [comment]
> 我记得新人限免的漫画有：《鬼灭之刃》
> 还有新人限免比较好看的漫画吗？

《总之就是非常可爱（总之就是非常酸bushi）》

**Comment by O2C14** [comment]
还有现在哔哩哔哩漫画没有那个index.bat文件了
也就是说不能自动排序了

**Comment by O2C14** [comment]
![QQ截图20210219133339](https://user-images.githubusercontent.com/70356077/108462162-1d3c3a00-72b7-11eb-9b61-7514e0e3413b.png)
为什么“开始转换”的按钮不能点击

**Comment by niuqudechongdong** [comment]
你把你的缓存文件发一些出来，我看下我之前下载的程序能不能转换

**Comment by O2C14** [comment]
噢不用了，我的模拟器出bug了
缓存是空的

**Comment by O2C14** [comment]
我再试试

**Comment by niuqudechongdong** [comment]
我记得我第一次也是用这个程序

**Comment by O2C14** [comment]
![image](https://user-images.githubusercontent.com/70356077/108462769-28439a00-72b8-11eb-830b-5ab05780c4b0.png)
图片依旧损坏

**Comment by O2C14** [comment]
+qq3251496755
我给你试试

**Comment by O2C14** [comment]
![image](https://user-images.githubusercontent.com/70356077/108462923-69d44500-72b8-11eb-858d-70905bb590ae.png)
这是我用notepad++的宏转出来的，不过烦的是没有排序。79话，1508张根本排不过来

**Comment by O2C14** [comment]
![image](https://user-images.githubusercontent.com/70356077/108463085-b3bd2b00-72b8-11eb-913a-776623160741.png)
质量还是很不错的可以做壁纸（馋她身子bushi）

**Comment by O2C14** [comment]
用app转换的跟没转一样，前9个字都没有删除↓
![image](https://user-images.githubusercontent.com/70356077/108463381-4231ac80-72b9-11eb-8f69-d6ddded4bf4b.png)

**Comment by happy888888** [comment]
你试过直接用本工具下载指定章节吗，比如下载`总之就是非常可爱`的第142话，就是运行
`mangaDownloader.exe -m 25900 -e 551856 -p D:\download`
其中25900是漫画id，551856是第142话的章节id
直接通过漫画id和章节id来下载

**Comment by O2C14** [comment]
> @O2C14
> 你试过直接用本工具下载指定章节吗，比如下载`总之就是非常可爱`的第142话，就是运行
> `mangaDownloader.exe -m 25900 -e 551856 -p D:\download`
> 其中25900是漫画id，551856是第142话的章节id
> 直接通过漫画id和章节id来下载，看看能不能下载新人限免

让我康康

**Comment by happy888888** [comment]
> > @O2C14
> > 你试过直接用本工具下载指定章节吗，比如下载`总之就是非常可爱`的第142话，就是运行
> > `mangaDownloader.exe -m 25900 -e 551856 -p D:\download`
> > 其中25900是漫画id，551856是第142话的章节id
> > 直接通过漫画id和章节id来下载，看看能不能下载新人限免
> 
> 让我康康

ep号直接填序号也行，比如漫画的第一章就填1，第二章就填2，注意番外也算一章

**Comment by O2C14** [comment]
> > > @O2C14
> > > 你试过直接用本工具下载指定章节吗，比如下载`总之就是非常可爱`的第142话，就是运行
> > > `mangaDownloader.exe -m 25900 -e 551856 -p D:\download`
> > > 其中25900是漫画id，551856是第142话的章节id
> > > 直接通过漫画id和章节id来下载，看看能不能下载新人限免
> > 
> > 
> > 让我康康
> 
> ep号直接填序号也行，比如漫画的第一章就填1，第二章就填2，注意番外也算一章

mangaDownloader.exe在哪

**Comment by niuqudechongdong** [comment]
直接点mangaDownloader就可以用，可以不需要命令窗口
在右边的release里下载exe程序

**Comment by happy888888** [comment]
我没太懂这个新人限免的意思，如果是限免卡的话应该也是要先对漫画使用后才能使用工具下载的，限免卡相当于计时的解锁，不解锁就可以看的我没遇到过这种情况

**Comment by O2C14** [comment]
> 我没太懂这个新人限免的意思，如果是限免卡的话应该也是要先对漫画使用后才能使用工具下载的，限免卡相当于计时的解锁，不解锁就可以看的我没遇到过这种情况

是指这种限免
![image](https://user-images.githubusercontent.com/70356077/108466698-04d01d80-72bf-11eb-8991-e0e99584fb63.png)

不过也非常感谢你的热心帮助

**Comment by happy888888** [comment]
这种应该算是没有锁定的，在本工具内输入这个漫画的mc号直接下载会提示未解锁是吗？

**Comment by O2C14** [comment]
> 色的锁吗？

有黄色的锁

**Comment by happy888888** [comment]
> > 色的锁吗？
> 
> 有黄色的锁

哪些漫画有新人限免呢？ 只有新注册的账号才有这个吗？是的话我去新注册个账号看看

**Comment by O2C14** [comment]
> > > 色的锁吗？
> > 
> > 
> > 有黄色的锁
> 
> 哪些漫画有新人限免呢？ 只有新注册的账号才有这个吗？是的话我去新注册个账号看看
新注册的账号才有

**Comment by niuqudechongdong** [comment]
用新版本的bilibili漫画APP上才能看到新人限免，用新注册的账号才有
《鬼灭之刃》、《总之就是非常可爱》

**Comment by happy888888** [comment]
把`BiliClient/BiliApi.py`文件以下部分
https://github.com/happy888888/BiliExp/blob/d168a40944b726d2ae16ca173639b9cd18e3fcdd/BiliClient/BiliApi.py#L931-L937
修改为
```
    def mangaImageIndex(self, ep_id: int, device='android', version='3.7.0'):
        "获取漫画图片列表"
        url = f'https://manga.bilibili.com/twirp/comic.v1.Comic/GetImageIndex'
        post_data = {
            "device": device,
            "version": version,
            "ep_id": ep_id
            }
        return self._session.post(url, post_data).json()
```
再把
https://github.com/happy888888/BiliExp/blob/d168a40944b726d2ae16ca173639b9cd18e3fcdd/BiliClient/BiliApi.py#L895-L901
修改为
```
def mangaDetail(self, comic_id: int, device='android', version='3.7.0'):
        "获取漫画信息"
        url = f'https://manga.bilibili.com/twirp/comic.v1.Comic/ComicDetail'
        post_data = {
            "device": device,
            "version": version,
            "comic_id": comic_id
            }
        return self._session.post(url, post_data).json()
```

就可以下载新人限免部分了，B站只是检测了一下平台和版本(最关键的地方就是把原来代码里的pc改为android和添加一个version='3.7.0')，B站并没有做过多的加密

**Comment by niuqudechongdong** [comment]
我觉得，用app端的接口下载漫画还可能会有一些好处：
一般b站引进更新很久的漫画，刚上架三天都可以限免观看，比如上星期上架的《大主宰》（400多章），这样就可以下载下来以后再看（那时候我没有测试网页端有没有三天限免，如果不可以，那app端下载就会有点用处）

**Comment by O2C14** [comment]
> 把`BiliClient/BiliApi.py`文件以下部分
> https://github.com/happy888888/BiliExp/blob/d168a40944b726d2ae16ca173639b9cd18e3fcdd/BiliClient/BiliApi.py#L931-L937
> 
> 
> 修改为
> ```
>     def mangaImageIndex(self, ep_id: int, device='android', version='3.7.0'):
>         "获取漫画图片列表"
>         url = f'https://manga.bilibili.com/twirp/comic.v1.Comic/GetImageIndex'
>         post_data = {
>             "device": device,
>             "version": version,
>             "ep_id": ep_id
>             }
>         return self._session.post(url, post_data).json()
> ```
> 
> 再把
> https://github.com/happy888888/BiliExp/blob/d168a40944b726d2ae16ca173639b9cd18e3fcdd/BiliClient/BiliApi.py#L895-L901
> 
> 
> 修改为
> ```
> def mangaDetail(self, comic_id: int, device='android', version='3.7.0'):
>         "获取漫画信息"
>         url = f'https://manga.bilibili.com/twirp/comic.v1.Comic/ComicDetail'
>         post_data = {
>             "device": device,
>             "version": version,
>             "comic_id": comic_id
>             }
>         return self._session.post(url, post_data).json()
> ```
> 
> 就可以下载新人限免部分了，B站只是检测了一下平台和版本(最关键的地方就是把原来代码里的pc改为android和添加一个version='3.7.0')，B站并没有做过多的加密

非常感谢啊啊
建议放到主页让别人也看看

**Comment by happy888888** [comment]
> 我觉得，用app端的接口下载漫画还可能会有一些好处：
> 一般b站引进更新很久的漫画，刚上架三天都可以限免观看，比如上星期上架的《大主宰》（400多章），这样就可以下载下来以后再看（那时候我没有测试网页端有没有三天限免，如果不可以，那app端下载就会有点用处）

网页版与app用的同一个接口只是参数不一样，能做参数替换的话(比如写个油猴脚本)就能在电脑上看限免。(推测此限制是不让用户方便另存为保存漫画)。 不过通用卷这种东西在网页版上是一点踪影都没有........

**Comment by O2C14** [comment]
> > 我觉得，用app端的接口下载漫画还可能会有一些好处：
> > 一般b站引进更新很久的漫画，刚上架三天都可以限免观看，比如上星期上架的《大主宰》（400多章），这样就可以下载下来以后再看（那时候我没有测试网页端有没有三天限免，如果不可以，那app端下载就会有点用处）
> 
> 网页版与app用的同一个接口只是参数不一样，能做参数替换的话(比如写个油猴脚本)就能在电脑上看限免。(推测此限制是不让用户方便另存为保存漫画)。 不过通用卷这种东西在网页版上是一点踪影都没有........

那可把油猴脚本写出来吗，非常感谢

**Comment by O2C14** [comment]
@happy888888 大佬大佬，能把以上你所修改的部分在下一个版本实现吗，非常感谢

**Comment by O2C14** [comment]
@happy888888 大佬大佬，你是怎么打包生成mangaDownloader.exe，我想把改动的文件生成mangaDownloader.exe

**Comment by niuqudechongdong** [comment]
大佬，想问一下，为什么下载不了《反派初始化》，mc号为25940的限时免费章节？

**Comment by happy888888** [comment]
准确来讲这不是`限时免费章节`而是`限时免费卷`，本项目下载漫画是按章节下载的所以会提前判断章节是否解锁，但某些漫画按卷买的(一个卷包含多个章节)，这类漫画要判断卷是否解锁才行，同理如果漫画既可以按卷买也可以按章节买，卷和章节只要有一个解锁就能解锁(对B站来说貌似卷和章节是两种商品，不知道如果买了卷里面的一个章节，再买这个卷会怎样，B站这波操作很让人迷惑)

取消代码里对章节是否解锁的判断就能下载了
https://github.com/happy888888/BiliExp/blob/d168a40944b726d2ae16ca173639b9cd18e3fcdd/BiliClient/Manga.py#L94
改为
```
                if not False:
```

**Comment by niuqudechongdong** [comment]
我找了一个漫画看了下，写着单话购买可以随时切换成整卷购买，并且只要补差价即可
![image](https://user-images.githubusercontent.com/64181801/108651187-3550cb00-74fc-11eb-93b8-a4c63ac56aee.png)

**Comment by niuqudechongdong** [comment]
已经可以了，不过有点小瑕疵是改动后，发现没有购买的章节不能像以前一样发出提醒，而是照常下载（没购买的章节，每章会下载2页）。

**Comment by happy888888** [comment]
> 已经可以了，不过有点小瑕疵是改动后，发现没有购买的章节不能像以前一样发出提醒，而是照常下载（没购买的章节，每章会下载2页）。

因为这样修改后会跳过对章节是否解锁的判断，如果购买了一整卷，那么解锁的是这个卷而不是卷里面包含的章节，卷虽然处于解锁状态但是章节仍然处于锁定状态，但是不影响实际阅读，因为卷和章节其中一个购买了就能阅读。

也就是说目前本项目通过章节是否锁定来判断章节是否可读在这种能按卷购买的漫画里是不正确的。上述修改就是把这个判断关了。

**Comment by niuqudechongdong** [comment]
不过，我天宫赐福是按一整卷一整卷来购买的，也能照常下载

**Comment by happy888888** [comment]
可能购买的解锁情况与试读的不同吧，购买可能是同时解锁了卷和章节的，而试读既有可能只试读卷也有可能只试读章节，不过解锁情况就只有4种，卷和章节都没解锁，卷解锁了章节没解锁，卷没解锁章节解锁了和两者都解锁了，只要判断到后面三种情况就触发下载应该能解决这个问题。

B站漫画的解锁机制应该一直都在升级的，我这里只能凭借一些漫画或者活动例子进行猜测，实际上B站服务器与app之间的漫画详情数据包中有很多以`discount`开头的字段推断是以活动相关的，比如你上面给的《反派初始化》漫画免费读90天的活动，从数据包中`"discount_end":"2021-06-01 00:00:00","discount_type":6,"ep_discount_type":0` 字段就能猜出`discount_end`代表的活动截至日期，`discount_type`和`ep_discount_type`应该分别代表漫画活动类型和章节活动类型，但对于具体的数字`6`就没办法判断具体是什么活动了(`0`应该可以猜出是没有活动)，只能通过大量漫画的数据对比才能猜出这些活动类型数字代表的含义。

总之随着B站的更新，数据包格式随时都可能变，有时候本项目跟不上官方的变化也是正常的，这本来就不是官方的工具。

**Comment by niuqudechongdong** [comment]
明白了，谢谢大佬。
我是昨天突然看到《反派初始化》有限免，就想尝试一下能不能下载（其实我并没有在追这个漫画）

**Comment by happy888888** [comment]
已实现，请更新到1.2.0版本
