### ISSUE TITLE
单独执行的风纪委员没有达到预期设定时间只运行一次就结束

### ISSUE THREAD

**Issue by wangmanv2** [happy888888/BiliExp#253]
单独执行的风纪委员没有达到预期设定时间只运行一次就结束（设置文件参考 https://github.com/happy888888/BiliExp/issues/178 中的第一个像素级复制只修改了后面的用户部分）
即使增加等待时间到 2700 间隔查询时间到 300 也是一次执行 https://github.com/wangmanv2/BiliExp/actions/runs/580352178 并且当日也还是有可审阅的案件的 https://github.com/wangmanv2/BiliExp/actions/runs/580358852 这个就抓到了，但是也没有等待。

但是完整的 BiliExp 是可以等待风纪委员执行的 https://github.com/wangmanv2/BiliExp/actions/runs/580318369

**Comment by happy888888** [comment]
run_once 参数为true是只执行一次后直接退出，依靠外部多次执行来覆盖所有案件

**Comment by wangmanv2** [comment]
噢噢，明白了，之前没看到这个参数。（瞎了X_X）
