### ISSUE TITLE
云函数config中将天选抽奖和互动抽奖关闭，还是会执行。

### ISSUE THREAD

**Issue by XavierLee-0** [happy888888/BiliExp#254]
云函数配置文件版本1.2.0
在config中已经将天选抽奖和互动抽奖的相关开关改成false。但是我这里还是会执行。
![image](https://user-images.githubusercontent.com/63280021/108594295-2959f180-73b4-11eb-8bc4-7c3bdf8f78a3.png)
![image](https://user-images.githubusercontent.com/63280021/108594305-4262a280-73b4-11eb-8794-86e62d7a6d78.png)
![image](https://user-images.githubusercontent.com/63280021/108594307-455d9300-73b4-11eb-80f3-d2f4a38a8512.png)
![image](https://user-images.githubusercontent.com/63280021/108594310-48588380-73b4-11eb-9d75-5cc71efde5de.png)

**Comment by happy888888** [comment]
那试试删掉配置，比如删掉天选就把配置文件第29行到59行（包括）都删除了。

**Comment by happy888888** [comment]
不对啊，你不是用的actions吗？

**Comment by XavierLee-0** [comment]
这个actions是部署到腾讯云云函数的。重新仔细看了一遍Readme,发现有地方修改了。原来现在secert中biliconfig仅供actions使用，以前的那个版本好像即使是部署到云函数，那三个secert都要添加。

**Comment by happy888888** [comment]
把actions关闭了，不然actions和云函数都在执行任务
