### ISSUE TITLE
请问这是部署云函数成功的意思吗，但我在控制台里没看到

### ISSUE THREAD

**Issue by Sumouruge2390** [happy888888/BiliExp#255]
![image](https://user-images.githubusercontent.com/50762988/108599457-3a166180-73cc-11eb-9413-022cd4baaab0.png)

**Comment by Sumouruge2390** [comment]
windows腾讯云函数

**Comment by happy888888** [comment]
没有，确认一下`TENCENT_SECRET_ID`是否填对

**Comment by Sumouruge2390** [comment]
> 没有，确认一下`TENCENT_SECRET_ID`是否填对

我从访问密钥这个界面直接复制的呀，应该没有错

**Comment by happy888888** [comment]
https://github.com/Sumouruge2390/BiliExp/runs/1942185036?check_suite_focus=true#step:3:121

**Comment by Sumouruge2390** [comment]
> https://github.com/Sumouruge2390/BiliExp/runs/1942185036?check_suite_focus=true#step:3:121
已解决，感谢

**Comment by mmkakac** [comment]
兄弟怎么解决的，我也是部署之后腾讯云函数里没有、

**Comment by Sumouruge2390** [comment]
我上次是确认了一下TENCENT_SECRET_ID，结果发现填错了



---原始邮件---
发件人: "mmkakac"<notifications@github.com&gt;
发送时间: 2021年3月3日(周三) 中午11:06
收件人: "happy888888/BiliExp"<BiliExp@noreply.github.com&gt;;
抄送: "Sumouruge2390"<2390379465@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [happy888888/BiliExp] 请问这是部署云函数成功的意思吗，但我在控制台里没看到 (#255)




 
兄弟怎么解决的，我也是部署之后腾讯云函数里没有、
