### ISSUE TITLE
部署云函数时遇到的问题，不清楚怎么回事^8^

### ISSUE THREAD

**Issue by reoyf** [happy888888/BiliExp#256]
25l正在初始化...
行动：“部署”-阶段：“开发”-应用：“ bilibili”-实例：“ BiliExp”
上载中...

 错误：请求失败，状态码为400
    在createError（/usr/local/lib/node_modules/serverless/node_modules/axios/lib/core/createError.js:16:15）
    在解决时（/usr/local/lib/node_modules/serverless/node_modules/axios/lib/core/settle.js:17:12）
    在IncomingMessage.handleStreamEnd（/usr/local/lib/node_modules/serverless/node_modules/axios/lib/adapters/http.js:260:11）
    在IncomingMessage.emit（events.js：327：22）
    在endReadableNT（内部/流/可读.js：1327：12）
    在processTicksAndRejections（内部/进程/task_queues.js:80:21）

304s› BiliExp›请求失败，状态码为400

**Comment by happy888888** [comment]
我也不太清楚，可能是腾讯云那边抽风了，隔段时间再试吧

**Comment by reoyf** [comment]
解决了，自己动手丰衣足食。究其原因-问题只能是github或者云函数之一，刚才把日志和作者正确运行的日志进行对比，发现是在上传云函数出错，我的云函数账号和新注册的账号有什么区别呢？发现云函数那里的微信绑定了两个账号，秘钥是在主账号获取的，但是tx云函数默认另一个也是这个秘钥（好像是逻辑bug），刚才把另一个账号解绑就好了
