### ISSUE TITLE
腾讯云修改天选时刻抽奖的配置文件

### ISSUE THREAD

**Issue by Sumouruge2390** [happy888888/BiliExp#257]
START RequestId:20f6ddd9-6edd-4ebf-be7d-c000b1bb1175

配置加载异常，原因为<string>:2 Unexpected """ at column 5，退出程序

日志报错，出现上述提示

**Comment by Sumouruge2390** [comment]
![5b60434db53927d0294ec6c706d728d](https://user-images.githubusercontent.com/50762988/108616145-c44edc00-7445-11eb-9304-980f70d6ba17.png)

**Comment by happy888888** [comment]
配置文件贴上来

**Comment by Sumouruge2390** [comment]
如下，cookie信息改过了
{
    "version": "1.2.0",
    "default": {
        "xlive_anchor_task": {
            "enable": true, 
            "anchor_type": [[0, 0], [1, 0]],
            "delay": 0,
            "gift_filter": ["照片","自拍","代金卷","船长","优惠券","上船","素颜照","加速器","自画像","抵扣卷","写真","王者","舰长"],
            "room_filter": [],
            "danmu_filter": [],
            "price_limit": 0,
            "unfollow": true,
            "follow_group": "",
            "clean_group_interval": 0,
            "search_interval": 500,
            "search_areas": [
                {"paid": 1,"aid": 0,"sort": "","ps": 50},
                {"paid": 2,"aid": 0,"sort": "","ps": 50},
                {"paid": 3,"aid": 0,"sort": "","ps": 50},
                {"paid": 6,"aid": 0,"sort": "","ps": 50}
            ],
            "timeout": 850,
            "run_once": true
    },
    "log_file": "BiliExp.log",
    "log_console": true,
    "users": [{
        "cookieDatas": {
            "SESSDATA": "你的cookie",
            "bili_jct": "你的cookie",
            "DedeUserID": "你的uid"
        },
        "tasks": {}
    }]
}

**Comment by Sumouruge2390** [comment]
> 配置文件贴上来

楼下

**Comment by Sumouruge2390** [comment]
> > 配置文件贴上来
> 
> 楼下

就是直接照搬的推荐写法

**Comment by happy888888** [comment]
23行和24行之间加一个反括号`}`就行
```
{
    "version": "1.2.0",
    "default": {
        "xlive_anchor_task": {
            "enable": true, 
            "anchor_type": [[0, 0], [1, 0]],
            "delay": 0,
            "gift_filter": ["照片","自拍","代金卷","船长","优惠券","上船","素颜照","加速器","自画像","抵扣卷","写真","王者","舰长"],
            "room_filter": [],
            "danmu_filter": [],
            "price_limit": 0,
            "unfollow": true,
            "follow_group": "天选时刻",
            "clean_group_interval": 0,
            "search_interval": 500,
            "search_areas": [
                {"paid": 1,"aid": 0,"sort": "","ps": 50},
                {"paid": 2,"aid": 0,"sort": "","ps": 50},
                {"paid": 3,"aid": 0,"sort": "","ps": 50},
                {"paid": 6,"aid": 0,"sort": "","ps": 50}
            ],
            "timeout": 3300,
            "run_once": false
        }
    },
    "log_file": "BiliExp.log",
    "log_console": true,
    "users": [{
        "cookieDatas": {
            "SESSDATA": "你的cookie",
            "bili_jct": "你的cookie",
            "DedeUserID": "你的uid"
        },
        "tasks": {}
    }]
}
```

**Comment by Sumouruge2390** [comment]
> 23行和24行之间加一个反括号`}`就行
> 
> ```
> {
>     "version": "1.2.0",
>     "default": {
>         "xlive_anchor_task": {
>             "enable": true, 
>             "anchor_type": [[0, 0], [1, 0]],
>             "delay": 0,
>             "gift_filter": ["照片","自拍","代金卷","船长","优惠券","上船","素颜照","加速器","自画像","抵扣卷","写真","王者","舰长"],
>             "room_filter": [],
>             "danmu_filter": [],
>             "price_limit": 0,
>             "unfollow": true,
>             "follow_group": "天选时刻",
>             "clean_group_interval": 0,
>             "search_interval": 500,
>             "search_areas": [
>                 {"paid": 1,"aid": 0,"sort": "","ps": 50},
>                 {"paid": 2,"aid": 0,"sort": "","ps": 50},
>                 {"paid": 3,"aid": 0,"sort": "","ps": 50},
>                 {"paid": 6,"aid": 0,"sort": "","ps": 50}
>             ],
>             "timeout": 3300,
>             "run_once": false
>         }
>     },
>     "log_file": "BiliExp.log",
>     "log_console": true,
>     "users": [{
>         "cookieDatas": {
>             "SESSDATA": "你的cookie",
>             "bili_jct": "你的cookie",
>             "DedeUserID": "你的uid"
>         },
>         "tasks": {}
>     }]
> }
> ```

已解决
