### ISSUE TITLE
天选关键词过滤无效，动态抽奖转发评论修改了但还是默认的两句话

### ISSUE THREAD

**Issue by windy1021** [happy888888/BiliExp#258]

**Comment by windy1021** [comment]
执行环境是Actions，我修改了天选的礼物屏蔽词但是日志上显示还是会抽含有关键词的礼物

**Comment by happy888888** [comment]
配置了secrets(ADVCONFIG)了吗，如果只配置了BILICONFIG使用的就是默认配置

**Comment by windy1021** [comment]
> 塔里夫秘密 （阿德夫康菲格） -

谢谢解决了！配置的时候看漏了那一行
