### ISSUE TITLE
配置加载异常，原因为[Errno 2] No such file or directory: '/BiliExp/config.json'，退出程序

### ISSUE THREAD

**Issue by Immortal68** [happy888888/BiliExp#259]
Connecting to api.github.com (192.30.255.116:443)
Connecting to codeload.github.com (13.229.189.0:443)
saving to '/tmp/BiliExp.zip'
BiliExp.zip          10317 --:--:-- ETA
BiliExp.zip          98.2k --:--:-- ETA
BiliExp.zip          100% |********************************|  129k  0:00:00 ETA
'/tmp/BiliExp.zip' saved
Archive:  /tmp/BiliExp.zip
   creating: happy888888-BiliExp-cc009b0/
   creating: happy888888-BiliExp-cc009b0/.github/
  inflating: happy888888-BiliExp-cc009b0/.github/pull.yml
   creating: happy888888-BiliExp-cc009b0/.github/workflows/
  inflating: happy888888-BiliExp-cc009b0/.github/workflows/deploy_for_aliyun.yml
  inflating: happy888888-BiliExp-cc009b0/.github/workflows/deploy_for_tencentyun.yml
   creating: happy888888-BiliExp-cc009b0/BiliClient/
  inflating: happy888888-BiliExp-cc009b0/BiliClient/Article.py
  inflating: happy888888-BiliExp-cc009b0/BiliClient/Audio.py
  inflating: happy888888-BiliExp-cc009b0/BiliClient/BiliApi.py
  inflating: happy888888-BiliExp-cc009b0/BiliClient/Danmu2Ass.py
  inflating: happy888888-BiliExp-cc009b0/BiliClient/Downloader.py
  inflating: happy888888-BiliExp-cc009b0/BiliClient/Manga.py
  inflating: happy888888-BiliExp-cc009b0/BiliClient/Video.py
  inflating: happy888888-BiliExp-cc009b0/BiliClient/__init__.py
  inflating: happy888888-BiliExp-cc009b0/BiliClient/asyncBiliApi.py
  inflating: happy888888-BiliExp-cc009b0/BiliExp.py
   creating: happy888888-BiliExp-cc009b0/Docker/
  inflating: happy888888-BiliExp-cc009b0/Docker/Dockerfile
  inflating: happy888888-BiliExp-cc009b0/Docker/entrypoint.sh
  inflating: happy888888-BiliExp-cc009b0/LICENSE
  inflating: happy888888-BiliExp-cc009b0/README.md
   creating: happy888888-BiliExp-cc009b0/browser_assist/
  inflating: happy888888-BiliExp-cc009b0/browser_assist/README.md
   creating: happy888888-BiliExp-cc009b0/config/
  inflating: happy888888-BiliExp-cc009b0/config/README.md
  inflating: happy888888-BiliExp-cc009b0/config/activities.json
  inflating: happy888888-BiliExp-cc009b0/config/config.json
  inflating: happy888888-BiliExp-cc009b0/mangaDownloader.py
   creating: happy888888-BiliExp-cc009b0/player_proxy/
  inflating: happy888888-BiliExp-cc009b0/player_proxy/README.md
  inflating: happy888888-BiliExp-cc009b0/player_proxy/player_proxy.js
  inflating: happy888888-BiliExp-cc009b0/requirements.txt
   creating: happy888888-BiliExp-cc009b0/serverless/
  inflating: happy888888-BiliExp-cc009b0/serverless/aliyun_serverless.yml
  inflating: happy888888-BiliExp-cc009b0/serverless/serverless.yml
   creating: happy888888-BiliExp-cc009b0/tasks/
  inflating: happy888888-BiliExp-cc009b0/tasks/__init__.py
  inflating: happy888888-BiliExp-cc009b0/tasks/activity_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/clean_dynamic_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/coin_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/exchangeCoupons_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/group_sign_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/import_once.py
  inflating: happy888888-BiliExp-cc009b0/tasks/judgement_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/lottery_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/manga_auto_buy_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/manga_comrade_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/manga_sign_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/manga_vip_reward_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/msg_notify_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/push_message_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/share_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/silver2coin_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/vip_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/watch_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/xliveSign_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/xlive_anchor_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/xlive_bag_send_task.py
  inflating: happy888888-BiliExp-cc009b0/tasks/xlive_heartbeat_task.py
  inflating: happy888888-BiliExp-cc009b0/topicRepost.py
  inflating: happy888888-BiliExp-cc009b0/videoDownloader.py
  inflating: happy888888-BiliExp-cc009b0/videoUploader.py
   creating: happy888888-BiliExp-cc009b0/?????????up???/
  inflating: happy888888-BiliExp-cc009b0/?????????up???/README.md
  inflating: happy888888-BiliExp-cc009b0/?????????up???/youtube???????????????.py
  inflating: happy888888-BiliExp-cc009b0/?????????up???/???????????????????????????????????????.py
  inflating: happy888888-BiliExp-cc009b0/?????????up???/???????????????????????????????????????.py
配置加载异常，原因为[Errno 2] No such file or directory: '/BiliExp/config.json'，退出程序
请问应该怎么解决？谢谢！

**Comment by happy888888** [comment]
你需要填写配置文件https://github.com/happy888888/BiliExp/blob/cc009b0275eafa8ce16dc4abaa36fffd42aadf4c/config/config.json

**Comment by Immortal68** [comment]
> 你需要填充配置文件https://github.com/happy888888/BiliExp/blob/cc009b0275eafa8ce16dc4abaa36fffd42aadf4c/config/config.json

我已经填写完成了，但依旧是这个情况

**Comment by happy888888** [comment]
把这个文件挂载到docker的`/BiliExp`目录了吗，程序没找到这个文件

**Comment by b911ss** [comment]
> 把这个文件挂载到docker的`/BiliExp`目录了吗，程序没找到这个文件

大哥，docker不能运行1.2.0版本是吗

**Comment by Immortal68** [comment]
> 把这个文件挂载到docker的`/BiliExp`目录了吗，程序没找到这个文件

Connecting to api.github.com (192.30.255.117:443)
Connecting to codeload.github.com (13.229.189.0:443)
saving to '/tmp/BiliExp.zip'
BiliExp.zip            2% |                                |  3429  0:00:37 ETA
BiliExp.zip            3% |*                               |  4799  0:00:53 ETA
BiliExp.zip           12% |****                            | 17115  0:00:20 ETA
BiliExp.zip           20% |******                          | 26705  0:00:15 ETA
BiliExp.zip           26% |********                        | 34869  0:00:13 ETA
BiliExp.zip           29% |*********                       | 38979  0:00:14 ETA
BiliExp.zip           35% |***********                     | 47199  0:00:12 ETA
BiliExp.zip           36% |***********                     | 48513  0:00:13 ETA
BiliExp.zip           39% |************                    | 52623  0:00:13 ETA
BiliExp.zip           55% |*****************               | 73173  0:00:08 ETA
BiliExp.zip           60% |*******************             | 80023  0:00:07 ETA
BiliExp.zip           62% |********************            | 82763  0:00:07 ETA
BiliExp.zip           66% |*********************           | 88243  0:00:06 ETA
BiliExp.zip           66% |*********************           | 88243  0:00:06 ETA
BiliExp.zip           66% |*********************           | 88243  0:00:07 ETA
wget: connection closed prematurely
Archive:  /tmp/BiliExp.zip
unzip: short read
mv: can't rename '/tmp/*BiliExp*': No such file or directory
python3: can't open file '/tmp/BiliExp/BiliExp.py': [Errno 2] No such file or directory
好像出了新的问题，我对这方面也不是特别懂，麻烦开发者指导一下，感谢

**Comment by happy888888** [comment]
> > 把这个文件挂载到docker的`/BiliExp`目录了吗，程序没找到这个文件
> 
> Connecting to api.github.com (192.30.255.117:443)
> Connecting to codeload.github.com (13.229.189.0:443)
> saving to '/tmp/BiliExp.zip'
> BiliExp.zip 2% | | 3429 0:00:37 ETA
> BiliExp.zip 3% |* | 4799 0:00:53 ETA
> BiliExp.zip 12% |**** | 17115 0:00:20 ETA
> BiliExp.zip 20% |****** | 26705 0:00:15 ETA
> BiliExp.zip 26% |******** | 34869 0:00:13 ETA
> BiliExp.zip 29% |********* | 38979 0:00:14 ETA
> BiliExp.zip 35% |*********** | 47199 0:00:12 ETA
> BiliExp.zip 36% |*********** | 48513 0:00:13 ETA
> BiliExp.zip 39% |************ | 52623 0:00:13 ETA
> BiliExp.zip 55% |***************** | 73173 0:00:08 ETA
> BiliExp.zip 60% |******************* | 80023 0:00:07 ETA
> BiliExp.zip 62% |******************** | 82763 0:00:07 ETA
> BiliExp.zip 66% |********************* | 88243 0:00:06 ETA
> BiliExp.zip 66% |********************* | 88243 0:00:06 ETA
> BiliExp.zip 66% |********************* | 88243 0:00:07 ETA
> wget: connection closed prematurely
> Archive: /tmp/BiliExp.zip
> unzip: short read
> mv: can't rename '/tmp/_BiliExp_': No such file or directory
> python3: can't open file '/tmp/BiliExp/BiliExp.py': [Errno 2] No such file or directory
> 好像出了新的问题，我对这方面也不是特别懂，麻烦开发者指导一下，感谢

下载代码失败了，重新运行一下

**Comment by Immortal68** [comment]
> > > 把这个文件挂载到docker的`/BiliExp`目录了吗，程序没找到这个文件
> > 
> > 
> > Connecting to api.github.com (192.30.255.117:443)
> > Connecting to codeload.github.com (13.229.189.0:443)
> > saving to '/tmp/BiliExp.zip'
> > BiliExp.zip 2% | | 3429 0:00:37 ETA
> > BiliExp.zip 3% |* | 4799 0:00:53 ETA
> > BiliExp.zip 12% |**** | 17115 0:00:20 ETA
> > BiliExp.zip 20% |****** | 26705 0:00:15 ETA
> > BiliExp.zip 26% |******** | 34869 0:00:13 ETA
> > BiliExp.zip 29% |********* | 38979 0:00:14 ETA
> > BiliExp.zip 35% |*********** | 47199 0:00:12 ETA
> > BiliExp.zip 36% |*********** | 48513 0:00:13 ETA
> > BiliExp.zip 39% |************ | 52623 0:00:13 ETA
> > BiliExp.zip 55% |***************** | 73173 0:00:08 ETA
> > BiliExp.zip 60% |******************* | 80023 0:00:07 ETA
> > BiliExp.zip 62% |******************** | 82763 0:00:07 ETA
> > BiliExp.zip 66% |********************* | 88243 0:00:06 ETA
> > BiliExp.zip 66% |********************* | 88243 0:00:06 ETA
> > BiliExp.zip 66% |********************* | 88243 0:00:07 ETA
> > wget: connection closed prematurely
> > Archive: /tmp/BiliExp.zip
> > unzip: short read
> > mv: can't rename '/tmp/_BiliExp_': No such file or directory
> > python3: can't open file '/tmp/BiliExp/BiliExp.py': [Errno 2] No such file or directory
> > 好像出了新的问题，我对这方面也不是特别懂，麻烦开发者指导一下，感谢
> 
> 下载代码失败了，重新运行一下

终于部署成功了，感谢您的指导！谢谢！

**Comment by Immortal68** [comment]
@happy888888 我看docker运行一次之后这个项目停止了，是第二天十二点会自动启动吗？

**Comment by happy888888** [comment]
不会，你可以使用cron定时启动docker，也可以让docker不退出
`docker run -d -v /home/user/Biliexp:/BiliExp happy888888/biliexp:runner-latest -d -c "0 12 * * *"`
这样docker运行后就不会停止，每天12点执行一次

**Comment by Immortal68** [comment]
> 不会，你可以使用cron定时启动docker，也可以让docker不退出
> `docker run -d -v /home/user/Biliexp:/BiliExp happy888888/biliexp:runner-latest -d -c "0 12 * * *"`
> 这样docker运行后就不会停止，每天12点执行一次

好的，谢谢！
