### ISSUE TITLE
关于私信消息的建议

### ISSUE THREAD

**Issue by niuqudechongdong** [happy888888/BiliExp#261]
好像每次运行都会关注一些UP主，并且一关注就会有一条私信消息，可不可以添加每天自动删除这些一关注就推送的消息（今天关注的UP主发送的信息）。因为每天一上b站就能看到好几条私信，这些私信都是没用的信息，而且我记得在程序运行结束时，还会取消关注这些UP主，所以希望在取消关注UP主时，还能删除他们的私信

**Comment by happy888888** [comment]
可以把参与天选时刻抽奖的任务关了，有的主播要求关注后才能抽奖。

**Comment by if1y** [comment]
如果正好删除了关键中奖信息（有些非官方系统的抽奖，是UP主直接私信的）、或者其它需要保留的信息，又会带来额外的问题。问题不太可控，所以还是不删的好。
觉得烦可以把陌生人消息收纳起来，或者直接停用相关功能。

**Comment by niuqudechongdong** [comment]
没开免打扰，我是怕会把一些像你说的重要信息屏蔽掉，所以我现在是停用了天选时刻的功能（哈哈哈，因为我觉得中奖没啥希望）

不过你说的“问题不太可控”，我有点不明白？因为我觉得我想删除在完成“天选时刻”任务时一关注UP主，就立即发送的信息，好像本程序会记录本次运行时关注的UP主，并在本次程序运行结束前会取消关注这些UP主，所以在完成天选任务后删除本次运行时关注的UP主发送的"第一条"私信，我觉得理论上应该是可行的。而你说的“中奖信息”（是UP主直接私信），应该不太可能在本次程序运行的这短短10分钟私信你中奖消息吧?(我不太确定)，所以我觉得这样不太可能删除一些重要的消息

**Comment by if1y** [comment]
之前说的中奖只是临场举例。中奖不只有天选时刻，还有其它比如动态抽奖。如果是小up，没有动态抽奖权限，一般会用截图、随机数之类的方式，有结果会发私信。如果事情确实就是那么巧合，结果删掉了……

然后我记得本程序对于【天选关注后再取关】的处理有一点点小问题（不知道现在修复没）。
如果那个up是本身就关注过的，只要其对应的天选时刻的条件是关注，那么还是会被取关。如果取关他们的时候再删除私信……
这就是我说的不可控之一 _（比如之前和up有私信聊天需要保留，比如前不久刚好私信了中奖通知还没看，比如……那么可能会误删）_

另外这个指定为“第一条”私信能不能实现，还要看api。即使能实现，盲目指定“第一”这个顺序好像还是不太对，或者换成最新一条，也有点不太对。因为消息记录是相对的……我可能描述得不太清楚

--------

### 不管怎么样：

我觉得，依赖于目前的关键词过滤提醒，加一个删除的行为应该是最优的实现，这样的准确度会相对好很多。
**不过考虑到使用本程序的小白不少，连开启了自动关注都不知道，还来质问脚本是否存在后门。个人觉得还是不涉及这种行为最好。** _（这也是我指的不可控主要所在）_
另外，**既然已经取关了，此时已经属于陌生人关系，可以自动收纳起来的。** 收纳了就不要强迫症啦~

**Comment by niuqudechongdong** [comment]
好的，我大致明白了。顺带问一下，自动收纳功能是指B站消息中心》收起未关注人消息  这个功能吗？运行程序结束后，虽然自动取关了，但每次上B站时，还是能看到“谢谢关注”类的消息提醒

想探讨一下：
我记得动态抽奖的前提是要关注有发抽奖动态的UP主，而我想删除的是每次运行抽奖程序时由程序自动关注的UP主的第一条私信，而不是自己主动关注的UP主的私信，所以不太可能发生你说的误删除和UP主的私信（毕竟是第一次关注，当然，除非发生你说的【天选关注后再取关】的处理这个问题就会误删）。

你说的“第一条”私信能不能实现确实是一个问题，能不能用时间来定义“第一条”呢，比如，运行这个程序时上下2分钟内由程序自动关注的UP主发的私信？

**Comment by happy888888** [comment]
> 之前说的中奖只是临场举例。中奖不只有天选时刻，还有其它比如动态抽奖。如果是小up，没有动态抽奖权限，一般会用截图、随机数之类的方式，有结果会发私信。如果事情确实就是那么巧合，结果删掉了……
> 
> 然后我记得本程序对于【天选关注后再取关】的处理有一点点小问题（不知道现在修复没）。
> 如果那个up是本身就关注过的，只要其对应的天选时刻的条件是关注，那么还是会被取关。如果取关他们的时候再删除私信……
> 这就是我说的不可控之一 _（比如之前和up有私信聊天需要保留，比如前不久刚好私信了中奖通知还没看，比如……那么可能会误删）_
> 
> 另外这个指定为“第一条”私信能不能实现，还要看api。即使能实现，盲目指定“第一”这个顺序好像还是不太对，或者换成最新一条，也有点不太对。因为消息记录是相对的……我可能描述得不太清楚
> 
> ### 不管怎么样：
> 我觉得，依赖于目前的关键词过滤提醒，加一个删除的行为应该是最优的实现，这样的准确度会相对好很多。
> **不过考虑到使用本程序的小白不少，连开启了自动关注都不知道，还来质问脚本是否存在后门。个人觉得还是不涉及这种行为最好。** _（这也是我指的不可控主要所在）_
> 另外，**既然已经取关了，此时已经属于陌生人关系，可以自动收纳起来的。** 收纳了就不要强迫症啦~

天选取关非本项目关注的up主的问题早就解决了，关注每个up主前都会提前判断是否已经关注的(不排除刚好因为网络原因判断失败)

**Comment by happy888888** [comment]
> 好的，我大致明白了。顺带问一下，自动收纳功能是指B站消息中心》收起未关注人消息 这个功能吗？运行程序结束后，虽然自动取关了，但每次上B站时，还是能看到“谢谢关注”类的消息提醒
> 
> 想探讨一下：
> 我记得动态抽奖的前提是要关注有发抽奖动态的UP主，而我想删除的是每次运行抽奖程序时**由程序自动关注**的UP主的第一条私信，而不是自己主动关注的UP主的私信，所以不太可能发生你说的误删除和UP主的私信（毕竟是第一次关注，当然，除非发生你说的【天选关注后再取关】的处理这个问题就会误删）。
> 
> 你说的“第一条”私信能不能实现确实是一个问题。
> 设想：能不能用**时间**来限制“第一条”呢，比如，运行这个程序时由程序自动关注UP主后2分钟内发的“第一条”私信？

目前已经采取过的处理方法是把所有未读消息设为已读，这样就不会有个未读消息数字提醒了，但是消息还在

**Comment by if1y** [comment]
是那个收纳。收纳之后消息本身还是保留的，但是只会出现在收纳区里面。如果在外面，说明还是关注着的。

上面说的那些其实只是想把我之前的话解释清楚。
而我认为**最核心的顾虑来自删除行为本身，以及造成不明真相之人的误解**。

**最后的最后，以上均只代表我个人的看法。
具体如何请以作者态度为准。**

**Comment by if1y** [comment]
> 目前已经采取过的处理方法是把所有未读消息设为已读，这样就不会有个未读消息数字提醒了，但是消息还在

我是知道一开始是有这个“已读”操作的，也确实被已读了。
但是大概从改了天选时刻轮询逻辑的时候开始，就无效了，我觉得问题不大所以一直没提出来……

**Comment by happy888888** [comment]
> > 目前已经采取过的处理方法是把所有未读消息设为已读，这样就不会有个未读消息数字提醒了，但是消息还在
> 
> 我是知道一开始是有这个“已读”操作的，也确实被已读了。
> 但是大概从改了天选时刻轮询逻辑的时候开始，就无效了，我觉得问题不大所以一直没提出来……

需要开启msg_notify_task任务才行，这个任务本来是给多账号用户查看私信消息或者`@`消息用的(因为无论电脑还是app上切换账户都很麻烦)，启用这个功能就会把谁`@`过你或者私信消息的最后一条显示在日志里

**Comment by niuqudechongdong** [comment]
我特意去云函数里看了下，发现我已经开启了msg_notify_task任务，但还是有私信

**Comment by happy888888** [comment]
> 我特意去云函数里看了下，发现我已经开启了msg_notify_task任务，但还是有私信

云函数日志里有显示别人给你发的私信消息消息吗？ 你保持私信的未读状态再运行一次呢？

**Comment by if1y** [comment]
> > > 目前已经采取过的处理方法是把所有未读消息设为已读，这样就不会有个未读消息数字提醒了，但是消息还在
> > 
> > 
> > 我是知道一开始是有这个“已读”操作的，也确实被已读了。
> > 但是大概从改了天选时刻轮询逻辑的时候开始，就无效了，我觉得问题不大所以一直没提出来……
> 
> 需要开启msg_notify_task任务才行，这个任务本来是给多账号用户查看私信消息或者`@`消息用的(因为无论电脑还是app上切换账户都很麻烦)，启用这个功能就会把谁`@`过你或者私信消息的最后一条显示在日志里

大佬，我没有这么小白，当然是开了的啦 😅
日志显示有记录 `成功设置XXXXX消息为已读`，但进APP还是有对应私信的数字气泡。

**Comment by niuqudechongdong** [comment]
日志里显示的：**收到(514****4)的私信消息1条，被关键字“关注”过滤

**Comment by happy888888** [comment]
> > > > 目前已经采取过的处理方法是把所有未读消息设为已读，这样就不会有个未读消息数字提醒了，但是消息还在
> > > 
> > > 
> > > 我是知道一开始是有这个“已读”操作的，也确实被已读了。
> > > 但是大概从改了天选时刻轮询逻辑的时候开始，就无效了，我觉得问题不大所以一直没提出来……
> > 
> > 
> > 需要开启msg_notify_task任务才行，这个任务本来是给多账号用户查看私信消息或者`@`消息用的(因为无论电脑还是app上切换账户都很麻烦)，启用这个功能就会把谁`@`过你或者私信消息的最后一条显示在日志里
> 
> 大佬，我没有这么小白，当然是开了的啦 😅
> 日志显示有记录 `成功设置XXXXX消息为已读`，但进APP还是有对应私信的数字气泡。

我刚才测试的
小号向大号发送消息，进入app查看有气泡，运行msg_notify_task，app退出重进，气泡消失消息还在

**Comment by happy888888** [comment]
一般只有天选会自动关注up，动态抽奖除了跟踪转发模式都是从已经关注的up主中抽，不会主动关注其他up主

**Comment by if1y** [comment]
> 我刚才测试的
> 小号向大号发送消息，进入app查看有气泡，运行msg_notify_task，app退出重进，气泡消失消息还在

这边确实是气泡还在的……不知道怎么回事
不信的话我可以从现在起不去手动消除气泡，再拿日志一比对……（正好私信也没有标记未读的功能）

**Comment by happy888888** [comment]
> > 我刚才测试的
> > 小号向大号发送消息，进入app查看有气泡，运行msg_notify_task，app退出重进，气泡消失消息还在
> 
> 这边确实是气泡还在的……不知道怎么回事
> 不信的话我可以从现在起不去手动消除气泡，再拿日志一比对……（正好私信也没有标记未读的功能）

如果标记已读失败的话，运行两次msg_notify_task日志里就会有两次一样的消息了

**Comment by if1y** [comment]
> 如果标记已读失败的话，运行两次msg_notify_task日志里就会有两次一样的消息了

确实如你所说，没有重复提示，说明已经“已读”了，但客户端的气泡又确实还在……不懂
莫非是客户端在同步已读状态时有bug？

**Comment by happy888888** [comment]
> > 如果标记已读失败的话，运行两次msg_notify_task日志里就会有两次一样的消息了
> 
> 确实如你所说，没有重复提示，说明已经“已读”了，但客户端的气泡又确实还在……不懂
> 莫非是客户端在同步已读状态时有bug？

你退出app重进后气泡还在吗？杀杀后台呢

**Comment by if1y** [comment]
> 你退出app重进后气泡还在吗？杀杀后台呢
> 网页端手动"已读"再回到app端看气泡或者反过来试试呢

之前一口气手动消除了一个月的气泡，中间肯定是打开过很多次APP（或重启系统）的，也就意味着有彻底杀过后台。不过气泡一直都在，直到手动一条条打开。

网页和APP互相已读倒是没有专门测试过，有机会可以看看。

**Comment by happy888888** [comment]
直接上结论
目前我这里气泡是能删除的，经过测试app聊天列表里的对话框是存在方法删除的，但是对话框里的所有对话都是没办法删除的(就算删除了列表里的对话框对话内容也保存在手机中的)

app向服务器同步消息的过程没办法控制，目前最好的办法只能关闭天选。

**Comment by if1y** [comment]
难怪。
那就是APP下载了消息后，单独记录其“已读”属性，所以还会显示气泡。
我也验证了网页版，网页没有气泡时，APP依然存在。确实是二者不同步。

---

不过，使用APP的已读API或许能解决问题？

**Comment by happy888888** [comment]
> 难怪。
> 那就是APP下载了消息后，单独记录其“已读”属性，所以还会显示气泡。
> 我也验证了网页版，网页没有气泡时，APP依然存在。确实是二者不同步。
> 
> 不过，使用APP的已读API或许能解决问题？

不能，无论什么api都是与B站服务器交互，干涉不了app与服务器的交互，而且我的app没有此问题，代表不同版本的app同步逻辑可能不一样，本项目无论如何都无法干涉
