### ISSUE TITLE
直播抽奖推送有消息但B站系统却无

### ISSUE THREAD

**Issue by jiang3231634** [happy888888/BiliExp#262]
请问下大佬：后台推送的日记里面有直播间的中奖记录，但是在B站那边却没有，这个是系统原因还是怎么呢？

**Comment by happy888888** [comment]
我只看到了抽奖记录并没看到中奖记录....

**Comment by jiang3231634** [comment]
[INFO]: 锦年微光_江浡: 参与直播间989573的天选时刻907591(2.33元红包)成功
[INFO]: 锦年微光_江浡: 参与直播间21453736的天选时刻907572(现金2元红包)成功
[INFO]: 锦年微光_江浡: 参与(必剪)活动第(2/2)次，结果为(未中奖0)
[INFO]: 锦年微光_江浡: 获取(考拉)活动抽奖次数错误，消息为(活动已结束)
[INFO]: 锦年微光_江浡: 获取(使命)活动抽奖次数错误，消息为(活动已结束)
[INFO]: 锦年微光_江浡: 获取(健身)活动抽奖次数错误，消息为(活动已结束)
[INFO]: 锦年微光_江浡: 获取(跳舞)活动抽奖次数错误，消息为(活动已结束)
[INFO]: 锦年微光_江浡: 获取(灵感)活动抽奖次数错误，消息为(活动已结束)
[INFO]: 锦年微光_江浡: 获取(声优)活动抽奖次数错误，消息为(活动已结束)
[INFO]: 锦年微光_江浡: 获取(新番)活动抽奖次数错误，消息为(活动不存在)
[INFO]: 锦年微光_江浡: 获取(国创)活动抽奖次数错误，消息为(活动已结束)
[INFO]: 锦年微光_江浡: 获取(娱乐)活动抽奖次数错误，消息为(活动已结束)
[INFO]: 锦年微光_江浡: 参与直播间21710524的天选时刻907584(10元舰长代金券【开舰长有效】)成功
[INFO]: 锦年微光_江浡: 参与直播间22731475的天选时刻907594(2元红包)成功
[INFO]: 锦年微光_江浡: 取关主播499243737
[INFO]: 锦年微光_江浡: 取关主播360161798
[INFO]: 锦年微光_江浡: 参与直播间38227的天选时刻907586(5.2元红包)成功
[INFO]: 锦年微光_江浡: 参与直播间22247501的天选时刻907593(2元红包)成功
[INFO]: 锦年微光_江浡: 参与直播间22080761的天选时刻907604(5元红包)成功
[INFO]: 锦年微光_江浡: 参与直播间21710524的天选时刻907602(10元舰长代金券【开舰长有效】)成功
[INFO]: 锦年微光_江浡: 取关主播36514186
[INFO]: 锦年微光_江浡: 取关主播1819745929
[INFO]: 锦年微光_江浡: 取关主播258581
[INFO]: 锦年微光_江浡: 取关主播442203666
[INFO]: 锦年微光_江浡: 取关主播380565104
[INFO]: 锦年微光_江浡: 参与直播间22023401的天选时刻907613(照片)成功
[INFO]: 锦年微光_江浡: 参与直播间22669778的天选时刻907614(2.33红包)成功
[INFO]: 锦年微光_江浡: 参与直播间22695604的天选时刻907626(1.88元红包)成功
[INFO]: 锦年微光_江浡: 参与直播间22731475的天选时刻907615(2元红包)成功

有的呢，难道是历史记录？

**Comment by jiang3231634** [comment]
> 我只看到了抽奖记录并没看到中奖记录....

[INFO]: 锦年微光_江浡: 参与直播间989573的天选时刻907591(2.33元红包)成功
[INFO]: 锦年微光_江浡: 参与直播间21453736的天选时刻907572(现金2元红包)成功
[INFO]: 锦年微光_江浡: 参与(必剪)活动第(2/2)次，结果为(未中奖0)
[INFO]: 锦年微光_江浡: 获取(考拉)活动抽奖次数错误，消息为(活动已结束)
[INFO]: 锦年微光_江浡: 获取(使命)活动抽奖次数错误，消息为(活动已结束)
[INFO]: 锦年微光_江浡: 获取(健身)活动抽奖次数错误，消息为(活动已结束)
[INFO]: 锦年微光_江浡: 获取(跳舞)活动抽奖次数错误，消息为(活动已结束)
[INFO]: 锦年微光_江浡: 获取(灵感)活动抽奖次数错误，消息为(活动已结束)
[INFO]: 锦年微光_江浡: 获取(声优)活动抽奖次数错误，消息为(活动已结束)
[INFO]: 锦年微光_江浡: 获取(新番)活动抽奖次数错误，消息为(活动不存在)
[INFO]: 锦年微光_江浡: 获取(国创)活动抽奖次数错误，消息为(活动已结束)
[INFO]: 锦年微光_江浡: 获取(娱乐)活动抽奖次数错误，消息为(活动已结束)
[INFO]: 锦年微光_江浡: 参与直播间21710524的天选时刻907584(10元舰长代金券【开舰长有效】)成功
[INFO]: 锦年微光_江浡: 参与直播间22731475的天选时刻907594(2元红包)成功
[INFO]: 锦年微光_江浡: 取关主播499243737
[INFO]: 锦年微光_江浡: 取关主播360161798
[INFO]: 锦年微光_江浡: 参与直播间38227的天选时刻907586(5.2元红包)成功
[INFO]: 锦年微光_江浡: 参与直播间22247501的天选时刻907593(2元红包)成功
[INFO]: 锦年微光_江浡: 参与直播间22080761的天选时刻907604(5元红包)成功
[INFO]: 锦年微光_江浡: 参与直播间21710524的天选时刻907602(10元舰长代金券【开舰长有效】)成功
[INFO]: 锦年微光_江浡: 取关主播36514186
[INFO]: 锦年微光_江浡: 取关主播1819745929
[INFO]: 锦年微光_江浡: 取关主播258581
[INFO]: 锦年微光_江浡: 取关主播442203666
[INFO]: 锦年微光_江浡: 取关主播380565104
[INFO]: 锦年微光_江浡: 参与直播间22023401的天选时刻907613(照片)成功
[INFO]: 锦年微光_江浡: 参与直播间22669778的天选时刻907614(2.33红包)成功
[INFO]: 锦年微光_江浡: 参与直播间22695604的天选时刻907626(1.88元红包)成功
[INFO]: 锦年微光_江浡: 参与直播间22731475的天选时刻907615(2元红包)成功
有的呢，难道这个是历史记录吗[笑cry]

**Comment by jiang3231634** [comment]
> 我只看到了抽奖记录并没看到中奖记录....

[INFO]: 锦年微光_江浡: 参与直播间22655683的天选时刻907664(自拍一张)成功
[INFO]: 锦年微光_江浡: 参与直播间21589042的天选时刻907665(6.66元红包~)成功
[INFO]: 锦年微光_江浡: 参与直播间14389566的天选时刻907667(5r新年红包)成功
[INFO]: 锦年微光_江浡: 参与直播间22207531的天选时刻907656(加速器中奖私信领)成功
[INFO]: 锦年微光_江浡: 参与直播间5441的天选时刻907666(30元支付宝红包)成功
[INFO]: 锦年微光_江浡: 参与直播间22344301的天选时刻907663(5.2元红包)成功
[INFO]: 锦年微光_江浡: 参与直播间22695604的天选时刻907648(1.88元红包)成功
[INFO]: 锦年微光_江浡: 天选时刻抽奖任务超时(2700秒)
[INFO]: 锦年微光_江浡: 取关主播1556938849
[INFO]: 锦年微光_江浡: 取关主播650408453
[INFO]: 锦年微光_江浡: 取关主播387606056
[INFO]: 锦年微光_江浡: 取关主播52291466
[INFO]: 锦年微光_江浡: 取关主播5189085
[INFO]: 锦年微光_江浡: 取关主播298700876
[INFO]: 锦年微光_江浡: 取关主播322892
[INFO]: 锦年微光_江浡: 取关主播529225262
[INFO]: 锦年微光_江浡: 取关主播76754317
[INFO]: 推送消息(server酱消息推送1),结果:{"errno":0,"errmsg":"success","dataset":"done"}
这个是最后一条

**Comment by happy888888** [comment]
这只是参与抽奖的信息，并不是中奖信息

**Comment by jiang3231634** [comment]
> 这只是参与抽奖的信息，并不是中奖信息

  啊，括号里的不是中奖信息吗。。。我第一次用大佬您代码的时候看到括号里的消息才去B站后台看然后真的有对应的中奖信息欸。。😅
