### ISSUE TITLE
为什么会连接不到主机，报错如下

### ISSUE THREAD

**Issue by MuYuanGe** [happy888888/BiliExp#266]
[INFO]: 当前程序版本为v1.1.9,配置文件版本为v1.1.9
[WARNING]: 登录验证id为341778728的账户失败，原因为Cannot connect to host api.bilibili.com:443 ssl:False [Connect call failed ('58.222.35.203', 443)]，跳过此账户后续操作
[WARNING]: 推送消息(server酱消息推送)异常，原因为Cannot connect to host sc.ftqq.com:443 ssl:False [Connect call failed ('220.181.136.120', 443)]
我是在openwrt上用docker配置的

**Comment by happy888888** [comment]
有使用代理吗，有的话关闭

**Comment by MuYuanGe** [comment]
> 有使用代理吗，有的话关闭

不行，关了也没用，算了，不用docker了，改用github了
