### ISSUE TITLE
actions上能否把风纪委员投票提前?

### ISSUE THREAD

**Issue by pofang** [happy888888/BiliExp#267]
我所有任务是每晚18点运行，但到这个时间风纪偶尔没有票投，是否能单把风纪委员这个任务定时到中午12点?

**Comment by if1y** [comment]
风纪是子任务，子任务依赖于整体的执行时间。
所以需要把 Actions 执行时间改到12:00。

**Comment by happy888888** [comment]
可以参考某位老哥的方法，多开程序，写两份配置文件，用两个actions来分别执行不同的任务`https://github.com/wangmanv2/BiliExp/tree/master/.github/workflows`
