### ISSUE TITLE
如何准确的生成requirements.txt依赖配置

### ISSUE THREAD

**Issue by FairyWorld** [happy888888/BiliExp#275]
- 大佬，我刚学py不久，想求教一下你项目根路径的requirements.txt是通过什么命令生成的？网上的教程要么多了很多的依赖要么就缺少很多依赖项目

- 几个月前运行机器人up主投稿功能安装依赖弄了很久(当时忘记用你github的requirements.txt)，我记得当时有些依赖的import是在if语句里面的，大概是下面这种，通过博客找来的命令生成requirements.txt都会缺少这个依赖，最后是我一个个手动把依赖的名字补全才能运行
```
if find_spec('.BiliApi', __name__):
    from .BiliApi import BiliApi as bili
```

**Comment by happy888888** [comment]
我的requirements.txt一般是手动写的

BiliApi.py是模块内部的文件不算外部依赖，requirements.txt包含的是依赖的pypi上的外部模块，并不是项目内部已经存在的内部模块

我没太懂你说的把依赖补全是补了一些什么东西，依赖分析可以使用pipreqs等工具来生成requirements.txt

**Comment by FairyWorld** [comment]
> 我的requirements.txt一般是手动写的
> 
> BiliApi.py是模块内部的文件不算外部依赖，requirements.txt包含的是依赖的pypi上的外部模块，并不是项目内部已经存在的内部模块
> 
> 我没太懂你说的把依赖补全是补了一些什么东西，依赖分析可以使用pipreqs等工具来生成requirements.txt

原来你也是手写的，因为想把所有第三方依赖写入到requirements.txt里, 然后云函数可以在线安装。当时我搜索到[生成依赖的博客参考](https://www.cnblogs.com/flyfish919/p/7711394.html)好几篇，这些教程使用到的命令基本差不多, 当时生成的requirements.txt都会缺少几个导致安装完还是不能运行, 需要把缺少的依赖安装一下或者手动填写到requirements.txt重新递归安装所有依赖

**Comment by happy888888** [comment]
云函数需要在本地把依赖包安装到项目文件夹中再上传

不管是不是在if语句里，pipreqs都可以生成import导入的第三方依赖，目前还没发现遗漏的情况，除了import可以导入模块外，还有importlib.import_module()这个方法可以导入模块，这属于动态导入，如果第三方依赖依靠动态导入的话就没办法使用工具生成requirements.txt了，动态导入的模块名称一般是程序运行时临时生成的，没办法在运行前确定导入了些什么模块，不过正常情况下都是用import进行静态导入

**Comment by happy888888** [comment]
有些if语句里的导入属于条件导入，这代表需要满足一定条件才导入模块，因为某些模块可能是不需要的
以本项目为例，不使用漫画下载器生成pdf，那么`PyMuPDF`模块就是不需要的，不使用账号密码进行登录，`rsa`模块就是不需要的，配置文件里的不带注释，`json5`模块就是不需要的，除此外还有一些可能用不到的模块就不用一开始就装上
