### ISSUE TITLE
昨天更新了后发现今天没有自动投币

### ISSUE THREAD

**Issue by licksk** [happy888888/BiliExp#278]
更新了，今天12点打开B站发现没有自动投币，然后就把项目删除重新叉了，重新运行发现还是没有自动投币，不知道是哪里我没有设置好，还是怎么回事。

**Comment by happy888888** [comment]
https://github.com/licksk/BiliExp/runs/1996926092?check_suite_focus=true#step:4:24
可能已经投满5个币了，不需要再投

**Comment by licksk** [comment]
我没有自己投币 硬币记录里也没有当天的投币记录，今天也是没有投币。更新之前每天都正常，投币记录也可以看到😅

**Comment by licksk** [comment]
又好了😁
