### ISSUE TITLE
战友日活动

### ISSUE THREAD

**Issue by niuqudechongdong** [happy888888/BiliExp#28]
现在战友日活动已经开启了😊

-有个想法：投硬币的可不可以弄成大家（用着这个脚本的账号）互相投币，这样可以让大家更快升级，又可以得经验又可以得到硬币，（或者按顺序投币，这样前面的应该很快就可以到6级），最近看到6级账号送9个月实在有点心动。不过，实现起来好像有点麻烦。

**Comment by happy888888** [comment]
站友日貌似是几天内每天都可以兑换，那岂不是会兑换很多次(指本来就有许多B币的人)，我想的办法是指定每月一号，但是不知道会不会日期被修改。

B币肯定有人想给自己充电的，也不能都转换成漫画卷......

互相投币这个应该是实现不了了，记录使用者账户信息会被喷死的（别说用户不愿意，光是记录信息并保存和共享本身就实现不了），这玩意儿只能有个平台去做并运营维护才可能实现，这里实现不了。投币每个视频每人最多投两个(还得是原创)，没发过视频的人肯定不乐意这样啊。

说实话萌节活动真是一年不如一年了，可惜好的时候我都错过了(等级限制)，看看今年还要邀请3个人是什么玩意儿.......

**Comment by niuqudechongdong** [comment]
我记得去年有段时间是每月十号，今年改了一下。确实有些人是给自己充电的，可能只能默认关闭这个功能，自己想要的才打开。

我看今年的萌新节，只要3个没有开过大会员的人领了红包就行，没要求他们要开大会员，比去年多了一个步骤。（我也是今年用了脚本才刚刚上了4，哈哈哈）

这确实是我考虑欠妥了
我之前想法是，想被投币的自愿提交账号ID给你，然后你加密（怕被Ｂ站官方发现），然后觉反正都要投给别人，还不如给需要的人（现在觉得这个想法确实欠妥）。我的视频都是转载油管的，哈哈哈
忽略我这个想法吧

**Comment by happy888888** [comment]
目前已增加自动领取每月10漫读劵(每月1号)和参加站友日活动功能，参与日期可以手动指定(支持指定多个即多次参与，不指定则不参与，默认不参与)

你说的互相投币这个，完全可以搭个平台或者整个交流群什么的来实现(以前那些互赞群那种形式)，规模大了在考虑引入数据库，后端这些内容。感觉说不定这些东西已经有人在做了。

或者去买点小号(网上好像有1级小号2RMB一个的)，每个号一天能产生一个硬币，都投给自己岂不美滋滋，等小号养起来等级高了还能卖掉，岂不美滋滋。号多还可以帮忙刷播放量什么的，能干的事情很多。

总之思路很多，只是我一个学生党没有这么多精力去做.......

**Comment by happy888888** [comment]
对了你有腾讯云吗，我发现了腾讯serverless官方还有这么个活动.....
https://mp.weixin.qq.com/s/_y7cuaTg0DOOpmYKc3puLw

**Comment by niuqudechongdong** [comment]
猜到你也是一个学生了😆，哈哈。

我还在用腾讯云，不过，我现在身边没有电脑。好像这个官方活动的部署方式有点不一样。
