### ISSUE TITLE
转发抽奖相关

### ISSUE THREAD

**Issue by T1573** [happy888888/BiliExp#280]
能不能在跟转功能那加一个大号转发的标签，小号跟转自动带上，不用判断原动态，判断是否加标签功能不太准的样子。

**Comment by happy888888** [comment]
跟踪转发没有带标签的功能

**Comment by T1573** [comment]
> 跟踪转发没有带标签的功能

啊这，我就说开了怎么也没带，能不能加一个这个功能，直接跟大号的标签转

**Comment by happy888888** [comment]
已加上
