### ISSUE TITLE
docker日志显示这样是成功了吗？

### ISSUE THREAD

**Issue by Tongmengjun** [happy888888/BiliExp#283]
Connecting to github.com (13.229.188.59:443)
Connecting to codeload.github.com (13.250.162.133:443)
saving to '/tmp/BiliExp.zip'
BiliExp.zip          11704 --:--:-- ETA
BiliExp.zip          11704 --:--:-- ETA
BiliExp.zip          17184 --:--:-- ETA
BiliExp.zip          34035 --:--:-- ETA
BiliExp.zip          34035 --:--:-- ETA
BiliExp.zip          46292 --:--:-- ETA
BiliExp.zip          47662 --:--:-- ETA
BiliExp.zip          47662 --:--:-- ETA
BiliExp.zip          61951 --:--:-- ETA
BiliExp.zip          78391 --:--:-- ETA
BiliExp.zip          85233 --:--:-- ETA
BiliExp.zip          85233 --:--:-- ETA
BiliExp.zip          86595 --:--:-- ETA
BiliExp.zip          87965 --:--:-- ETA
BiliExp.zip           100k --:--:-- ETA
BiliExp.zip           111k --:--:-- ETA
BiliExp.zip           115k --:--:-- ETA
BiliExp.zip           119k --:--:-- ETA
BiliExp.zip           124k --:--:-- ETA
BiliExp.zip           133k --:--:-- ETA
BiliExp.zip           137k --:--:-- ETA
BiliExp.zip           141k --:--:-- ETA
BiliExp.zip           149k --:--:-- ETA
BiliExp.zip           153k --:--:-- ETA
BiliExp.zip           164k --:--:-- ETA
BiliExp.zip           184k --:--:-- ETA
BiliExp.zip           190k --:--:-- ETA
BiliExp.zip           191k --:--:-- ETA
BiliExp.zip           191k --:--:-- ETA
BiliExp.zip           191k --:--:-- ETA
BiliExp.zip           191k --:--:-- ETA
BiliExp.zip           191k --:--:-- ETA
BiliExp.zip           191k  - stalled -
BiliExp.zip           191k  - stalled -
BiliExp.zip           192k --:--:-- ETA
BiliExp.zip           211k --:--:-- ETA
BiliExp.zip           217k --:--:-- ETA
BiliExp.zip           225k --:--:-- ETA
BiliExp.zip          100% |********************************|  234k  0:00:00 ETA
'/tmp/BiliExp.zip' saved
Archive:  /tmp/BiliExp.zip
   creating: BiliExp-1.2.0/
   creating: BiliExp-1.2.0/.github/
  inflating: BiliExp-1.2.0/.github/pull.yml
   creating: BiliExp-1.2.0/.github/workflows/
  inflating: BiliExp-1.2.0/.github/workflows/auto_clean_workflows.yml
  inflating: BiliExp-1.2.0/.github/workflows/auto_handle_issue.yml
  inflating: BiliExp-1.2.0/.github/workflows/deploy_for_serverless.yml
  inflating: BiliExp-1.2.0/.github/workflows/run_BiliExp.yml
   creating: BiliExp-1.2.0/BiliClient/
  inflating: BiliExp-1.2.0/BiliClient/Article.py
  inflating: BiliExp-1.2.0/BiliClient/Audio.py
  inflating: BiliExp-1.2.0/BiliClient/BiliApi.py
  inflating: BiliExp-1.2.0/BiliClient/Danmu2Ass.py
  inflating: BiliExp-1.2.0/BiliClient/Downloader.py
  inflating: BiliExp-1.2.0/BiliClient/Manga.py
  inflating: BiliExp-1.2.0/BiliClient/Video.py
  inflating: BiliExp-1.2.0/BiliClient/__init__.py
  inflating: BiliExp-1.2.0/BiliClient/asyncBiliApi.py
  inflating: BiliExp-1.2.0/BiliClient/asyncXliveWs.py
   creating: BiliExp-1.2.0/BiliClient/wasm_enc/
  inflating: BiliExp-1.2.0/BiliClient/wasm_enc/__init__.py
  inflating: BiliExp-1.2.0/BiliClient/wasm_enc/bili.wasm
  inflating: BiliExp-1.2.0/BiliClient/wasm_enc/rustwasm.py
  inflating: BiliExp-1.2.0/BiliClient/wasm_enc/spyder.py
  inflating: BiliExp-1.2.0/BiliClient/wasm_enc/stdweb.py
  inflating: BiliExp-1.2.0/BiliExp.py
   creating: BiliExp-1.2.0/Docker/
  inflating: BiliExp-1.2.0/Docker/Dockerfile-runner
  inflating: BiliExp-1.2.0/Docker/entrypoint.sh
  inflating: BiliExp-1.2.0/Docker/init.sh
  inflating: BiliExp-1.2.0/LICENSE
  inflating: BiliExp-1.2.0/README.md
   creating: BiliExp-1.2.0/browser_assist/
  inflating: BiliExp-1.2.0/browser_assist/README.md
   creating: BiliExp-1.2.0/config/
  inflating: BiliExp-1.2.0/config/activities.json
  inflating: BiliExp-1.2.0/config/config.json
  inflating: BiliExp-1.2.0/config/user.json
  inflating: BiliExp-1.2.0/mangaDownloader.py
   creating: BiliExp-1.2.0/packaging/
  inflating: BiliExp-1.2.0/packaging/BiliExp.spec
  inflating: BiliExp-1.2.0/packaging/mangaDownloader.spec
  inflating: BiliExp-1.2.0/packaging/videoDownloader.spec
  inflating: BiliExp-1.2.0/packaging/videoUploader.spec
   creating: BiliExp-1.2.0/player_proxy/
  inflating: BiliExp-1.2.0/player_proxy/README.md
  inflating: BiliExp-1.2.0/player_proxy/player_proxy.js
  inflating: BiliExp-1.2.0/requirements.txt
   creating: BiliExp-1.2.0/run_in_Actions/
  inflating: BiliExp-1.2.0/run_in_Actions/config.json
  inflating: BiliExp-1.2.0/run_in_Actions/requirements.txt
  inflating: BiliExp-1.2.0/run_in_Actions/run_BiliExp.sh
  inflating: BiliExp-1.2.0/run_in_Actions/secrets2config.py
   creating: BiliExp-1.2.0/serverless/
  inflating: BiliExp-1.2.0/serverless/aliyun_serverless.yml
  inflating: BiliExp-1.2.0/serverless/deploy.sh
  inflating: BiliExp-1.2.0/serverless/requirements.txt
  inflating: BiliExp-1.2.0/serverless/serverless.yml
   creating: BiliExp-1.2.0/tasks/
  inflating: BiliExp-1.2.0/tasks/__init__.py
  inflating: BiliExp-1.2.0/tasks/activity_task.py
  inflating: BiliExp-1.2.0/tasks/clean_dynamic_task.py
  inflating: BiliExp-1.2.0/tasks/coin_task.py
  inflating: BiliExp-1.2.0/tasks/exchangeCoupons_task.py
  inflating: BiliExp-1.2.0/tasks/group_sign_task.py
  inflating: BiliExp-1.2.0/tasks/import_once.py
  inflating: BiliExp-1.2.0/tasks/judgement_task.py
  inflating: BiliExp-1.2.0/tasks/lottery_task.py
  inflating: BiliExp-1.2.0/tasks/manga_auto_buy_task.py
  inflating: BiliExp-1.2.0/tasks/manga_sign_task.py
  inflating: BiliExp-1.2.0/tasks/manga_vip_reward_task.py
  inflating: BiliExp-1.2.0/tasks/msg_notify_task.py
  inflating: BiliExp-1.2.0/tasks/push_message_task.py
  inflating: BiliExp-1.2.0/tasks/share_task.py
  inflating: BiliExp-1.2.0/tasks/silver2coin_task.py
  inflating: BiliExp-1.2.0/tasks/vip_task.py
  inflating: BiliExp-1.2.0/tasks/watch_task.py
  inflating: BiliExp-1.2.0/tasks/xliveSign_task.py
  inflating: BiliExp-1.2.0/tasks/xlive_anchor_task.py
  inflating: BiliExp-1.2.0/tasks/xlive_bag_send_task.py
  inflating: BiliExp-1.2.0/tasks/xlive_heartbeat_task.py
  inflating: BiliExp-1.2.0/videoDownloader.py
  inflating: BiliExp-1.2.0/videoUploader.py
   creating: BiliExp-1.2.0/?????????up???/
  inflating: BiliExp-1.2.0/?????????up???/README.md
  inflating: BiliExp-1.2.0/?????????up???/youtube???????????????.py
  inflating: BiliExp-1.2.0/?????????up???/???????????????????????????????????????.py
  inflating: BiliExp-1.2.0/?????????up???/???????????????????????????????????????.py

**Comment by happy888888** [comment]
你看看日志文件内容，跟配置文件在同一个文件夹

**Comment by Tongmengjun** [comment]
config文件夹是吗？里面没有日志

**Comment by happy888888** [comment]
> config文件夹是吗？里面没有日志

https://github.com/happy888888/BiliExp/blob/92dae46b60296f39a11a23931daa8de92fcc38fb/config/config.json#L234-L235

`log_console`在执行时将日志输出到控制台

**Comment by Tongmengjun** [comment]
今天docker拉又出现这个问题了，请问怎么解决？

saving to '/tmp/BiliExp.zip'
BiliExp.zip            1% |                                |  3473  0:01:08 ETA
BiliExp.zip            6% |*                               | 14433  0:00:31 ETA
BiliExp.zip            6% |**                              | 15803  0:00:42 ETA
BiliExp.zip           14% |****                            | 34983  0:00:23 ETA
BiliExp.zip           15% |****                            | 36353  0:00:28 ETA
BiliExp.zip           20% |******                          | 48683  0:00:23 ETA
BiliExp.zip           21% |******                          | 51423  0:00:25 ETA
BiliExp.zip           21% |******                          | 51423  0:00:29 ETA
BiliExp.zip           25% |********                        | 62383  0:00:25 ETA
BiliExp.zip           35% |***********                     | 84301  0:00:18 ETA
BiliExp.zip           43% |*************                   |  101k  0:00:14 ETA
BiliExp.zip           46% |**************                  |  109k  0:00:13 ETA
BiliExp.zip           49% |***************                 |  117k  0:00:13 ETA
BiliExp.zip           52% |****************                |  122k  0:00:12 ETA
BiliExp.zip           52% |****************                |  123k  0:00:13 ETA
BiliExp.zip           60% |*******************             |  142k  0:00:10 ETA
BiliExp.zip           62% |*******************             |  146k  0:00:10 ETA
BiliExp.zip           65% |*********************           |  154k  0:00:09 ETA
BiliExp.zip           67% |*********************           |  158k  0:00:09 ETA
BiliExp.zip           71% |**********************          |  167k  0:00:07 ETA
BiliExp.zip           72% |***********************         |  169k  0:00:08 ETA
BiliExp.zip           73% |***********************         |  173k  0:00:07 ETA
BiliExp.zip           81% |**************************      |  190k  0:00:05 ETA
wget: connection closed prematurely
unzip: short read
Archive:  /tmp/BiliExp.zip
mv: can't rename '/tmp/BiliExp*': No such file or directory
cp: can't stat '/tmp/BiliExp': No such file or directory
./entrypoint.sh: cd: line 54: can't cd to /tmp/BiliExp: No such file or directory

**Comment by happy888888** [comment]
docker运行参数加上`-t 1.2.0`这样就可以缓存1.2.0版本的代码而不用每次下载，国内下载github很可能失败

**Comment by Tongmengjun** [comment]
加上了的，每次到百分之80，81就失败了。

**Comment by happy888888** [comment]
网络问题，只能多试几次，或者手动下载代码，在config.json配置文件所在文件夹新建一个code-cache文件夹再把代码放进去

**Comment by happy888888** [comment]
目前新版镜像使用了`fastgit.org`镜像站对`github.com`进行加速，应该不会出现下载失败的问题了
