### ISSUE TITLE
Docker从1.1.9升到1.2.0版本运行报错

### ISSUE THREAD

**Issue by Mateoust** [happy888888/BiliExp#284]
Connecting to api.github.com (192.30.255.116:443)
Connecting to codeload.github.com (13.229.189.0:443)
saving to '/tmp/BiliExp.zip'

BiliExp.zip           16% |*****                           | 39730  0:00:05 ETA
BiliExp.zip           20% |******                          | 49320  0:00:07 ETA
BiliExp.zip           20% |******                          | 49320  0:00:11 ETA
BiliExp.zip           20% |******                          | 50690  0:00:15 ETA
BiliExp.zip           21% |******                          | 52060  0:00:18 ETA
BiliExp.zip           22% |*******                         | 53430  0:00:21 ETA
BiliExp.zip           31% |*********                       | 75608  0:00:15 ETA
BiliExp.zip           31% |**********                      | 76978  0:00:17 ETA
BiliExp.zip           31% |**********                      | 76978  0:00:19 ETA
BiliExp.zip           32% |**********                      | 79718  0:00:20 ETA
BiliExp.zip           35% |***********                     | 86568  0:00:19 ETA
BiliExp.zip           41% |*************                   | 99.2k  0:00:16 ETA
BiliExp.zip           49% |***************                 |  116k  0:00:13 ETA
BiliExp.zip           49% |***************                 |  117k  0:00:14 ETA
BiliExp.zip           57% |******************              |  135k  0:00:11 ETA
BiliExp.zip           60% |*******************             |  142k  0:00:10 ETA
BiliExp.zip           69% |**********************          |  164k  0:00:07 ETA
BiliExp.zip           71% |**********************          |  170k  0:00:07 ETA
BiliExp.zip           72% |***********************         |  171k  0:00:07 ETA
BiliExp.zip           75% |************************        |  179k  0:00:06 ETA
BiliExp.zip           82% |**************************      |  195k  0:00:04 ETA
BiliExp.zip           85% |***************************     |  203k  0:00:03 ETAwget: connection closed prematurely
Archive:  /tmp/BiliExp.zip
unzip: short read
mv: can't rename '/tmp/*BiliExp*': No such file or directory
python3: can't open file '/tmp/BiliExp/BiliExp.py': [Errno 2] No such file or directory
Connecting to api.github.com (192.30.255.116:443)
Connecting to codeload.github.com (54.251.140.56:443)
saving to '/tmp/BiliExp.zip'

BiliExp.zip          13057 --:--:-- ETA
BiliExp.zip          38284 --:--:-- ETA
BiliExp.zip          56088 --:--:-- ETA
BiliExp.zip          61568 --:--:-- ETA
BiliExp.zip          62938 --:--:-- ETA
BiliExp.zip          62938 --:--:-- ETA
BiliExp.zip          62938 --:--:-- ETA
BiliExp.zip          65678 --:--:-- ETA
BiliExp.zip          79370 --:--:-- ETA
BiliExp.zip          91692 --:--:-- ETA
BiliExp.zip           108k --:--:-- ETA
BiliExp.zip           108k --:--:-- ETA
BiliExp.zip           108k --:--:-- ETA
BiliExp.zip           109k --:--:-- ETA
BiliExp.zip           118k --:--:-- ETA
BiliExp.zip           120k --:--:-- ETA
BiliExp.zip           129k --:--:-- ETA
BiliExp.zip           136k --:--:-- ETA
BiliExp.zip           145k --:--:-- ETA
BiliExp.zip           156k --:--:-- ETA
BiliExp.zip           170k --:--:-- ETA
BiliExp.zip           178k --:--:-- ETA
BiliExp.zip           186k --:--:-- ETA
BiliExp.zip           212k --:--:-- ETA
BiliExp.zip           218k --:--:-- ETA
BiliExp.zip           224k --:--:-- ETA
BiliExp.zip           229k --:--:-- ETA
BiliExp.zip           230k --:--:-- ETA
BiliExp.zip           233k --:--:-- ETA
BiliExp.zip           236k --:--:-- ETA
BiliExp.zip          100% |********************************|  236k  0:00:00 ETA
'/tmp/BiliExp.zip' saved
Archive:  /tmp/BiliExp.zip
   creating: happy888888-BiliExp-8c3b314/
   creating: happy888888-BiliExp-8c3b314/.github/
  inflating: happy888888-BiliExp-8c3b314/.github/pull.yml
   creating: happy888888-BiliExp-8c3b314/.github/workflows/
  inflating: happy888888-BiliExp-8c3b314/.github/workflows/auto_clean_workflows.yml
  inflating: happy888888-BiliExp-8c3b314/.github/workflows/auto_handle_issue.yml
  inflating: happy888888-BiliExp-8c3b314/.github/workflows/deploy_for_serverless.yml
  inflating: happy888888-BiliExp-8c3b314/.github/workflows/run_BiliExp.yml
   creating: happy888888-BiliExp-8c3b314/BiliClient/
  inflating: happy888888-BiliExp-8c3b314/BiliClient/Article.py
  inflating: happy888888-BiliExp-8c3b314/BiliClient/Audio.py
  inflating: happy888888-BiliExp-8c3b314/BiliClient/BiliApi.py
  inflating: happy888888-BiliExp-8c3b314/BiliClient/Danmu2Ass.py
  inflating: happy888888-BiliExp-8c3b314/BiliClient/Downloader.py
  inflating: happy888888-BiliExp-8c3b314/BiliClient/Manga.py
  inflating: happy888888-BiliExp-8c3b314/BiliClient/Video.py
  inflating: happy888888-BiliExp-8c3b314/BiliClient/__init__.py
  inflating: happy888888-BiliExp-8c3b314/BiliClient/asyncBiliApi.py
  inflating: happy888888-BiliExp-8c3b314/BiliClient/asyncXliveWs.py
   creating: happy888888-BiliExp-8c3b314/BiliClient/wasm_enc/
  inflating: happy888888-BiliExp-8c3b314/BiliClient/wasm_enc/__init__.py
  inflating: happy888888-BiliExp-8c3b314/BiliClient/wasm_enc/bili.wasm
  inflating: happy888888-BiliExp-8c3b314/BiliClient/wasm_enc/rustwasm.py
  inflating: happy888888-BiliExp-8c3b314/BiliClient/wasm_enc/spyder.py
  inflating: happy888888-BiliExp-8c3b314/BiliClient/wasm_enc/stdweb.py
  inflating: happy888888-BiliExp-8c3b314/BiliExp.py
   creating: happy888888-BiliExp-8c3b314/Docker/
  inflating: happy888888-BiliExp-8c3b314/Docker/Dockerfile-runner
  inflating: happy888888-BiliExp-8c3b314/Docker/entrypoint.sh
  inflating: happy888888-BiliExp-8c3b314/Docker/init.sh
  inflating: happy888888-BiliExp-8c3b314/LICENSE
  inflating: happy888888-BiliExp-8c3b314/README.md
   creating: happy888888-BiliExp-8c3b314/browser_assist/
  inflating: happy888888-BiliExp-8c3b314/browser_assist/README.md
   creating: happy888888-BiliExp-8c3b314/config/
  inflating: happy888888-BiliExp-8c3b314/config/activities.json
  inflating: happy888888-BiliExp-8c3b314/config/config.json
  inflating: happy888888-BiliExp-8c3b314/config/user.json
  inflating: happy888888-BiliExp-8c3b314/mangaDownloader.py
   creating: happy888888-BiliExp-8c3b314/packaging/
  inflating: happy888888-BiliExp-8c3b314/packaging/BiliExp.spec
  inflating: happy888888-BiliExp-8c3b314/packaging/mangaDownloader.spec
  inflating: happy888888-BiliExp-8c3b314/packaging/videoDownloader.spec
  inflating: happy888888-BiliExp-8c3b314/packaging/videoUploader.spec
   creating: happy888888-BiliExp-8c3b314/player_proxy/
  inflating: happy888888-BiliExp-8c3b314/player_proxy/README.md
  inflating: happy888888-BiliExp-8c3b314/player_proxy/player_proxy.js
  inflating: happy888888-BiliExp-8c3b314/requirements.txt
   creating: happy888888-BiliExp-8c3b314/run_in_Actions/
  inflating: happy888888-BiliExp-8c3b314/run_in_Actions/config.json
  inflating: happy888888-BiliExp-8c3b314/run_in_Actions/requirements.txt
  inflating: happy888888-BiliExp-8c3b314/run_in_Actions/run_BiliExp.sh
  inflating: happy888888-BiliExp-8c3b314/run_in_Actions/secrets2config.py
   creating: happy888888-BiliExp-8c3b314/serverless/
  inflating: happy888888-BiliExp-8c3b314/serverless/aliyun_serverless.yml
  inflating: happy888888-BiliExp-8c3b314/serverless/deploy.sh
  inflating: happy888888-BiliExp-8c3b314/serverless/requirements.txt
  inflating: happy888888-BiliExp-8c3b314/serverless/serverless.yml
   creating: happy888888-BiliExp-8c3b314/tasks/
  inflating: happy888888-BiliExp-8c3b314/tasks/__init__.py
  inflating: happy888888-BiliExp-8c3b314/tasks/activity_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/clean_dynamic_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/coin_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/exchangeCoupons_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/group_sign_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/import_once.py
  inflating: happy888888-BiliExp-8c3b314/tasks/judgement_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/lottery_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/manga_auto_buy_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/manga_sign_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/manga_vip_reward_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/msg_notify_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/push_message_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/share_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/silver2coin_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/vip_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/watch_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/xliveSign_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/xlive_anchor_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/xlive_bag_send_task.py
  inflating: happy888888-BiliExp-8c3b314/tasks/xlive_heartbeat_task.py
  inflating: happy888888-BiliExp-8c3b314/videoDownloader.py
  inflating: happy888888-BiliExp-8c3b314/videoUploader.py
   creating: happy888888-BiliExp-8c3b314/?????????up???/
  inflating: happy888888-BiliExp-8c3b314/?????????up???/README.md
  inflating: happy888888-BiliExp-8c3b314/?????????up???/youtube???????????????.py
  inflating: happy888888-BiliExp-8c3b314/?????????up???/???????????????????????????????????????.py
  inflating: happy888888-BiliExp-8c3b314/?????????up???/???????????????????????????????????????.py
Traceback (most recent call last):
  File "/tmp/BiliExp/BiliExp.py", line 7, in 
    from BiliClient import asyncbili
  File "/tmp/BiliExp/BiliClient/__init__.py", line 11, in 
    from .asyncBiliApi import asyncBiliApi as asyncbili #B站接口模块，由aiohttp模块实现异步http请求
  File "/tmp/BiliExp/BiliClient/asyncBiliApi.py", line 9, in 
    from .wasm_enc import calc_sign
  File "/tmp/BiliExp/BiliClient/wasm_enc/__init__.py", line 1, in 
    from .spyder import calc_sign
  File "/tmp/BiliExp/BiliClient/wasm_enc/spyder.py", line 3, in 
    from .rustwasm import RustWasm
  File "/tmp/BiliExp/BiliClient/wasm_enc/rustwasm.py", line 5, in 
    from wasmtime import Store, Module, Instance
ModuleNotFoundError: No module named 'wasmtime'
Connecting to api.github.com (192.30.255.117:443)
Connecting to codeload.github.com (13.229.189.0:443)
saving to '/tmp/BiliExp.zip'

BiliExp.zip          11681 --:--:-- ETA
BiliExp.zip          15791 --:--:-- ETA
BiliExp.zip          19901 --:--:-- ETA
BiliExp.zip          30671 --:--:-- ETA
BiliExp.zip          43763 --:--:-- ETA
BiliExp.zip          60154 --:--:-- ETA
BiliExp.zip          65634 --:--:-- ETA
BiliExp.zip          75874 --:--:-- ETA
BiliExp.zip          86834 --:--:-- ETA
BiliExp.zip          95054 --:--:-- ETA
BiliExp.zip          95054 --:--:-- ETA
BiliExp.zip          95054 --:--:-- ETA
BiliExp.zip          96424 --:--:-- ETA
BiliExp.zip          99164 --:--:-- ETA
BiliExp.zip           110k --:--:-- ETA
BiliExp.zip           111k --:--:-- ETA
BiliExp.zip           123k --:--:-- ETA
BiliExp.zip           128k --:--:-- ETA
BiliExp.zip           140k --:--:-- ETA
BiliExp.zip           162k --:--:-- ETA
BiliExp.zip           191k --:--:-- ETAwget: error getting response
Archive:  /tmp/BiliExp.zip
unzip: short read
mv: can't rename '/tmp/BiliExp': Invalid argument
Traceback (most recent call last):
  File "/tmp/BiliExp/BiliExp.py", line 7, in 
    from BiliClient import asyncbili
  File "/tmp/BiliExp/BiliClient/__init__.py", line 11, in 
    from .asyncBiliApi import asyncBiliApi as asyncbili #B站接口模块，由aiohttp模块实现异步http请求
  File "/tmp/BiliExp/BiliClient/asyncBiliApi.py", line 9, in 
    from .wasm_enc import calc_sign
  File "/tmp/BiliExp/BiliClient/wasm_enc/__init__.py", line 1, in 
    from .spyder import calc_sign
  File "/tmp/BiliExp/BiliClient/wasm_enc/spyder.py", line 3, in 
    from .rustwasm import RustWasm
  File "/tmp/BiliExp/BiliClient/wasm_enc/rustwasm.py", line 5, in 
    from wasmtime import Store, Module, Instance
ModuleNotFoundError: No module named 'wasmtime'

一开始下载文件失败了。然后重试了几次就可以了。但是会报上面的错误。用的镜像是runner的1.2.0版本。然后我试了下指定1.1.9则没有这个问题。然后又试了下latest的1.1.8也没有问题。麻烦大大帮我看一下

**Comment by happy888888** [comment]
重新pull一下镜像试试

**Comment by Mateoust** [comment]
> 重新pull一下镜像试试

刚刚重新pull了几次，现在已经正常了。估计是国内服务器连接github不稳定导致的问题吧。之前试了蛮多次都不行。感谢大佬的帮助。另外大大有考虑放一个gitee的镜像吗？
