### ISSUE TITLE
[Feature Request]action运行时，允许通过secrets"biliconfig"映射用户show_name

### ISSUE THREAD

**Issue by zhongfly** [happy888888/BiliExp#286]
我认为可以修改https://github.com/happy888888/BiliExp/blob/master/run_in_Actions/secrets2config.py#L48 来实现
然后多个用户之间用空行分割

**Comment by zhongfly** [comment]
https://github.com/happy888888/BiliExp/pull/288

**Comment by happy888888** [comment]
actions为了安全，显示日志时会屏蔽secrets里出现的内容并用星号代替，这会导致show_name无法正常显示，不建议这样配置
