### ISSUE TITLE
cookies 是有效的，也提示cookies失效

### ISSUE THREAD

**Issue by newhackerman** [happy888888/BiliExp#289]
![image](https://user-images.githubusercontent.com/15150570/109823982-6014ef00-7c73-11eb-9205-c752a14efe23.png)

**Comment by happy888888** [comment]
运行环境是什么？日志内容呢？

**Comment by newhackerman** [comment]
centos 7.3 我首先是根据教程用docker的形式部署的，一直提示找到不挂载点/BiliExp 这种方式没弄好就
试着直接用命令的方式启动，改了config/config.json里的users第一组配置（SESSDATA，bili_jct，DedeUserID）这个用google浏览器登录Bilibili取到的
[WARNING]: id为账号uid的账户cookie失效，跳过此账户后续操作

**Comment by happy888888** [comment]
看日志，配置文件并没有修改成功，

**Comment by newhackerman** [comment]
我再看看吧，谢谢了
