### ISSUE TITLE
为什么腾讯云的docker容器不执行而阿里云的容器执行？

### ISSUE THREAD

**Issue by Tongmengjun** [happy888888/BiliExp#291]
昨天下午不知道动了一下哪里，然后腾讯云的镜像挂了，搞一通宵那个镜像一直都是在执行但是账号没有任何反应，不管crontab设置什么时间执行。但是刚刚用阿里云试了一下，同样的命令同样的动作，阿里云的却可以执行，不知道是什么鬼，两个我都试了一下每分钟执行但是腾讯云的就是执行不了。并且两个服务器进入docker的终端都显示
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown。阿里云和腾讯云中两个文件唯一的不同是阿里云的运行产生了一个BIliExp.log日志。

**Comment by happy888888** [comment]
你用的什么命令执行？

**Comment by Tongmengjun** [comment]
docker run \
-v /home/user/Biliexp:/BiliExp \
happy888888/biliexp:runner-latest \
-t 1.2.0
docker用这个拉取的，容器在运行但是日志啥的都不输出，按照你前面给的设置为true了，而且账号里面也没有记录

**Comment by happy888888** [comment]
你是用的腾讯云TKE运行的吗，如果需要远程登录，不能使用"/bin/bash"而应该使用"/bin/sh"

**Comment by Tongmengjun** [comment]
不是的，我用的是云服务器上装的docker

**Comment by happy888888** [comment]
如果是用的云服务器远程登录，要先创建一个文件夹(比如/home/user/Biliexp)，把config.json放进去，然后运行`docker run -v /home/user/Biliexp:/BiliExp happy888888/biliexp:runner-latest -t 1.2.0`，docker就会从github下载代码然后运行，如果下载失败，就在你创建的文件夹里(比如/home/user/Biliexp)创建一个`code-cache`文件夹，把本项目下的`BiliExp.py` `tasks` `BiliClient(不包含文件夹下的wasm_enc文件夹)` 三个文件(夹)都放到`code-cache`文件夹里，然后再运行docker

文件结构如下图所示
![image](https://user-images.githubusercontent.com/67217225/110068347-71174a80-7db0-11eb-9c22-9c4f26701e0e.png)
![image](https://user-images.githubusercontent.com/67217225/110068383-7eccd000-7db0-11eb-9528-e8843e7a4008.png)

**Comment by happy888888** [comment]
如果运行成功就会在config.json同级目录生成一个BIliExp.log日志文件

**Comment by Tongmengjun** [comment]
可以了，刚刚把json的注释全部删除了就发现可以了

**Comment by Tongmengjun** [comment]
非常感谢大佬

**Comment by Tongmengjun** [comment]
[WARNING]: bili_11106417990----123456: 获取直播间列表失败,信息为(请求被拦截)
[WARNING]: bili_48101541755----huikai19921125: 获取直播间列表失败,信息为(请求被拦截)
[WARNING]: 88922796756_bili----guxiongjie: 获取直播间列表失败,信息为(请求被拦截)
[WARNING]: bili_28859780459----cgd4320811: 获取直播间列表失败,信息为(请求被拦截)
[WARNING]: bili_4854947370----gh320917: 获取直播间列表失败,信息为(请求被拦截)
[WARNING]: bili_48101541755----huikai19921125: 获取直播间列表失败,信息为(请求被拦截)
[WARNING]: bili_11106417990----123456: 获取直播间列表失败,信息为(请求被拦截)
[WARNING]: 88922796756_bili----guxiongjie: 获取直播间列表失败,信息为(请求被拦截)

日志显示获取直播间失败，是我的ip问题吗？

**Comment by Tongmengjun** [comment]
[WARNING]: bili_11106417990----123456: 获取直播间列表失败,信息为(请求被拦截)
[WARNING]: bili_48101541755----huikai19921125: 获取直播间列表失败,信息为(请求被拦截)
[WARNING]: 88922796756_bili----guxiongjie: 获取直播间列表失败,信息为(请求被拦截)
[WARNING]: bili_28859780459----cgd4320811: 获取直播间列表失败,信息为(请求被拦截)
[WARNING]: bili_4854947370----gh320917: 获取直播间列表失败,信息为(请求被拦截)
[WARNING]: bili_48101541755----huikai19921125: 获取直播间列表失败,信息为(请求被拦截)
[WARNING]: bili_11106417990----123456: 获取直播间列表失败,信息为(请求被拦截)
[WARNING]: 88922796756_bili----guxiongjie: 获取直播间列表失败,信息为(请求被拦截)

日志显示获取直播间失败，是我的ip问题吗？

**Comment by happy888888** [comment]
对的，请求太频繁一般暂停30分钟就好了
