### ISSUE TITLE
【小白求助】在actions中运行，Process completed with exit code 6.

### ISSUE THREAD

**Issue by DawnFaramita** [happy888888/BiliExp#293]
![111](https://user-images.githubusercontent.com/79857801/109908718-b586e580-7cdf-11eb-844a-1f41ae356e0d.PNG)

我把config.json修改了几个选项之后整个放到了secrets(ADVCONFIG)中
是这个原因吗？

**Comment by happy888888** [comment]
对啊，修改不符合json格式导致程序加载失败，看看引号逗号括号这些有没有遗漏

**Comment by DawnFaramita** [comment]
> 对啊，修改不符合json格式导致程序加载失败，看看引号逗号括号这些有没有遗漏

![rtsgdsgdsf](https://user-images.githubusercontent.com/79857801/109910438-119f3900-7ce3-11eb-8cf1-4df6994aa690.PNG)
大佬，是这个逗号吗？
我改动之前就没有这个逗号

**Comment by DawnFaramita** [comment]
> 对啊，修改不符合json格式导致程序加载失败，看看引号逗号括号这些有没有遗漏

![捕获](https://user-images.githubusercontent.com/79857801/109910731-c9cce180-7ce3-11eb-8f95-b449cbf28136.PNG)
加了逗号之后，这样子是不是成功了？

**Comment by happy888888** [comment]
这样是成功了，不过同级配置的最后一项末尾不用逗号的

**Comment by DawnFaramita** [comment]
> 这样是成功了，不过同级配置的最后一项末尾不用逗号的

我把这两个调换了顺序。。。
多谢大佬

**Comment by happy888888** [comment]
把配置文件235行https://github.com/happy888888/BiliExp/blob/92dae46b60296f39a11a23931daa8de92fcc38fb/config/config.json#L235
设置为true可显示执行日志
