### ISSUE TITLE
window本地部署无法运行

### ISSUE THREAD

**Issue by xiuxiububu** [happy888888/BiliExp#295]
win10 20H2 python3.9 代码版本1.2.0 
本来我下载源代码后配置好成功运行了代码，但是用win10计划任务和powershell发现，当使用绝对路径运行代码时，显示“配置加载异常，原因为未找到配置文件，退出程序”，只有在当前文件夹下才能正常运行代码。而后我尝试使用release里的BiliExp-win32_64版本，仅填写SESSDATA，bili_jct，DedeUserID三项后，程序无法正常运行

**Comment by happy888888** [comment]
代码用绝对路径运行，配置文件也需要用绝对路径加载
python D:\BiliExp\BiliExp.py -c D:\BiliExp\config.json

**Comment by xiuxiububu** [comment]
添加 -c后自动成功运行，但是提示
`D:\BiliExp-master\BiliExp.py:84: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
  await asyncio.wait([run_user_tasks(user, configData["default"]) for user in configData["users"]]) #执行任务
D:\BiliExp-master\BiliExp.py:138: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
  await asyncio.wait(task_array)        #异步等待所有任务完成`
参考[https://docs.python.org/3/library/asyncio-task.html#asyncio.wait](url)
