### ISSUE TITLE
请教一个互动抽奖的技术性问题

### ISSUE THREAD

**Issue by if1y** [happy888888/BiliExp#297]
这几天在研究正则优化互动抽奖的精准度，想问问这个标志 ![image](https://user-images.githubusercontent.com/32222791/110202315-a734f700-7ea2-11eb-8d22-ff7874309e7c.png)，在程序读取动态的时候包括哪些信息？

F12 看源码是这样的：
![image](https://user-images.githubusercontent.com/32222791/110202345-db101c80-7ea2-11eb-9179-0a8151f34743.png)

**Comment by happy888888** [comment]
每个"动态标签"都是动态构建的，当你用鼠标把浏览器页面拉到底部时浏览器开始向服务器请求数据并增加页面上的"动态标签"。

程序读取动态，既可以通过浏览器读取网页上的动态标签，也可以直接模拟浏览器直接向服务器请求数据。如果是前者程序拿到的数据就跟你f12看到的一样，本项目没有使用浏览器所以采用后者，只关心浏览器和服务器交互的数据格式不关心网页源码

**Comment by if1y** [comment]
感谢指点，反应过来了应该看api
