### ISSUE TITLE
漫画下载

### ISSUE THREAD

**Issue by niuqudechongdong** [happy888888/BiliExp#298]
大佬，请问下载《鲲吞天下》mc:26723的漫画时，转换成pdf时，最后提示：
正在合并下载图片为pdf
Corrupt JPEG data: premature end of data segment
文件保存至./鲲吞天下/鲲吞天下.pdf

这是什么意思？

**Comment by happy888888** [comment]
你下载了哪些章节？

**Comment by niuqudechongdong** [comment]
哈哈哈，我下载了全部章节

**Comment by happy888888** [comment]
那你直接看看pdf有没有什么问题

**Comment by niuqudechongdong** [comment]
pdf的前面几百页能看到
后面不知道是不是因为文件太大了，就卡住了。。。

**Comment by happy888888** [comment]
确实一张图片几MB，一章几十张图片，一本漫画上百章，感觉合并成pdf并不是很好的打包方法

**Comment by niuqudechongdong** [comment]
确实是，而且有时候拼接的不是很好，大部分时候都还可以
![image](https://user-images.githubusercontent.com/64181801/110243381-1d198b00-7f95-11eb-961a-98e9af88b66a.png)

![image](https://user-images.githubusercontent.com/64181801/110243412-31f61e80-7f95-11eb-8621-c5c489aefcff.png)

**Comment by niuqudechongdong** [comment]
但我之前用微软商店的软件“漫画加加”来看压缩的漫画文件（把图片打包成zip形式），感觉更是对不齐

所以我现在也不知道用什么来看本地漫画比较好

**Comment by happy888888** [comment]
每张图片长宽比例不一样，总不能强行拉伸吧。😂

**Comment by niuqudechongdong** [comment]
第一张图应该是程序错了？我看两张图的分辨率是一样的（第一张图的中间跟下载的图片）

**Comment by happy888888** [comment]
你用的什么打开pdf，我试了一下edge貌似是对齐的

**Comment by niuqudechongdong** [comment]
googe来的

**Comment by happy888888** [comment]
00章的最后一张图片是2000*2148，01章的第一张图片是1200*1730，第二张图片是1200*1952，图片长宽比不一样导致了对不齐

**Comment by niuqudechongdong** [comment]
害，原来是这样，失误了，没看清

**Comment by happy888888** [comment]
看了一下网页版，发现B站的处理方式是直接把每张图片宽度固定，长宽比例不变进行的拉伸

**Comment by niuqudechongdong** [comment]
我说怎么b站那里就能做到连接完整。

之前我用漫画加加软件看国漫，发现基本每张都不怎么对的上，所以我才想好像这个程序有可以合成pdf的，试了下，发现还可以。
但有几点小麻烦：
1.刚才说的，有时候合成的pdf太大了，容易卡住
2.另一个问题是，不好找自己需要的章节，这样比较难找到上次看的地方，特别是文件大的时候。（结合可以看pdf形式漫画的软件会不会比较好？）

**Comment by happy888888** [comment]
漫画加加的zip格式内部结构呢？对不齐的问题只能靠图片拉伸变换为统一的宽度了，还可以降低图片质量减小体积

**Comment by happy888888** [comment]
> 我说怎么b站那里就能做到连接完整。
> 
> 之前我用漫画加加软件看国漫，发现基本每张都不怎么对的上，所以我才想好像这个程序有可以合成pdf的，试了下，发现还可以。
> 但有几点小麻烦：
> 1.刚才说的，有时候合成的pdf太大了，容易卡住
> 2.另一个问题是，不好找自己需要的章节，这样比较难找到上次看的地方，特别是文件大的时候。（结合可以看pdf形式漫画的软件会不会比较好？）

主要是不知道有哪些可以看离线漫画的软件，要保留浏览记录的话或许可以使用epub格式当电子书看？

**Comment by niuqudechongdong** [comment]
我是把程序下载的文件夹压缩成一个zip文件（每部漫画一个文件夹，也可以每一章节一个文件夹）

我用的是微软商店的Comics++（漫画加加），这个软件的话，打开后，可以打开上次看的页面
不过无论是这些软件观看本地漫画还是用pdf看，都没法可以给你选定跳到某一章节，在章节数很多时，这个问题尤为明显，如果是每一章节一个zip，我试了下500个章节（zip）就会卡住（这个是通病，可以忽略这个问题）

**Comment by happy888888** [comment]
试试手机上使用https://github.com/feilongfl/Cimoc/releases/tag/v1.5.6
可以直接看文件夹不需要打包

**Comment by niuqudechongdong** [comment]
这个可以，安卓端的话，听说布卡漫画也挺不错的

有没有是电脑端的漫画阅读器？

**Comment by happy888888** [comment]
[comicsviewer-v3.18.zip](https://github.com/happy888888/BiliExp/files/6098943/comicsviewer-v3.18.zip)
这个可以直接浏览文件夹，也有自动对齐，但是没有跳章节的。估计只有电子书类似的格式才支持跳章节

**Comment by niuqudechongdong** [comment]
好的，谢谢大佬，这个我好像听别人介绍过

**Comment by niuqudechongdong** [comment]
这个是怎么设置卷轴模式的（对齐）？

**Comment by happy888888** [comment]
这个是一页一页分开显示的，不能实现两页各占一半屏幕那种滚动

**Comment by niuqudechongdong** [comment]
我也是没找到，对于国漫来说，还是用卷轴模式比较好（所以我之前改用漫画加加）

**Comment by happy888888** [comment]
给pdf加个目录用于跳转？感觉实现类似于卷轴模式的阅读只能用pdf了，不然就得自己实现阅读器，已经超越本项目的范围了

**Comment by niuqudechongdong** [comment]
这个方法也可以，自己实现阅读器的话还是太费精力了，没什么必要

对了，大佬，可以实现以下功能吗？
1.在合成pdf时，可以在添加一个选项吗？就是有两种方案可供选择  ①整本合成一个PDF（现在这个程序的功能就是这样） ②每一章节合成一个pdf文件。这样很多章节的漫画就不会卡顿，防止pdf文件过大。

2.这个程序在合成pdf时，必须要先下载一些漫画，才能用-f参数。可不可以不用下载漫画，直接合成pdf文件，就是说，我下载的其他网站的漫画（已经下好），但是我想用本程序来合成pdf。这样这个程序也能作为一个单独的pdf合成软件。也希望能提供两种pdf合成方式（整本和分章节）
（第2个构想可能有点问题，比如用其他程序下载的漫画文件的命名方式有点不一样，所以可能合成不了）
