### ISSUE TITLE
获取动态列表异常

### ISSUE THREAD

**Issue by Cnzw** [happy888888/BiliExp#299]
**今天又没问题了**

~~前几天都使用正常的, 就今天出现了~~

使用linux直接部署, Cron定时任务. 以下为启动脚本:
`/usr/local/bin/BiliExp -c /etc/BiliExp/config.json -l /www/wwwroot/***/elog/BiliExp.log`

~~配置文件应该没问题, 毕竟正常运行了快半个月了.~~

log:
```
[INFO]: 当前程序版本为v1.1.9,配置文件版本为v1.1.9
...
[WARNING]: ***: 银瓜子兑换硬币失败，信息为(银瓜子余额不足)
[WARNING]: ***: 获取动态列表、异常，原因为argument of type 'NoneType' is not iterable，跳过动态清理
[INFO]: 推送消息(Bark推送),结果:{"code":200,"data":null,"message":""}
```

**Comment by happy888888** [comment]
如果***影响正常使用***可以考虑升级到新版代码
