### ISSUE TITLE
多账户如何填userData.py

### ISSUE THREAD

**Issue by Chillily** [happy888888/BiliExp#3]
cookieDatas = [{ 
    "SESSDATA": "账户1","账户2","账户3",
    "bili_jct": "1","2","3",
    "DedeUserID": "1","2","3",
    }]

app_access_keys = [""] 

SCKEY = "" 

是这样吗

**Comment by happy888888** [comment]
cookieDatas = [{
"SESSDATA": "账户1",
"bili_jct": "1",
"DedeUserID": "1",
},
{
"SESSDATA": "账户2",
"bili_jct": "2",
"DedeUserID": "2",
},
{
"SESSDATA": "账户3",
"bili_jct": "3",
"DedeUserID": "3",
}]

app_access_keys = ["access_keys1","access_keys2","access_keys3"] #access_keys是手机app的

SCKEY = ""
