### ISSUE TITLE
linux里部署的可以自动更新吗？另外日志希望加上时间戳

### ISSUE THREAD

**Issue by kudouxinyi** [happy888888/BiliExp#301]
linux里部署的，版本1.20可以自动更新吗？还是说源代码更新时候需要手动更新
另外日志希望加上时间戳。

**Comment by happy888888** [comment]
直接在BiliExp.py中添加这两行可以实现日志增加时间
https://github.com/happy888888/BiliExp/blob/dfe59ed6c93eacca689a34402fe6500abc09e922/BiliExp.py#L28-L29
