### ISSUE TITLE
天选时刻 礼物名称黑名单 命中关键词但没有过滤

### ISSUE THREAD

**Issue by devioa** [happy888888/BiliExp#304]
![QQ截图20210312173820](https://user-images.githubusercontent.com/38558065/110921643-c24baf00-8359-11eb-9d24-a528d717e5eb.png)
![QQ截图20210312173806](https://user-images.githubusercontent.com/38558065/110921649-c5469f80-8359-11eb-9973-1b708a149856.png)

我在 gift_filter 里添加了写真和大航海关键词到黑名单，却还是参与了。

**Comment by devioa** [comment]
GitHub Actions，使用 ADVCONFIG 天选时刻

**Comment by devioa** [comment]
![QQ截图20210313084050](https://user-images.githubusercontent.com/38558065/111012683-d46c3280-83d7-11eb-90f8-33fe39361952.png)

可是我这里疯狂复现

**Comment by happy888888** [comment]
将你修改后的配置文件粘贴到这里
```
保持格式
```

**Comment by devioa** [comment]
`{
    "version": "1.2.0",
    "default": {
        "xlive_anchor_task": {
            "enable": true, 
            "anchor_type": [[0, 0], [1, 0]],
            "delay": 0,
            "gift_filter": ["开通","大航海","表情","照片","自拍","代金卷","代金券","船长","优惠券","上船","素颜","加速器","自画像","抵扣卷","抵扣券","写真","王者","舰长"],
            "room_filter": [],
            "danmu_filter": [],
            "price_limit": 0,
            "unfollow": true,
            "follow_group": "天选时刻",
            "clean_group_interval": 0,
            "search_interval": 600,
            "search_areas": [
                {"paid": 1,"aid": 0,"sort": "","ps": 50},
                {"paid": 2,"aid": 0,"sort": "","ps": 50},
                {"paid": 3,"aid": 0,"sort": "","ps": 50},
                {"paid": 6,"aid": 0,"sort": "","ps": 50},
                {"paid": 9,"aid": 0,"sort": "","ps": 50}
            ],
            "timeout": 3600,
            "run_once": false
        }
    },
    "log_file": "BiliExp.log",
    "log_console": true,
    "users": [{
        "cookieDatas": {
            "SESSDATA": "你的cookie",
            "bili_jct": "你的cookie",
            "DedeUserID": "你的uid"
        },
        "tasks": {}
    }]
}`

**Comment by devioa** [comment]
@happy888888 我这配置文件有问题吗

**Comment by happy888888** [comment]
没问题，我从你发出配置文件直到现在挂了几个小时也没发现关键字过滤漏掉的情况

**Comment by devioa** [comment]
> 没问题，我从你发出配置文件直到现在挂了几个小时也没发现关键字过滤漏掉的情况

可我这是什么情况呢，一直不停地参与什么自拍照片写真上舰优惠券……

**Comment by happy888888** [comment]
试试重新覆盖填写一遍ADVCONFIG

**Comment by devioa** [comment]
没用，已经覆盖过好几遍了
