### ISSUE TITLE
好像更新不了代码了

### ISSUE THREAD

**Issue by niuqudechongdong** [happy888888/BiliExp#31]
我之前明明是重新fork了，现在发现还是跟之前一样，不能合并代码。
感觉之后想要更新，都要重新fork一遍了😢

**Comment by happy888888** [comment]
可能这次是因为合并了其他人的pr吧。以后应该不会出现这种情况了。
其实只要原来的代码还能用，就不用急着更新的，我的云函数都一直没更新，打算等登录失效再说，现在账号登陆一次有效期好像变成半年了，正常情况下部署成功后都不用管了。

我记得有一个自动同步仓库的actions的，可以定时和主仓库同步，不过完全没必要。

**Comment by niuqudechongdong** [comment]
我是因为之前部署的清理动态的函数现在发现没成功，现在正好也有腾讯云，想更新一下。
不过，现在算了，等以后登陆失效了再说吧。现在登陆变成那么久了吗？很舒服

**Comment by happy888888** [comment]
![image](https://user-images.githubusercontent.com/67217225/95011867-7ab44f00-0666-11eb-9af3-80b85136b878.png)
这里看cookie的过期时间
