### ISSUE TITLE
  "gift_filter": 这个参数无效啊

### ISSUE THREAD

**Issue by insoxin** [happy888888/BiliExp#315]
"gift_filter": ["照片","自拍","代金卷","船长","优惠券","上船","素颜照","加速器","自画像","抵扣卷","写真","王者","舰长"], 

然后还是中奖了好多优惠券,自拍

https://raw.githubusercontent.com/insoxin/cdn/master/img/0DC31453-38A5-4AB0-9D59-55B684FF2AA1.jpeg

https://github.com/insoxin/cdn/tree/master/img

今天部分中奖的,

**Comment by happy888888** [comment]
https://github.com/happy888888/BiliExp/issues/258

**Comment by insoxin** [comment]
> #258

配置了亲,我把Default branch 版本号 那个改为master,删除其他版本了

**Comment by happy888888** [comment]
https://github.com/happy888888/BiliExp#使用方式仅自动操作脚本部分

**Comment by insoxin** [comment]
> https://github.com/happy888888/BiliExp#使用方式仅自动操作脚本部分

不可以直接改文件吗
