### ISSUE TITLE
自动同步代码的疑问

### ISSUE THREAD

**Issue by FairyWorld** [happy888888/BiliExp#316]
我重新fork了一遍你的仓库，我发现dev1.2.1分支下.github/pull.yml中的配置如下:
```
version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: happy888888:master    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: true    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
```

#### 一些疑问:
1. 你仓库的默认分支是dev1.2.1, 但是pull.yml配置是同步master分支, 如果我fork后默认分支也是dev1.2.1, 我想了解下如果你更新了代码, 我的默认分支还是保留dev1.2.1能不能执行pull.yml, 把你的master同步到我的master上? 
2. 还是说只能同步默认分支, 也就是说我要修改upstream和base指向你的dev1.2.1。
3. 配置中的mergeMethod使用了hardreset会不会覆盖我的commit, 感觉rebase模式更好？之前有试过你提交代码后我之前修改的run_BiliExp.yml的定时器被回滚了, 而且在commit历史记录中消失的现象, 不知道是不是这个原因造成的

**Comment by insoxin** [comment]
你理解没错,只是作者没按github文档标准的来

推荐你一个办法
Default branch 设置master    网址在/settings/branches

pull 作者库到你库,  更新后删除旧库即可

**Comment by happy888888** [comment]
1. dev1.2.1是1.2.1版本的开发分支，完成后会合并到master分支，直接使用master分支就好，dev分支相当于草稿
2. https://github.com/happy888888/BiliExp/issues/187 根据此issue的问题，本项目实现了Actions和代码分离，可以不fork仓库，仅仅复制一份run_BiliExp.yml，配置好账号信息(对应sercrets中 BILICONFIG和ADVCONFIG)和代码来源仓库及分支(对应sercrets中REPOSITORY和REF)就能使用。所以并不需要同步代码到自己的仓库，仓库里只放一个run_BiliExp.yml用来让actions拉取代码和执行代码就行。

**Comment by happy888888** [comment]
> 你理解没错,只是作者没按github文档标准的来
> 
> 推荐你一个办法
> Default branch 设置master 网址在/settings/branches
> 
> pull 作者库到你库, 更新后删除旧库即可

***github文档标准*** 指的啥
