### ISSUE TITLE
请问能否在“部分功能的配置文件推荐写法”里添加docker部署运行的推荐配置

### ISSUE THREAD

**Issue by someash** [happy888888/BiliExp#317]
顺便问一下docker运行大约内存占用情况如何？

**Comment by happy888888** [comment]
内存占用大概40MB左右，内存占用主要与开启的功能和账号数量有关，如果仅仅是单账号只开了投币，观看，分享功能，占用就很低

一般运行签到这种每天只运行一次的任务，直接使用默认配置文件就好，其他功能使用actions版本的配置文件就好，其他的主要就是cron表达式执行周期有区别

**Comment by someash** [comment]
docker设置天选"timeout": 3300的话是不是运行55分钟后，就不参加天选了？

**Comment by happy888888** [comment]
对的，55分钟后就退出了

**Comment by someash** [comment]
那我可以定义86400么

**Comment by happy888888** [comment]
> 那我可以定义86400么

可以

**Comment by someash** [comment]
请问 动态抽奖的"time_quantum"设置为[-43200, 43200]    (action的推荐设置)的话，因为docker默认定时为每天十二点，不会因为这两个时间点的重合出问题吗？

**Comment by someash** [comment]
请问，我看动态抽奖的设定是只转发自己关注的up的动态抽奖吗？
那有没有推荐的跟随转发uid？
顺便我刚刚12点的时候发现容器停止了12个小时并且在中午12点并没有启动，我准备等明天中午看看会不会复现这个问题

**Comment by happy888888** [comment]
要么使用crontab定时启动容器(单次执行完后退出容器)，要么使用容器内部的crontab定时运行(容器永远不退出)

**Comment by someash** [comment]
> 要么使用crontab定时启动容器(单次执行完后退出容器)，要么使用容器内部的crontab定时运行(容器永远不退出)

懂了，也就是说要加-d，我去改一下参数

**Comment by someash** [comment]
![image](https://user-images.githubusercontent.com/32922655/111576657-de34d200-87eb-11eb-9e9e-df8ef85a0a16.png)
加参数后有问题，不生成日志而且根据账户天选参加情况看应该是没有正常启动，卡在某一步不动了

**Comment by happy888888** [comment]
`0 12 * * *`的意思是每天12点运行1次
