### ISSUE TITLE
docker运行出错，大佬帮忙看看日志是什么情况

### ISSUE THREAD

**Issue by jjss520** [happy888888/BiliExp#318]
我手动运行的命令/ # /usr/local/bin/python3 /tmp/BiliExp/BiliExp.py -c /BiliExp/config.json -l /BiliExp/BiliExp.log  
                             
配置加载异常，原因为Expecting property name enclosed in double quotes: line 3 column 25 (char 27)，退出程序
然后就出现了这个提示，好像是要加什么双引号，config.json里面只修改了帐号信息，其它没动

**Comment by jjss520** [comment]
重新删除容器，重新部署，可以了，手动命令，有日志log生成了
重新生成的镜像日志还是有个报错
wget: error getting response: Connection reset by peer | stderr
好像是证书啥的，通过度娘
终端执行
apk update
apk add ca-certificates
update-ca-certificates
apk --no-cache add openssl wget
然后重启容器就能提取代码了，然后执行命令，就在成功跑起来了。

**Comment by happy888888** [comment]
应该是alpine镜像的证书问题
