### ISSUE TITLE
读取活动列表异常

### ISSUE THREAD

**Issue by vay1314** [happy888888/BiliExp#324]
运行环境：docker
日志中这几天一直显示[WARNING]: XXXX: 读取活动列表异常,原因为([Errno 2] No such file or directory: './config/activities.json')
我查看了下/tmp/BiliExp/config下有activities.json这个文件

**Comment by happy888888** [comment]
你可以把配置文件config.json中的`./config/activities.json`改为`/tmp/BiliExp/config/activities.json`，不过本项目提供的转盘抽奖活动列表里的活动很可能是过期的活动，你可以自己寻找转盘抽奖活动并填写activities.json放到与config.json文件同一目录，并把config.json文件中的加载路径改为`/BiliExp/activities.json`, 否则可以关闭转盘抽奖功能
[转盘抽奖活动sid获取方法](https://github.com/happy888888/BiliExp/tree/66cd38b20b7ab5ec68308cc4bda141bea6c2c367/config#activities%E6%B4%BB%E5%8A%A8%E5%88%97%E8%A1%A8%E5%BF%85%E9%80%89)

**Comment by vay1314** [comment]
> 你可以把配置文件config.json中的`./config/activities.json`改为`/tmp/BiliExp/config/activities.json`，不过本项目提供的转盘抽奖活动列表里的活动很可能是过期的活动，你可以自己寻找转盘抽奖活动并填写activities.json放到与config.json文件同一目录，并把config.json文件中的加载路径改为`/BiliExp/activities.json`, 否则可以关闭转盘抽奖功能
> [转盘抽奖活动sid获取方法](https://github.com/happy888888/BiliExp/tree/66cd38b20b7ab5ec68308cc4bda141bea6c2c367/config#activities%E6%B4%BB%E5%8A%A8%E5%88%97%E8%A1%A8%E5%BF%85%E9%80%89)

好的，谢谢
