### ISSUE TITLE
Warning: : id为***的账户cookie失效，跳过此账户后续操作

### ISSUE THREAD

**Issue by EmiyaNiu** [happy888888/BiliExp#332]
![image](https://user-images.githubusercontent.com/76079298/112258610-bb019b00-8ca1-11eb-85e3-72b494d29c35.png)
在g站actions运行，今天出现这种情况

**Comment by happy888888** [comment]
cookie失效了，重新获取一遍，注意浏览器不要退出，一般cookie有效期能达到半年，但是退出账号立即失效

**Comment by EmiyaNiu** [comment]
> cookie失效了，重新获取一遍，注意浏览器不要退出，一般cookie有效期能达到半年，但是退出账号立即失效

重新获取还是显示失效，需要重新登录吗？

**Comment by EmiyaNiu** [comment]
> cookie失效了，重新获取一遍，注意浏览器不要退出，一般cookie有效期能达到半年，但是退出账号立即失效

![image](https://user-images.githubusercontent.com/76079298/112262506-ba203780-8ca8-11eb-9e2d-bdca2de8a9bb.png)

**Comment by EmiyaNiu** [comment]
重新登录了账号，可以了，谢谢大佬！

**Comment by happy888888** [comment]
后续有关于cookie失效的问题转至 #333
