### ISSUE TITLE
cookies失效问题（已确认cookies有效时间）

### ISSUE THREAD

**Issue by zhongfly** [happy888888/BiliExp#333]
![image](https://user-images.githubusercontent.com/11155705/112267066-df647400-8caf-11eb-896c-97ffe9f28c97.png)
上图可以看到cookies有效
但尝试了1.2.0windows版以及最新的1.2.1action运行，均提示失效
退出登录后，重新登录，获取cookies，依然提示失效
修改密码，重新登录，获取cookies，依然提示失效

**Comment by T1573** [comment]
同样的问题，账号全部提示失效

**Comment by happy888888** [comment]
> 同样的问题，账号全部提示失效

你重新在浏览器上退出登录一次试试 参考 #332

**Comment by zhongfly** [comment]
> 你重新在浏览器上退出登录一次试试 参考 #332

尝试重新登录多次，登陆后根据readme中的方法，复制相关的cookies到配置文件中，windows下运行仍提示失效。
（我确认的确是将最新登录后获得的cookies填入配置，cookies绝不是退出登录前的）

**Comment by motao123** [comment]
Github和腾讯云serverless试了，都不行-.-

**Comment by Tongmengjun** [comment]
新账号填的cookie也不行，b站有相应措施了？

**Comment by T1573** [comment]
> > 同样的问题，账号全部提示失效
> 
> 你重新在浏览器上退出登录一次试试 参考 #332

不行，新号也不行

**Comment by dsyo2008** [comment]
一样不行，昨天没问题，现在貌似突然不行

**Comment by Tongmengjun** [comment]
> 一样不行，昨天没问题，现在貌似突然不行

大面积失效了，B站应该检测到了，我的重启服务器和docker，重拉镜像都不行，新号上去也不可以。

**Comment by T1573** [comment]
> > 同样的问题，账号全部提示失效
> 
> 放大缩小#332

这个应该是你这边的问题，隔壁动态抽奖用同样的cookie可以登录，这边就不行，可能b站改了什么接口之类的，我也不太懂，如果有需要的话我可以把群号给你，你们py一下，我还是喜欢用你这个，话说这个平台没私聊功能吗？

**Comment by T1573** [comment]
> > 同样的问题，账号全部提示失效
> 
> 你重新在浏览器上退出登录一次试试 参考 #332

这个应该是你这边的问题，隔壁动态抽奖用同样的cookie可以登录，这边就不行，可能b站改了什么接口之类的，我也不太懂，如果有需要的话我可以把群号给你，你们py一下，我还是喜欢用你这个，话说这个平台没私聊功能吗？

**Comment by Tongmengjun** [comment]
> > > 同样的问题，账号全部提示失效
> > 
> > 
> > 你重新在浏览器上退出登录一次试试 参考 #332
> 
> 这个应该是你这边的问题，隔壁动态抽奖用同样的cookie可以登录，这边就不行，可能b站改了什么接口之类的，我也不太懂，如果有需要的话我可以把群号给你，你们py一下，我还是喜欢用你这个，话说这个平台没私聊功能吗？

兄弟，发个群我进去瞧瞧

**Comment by Silentely** [comment]
重新登录获取cookie也依旧提示失效

**Comment by happy888888** [comment]
已修复，请同步最新代码，release版本将在后续更新

**Comment by zhongfly** [comment]
> 已修复，请同步最新代码，release版本将在后续更新

未修复
19：48分已同步最新代码，56分运行仍提示失效

**Comment by Silentely** [comment]
> > 已修复，请同步最新代码，release版本将在后续更新
> 
> 未修复
> 19：48分已同步最新代码，56分运行仍提示失效

修复了 我刚运行成功，你需要把分支改为dev1.2.1的

**Comment by zhongfly** [comment]
> > > 已修复，请同步最新代码，release版本将在后续更新
> > 
> > 
> > 未修复
> > 19：48分已同步最新代码，56分运行仍提示失效
> 
> 修复了 我刚运行成功，你需要把分支改为dev1.2.1的

![image](https://user-images.githubusercontent.com/11155705/112307152-8c081b00-8cdb-11eb-88ac-a84546dd8069.png)

**Comment by Silentely** [comment]
> > > > 已修复，请同步最新代码，release版本将在后续更新
> > > 
> > > 
> > > 未修复
> > > 19：48分已同步最新代码，56分运行仍提示失效
> > 
> > 
> > 修复了 我刚运行成功，你需要把分支改为dev1.2.1的
> 
> ![image](https://user-images.githubusercontent.com/11155705/112307152-8c081b00-8cdb-11eb-88ac-a84546dd8069.png)

我这边正在运行 没问题。不知道你哪一步错了

**Comment by zhongfly** [comment]
如果拉取最新代码仍失效的，建议再次重新登录获取新的cookies

**Comment by ilhmtfmlt** [comment]
牛逼牛逼，诶嘿嘿作者，牛逼牛逼已经可以了，

**Comment by insoxin** [comment]
新版本改了ua,旧的cookie也可以用,一切正常了

**Comment by Tongmengjun** [comment]
> 新版本改了ua,旧的cookie也可以用,一切正常了

你们是什么拉的？

**Comment by insoxin** [comment]
> > 新版本改了ua,旧的cookie也可以用,一切正常了
> 
> 你们是什么拉的？

pull

**Comment by Tongmengjun** [comment]
> > > 新版本改了ua,旧的cookie也可以用,一切正常了
> > 
> > 
> > 你们是什么拉的？
> 
> pull

用云函数还是本地的？

**Comment by Mark2T** [comment]
docker 运行日志
 [INFO]: 当前程序版本为v1.2.0,配置文件版本为v1.2.1
[WARNING]: id为287076891的账户cookie失效，跳过此账户后续操作
docker 请问如何拉最新的

**Comment by if1y** [comment]
应该是改了接口，旧版本APP已经不能正常显示部分接口内容了

**Comment by insoxin** [comment]
> > > > 新版本改了ua,旧的cookie也可以用,一切正常了
> > > 
> > > 
> > > 你们是什么拉的？
> > 
> > 
> > pull
> 
> 用云函数还是本地的？

github

**Comment by happy888888** [comment]
> docker 运行日志
> [INFO]: 当前程序版本为v1.2.0,配置文件版本为v1.2.1
> [WARNING]: id为287076891的账户cookie失效，跳过此账户后续操作
> docker 请问如何拉最新的

目前已发布1.2.1的release版，docker重新运行就会下载新代码，不需要重新pull镜像

**Comment by youzouzach** [comment]
> > docker 运行日志
> > [INFO]: 当前程序版本为v1.2.0,配置文件版本为v1.2.1
> > [WARNING]: id为287076891的账户cookie失效，跳过此账户后续操作
> > docker 请问如何拉最新的
> 
> 目前已发布1.2.1的release版，docker重新运行就会下载新代码，不需要重新pull镜像

Dev1.21分支并且浏览器退出B站重新登录更换cookie都试过了，依然actions失败
[INFO]: 当前程序版本为v1.2.1,配置文件版本为v1.2.1
Warning: : id为***的账户cookie失效，跳过此账户后续操作

**Comment by happy888888** [comment]
> > > docker 运行日志
> > > [INFO]: 当前程序版本为v1.2.0,配置文件版本为v1.2.1
> > > [WARNING]: id为287076891的账户cookie失效，跳过此账户后续操作
> > > docker 请问如何拉最新的
> > 
> > 
> > 目前已发布1.2.1的release版，docker重新运行就会下载新代码，不需要重新pull镜像
> 
> Dev1.21分支并且浏览器退出B站重新登录更换cookie都试过了，依然actions失败
> [INFO]: 当前程序版本为v1.2.1,配置文件版本为v1.2.1
> Warning: : id为***的账户cookie失效，跳过此账户后续操作

更新到最新代码
