### ISSUE TITLE
昨日更新后使用advconfig与腾讯云函数的疑问

### ISSUE THREAD

**Issue by b9735** [happy888888/BiliExp#340]
secret里配置advconfig复制最新的config没有改动的情况下，运行日志一片空白，且最长运行时间为16min；去除advconfig就正常了

腾讯云函数删除旧版又跑了下action部署函数，结果一直调用失败，报错为

START RequestId:c5b01a3e-a71d-4548-87b7-f895549c03a9

ERROR RequestId:c5b01a3e-a71d-4548-87b7-f895549c03a9 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/BiliExp.py\", line 7, in \u003cmodule\u003e\n    from BiliClient import asyncbili\n  File \"/var/user/BiliClient/__init__.py\", line 12, in \u003cmodule\u003e\n    from .asyncBiliApi import asyncBiliApi as asyncbili #B站接口模块，由aiohttp模块实现异步http请求\n  File \"/var/user/BiliClient/asyncBiliApi.py\", line 2, in \u003cmodule\u003e\n    from aiohttp import ClientSession\n  File \"/var/user/aiohttp/__init__.py\", line 6, in \u003cmodule\u003e\n    from .client import (\n  File \"/var/user/aiohttp/client.py\", line 35, in \u003cmodule\u003e\n    from . import hdrs, http, payload\n  File \"/var/user/aiohttp/http.py\", line 7, in \u003cmodule\u003e\n    from .http_parser import (\n  File \"/var/user/aiohttp/http_parser.py\", line 15, in \u003cmodule\u003e\n    from .helpers import NO_EXTENSIONS, BaseTimerContext\n  File \"/var/user/aiohttp/helpers.py\", line 62, in \u003cmodule\u003e\n    import idna_ssl\nModuleNotFoundError: No module named 'idna_ssl'","statusCode":443}

END RequestId:c5b01a3e-a71d-4548-87b7-f895549c03a9

Report RequestId:c5b01a3e-a71d-4548-87b7-f895549c03a9 Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by happy888888** [comment]
不显示日志是因为配置文件advconfig中没有开启显示，云函数报错参考 #281
