### ISSUE TITLE
[INFO]: 当前程序版本为v1.1.8,配置文件版本为v1.1.8 [WARNING]: id为283906986的账户cookie失效，跳过此账户后续操作 [INFO]: 未定义消息推送

### ISSUE THREAD

**Issue by 18-air** [happy888888/BiliExp#344]
[INFO]: 当前程序版本为v1.1.8,配置文件版本为v1.1.8
[WARNING]: id为**39069***的账户cookie失效，跳过此账户后续操作
[INFO]: 未定义消息推送
突然不能使用了，重新去config.json里面填了cookie还是无法使用。提示一样的内容。

**Comment by happy888888** [comment]
使用最新版，1.2.1版解决了这个问题

**Comment by youzouzach** [comment]
同样问题。提示cookie失效

**Comment by happy888888** [comment]
有关cookie失效问题转至这个issue #333
