### ISSUE TITLE
建议给docker增加手动运行一次命令

### ISSUE THREAD

**Issue by someash** [happy888888/BiliExp#347]
方便定时运行的情况下，替换失效cookie后已经过了定时运行时间的情况下不需要重新部署容器就能运行当天任务

**Comment by happy888888** [comment]
不加-d参数就可以单次运行一次

**Comment by someash** [comment]
> 不加-d参数就可以单次运行一次

我知道。。但是你已经创建了一个定时运行的容器，它提示你ck失效了，你替换完ck，为了今天还能运行，还得重新部署不是很离谱么。。建议还是增加这么个功能，不过不着急。。可以等有空了再加

**Comment by happy888888** [comment]
加了-d参数那个容器就一直跑着，再run一个不带-d参数的容器，相当于同时两个容器在运行不过不带-d参数的容器运行一次后马上退出了

**Comment by happy888888** [comment]
或者进入正在运行的容器手动执行一次
docker exec -it 容器名 /bin/bash
/usr/local/bin/python3 BiliExp.py -c /BiliExp/config.json
