### ISSUE TITLE
linux运行不了

### ISSUE THREAD

**Issue by dmserver** [happy888888/BiliExp#348]
Traceback (most recent call last):
  File "BiliExp.py", line 166, in <module>
  File "BiliExp.py", line 150, in main
  File "asyncio/base_events.py", line 484, in run_until_complete
  File "BiliExp.py", line 78, in start
  File "BiliExp.py", line 78, in <listcomp>
AttributeError: module 'asyncio' has no attribute 'create_task'
[9104] Failed to execute script BiliExp

图片
https://z3.ax1x.com/2021/03/25/6OCYGj.png
https://imgurl.org/delete/8c9c99849e52c957

**Comment by YujiaCheng1996** [comment]
腾讯云函数也是报这个错：
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/BiliExp.py\", line 150, in main\n    loop.run_until_complete(loop.create_task(start(configData)))\n  File \"/var/lang/python3/lib/python3.6/asyncio/base_events.py\", line 466, in run_until_complete\n    return future.result()\n  File \"/var/user/BiliExp.py\", line 78, in start\n    await asyncio.wait([asyncio.create_task(run_user_tasks(user, configData[\"default\"], configData.get(\"http_header\", None))) for user in configData[\"users\"]]) #执行任务\n  File \"/var/user/BiliExp.py\", line 78, in <listcomp>\n    await asyncio.wait([asyncio.create_task(run_user_tasks(user, configData[\"default\"], configData.get(\"http_header\", None))) for user in configData[\"users\"]]) #执行任务\nAttributeError: module 'asyncio' has no attribute 'create_task'","statusCode":430} 
编辑器也提示：
Module 'asyncio' has no 'create_task' member

**Comment by happy888888** [comment]
> 腾讯云函数也是报这个错：
> {"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n File "/var/user/BiliExp.py", line 150, in main\n loop.run_until_complete(loop.create_task(start(configData)))\n File "/var/lang/python3/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete\n return future.result()\n File "/var/user/BiliExp.py", line 78, in start\n await asyncio.wait([asyncio.create_task(run_user_tasks(user, configData["default"], configData.get("http_header", None))) for user in configData["users"]]) #执行任务\n File "/var/user/BiliExp.py", line 78, in \n await asyncio.wait([asyncio.create_task(run_user_tasks(user, configData["default"], configData.get("http_header", None))) for user in configData["users"]]) #执行任务\nAttributeError: module 'asyncio' has no attribute 'create_task'","statusCode":430}
> 编辑器也提示：
> Module 'asyncio' has no 'create_task' member

尝试重新部署

**Comment by YujiaCheng1996** [comment]
> > 腾讯云函数也是报这个错：
> > {"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n File "/var/user/BiliExp.py", line 150, in main\n loop.run_until_complete(loop.create_task(start(configData)))\n File "/var/lang/python3/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete\n return future.result()\n File "/var/user/BiliExp.py", line 78, in start\n await asyncio.wait([asyncio.create_task(run_user_tasks(user, configData["default"], configData.get("http_header", None))) for user in configData["users"]]) #执行任务\n File "/var/user/BiliExp.py", line 78, in \n await asyncio.wait([asyncio.create_task(run_user_tasks(user, configData["default"], configData.get("http_header", None))) for user in configData["users"]]) #执行任务\nAttributeError: module 'asyncio' has no attribute 'create_task'","statusCode":430}
> > 编辑器也提示：
> > Module 'asyncio' has no 'create_task' member
> 
> 已修复，尝试重新部署

新版本部署运行成功
