### ISSUE TITLE
日志一直在输出[WARNING]: HTTPS proxies https://127.0.0.1:1080 are not supported, ignoring

### ISSUE THREAD

**Issue by dantesawake** [happy888888/BiliExp#349]
![QQ截图20210325143907](https://user-images.githubusercontent.com/45136111/112429815-2ae25500-8d78-11eb-9c10-69d92b3c9f00.png)

**Comment by happy888888** [comment]
你开了代理吗？

**Comment by dantesawake** [comment]
> 你开了代理吗？

哦哦感谢
