### ISSUE TITLE
请问如何关闭投币功能

### ISSUE THREAD

**Issue by QwQ-2333** [happy888888/BiliExp#35]
是更改这个吗
rdata = {
       "直播签到": False,
       "投币数量": 0,
       "视频观看": False,
       "视频分享": False,
       "脚本执行前经验": 0,
       "脚本执行前硬币": 0,
       }

**Comment by happy888888** [comment]
第100行
toubi_num = coin_exp_num if coin_num > coin_exp_num else coin_num
改为下面
toubi_num = 0

**Comment by QwQ-2333** [comment]
谢谢

**Comment by QwQ-2333** [comment]
谢谢
