### ISSUE TITLE
ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.

### ISSUE THREAD

**Issue by lancer-wang** [happy888888/BiliExp#350]
ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.

**Comment by lancer-wang** [comment]
github的action,今天刚fork的

**Comment by happy888888** [comment]
不需要安装这个，如果配置了advconfig，可以在配置里把日志显示打开

**Comment by lancer-wang** [comment]
![image](https://user-images.githubusercontent.com/69783837/112439237-d644d700-8d83-11eb-8346-44a2c67398ff.png)

**Comment by lancer-wang** [comment]
没影响是吧,那就好
