### ISSUE TITLE
修改action运行时间的时候提示invalid `cron` attribute

### ISSUE THREAD

**Issue by Jinzikyon** [happy888888/BiliExp#353]
修改.github/workflows/run_BiliExp.yml运行时间后workflows提示如下错误：
.github/workflows/run_BiliExp.yml
invalid `cron` attribute "*/60 0-24 * * *"

同时Workflows左侧菜单run_BiliExp也变成了.github/workflows/run_BiliExp.yml

**Comment by happy888888** [comment]
`0 0-24 * * *`
