### ISSUE TITLE
请遵守开源协议

### ISSUE THREAD

**Issue by acgnhiki** [happy888888/BiliExp#354]
这个项目的小心心请求签名加密代码 https://github.com/happy888888/BiliExp/tree/master/BiliClient/wasm_enc 是从我的项目 https://github.com/acgnhiki/bili-spyder/tree/master/src/bili_spyder 复制的。

请遵守GPLv3开源协议!

**Comment by happy888888** [comment]
已从仓库中删除以上侵权代码，release版中二进制文件和docker镜像自始至终都未曾包含以上侵权代码。

给您带来的困扰表达歉意。
