### ISSUE TITLE
漫画出错

### ISSUE THREAD

**Issue by niuqudechongdong** [happy888888/BiliExp#36]
报错如下{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/mangaTask.py\", line 206, in main\n    manga_task(x)\n  File \"/var/user/mangaTask.py\", line 117, in manga_task\n    now_day = time.localtime(time.time() + 28800 + time.timezone).tm_mday #获取今天是几号\nNameError: name 'time' is not defined}

**Comment by happy888888** [comment]
第三行改成如下，就是忘记导入time了......
import json, logging, time

**Comment by happy888888** [comment]
还有定时启动的时间，如果要积分兑换福利券，记得改为每天12:00启动

**Comment by niuqudechongdong** [comment]
我昨天设成12点01秒，发现不行，在12点03秒重新运行时才兑换到了券。
我兑换券只是为了看一下能不能在券即将过期时，就自动购买漫画。因为积分换的券一个星期就过期了

**Comment by niuqudechongdong** [comment]
脚本已经没问题了😊

**Comment by happy888888** [comment]
那就把时间调为12点过30秒吧，一般抢卷能持续2分钟。

我确实没有测试过即将过期的劵的识别准不准确，因为我没有自己统计时间，用的官方自己的即将过期的数据，官方貌似是2天内还是3天就会把劵标志为即将过期

**Comment by niuqudechongdong** [comment]
昨天我发现我在自己仓库改了漫画filter的参数，在部署时，云函数里的参数还是原来的样子。不知道是不是我操作弄错了

**Comment by happy888888** [comment]
你可以再测试一下合并看会不会出问题

**Comment by niuqudechongdong** [comment]
合并是指更新到最新代码吗？

**Comment by happy888888** [comment]
嗯

**Comment by niuqudechongdong** [comment]
现在可以了

**Comment by niuqudechongdong** [comment]
今天看到这个项目好像实现了用B站的账号密码登陆来获取cookie
https://github.com/BlueskyClouds/Bilibili-Manga

**Comment by happy888888** [comment]
不过是引用https://github.com/Hsury/Bilibili-Toolkit 罢了，你也可以直接拿来用啊
把那个项目的bilibili.py放到本项目下，代码开头加一个
```
import bilibili
```

再把
```
biliapi = BiliWebApi(cookieData)
```
改为
```
bilibili = bilibili.Bilibili()
bilibili.login('你的账户', '你的密码')
biliapi = BiliWebApi(bilibili.get_cookies())
```
所有类似的地方都这样改一下就行了..........

**Comment by niuqudechongdong** [comment]
我是看你很久之前说想实现登陆的😊，看到了就告诉你一下
现在的cookie就挺不错的，我觉得实现登陆可能更容易出错

**Comment by happy888888** [comment]
大号账号分高没问题，小号经常这么登录容易封禁，我就几个号被封禁了点赞投币都不行。。。。

**Comment by niuqudechongdong** [comment]
大号不会出错就行😊
我就弄了一个小号，懒得在弄一个了
