### ISSUE TITLE
提个建议哈  投币时间能不能间隔15秒或者30秒  其他任务也可以适当延长时间 会不会好一些

### ISSUE THREAD

**Issue by LoveForeverBoa** [happy888888/BiliExp#367]
![图片](https://user-images.githubusercontent.com/68955955/112715678-b1d03280-8f1c-11eb-8647-49ce61d1f066.png)

**Comment by Dimlitter** [comment]
我觉得可以在登陆后设置随机延时，在action上部署的朋友们大多在默认同一时间登入执行任务，感觉大批美国ip同一时间登录会被b站一网打尽(
