### ISSUE TITLE
log提示转发动态请求被拦截

### ISSUE THREAD

**Issue by C6Zn30** [happy888888/BiliExp#368]

**Comment by C6Zn30** [comment]
[2021-03-27 18:08:07,065*** [WARNING***: 彼岸花开富贵啊: 评论动态(用户:炎龙说数码,动态id:506359971140484602)失败，信息为请求被拦截
[2021-03-27 18:08:07,390*** [WARNING***: 彼岸花开富贵啊: 转发动态(用户:炎龙说数码,动态id:506359971140484602)失败，信息为请求被拦截
[2021-03-27 18:08:07,597*** [WARNING***: 彼岸花开富贵啊: 点赞动态(用户:炎龙说数码,动态id:506359971140484602)失败，信息为请求被拦截
[2021-03-27 18:08:08,985*** [WARNING***: 顺天从人: 获取动态列表失败，原因为请求被拦截，跳过转发抽奖动态

**Comment by C6Zn30** [comment]
都是在最后面出现的

**Comment by happy888888** [comment]
增大延时，配置中`"delay": [6, 8]`改为`"delay": [15, 20]`，短时间内不要转发大量动态，应该尽量增加延时

**Comment by T1573** [comment]
> 增大延时，配置中`"delay": [6, 8]`改为`"delay": [15, 20]`，短时间内不要转发大量动态，应该尽量增加延时

改到60，120都不行

**Comment by T1573** [comment]
> 增大延时，配置中`"delay": [6, 8]`改为`"delay": [15, 20]`，短时间内不要转发大量动态，应该尽量增加延时

[2021-03-26 01:17:52,191] [WARNING]: 就和: 获取空间动态列表失败，信息为请求被拦截，重试获取
[2021-03-26 01:17:52,223] [WARNING]: 就和: 获取空间动态列表失败，信息为请求被拦截，重试获取
[2021-03-26 01:17:52,270] [WARNING]: 就和: 获取空间动态列表失败，信息为请求被拦截，重试获取
[2021-03-26 01:17:52,270] [WARNING]: 就和: 获取空间动态列表失败次数太多，跳过获取
[2021-03-26 01:17:52,348] [INFO]: 就和: 创建动态(ヘ(￣ω￣ヘ))成功
[2021-03-26 01:19:39,567] [INFO]: 多: 评论动态(用户:伟龙零食俱乐部,动态id:506034919429354124)成功
[2021-03-26 01:19:39,723] [INFO]: 多: 转发动态(用户:伟龙零食俱乐部,动态id:506034919429354124)成功
[2021-03-26 01:19:39,770] [INFO]: 多: 点赞动态(用户:伟龙零食俱乐部,动态id:506034919429354124)成功
[2021-03-26 01:19:39,817] [INFO]: 多: 动态抽奖关注用户343198成功
[2021-03-26 01:19:39,895] [INFO]: 多: 创建动态(喵)成功
[2021-03-26 01:21:35,950] [WARNING]: 多: 获取空间动态列表失败，信息为请求被拦截，重试获取
[2021-03-26 01:21:35,981] [WARNING]: 多: 获取空间动态列表失败，信息为请求被拦截，重试获取
[2021-03-26 01:21:36,012] [WARNING]: 多: 获取空间动态列表失败，信息为请求被拦截，重试获取
[2021-03-26 01:21:36,012] [WARNING]: 多: 获取空间动态列表失败次数太多，跳过获取



像是这种，我调到2—5分钟都没用，转几条后必然会被拦截，b站锁的好像是获取空间次数，就很难受。

**Comment by happy888888** [comment]
> > 增大延时，配置中`"delay": [6, 8]`改为`"delay": [15, 20]`，短时间内不要转发大量动态，应该尽量增加延时
> 
> 改到60，120都不行

那就继续增大，B站限制了一定时间内同一个ip的请求数量，被拦截一定是短时间内同一个ip访问B站的次数过多导致的，这是对ip的限制不是对账号的限制

**Comment by T1573** [comment]
> > > 增大延时，配置中`"delay": [6, 8]`改为`"delay": [15, 20]`，短时间内不要转发大量动态，应该尽量增加延时
> > 
> > 
> > 改到60，120都不行
> 
> 那就继续增大，B站限制了一定时间内同一个ip的请求数量，被拦截一定是短时间内同一个ip访问B站的次数过多导致的，这是对ip的限制不是对账号的限制

你可以参考一下这个作者的代码，我用起来不会频繁https://github.com/shanmite/LotteryAutoScript（10分钟后删）

**Comment by happy888888** [comment]
> > > > 增大延时，配置中`"delay": [6, 8]`改为`"delay": [15, 20]`，短时间内不要转发大量动态，应该尽量增加延时
> > > 
> > > 
> > > 改到60，120都不行
> > 
> > 
> > 那就继续增大，B站限制了一定时间内同一个ip的请求数量，被拦截一定是短时间内同一个ip访问B站的次数过多导致的，这是对ip的限制不是对账号的限制
> 
> 你可以参考一下这个作者的代码，我用起来不会频繁[https://github.com/shanmite/LotteryAutoScript（10分钟后删）](https://github.com/shanmite/LotteryAutoScript%EF%BC%8810%E5%88%86%E9%92%9F%E5%90%8E%E5%88%A0%EF%BC%89)

这个项目应该是降低了请求频率的吧，那你直接使用这个项目进行动态转发，用本项目的其他功能不就行了

**Comment by T1573** [comment]
> 增大延时，配置中`"delay": [6, 8]`改为`"delay": [15, 20]`，短时间内不要转发大量动态，应该尽量增加延时
我还是喜欢整合式的，而且那个项目没有跟转，太容易被钓鱼，转发重复几率也比较高

**Comment by happy888888** [comment]
> > 增大延时，配置中`"delay": [6, 8]`改为`"delay": [15, 20]`，短时间内不要转发大量动态，应该尽量增加延时
> > 我还是喜欢整合式的，而且那个项目没有跟转，太容易被钓鱼，转发重复几率也比较高

本项目也可以通过增加运行次数来减小单次运行搜索的动态数量，比如每隔20分钟运行一次，每次只转发过去20分钟发布的动态，这样就能大大减小单次请求动态的数量，而且Actions和云函数每次运行的ip都是会变的，这样就能进一步减小被拦截的可能性

**Comment by T1573** [comment]
> > > 增大延时，配置中`"delay": [6, 8]`改为`"delay": [15, 20]`，短时间内不要转发大量动态，应该尽量增加延时
> > > 我还是喜欢整合式的，而且那个项目没有跟转，太容易被钓鱼，转发重复几率也比较高
> 
> 本项目也可以通过增加运行次数来减小单次运行搜索的动态数量，比如每隔20分钟运行一次，每次只转发过去20分钟别人发布的动态，这样就能大大减小单次请求动态的数量，也能完全覆盖所有动态，而且Actions和云函数每次运行的ip都是会变的，这样就能进一步减小被拦截的可能性

我也考虑过，但这样消息推送频率就太高了，对于寻找中奖的@消息非常困难，而且观看，转发，直播间签到任务会重复多次运行，导致异常几率加大

**Comment by happy888888** [comment]
以后可能会增加使用一个账号进行动态搜索，其他账号直接使用这个账号的搜索结果来进行转发的模式，由于现在每个账号支持独立的配置，导致每个账号都需要动态搜索，导致请求量剧增，如果不需要独立配置的话，一个账号的转发结果直接给所有账号用，就不用每个账号都进行动态搜索了

**Comment by happy888888** [comment]
> > > > 增大延时，配置中`"delay": [6, 8]`改为`"delay": [15, 20]`，短时间内不要转发大量动态，应该尽量增加延时
> > > > 我还是喜欢整合式的，而且那个项目没有跟转，太容易被钓鱼，转发重复几率也比较高
> > 
> > 
> > 本项目也可以通过增加运行次数来减小单次运行搜索的动态数量，比如每隔20分钟运行一次，每次只转发过去20分钟别人发布的动态，这样就能大大减小单次请求动态的数量，也能完全覆盖所有动态，而且Actions和云函数每次运行的ip都是会变的，这样就能进一步减小被拦截的可能性
> 
> 我也考虑过，但这样消息推送频率就太高了，对于寻找中奖的@消息非常困难，而且观看，转发，直播间签到任务会重复多次运行，导致异常几率加大

观看，转发这些每天只执行一次的任务不建议和动态转发任务一起开启。

短时间内动态转发太多抽奖可能降低中奖率的，尽量要使转发的时间分散，上面说的这种每隔20分钟执行一次的模式也是由于这个原因才增加的，以前都是一次转发一天的

**Comment by T1573** [comment]
> > > > > 增大延时，配置中`"delay": [6, 8]`改为`"delay": [15, 20]`，短时间内不要转发大量动态，应该尽量增加延时
> > > > > 我还是喜欢整合式的，而且那个项目没有跟转，太容易被钓鱼，转发重复几率也比较高
> > > 
> > > 
> > > 本项目也可以通过增加运行次数来减小单次运行搜索的动态数量，比如每隔20分钟运行一次，每次只转发过去20分钟别人发布的动态，这样就能大大减小单次请求动态的数量，也能完全覆盖所有动态，而且Actions和云函数每次运行的ip都是会变的，这样就能进一步减小被拦截的可能性
> > 
> > 
> > 我也考虑过，但这样消息推送频率就太高了，对于寻找中奖的@消息非常困难，而且观看，转发，直播间签到任务会重复多次运行，导致异常几率加大
> 
> 观看，转发这些每天只执行一次的任务不建议和其他需要每隔几十分钟就需要执行一次的任务一起开启。
> 
> 短时间内动态转发太多抽奖可能降低中奖率的，尽量要使转发的时间分散，上面说的这种每隔20分钟执行一次的模式也是由于这个原因才增加的，以前都是一次转发一天的

我转的都是非官方抽奖，都是up自己开奖，大部分都是从评论抽，所以并不影响

**Comment by T1573** [comment]
> 以后可能会增加使用一个账号进行动态搜索，其他账号直接使用这个账号的搜索结果来进行转发的模式，由于现在每个账号支持独立的配置，导致每个账号都需要动态搜索，导致请求量剧增，如果不需要独立配置的话，一个账号的转发结果直接给所有账号用，就不用每个账号都进行动态搜索了

期待新功能

**Comment by T1573** [comment]
> > > > > 增大延时，配置中`"delay": [6, 8]`改为`"delay": [15, 20]`，短时间内不要转发大量动态，应该尽量增加延时
> > > > > 我还是喜欢整合式的，而且那个项目没有跟转，太容易被钓鱼，转发重复几率也比较高
> > > 
> > > 
> > > 本项目也可以通过增加运行次数来减小单次运行搜索的动态数量，比如每隔20分钟运行一次，每次只转发过去20分钟别人发布的动态，这样就能大大减小单次请求动态的数量，也能完全覆盖所有动态，而且Actions和云函数每次运行的ip都是会变的，这样就能进一步减小被拦截的可能性
> > 
> > 
> > 我也考虑过，但这样消息推送频率就太高了，对于寻找中奖的@消息非常困难，而且观看，转发，直播间签到任务会重复多次运行，导致异常几率加大
> 
> 观看，转发这些每天只执行一次的任务不建议和其他需要每隔几十分钟就需要执行一次的任务一起开启。
> 
> 短时间内动态转发太多抽奖可能降低中奖率的，尽量要使转发的时间分散，上面说的这种每隔20分钟执行一次的模式也是由于这个原因才增加的，以前都是一次转发一天的

能否把@信息，私信关键词“恭喜”，“地址”，“领奖”，等消息换个渠道单独推送？比如运行日志我推给方糖，@信息中奖关键词推给Q酱，这样就可以把方糖设为免打扰，防止无意义信息打扰。

**Comment by happy888888** [comment]
> > > > > > 增大延时，配置中`"delay": [6, 8]`改为`"delay": [15, 20]`，短时间内不要转发大量动态，应该尽量增加延时
> > > > > > 我还是喜欢整合式的，而且那个项目没有跟转，太容易被钓鱼，转发重复几率也比较高
> > > > 
> > > > 
> > > > 本项目也可以通过增加运行次数来减小单次运行搜索的动态数量，比如每隔20分钟运行一次，每次只转发过去20分钟别人发布的动态，这样就能大大减小单次请求动态的数量，也能完全覆盖所有动态，而且Actions和云函数每次运行的ip都是会变的，这样就能进一步减小被拦截的可能性
> > > 
> > > 
> > > 我也考虑过，但这样消息推送频率就太高了，对于寻找中奖的@消息非常困难，而且观看，转发，直播间签到任务会重复多次运行，导致异常几率加大
> > 
> > 
> > 观看，转发这些每天只执行一次的任务不建议和其他需要每隔几十分钟就需要执行一次的任务一起开启。
> > 短时间内动态转发太多抽奖可能降低中奖率的，尽量要使转发的时间分散，上面说的这种每隔20分钟执行一次的模式也是由于这个原因才增加的，以前都是一次转发一天的
> 
> 能否把@信息，私信关键词“恭喜”，“地址”，“领奖”，等消息换个渠道单独推送？比如运行日志我推给方糖，@信息中奖关键词推给Q酱，这样就可以把方糖设为免打扰，防止无意义信息打扰。

推荐开两个云函数，一个每隔20分钟运行一次定时转发动态，关闭消息推送，一个一天运行一次负责推送@消息。
`获取空间动态列表失败`是动态清理任务的错误而不是抽奖动态转发的错误，这个任务不适合频繁运行，一般一两个星期执行一次就行。
