### ISSUE TITLE
Secrets里的账号信息应该怎么填啊？

### ISSUE THREAD

**Issue by mxzsw123456** [happy888888/BiliExp#37]
老大你看下我这填的出什么问题了吧，cookie没失效、格式也没填错但就是一直报错不知道为什么

![1](https://user-images.githubusercontent.com/47170569/95649456-0834ea80-0b10-11eb-883d-6d704f8c10fd.png)
![2](https://user-images.githubusercontent.com/47170569/95649460-09feae00-0b10-11eb-85b4-1183b9190f91.png)

**Comment by happy888888** [comment]
![image](https://user-images.githubusercontent.com/67217225/95651082-2f90b500-0b1a-11eb-90f2-ca0963d74dc8.png)

创建一个secrets存放所有账号信息，actions运行时会将内容输出到config/config.json文件，所以直接按照这个文件的格式写就行，本地运行也是直接填写这个文件就行。

**Comment by mxzsw123456** [comment]
> ![image](https://user-images.githubusercontent.com/67217225/95651082-2f90b500-0b1a-11eb-90f2-ca0963d74dc8.png)
> 
> 创建一个secrets存放所有账号信息，actions运行时会将内容输出到config/config.json文件，所以直接按照这个文件的格式写就行，本地运行也是直接填写这个文件就行。

老大我重新fork了一遍按照你图上改的还是出错肿么解？

![3](https://user-images.githubusercontent.com/47170569/95651411-d4ac8d00-0b1c-11eb-8c65-0dddf95f92a7.png)

**Comment by happy888888** [comment]
文件里还有一个email参数是不是写掉了，这个参数可以为空但是不能删掉

**Comment by mxzsw123456** [comment]
> 文件里还有一个email参数是不是写掉了，这个参数可以为空但是不能删掉

真神了填上这个参数果然完美运行了，感谢老大！
