### ISSUE TITLE
docker下拉取问题

### ISSUE THREAD

**Issue by vay1314** [happy888888/BiliExp#374]
感谢辛苦开发
现在使用-d指定了容器一直在运行，在每天12点签到了，但没看到自动同步github上的代码，请教这是还得自己拉取吗？

**Comment by happy888888** [comment]
容器只有在启动时会同步github代码，默认是获取当前最新release版代码

**Comment by vay1314** [comment]
> 容器只有在启动时会同步github代码，默认是获取当前最新release版代码

好吧，那只能想更新时重启容器了。但我发现重启容器后会报如下错误，好像是/tmp下的BiliExp没有删除，新下载的代码压宿包解压后无法命名成功

mv: can't rename '/tmp/happy888888-BiliExp-d64289b': Directory not empty,
mv: can't rename '/tmp/BiliExp': Invalid argument

**Comment by happy888888** [comment]
重启后容器内部文件会自动删除的，每次启动容器都会重新从github上下载代码

**Comment by vay1314** [comment]
> 重启后容器内部文件会自动删除的，每次启动容器都会重新从github上下载代码

不确定是不是容器问题，不过确实重启容器后/tmp目录下不会自动删除。我自行编辑了entrypoint.sh内容，增加了命令rm -rf /tmp/BiliExp 后正常了
