### ISSUE TITLE
机器人up动态发布失败

### ISSUE THREAD

**Issue by bzncu** [happy888888/BiliExp#375]
windows和谷歌colab上都试过了
代码如下
from BiliClient import Dynamic
cookies = { #这里是账号登录后获得的cookie
    "SESSDATA": "029908ca%2C1632625586%2C0a8ed%2A31",
    "bili_jct": "d329e30af3990c2e2e0ee14e8104c9d1",
    }
dynamic = Dynamic(cookies)
content = dynamic.Content()
content.add("测试1")
dynamic.submit() #提交动态
报错
AttributeError                            Traceback (most recent call last)
<ipython-input-14-1d970a63a359> in <module>()
     13 
     14 
---> 15 dynamic.submit() #提交动态

/content/BiliExp/BiliClient/Dynamic.py in submit(self)
    162         '''提交动态'''
    163         if self._content["type"] == 4:
--> 164             ret = self._api.dynamicCreate(**self._content)
    165         elif self._content["type"] == 0:
    166             ret = self._api.dynamicCreateDraw(**self._content)

AttributeError: 'BiliApi' object has no attribute 'dynamicCreate'

**Comment by happy888888** [comment]
更新一下[BiliClient/BiliApi.py](https://github.com/happy888888/BiliExp/blob/master/BiliClient/BiliApi.py)文件

**Comment by bzncu** [comment]
解决了，感谢大大
