### ISSUE TITLE
风纪委员运行失败

### ISSUE THREAD

**Issue by yun-Tong** [happy888888/BiliExp#377]
提示出现
        `风纪委员投票id为1799846的案件失败，信息为：Key: 'ArgVote.Vote' Error:Field validation for 'Vote' failed on the 'min' tag`
经测试手动使用可以投票

**Comment by happy888888** [comment]
是不是修改了风纪投票的配置

**Comment by yun-Tong** [comment]
> 是不是修改了风纪投票的配置

未修改投票设置

**Comment by gy39830** [comment]
> > 是不是修改了风纪投票的配置
> 
> 未修改默认配置
> 但使用的
> ![image](https://user-images.githubusercontent.com/57837738/113092819-55715980-9221-11eb-8daf-d0d9abc73948.png)
> 单独配置风纪委员

你这单独的要填完整参数

**Comment by yun-Tong** [comment]
好的，我知道了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "happy888888/BiliExp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 凌晨2:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [happy888888/BiliExp] 风纪委员运行失败 (#377)





   
是不是修改了风纪投票的配置
  
未修改默认配置
 但使用的
 
 单独配置风纪委员
  
你这单独的要填完整参数

**Comment by happy888888** [comment]
风纪委员参数少了几个，参见我仓库的配置文件
