### ISSUE TITLE
使用actions运行第一遍之后，第二天不会自动运行

### ISSUE THREAD

**Issue by weiai0** [happy888888/BiliExp#378]
使用actions运行第一遍之后，第二天不会自动运行，需要自行启动
![D0Z_~KQRK}@OFCMO%_MO87U](https://user-images.githubusercontent.com/71577227/113246085-d8aab200-92ea-11eb-9b1b-85aaaa412cc8.png)

使用第二种云函数运行到一半失败
![$D{ Q{MAW5566EI_U8 2PS](https://user-images.githubusercontent.com/71577227/113245982-a6995000-92ea-11eb-85a6-ec454b85fae3.png)

**Comment by happy888888** [comment]
actions我看任务是正常的，云函数最多只能执行900s，不推荐开启心跳功能
