### ISSUE TITLE
关于应用途径的一些不成熟思考。

### ISSUE THREAD

**Issue by JunzhouLiu** [happy888888/BiliExp#38]
投币，点赞，这些有可能会被恶意利用，如果有人改写这部分的代码，请求特定av/bv号，就可以实现刷点赞或者刷三连。
建议您添加相关免责的license，做一个风险规避。

**Comment by JunzhouLiu** [comment]
这是一个很实用的工具，建议您除了项目license之外，在readme等位置显眼做个免责声明。

**Comment by happy888888** [comment]
代码只能访问使用者自己的账号啊，刷点赞或者刷三连必须借助别人的账号吧，使用者想改为请求哪个av/bv号是他自己的事吧又改不了我仓库的代码。
