### ISSUE TITLE
使用advconfig出现cookie失效的情况

### ISSUE THREAD

**Issue by typhter** [happy888888/BiliExp#383]
使用的是actions。之前一直是好的，最近更新完biliconfig的cookie后发现一直提示cookie失效，删除advconfig后即可再次使用，但无法自定义配置。是我advconfig内容改错了还是cookie的问题

**Comment by happy888888** [comment]
可能advconfig改错了，可以不使用biliconfig直接在advconfig中填写cookie

**Comment by QwQ-2333** [comment]
我也这样

**Comment by happy888888** [comment]
> 我也这样

更新到最新版代码

**Comment by typhter** [comment]
删去了biliconfig，已经解决，谢谢
