### ISSUE TITLE
docker更改crontab

### ISSUE THREAD

**Issue by daomengRen** [happy888888/BiliExp#386]
docker在运行run的时候添加了crontab,假如后面想更改crontab,除了重新run,还有别的方法吗

**Comment by happy888888** [comment]
你想想看如果你不用docker直接在linux系统跑怎么修改crontab

使用docker只是多了一步进入docker容器的步骤而已，其他的修改crontab文件和重启cron进程的步骤与用不用docker没区别，只是crontab文件和cron进程在docker内部所以多了前面一个步骤

**Comment by daomengRen** [comment]
我修改后,发现重启容器又复原了,

**Comment by happy888888** [comment]
> 我修改后,发现重启容器又复原了,

docker重启容器不保留更改，除非修改镜像，你还是重新run吧
