### ISSUE TITLE
关于《BiliExp-Actions》 “star” 后没有看到“run BiliExp”

### ISSUE THREAD

**Issue by Cronopioss** [happy888888/BiliExp#39]
小白一枚，"Actions"里面没有"run BiliExp"，点一下右上角的"star"，"run BiliExp"就会出现在"Actions"里面——我按照步骤一步步来，也star了，但是没有run biliexp。如下图：
[https://i.loli.net/2020/10/14/lSZciyeIVqYs85T.png](url)
谢谢回复

**Comment by root86** [comment]
不是【设置】选项卡里面的【Actions】项，而是【Actions】选项卡。

**Comment by root86** [comment]
请转至"BiliExp-Actions"分支

**Comment by Cronopioss** [comment]
> 不是【设置】选项卡里面的【Actions】项，而是【Actions】选项卡。

thanks alot

**Comment by happy888888** [comment]
@Cronopioss 是这个Actions
![image](https://user-images.githubusercontent.com/67217225/95938299-2f3f3500-0e0c-11eb-8e22-903e12f03b25.png)
