### ISSUE TITLE
没有云服务器怎么在本地部署

### ISSUE THREAD

**Issue by Assassin-Neo** [happy888888/BiliExp#41]
没有云服务器怎么在本地部署

**Comment by happy888888** [comment]
你是指的BiliExp-Actions分支吗，我才更新了说明文件
下载代码，填写config/config.json文件
安装python3.8(windows直接去官网下载，ubuntu用apt-get install python3安装)和aiohttp(执行命令行pip install aiohttp)
在代码目录执行python BiliExp.py就行了

**Comment by happy888888** [comment]
BiliExp-Actions分支可以直接依靠github Actions执行，不需要本地执行

**Comment by Assassin-Neo** [comment]
> @ Assassin-Neo
> 你是指的BiliExp-Actions分支吗，我才更新了说明文件
> 下载代码，一定要先更新到最新代码，填充config / config.json文件
> 安装python3.8（windows直接去官网下载，ubuntu用apt-get install python3安装）和aiohttp（执行命令行pip install aiohttp）
> 在代码目录执行python BiliExp.py就行了

project clone到本地正常启动python项目就可以是吗？

**Comment by Assassin-Neo** [comment]
> BiliExp-Actions可以直接替换github Actions执行，不需要本地执行，先更新代码到最新
> 需要先去Actions页面启用Actions（绿色按钮），在单击右上角star
> ![图片](https://user-images.githubusercontent.com/67217225/95952280-658bad00-0e2a-11eb-8dc1-672b2b0974f9.png)

不用云服务器git上就可以跑这个项目了吗？

**Comment by happy888888** [comment]
@Assassin-Neo 对的，但是要先配置config.json文件和安装aiohttp依赖库

git上可以直接跑，不需要云服务器，得先去secrets配置账号信息

**Comment by Assassin-Neo** [comment]
> @Assassin-Neo 对的，但是要先配置config.json文件和安装aiohttp依赖库
> 
> git上可以直接跑，不需要云服务器，得先去secrets配置账号信息

![image](https://user-images.githubusercontent.com/42953784/95953686-bef4db80-0e2c-11eb-9476-6b6c9062bf10.png)
我刚刚又重新fork了一下

**Comment by happy888888** [comment]
![image](https://user-images.githubusercontent.com/67217225/95849036-77654580-0d81-11eb-8125-9adcd23ec25a.png)
<div align="center"><img src="https://s1.ax1x.com/2020/09/23/wjM09e.png" width="800" height="450" title="获取cookies示例"></div>

**Comment by Assassin-Neo** [comment]
> _**建议先看**_[readme](https://github.com/happy888888/BiliExp/blob/BiliExp-Actions/README.md)
> 
> ![image](https://user-images.githubusercontent.com/67217225/95849036-77654580-0d81-11eb-8125-9adcd23ec25a.png)
> 
> <img alt="" width="800" height="450" src="https://camo.githubusercontent.com/1d01fb4dbcaf07619be762bb00eab23542ee186f/68747470733a2f2f73312e617831782e636f6d2f323032302f30392f32332f776a4d3039652e706e67">

添加完Secret 运行action 的run就可以了吗
![image](https://user-images.githubusercontent.com/42953784/95957707-9ec81b00-0e32-11eb-9e9b-0edbe4c142f0.png)
![image](https://user-images.githubusercontent.com/42953784/95957793-c323f780-0e32-11eb-8ce1-4268750ceacf.png)

**Comment by happy888888** [comment]
@Assassin-Neo 对的

**Comment by Assassin-Neo** [comment]
> @Assassin-Neo 对的

![image](https://user-images.githubusercontent.com/42953784/95958408-b18f1f80-0e33-11eb-9f1c-6adf701ee5fb.png)
 是因为我没有安装依赖吗

**Comment by happy888888** [comment]
@Assassin-Neo 重新运行actions呢，把现在错误的这个删除了重新运行一次

**Comment by Assassin-Neo** [comment]
> @Assassin-Neo 重新运行actions呢，把现在错误的这个删除了重新运行一次

刚刚重新运行了 还是这 ；添加完Secret 又重新运行了一次

**Comment by happy888888** [comment]
@Assassin-Neo 你貌似运行的还是一个小时前错误的那个，重新运行会增加一个run BiliExp，你还是这有一个小时前那个

**Comment by Assassin-Neo** [comment]
> 重新运行会增加一个run BiliEx

那我再重新更新一下代码

**Comment by happy888888** [comment]
代码是对的，但是不要运行以前那个actions，删掉重新运行，点star或者run workflow都行，不要re-run job

**Comment by Assassin-Neo** [comment]
ok了 删了 重新弄了一下 就 ok 了 现在跑起来了 不报错了  十分感谢。
这个脚本就这样让他运行着，平时需要注意什么？

**Comment by Assassin-Neo** [comment]
![image](https://user-images.githubusercontent.com/42953784/95960670-9a056600-0e36-11eb-81fe-472c62e659ae.png)
 我看你 怎么运行了多个 biliExp 是因为 多个账号吗

**Comment by happy888888** [comment]
每天脚本就会运行一个biliExp，可以查看每次运行的状态，脚本默认每天中午12点启动

默认配置并没有开启脚本全部功能，具体的功能取config文件夹下面看

B站cookie有效期为半年，如果怕失效，可以在config文件夹的config.json文件里设置email或者SCKEY参数，会向邮箱和微信推送每次执行的详细信息

**Comment by Assassin-Neo** [comment]
> config.json

config.json如果我在git中配置这个文件 更新到仓库里 其他人就可以看到我配置的信息了不是

**Comment by happy888888** [comment]
创建一个secrets命名为advconfig，你把这个文件全部复制到这个secrets里面就行了，这样做默认的biliconfig就会失效

**Comment by Assassin-Neo** [comment]
> 创建一个secrets命名为advconfig，你把这个文件全部复制到这个secrets里面就行了，这样做默认的biliconfig就会失效

你说的这个文件指的是config.json？     刚刚填写的secret 只填写了 value部分 。。。。懂了 全复制进去就是把 修改过后的配置替换biliconfig 对吧

**Comment by Assassin-Neo** [comment]
你的readme文件里说了 哈哈哈哈 头一次从GitHub上搞自己想搞的事儿  谢谢咯  我去看看 config.json 有没有我要用到的功能

**Comment by happy888888** [comment]
修改后的config.json文件，全部复制到新建的advconfig中(不是biliconfig，biliconfig是简化的默认配置，配置advconfig后就会失效)

**Comment by Assassin-Neo** [comment]
> 修改后的config.json文件，全部复制到新建的advconfig中(不是biliconfig，biliconfig是简化的默认配置，配置advconfig后就会失效)

你说的advconfig 就是那个secret 如果我不复制config.json 默认执行的就是biliconfig 复制config.json的话 就是把默认配置覆盖 执行我在config.json配置的 是吧 biliconfig 是你程序里默认执行的 刚刚表述的有问题

**Comment by happy888888** [comment]
就是这个意思，biliconfig提供给懒得配置的人，advconfig提供给需要定制程序运行参数的人，因为要简化配置，本质都是动态生成了一个config.json文件，脚本只能从这个文件获取参数，因为还要同时兼容本地运行和云函数运行。

**Comment by Assassin-Neo** [comment]
> 修改后的config.json文件，全部复制到新建的advconfig中(不是biliconfig，biliconfig是简化的默认配置，配置advconfig后就会失效)

换句话说 就现在的config.json文件 我不做任何修改（
             "SESSDATA": "账号SESSDATA",
            "bili_jct": "账号bili_jct",
            "DedeUserID": "账号uid"）
除了这三个必填参数，我全部复制到secrets里面其实执行的还是默认配置  对嘛？

**Comment by happy888888** [comment]
@Assassin-Neo 对的，直接复制还是默认配置，开启具体功能只要把对应功能的false改为true就行，比如漫画客户端签到，把文件里面的```"manga_sign_task": false```改为```"manga_sign_task": true```就行

**Comment by Assassin-Neo** [comment]
> @Assassin-Neo 对的，直接复制还是默认配置，开启具体功能只要把对应功能的false改为true就行，比如漫画客户端签到，把文件里面的`"manga_sign_task": false`改为`"manga_sign_task": true`就行，投币等功能有更具体的参数也需要手动修改，因为有的白嫖党不想投币就不用开

投币的话 投的是哪个视频 这块的逻辑是啥 python 我刚开始看 语法逻辑还不明白

**Comment by happy888888** [comment]
@Assassin-Neo 随机投的，具体投的哪个会消息推送到邮箱或者去B站查硬币记录，主要是增加经验用的，具体的代码在tasks文件夹下面的coin_task.py文件中的def coin_task()函数里面，如果你要增加自己的功能，新建一个xxx.py文件和def xxx()函数放到task文件夹里面，配置文件中增加xxx这个参数，脚本启动时就会调用你写的xxx文件了，当然函数参数必须要符合规范

**Comment by Assassin-Neo** [comment]
> @Assassin-Neo 随机投的，具体投的哪个会消息推送到邮箱或者去B站查硬币记录，主要是增加经验用的，具体的代码在tasks文件夹下面的coin_task.py文件中的def coin_task()函数里面，如果你要增加自己的功能，新建一个xxx.py文件和def xxx()函数放到task文件夹里面，配置文件中增加xxx这个参数，脚本启动时就会调用你写的xxx文件了，当然函数参数必须要符合规范
> 
> 入口文件会根据config.json文件加载tasks文件夹下面的文件中的函数，并把文件中的参数传递到函数中，当然你可以自己编写task.py

要是我有两个账号 一个想投币 另一个不想投币 是不是 需要两个github账号 来运行这个脚本

**Comment by happy888888** [comment]
不用，配置文件default下面的配置只是全局默认配置，每个账户cookieDatas参数下面还有一个tasks参数，把default下面的配置放到tasks参数里面，就可以每个账户定制不同的参数，当tasks参数为空默认使用default下面的配置

**Comment by Assassin-Neo** [comment]
> 不用，配置文件default下面的配置只是全局默认配置，每个账户cookieDatas参数下面还有一个tasks参数，把default下面的配置放到tasks参数里面，就可以每个账户定制不同的参数，当tasks参数为空默认使用default下面的配置

ok了解了 谢谢咯  刚刚把Server酱 和github连接上了 Server酱的测试信息也发过来了 是不是 到时候 这个脚本的信息会自动推送到微信上了

**Comment by happy888888** [comment]
对的，你可以手动运行一次脚本试一试

**Comment by Assassin-Neo** [comment]
> 对的，你可以手动运行一次脚本试一试

重启一下就能收到信息嘛？

**Comment by Assassin-Neo** [comment]
> 对的，你可以手动运行一次脚本试一试

嗯嗯可以的 发送的邮箱是config.json里面配置的  不是默认的

**Comment by Assassin-Neo** [comment]
> 对的，你可以手动运行一次脚本试一试

对了 config.json中 我想替换个别的参数 是直接单个重写 还是 整体覆盖，整体覆盖吧？

**Comment by happy888888** [comment]
secrets中每次修改都是完全重新创建，想改只能重写一边

**Comment by Assassin-Neo** [comment]
> secrets中每次修改都是完全重新创建，想改只能重写一边

我的意思是 输入那三个参数 和投币参数   这样写secret能正常编译执行吗？ 还是说 我需要把整改config.json文件里的内容整体copy过来

**Comment by happy888888** [comment]
整体copy，因为你修改后原来的配置就没了

**Comment by happy888888** [comment]
我差点忘记标题了，你本地部署成功了吗

**Comment by Assassin-Neo** [comment]
> 整体copy，因为你修改后原来的配置就没了

secret两种读取方式：
1、secret的名字随意输入，输入三个参数（
"SESSDATA": "账号SESSDATA",
"bili_jct": "账号bili_jct",
"DedeUserID": "账号uid"）；
2、secret的名字命名为‘advconfig’，自定义功能的话就是把整个config.json输入进去，而不是只写部分功能参数。

**Comment by Assassin-Neo** [comment]
> 我差点忘记标题了，你本地部署成功了吗

我还没搞本地（github能运行脚本还是自动的这个我没想到），我说一下思路 clone下来 安装pip依赖 将用户参数写道config.json文件中 启动脚本（可以加到自动任务中）大概是这个思路吧

**Comment by Assassin-Neo** [comment]
> 我差点忘记标题了，你本地部署成功了吗

要是git上跑着 我本地也跑 b站账号会不会出问题

**Comment by happy888888** [comment]
@Assassin-Neo 不会，因为不涉及登录(我也没做登录，github上有人实现了登录的你可以引用)，频繁异地登录就会有问题。

**Comment by Assassin-Neo** [comment]
> 对的，你可以手动运行一次脚本试一试



> @Assassin-Neo 不会，因为不涉及登录(我也没做登录，github上有人实现了登录的你可以引用)，频繁异地登录就会有问题。

ok 晓得了 谢谢咯
