### ISSUE TITLE
希望增加针对单个up投币20个上限的功能

### ISSUE THREAD

**Issue by gongfuture** [happy888888/BiliExp#415]
因为一个up投满20个可以拿个牌子（笑

**Comment by windCloud152** [comment]
投币模块（代码67-105）

	1.添加模式2 (代码72)
		"do_task": [2,1] 
	2.填入up的 uid(代码88-89)
		2.1 单个up在"up": [],内填入uid
			"up": [],
		2.2 多个up
                        将up放置在特别关注或新增组内
			新增组组名替换特别关注即可
			"groupTag": "特别关注", 
		这两种方法不能同时用
		具体可以查看注释

**Comment by gongfuture** [comment]
@windCloud152 我的意思不是指多个up投币，而是指单个up总计投20个币后就不再向这个up投币，并且不会向已有牌子up投币
B站是有规定，开通粉丝勋章的up下累计投20个币后可以白嫖牌子，我是想能不能增加功能自动获得指定up牌子

**Comment by gongfuture** [comment]
这一段模块我看到了，但没看到类似需求功能的模块

**Comment by start0325** [comment]
投币满20之后手动移除对应的直播间号码就好了。
投币模块主要目的是每天涨经验的，设置上限还怎么涨经验。

**Comment by windCloud152** [comment]
需要投币的up放一个组，已拿硬币的up放一个组，差不多拿到牌子了，将其移开就行了

**Comment by gongfuture** [comment]
@windCloud152  好主意，谢谢
