### ISSUE TITLE
默认功能情况

### ISSUE THREAD

**Issue by Assassin-Neo** [happy888888/BiliExp#45]
以下打勾的都是默认配置支持的是吗？如：自动转发互动抽奖并评论、 参与官方转盘抽奖活动(activity) 转发抽奖是转发已关注的up抽奖，还是全网抽奖（自动关注、转发、评论）
![image](https://user-images.githubusercontent.com/42953784/96095587-63e0e880-0f01-11eb-849b-3af167c77d5f.png)

**Comment by happy888888** [comment]
并不是，默认开启的去config文件夹下面去看
具体配置在文件夹下的config.json里面改

**Comment by happy888888** [comment]
你的意思是默认开启所有功能吗....................

**Comment by lemako** [comment]
我也有这个问题 但是config.json里面只有个十二行的模板啊 是我太小白了吗

**Comment by happy888888** [comment]
@Assassin-Neo 官方转盘抽奖活动(activity) 目前活动是我搜集的存放在activity.json文件里，这个活动目前只能手动搜集。
转发抽奖是转发已经关注的up主的抽奖，本质是扫描1天内你自己的所有动态，发现抽奖就转发，全网的动态没办法搜集，我本来自己也有一个搜集抽奖动态的计划，但也只是搜集了5000个经常发抽奖动态的up主每天从他们的动态中过滤出抽奖，详情参见我的[B站专栏](https://www.bilibili.com/read/cv7968254)

@lemako 你用的代码是半个月前旧版本的，默认就开启了所有功能，你是觉得哪一部分功能没有启用。

**Comment by lemako** [comment]
@happy888888  
因为每天给我的邮箱和server酱推送的消息只有一条

{'直播签到': False, '投币数量': 5, '视频观看': True, '视频分享': True, '脚本执行前经验': 46435, '脚本执行前硬币': 1732}

这样的 

导致我不知道启用了哪些功能 不过我知道自动获取经验 直播签到 以及漫画签到是成功了的

主要是转发互动抽奖这里 不知道是以什么为基准抽奖的 是抽奖结束前吗 还是检测到就转发 那我关注的人转发的抽奖我并没有去抽

**Comment by happy888888** [comment]
@lemako 以前的版本只推送经验消息(主要是消息多了很烦人)，现在的版本会推送所有消息了

抽奖是每运行一次就转发今天中文12点到昨天中午12点之间的动态里面的抽奖，程序一天只运行1次

**Comment by happy888888** [comment]
@Assassin-Neo @lemako 
还有无其他问题或建议，否则此issue将被关闭。

**Comment by kkk8574990** [comment]
老哥能不能搞个只要关注动态含有#互动抽奖#就转发评论
而不是只有互动标签才转发评论吖

**Comment by happy888888** [comment]
@kkk8574990 曾经考虑过，但是这类抽奖只是口头上的不是官方渠道，具体的奖品与开奖时间都没办法直接取得，动态清理也没办法判断这类抽奖是否过期。
目前已考虑增加此功能。

**Comment by happy888888** [comment]
@kkk8574990 已支持转发关键字动态，关键字可以在config/config.json文件里的第21行进行配置，包含关键字就会被转发，同时不要与动态清理配置里的关键字重复否则可能刚转发就被清除。

目前本功能只在BiliExp-Actions分支支持，主分支云函数版未添加

**Comment by happy888888** [comment]
@kkk8574990 紧急修复模块丢失的问题

**Comment by happy888888** [comment]
@kkk8574990 修复B站动态格式导致的异常问题(B站动态格式是真的骚，原创的转发的带评论的不带的都不一样) 10/17 12:54
