### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by happy888888** [happy888888/BiliExp#48]
在这里可以提交对新增功能的建议

**Comment by carey036** [comment]
希望【config】里面增加 ‘是否’ 在 【console】 里面输出日志 以及 把日志输出到【文件】的 的选项

**Comment by happy888888** [comment]
@carey036 不把日志输出到文件和console那输出到哪啊😂，不需要看日志的也不用管这些吧.......

**Comment by carey036** [comment]
直接server酱发送就好了，输出到console不能删除，会被别人看到

**Comment by happy888888** [comment]
好吧，我去加个开关，其实看console是我现在主要排bug的手段，server酱看大量数据不方便，账号和开的功能一多能达到几千行的日志。我还在想怎么精简一下消息推送。

**Comment by carey036** [comment]
server发送的时候，内容加一个.replace("\n","\n\n")，就出现换行了

**Comment by happy888888** [comment]
@carey036 已采纳所有提议，但当有功能报错时不建议关闭控制台输出。

**Comment by Chillily** [comment]
转发抽奖搞个随机评论，可自定义语句的那种！

**Comment by happy888888** [comment]
@Chillily 
目前已实现，并在BiliExp-Actions分支更新，repost与reply参数支持传入字符串数组，也可以像原来那样只填写单个字符串以保持旧版本的兼容。
你好像是使用云函数部署的，把[/tasks/lottery_task.py](https://github.com/happy888888/BiliExp/blob/BiliExp-Actions/tasks/lottery_task.py)文件内容替换，并修改config.json文件就行。

**Comment by Azurlane-a** [comment]
能否整个动态发布P站的图片？发专栏的话，如果后期删成本太大，还要扣硬币。。

**Comment by happy888888** [comment]
@Azurlane-a
这只是一个用python发表专栏的演示，我想的是让其他开发者也能引用我写的发表专栏的库来开发其他脚本
这个脚本除了需要登录B站账号，还需要在里面cookie那里填入你P站登录后的cookie才能正常使用，而且国内用不了

提议我收到了，将在后续实现

**Comment by wangmanv2** [comment]
`风纪委员投票功能`能否根据内容进行情感分析，并通过分析的数值，来做一个自动投票？如果分数比较中立就跟随大流投票？目前好像没用判断功能直接就投票了。情感分析好像也有现成的东西可以直接拿来用。

**Comment by happy888888** [comment]
@wangmanv2 
这玩意儿太高级了，貌似不用建模和机器学习搞不定把

**Comment by gy39830** [comment]
能否添加个账号昵称用于在日志和推送，转盘抽奖若是中奖的话附带活动链接或者使用活动id号来命名会比较便捷一点？

**Comment by happy888888** [comment]
@gy39830 
1.添加自定义昵称 可以实现
2.抽奖的sid号码与活动本身名称没什么关系，参加转盘抽奖只需要sid，你如果发现新活动后完全可以把name字段设置为活动链接比如https://www.bilibili.com/blackboard/activity-dL62mSLVk.html，然后填写sid就行了，这只是一个每天参与抽奖的工具并不能自己寻找抽奖的活动，以前想过去实现扫描自动获取抽奖活动，但是发现B站网页的活动标签和手机app的活动里面都是不全的

**Comment by gy39830** [comment]
> @gy39830
> 1.添加自定义昵称 可以实现
> 2.抽奖的sid号码与活动本身名称没什么关系，参加转盘抽奖只需要sid，你如果发现新活动后完全可以把name字段设置为活动链接比如https://www.bilibili.com/blackboard/activity-dL62mSLVk.html ，然后填写sid就行了，这只是一个每天参与抽奖的工具并不能自己寻找抽奖的活动，以前想过去实现扫描自动获取抽奖活动，但是发现B站网页的活动标签和手机app的活动里面都是不全的

name设置链接的话推送就太淦了

**Comment by happy888888** [comment]
> > @gy39830
> > 1.添加自定义昵称 可以实现
> > 2.抽奖的sid号码与活动本身名称没什么关系，参加转盘抽奖只需要sid，你如果发现新活动后完全可以把name字段设置为活动链接比如https://www.bilibili.com/blackboard/activity-dL62mSLVk.html ，然后填写sid就行了，这只是一个每天参与抽奖的工具并不能自己寻找抽奖的活动，以前想过去实现扫描自动获取抽奖活动，但是发现B站网页的活动标签和手机app的活动里面都是不全的
> 
> name设置链接的话推送就太淦了

比如https://www.bilibili.com/blackboard/activity-dL62mSLVk.html   就只留下activity-dL62mSLVk作为名字

**Comment by ZhangSanMo** [comment]
https://github.com/happy888888/BiliExp/blob/59f28a870256f427f27be417398c6a90a5e16344/BiliExp.py#L65

@happy888888 可以把分号去掉么`;`？或者换成冒号`:`🤣

**Comment by happy888888** [comment]
> https://github.com/happy888888/BiliExp/blob/59f28a870256f427f27be417398c6a90a5e16344/BiliExp.py#L65
> 
> @happy888888 可以把分号去掉么`;`？或者换成冒号`:`🤣

有什么作用吗？ 已收到建议

**Comment by gy39830** [comment]
发弹幕能否检测已点亮的勋章房间不发弹幕？

**Comment by ZhangSanMo** [comment]
> > https://github.com/happy888888/BiliExp/blob/59f28a870256f427f27be417398c6a90a5e16344/BiliExp.py#L65
> > 
> > @happy888888 可以把分号去掉么`;`？或者换成冒号`:`🤣
> 
> 有什么作用吗？ 已收到建议

没有什么作用，就是一般没有见到用分号`;`的hhhh

**Comment by happy888888** [comment]
> > > https://github.com/happy888888/BiliExp/blob/59f28a870256f427f27be417398c6a90a5e16344/BiliExp.py#L65
> > > 
> > > @happy888888 可以把分号去掉么`;`？或者换成冒号`:`🤣
> > 
> > 
> > 有什么作用吗？ 已收到建议
> 
> 没有什么作用，就是一般没有见到用分号`;`的hhhh

已改

**Comment by happy888888** [comment]
> 发弹幕能否检测已点亮的勋章房间不发弹幕？

已修改

**Comment by YM1099** [comment]
希望能通过 Telegram Bot 推送消息

**Comment by windCloud152** [comment]
你好，能否新增一个文档说明一下出现的常规错误的原因及解决方法，比如我现在评论互动抽奖出现信息验证码错误未到，该怎么解决

**Comment by happy888888** [comment]
> 你好，能否新增一个文档说明一下出现的常规错误的原因及解决方法，比如我现在评论互动抽奖出现信息验证码错误未到，该怎么解决

评论速度太快会出现验证码，目前还不能自动填写验证码，可以通过配置文件里的delay参数增加延时降低转发速度

**Comment by windCloud152** [comment]
https://github.com/happy888888/BiliExp/issues/48#issuecomment-731909231
知道了

**Comment by happy888888** [comment]
> 希望能通过 Telegram Bot 推送消息

目前已重写消息推送部分，并已经支持Telegram Bot和其他用户完全自定义消息推送接口

**Comment by YM1099** [comment]
> > 希望能通过 Telegram Bot 推送消息
> 
> 目前已重写消息推送部分，并已经支持Telegram Bot和其他用户完全自定义消息推送接口

十分感谢😊

**Comment by 1076764805** [comment]
希望风纪委员能够设置每天的众裁数量，利用百度语言情感分析，不确定的案件就放弃，一直投票到设定数量就停止，该功能可以用来每个月混到S级拿20个硬币，然后年度奖励又能拿硬币和大会员，希望大佬考虑一下

**Comment by gy39830** [comment]
> 案件就放弃，一直投票到设定数量就停止，该功能可以用来每个月混到S级拿20个硬币，然后年度奖励又能拿硬币和大会员，希望大佬考虑一下

感觉没必要，就目前风纪脚本量，设定了也没有足够的案件，多定几个时间来达到投票量还差不多

**Comment by happy888888** [comment]
> 希望风纪委员能够设置每天的众裁数量，利用百度语言情感分析，不确定的案件就放弃，一直投票到设定数量就停止，该功能可以用来每个月混到S级拿20个硬币，然后年度奖励又能拿硬币和大会员，希望大佬考虑一下

目前默认用百度语言情感分析，可信度不高时投默认(删除)，可信度高时判断消极概率，概率高就投删除票，概率低又接着判断积极概率，概率高就投(否认)，概率低就投默认(删除)

默认投票，百度可信度门限，积极概率门限，消极概率门限可以在配置文件config.json文件中修改

目前配置文件中没有提供案件数量的选项，每次启动都会投完当前所有案件，可通过多次启动来覆盖更多案件

**Comment by TWOBUG31** [comment]
https://github.com/pjy612/Bilibili-LRHH是可以同时在不同直播间挂小心心的，是否可以借鉴提高小心心的获取速度？

**Comment by yun-Tong** [comment]
能增加一个定向送出直播间过期礼物的功能吗

**Comment by happy888888** [comment]
@TWOBUG31  @yun-Tong 
已实现

**Comment by wangmanv2** [comment]
bilibili直播中的天选时刻，有两种方式一种是发送弹幕一种是投送付费道具（当然也可以设置不需要投送道具）。
我看到了软件中有添加直播中的天选时刻，想询问这个功能是只支持发送弹幕，还是两种方式都支持，是否支持设定金额上限？还是只支持免费的呢天选时刻？

**Comment by happy888888** [comment]
> bilibili直播中的天选时刻，有两种方式一种是发送弹幕一种是投送付费道具（当然也可以设置不需要投送道具）。
> 我看到了软件中有添加直播中的天选时刻，想询问这个功能是只支持发送弹幕，还是两种方式都支持，是否支持设定金额上限？还是只支持免费的呢天选时刻？

我几乎不用直播，但是据我的分析这两种方式并没有区别，因为都是点一下"参加"(反正就是这个意思的一个按钮)就行了，当然要花费金瓜子什么的如果数量不够会提示余额不足，数量够会直接花出去

**Comment by yun-Tong** [comment]
在跟踪转发模式中，我只账号a负责增加转发内容，其余账号跟踪转发，但事实上转发内容因为跟踪了，实际最少转发了两次，b站的互动抽奖功能能不能加一个判断，如果已经转发的不需要再重复转发了，比如现在增加了点赞，可以根据是否点赞来决定是否再次转发。

**Comment by happy888888** [comment]
> 在跟踪转发模式中，我只账号a负责增加转发内容，其余账号跟踪转发，但事实上转发内容因为跟踪了，实际最少转发了两次，b站的互动抽奖功能能不能加一个判断，如果已经转发的不需要再重复转发了，比如现在增加了点赞，可以根据是否点赞来决定是否再次转发。

开启跟踪转发，就不会再转发自己的动态，转发的只有另一个账号转发的动态，怎么会重复？

**Comment by yun-Tong** [comment]
https://github.com/happy888888/BiliExp/issues/48#issuecomment-737153202
首先抱歉，上述的我表述的内容是我因为之前一次失误所误以为的错误。
初期因为不熟悉"tasks":{}的使用，以至于a账号转发了a账号的动态，b和c也在跟着转发，以至于三个账号一直在强制转发，大约一百条动态直接转发了一千多条，这次虽然没事这个循环错误，我认为这个流程是b和c跟着a转发一次，直接还要再转发自己关注列表的抽奖，所以想着增加一个已经转发的动态不再转发的功能

**Comment by windCloud152** [comment]
目前这个推荐最多挂几个账号

**Comment by happy888888** [comment]
> 目前这个推荐最多挂几个账号

目前没有设置数量上限，我测试过同时挂40个账号没有问题但没有开启所有功能。
你有多少个账号直接挂上去就行
