### ISSUE TITLE
部署到腾讯云报错

### ISSUE THREAD

**Issue by a449073718** [happy888888/BiliExp#49]
执行摘要测试失败
请求ID	
1053d0ef-2fa7-4167-9f10-2c9e4adee8d4
运行时间	
33ms
计费时间	
33ms
运行内存	
66.91015243530273MB
返回结果

{"errorCode":-1,"errorMessage":"User process exit when running"}

**Comment by happy888888** [comment]
有更详细的日志信息吗

**Comment by a449073718** [comment]
@happy888888 
执行日志

START RequestId: d4024fa1-0df9-416c-89b5-a5cc3937a7b6

Event RequestId: d4024fa1-0df9-416c-89b5-a5cc3937a7b6

日志配置异常，原因为[Errno 30] Read-only file system: '/var/user/BiliExp.log'

配置加载异常，原因为Expecting ',' delimiter: line 21 column 13 (char 507)，退出程序

[ERROR]; 配置加载异常，原因为Expecting ',' delimiter: line 21 column 13 (char 507)，退出程序

 

ERROR RequestId:d4024fa1-0df9-416c-89b5-a5cc3937a7b6 Result:{"errorCode":-1,"errorMessage":"User process exit when running"} 

END RequestId: d4024fa1-0df9-416c-89b5-a5cc3937a7b6

Report RequestId: d4024fa1-0df9-416c-89b5-a5cc3937a7b6 Duration:32ms Memory:128MB MemUsage:58.914062MB

**Comment by happy888888** [comment]
检查config文件夹下config.json文件的20行或者21行，看看末尾(注释前)是否有个逗号，逗号应该在最后(注释前)而不是在引号前面

**Comment by happy888888** [comment]
或者把github文件夹下的config/config.json复制过去重新配置一遍

**Comment by a449073718** [comment]
@happy888888 OK，已经配置好了，

**Comment by happy888888** [comment]
@a449073718 能正常运行吗。

**Comment by a449073718** [comment]
@happy888888 获取风纪委员信息异常，原因为'asyncBiliApi' object has no attribute 'juryInfo'，跳过投票

**Comment by a449073718** [comment]
@happy888888 可以了，

**Comment by happy888888** [comment]
@a449073718 风纪委员投票功能需要把我自己仓库BiliExp-Actions分支下的/models/asyncBiliApi.py替换云函数下的/models/asyncBiliApi.py文件
