### ISSUE TITLE
希望增加自动关注抽奖UP的功能~！

### ISSUE THREAD

**Issue by fmdxx1991** [happy888888/BiliExp#50]

**Comment by happy888888** [comment]
@fmdxx1991 
1. 关注up主异常容易被封禁，我有3个号关注了2000个up主被封
2. 很难判断哪些up主是抽奖up主，总不能把每个up主的动态都遍历一遍看他是否发过抽奖吧
3. 关注过多的up主一定程度会降低中奖率，我在B站专栏发布过统计分析数据

如果你有更好的实现思路，欢迎分享。

**Comment by Assassin-Neo** [comment]
> @fmdxx1991
> 
> 1. 关注up主异常容易被封禁，我有3个号关注了2000个up主被封
> 2. 很难判断哪些up主是抽奖up主，总不能把每个up主的动态都遍历一遍看他是否发过抽奖吧
> 3. 关注过多的up主一定程度会降低中奖率，我在B站专栏发布过统计分析数据
> 
> 如果你有更好的实现思路，欢迎分享。

（B站专栏发布过统计分析数据）可以发个链接吗

**Comment by Assassin-Neo** [comment]
> @fmdxx1991
> 
> 1. 关注up主异常容易被封禁，我有3个号关注了2000个up主被封
> 2. 很难判断哪些up主是抽奖up主，总不能把每个up主的动态都遍历一遍看他是否发过抽奖吧
> 3. 关注过多的up主一定程度会降低中奖率，我在B站专栏发布过统计分析数据
> 
> 如果你有更好的实现思路，欢迎分享。

可以从已关注的up中进行抽奖监控（抽奖的动态和一般的动态是否一样，有没有关键字）

**Comment by happy888888** [comment]
> > @fmdxx1991
> > 
> > 1. 关注up主异常容易被封禁，我有3个号关注了2000个up主被封
> > 2. 很难判断哪些up主是抽奖up主，总不能把每个up主的动态都遍历一遍看他是否发过抽奖吧
> > 3. 关注过多的up主一定程度会降低中奖率，我在B站专栏发布过统计分析数据
> > 
> > 如果你有更好的实现思路，欢迎分享。
> 
> （B站专栏发布过统计分析数据）可以发个链接吗

[专栏链接](https://www.bilibili.com/read/cv7793107)


> > @fmdxx1991
> > 
> > 1. 关注up主异常容易被封禁，我有3个号关注了2000个up主被封
> > 2. 很难判断哪些up主是抽奖up主，总不能把每个up主的动态都遍历一遍看他是否发过抽奖吧
> > 3. 关注过多的up主一定程度会降低中奖率，我在B站专栏发布过统计分析数据
> > 
> > 如果你有更好的实现思路，欢迎分享。
> 
> 可以从已关注的up中进行抽奖监控（抽奖的动态和一般的动态是否一样，有没有关键字）

目前转发抽奖是监视自己的动态(非个人动态，也包含关注的人发布的动态)，获取关注的人关注的人(套娃？)的动态目前不可行，也找不到有哪个页面可以显示这种动态

**Comment by happy888888** [comment]
@Assassin-Neo
@fmdxx1991

关于关注抽奖up主，可以去类似
```
https://t.bilibili.com/topic/name/互动抽奖/feed
https://t.bilibili.com/topic/name/抽奖/feed
https://t.bilibili.com/topic/name/动态抽奖/feed
```
的页面，使用[浏览器辅助脚本](https://github.com/happy888888/BiliExp/tree/master/browser_assist#关注话题页面up主主要是抽奖话题)对这些页面上的up主进行一键关注

**Comment by fmdxx1991** [comment]
@happy888888 是否可以自动关注 每日抽奖专栏 里的抽奖UP主呢？还可以添加一个抽奖结束之后取消关注

**Comment by happy888888** [comment]
@fmdxx1991
自动关注专栏里的up主不难，取消关注就麻烦了，很难区分哪些up主是脚本关注的，哪些是用户自己关注的，抽奖结束取消关注也有问题，有的抽奖up会连发几次抽奖，其中一次抽奖失效就取消关注也会影响其他抽奖。

如果在本地环境运行倒是可以建一个数据库，把脚本关注过的up主储存下来管理，但是云函数是只读环境，没办法保存关注了哪些up主，也就没办法区分哪些up主是用户自己关注的。
