### ISSUE TITLE
自动送礼bug

### ISSUE THREAD

**Issue by gy39830** [happy888888/BiliExp#55]
包裹礼物时间判定错误，永久礼物会被送掉

**Comment by happy888888** [comment]
目前我没有永久礼物可复现此问题，如果你有请访问如下地址
```
https://api.live.bilibili.com/xlive/web-room/v1/gift/bag_list
```
并回复结果

**Comment by gy39830** [comment]
永久值为0

**Comment by happy888888** [comment]
目前增加了判断礼物过期时间，您提供的接口```https://api.live.bilibili.com/gift/v2/gift/m_bag_list```是手机端的吗。

**Comment by lemako** [comment]
也提个bug，也可能是我填写格式有误，在最新版本里的config里的清理失效动态中填入任意中文都会导致action运行失败。

我都删了就运行成功了

**Comment by happy888888** [comment]
> 也提个bug，也可能是我填写格式有误，在最新版本里的config里的清理失效动态中填入任意中文都会导致action运行失败。
> 
> 我都删了就运行成功了

你咋填的，这个黑名单关键字参数写法参照上面抽奖转发的关键字格式，可以提供多个

**Comment by lemako** [comment]
> > 也提个bug，也可能是我填写格式有误，在最新版本里的config里的清理失效动态中填入任意中文都会导致action运行失败。
> > 我都删了就运行成功了
> 
> 你咋填的，这个黑名单关键字参数写法参照上面抽奖转发的关键字格式，可以提供多个

    "clean_dynamic_task": {/* 清理自己的动态，包括过期抽奖，失效动态 */
            "enable": true,
            "black_keywords": [抽奖]/* 黑名单关键字 */

改成任意文字都运行失败。

**Comment by happy888888** [comment]
> > > 也提个bug，也可能是我填写格式有误，在最新版本里的config里的清理失效动态中填入任意中文都会导致action运行失败。
> > > 我都删了就运行成功了
> > 
> > 
> > 你咋填的，这个黑名单关键字参数写法参照上面抽奖转发的关键字格式，可以提供多个
> 
> ```
> "clean_dynamic_task": {/* 清理自己的动态，包括过期抽奖，失效动态 */
>         "enable": true,
>         "black_keywords": [抽奖]/* 黑名单关键字 */
> ```
> 
> 改成任意文字都运行失败。

引号打掉了

**Comment by lemako** [comment]
> > > > 也提个bug，也可能是我填写格式有误，在最新版本里的config里的清理失效动态中填入任意中文都会导致action运行失败。
> > > > 我都删了就运行成功了
> > > 
> > > 
> > > 你咋填的，这个黑名单关键字参数写法参照上面抽奖转发的关键字格式，可以提供多个
> > 
> > 
> > ```
> > "clean_dynamic_task": {/* 清理自己的动态，包括过期抽奖，失效动态 */
> >         "enable": true,
> >         "black_keywords": [抽奖]/* 黑名单关键字 */
> > ```
> > 
> > 
> > 改成任意文字都运行失败。
> 
> 引号打掉了

原来如此 config那里没有提及 我相信和我一样的小白还是有挺多的 希望在config的说明文件夹或者config文件里加两个引号

**Comment by happy888888** [comment]
@lemako 
为了使没有基础的人也能使用提供了简单部署方式的屏蔽了配置文件。
至于json文件的格式不属于本项目需要教授的内容。
