### ISSUE TITLE
action不能自动启动任务

### ISSUE THREAD

**Issue by gangzhilian** [happy888888/BiliExp#56]
脚本可以正常使用，但是每天都需要我手动的在action->run workflow启动，我不知道是不是我在哪部分操作有问题，麻烦帮忙解决一下，谢谢

**Comment by kkk8574990** [comment]
我也是

**Comment by happy888888** [comment]
@gangzhilian  @kkk8574990 
建议修改一下 .github/workflows/run_BiliExp.yml 文件(加一个回车或者删除一行空行)，也就是做一次提交，或者重新fork一遍
这个是github的问题，不是代码的问题，我这里解决不了。

**Comment by 4kerSoo** [comment]
name: run BiliExp

on:
  schedule:
    - cron: 0 4  * * * #中午12:00执行，时间与其他脚本有依赖关系如无必要请勿修改
      
  workflow_dispatch:
  watch:
    types: started

**Comment by happy888888** [comment]
@4kerSoo 这里有什么问题吗

**Comment by gangzhilian** [comment]
可以了，修改文件重新提交一下就可以了
