### ISSUE TITLE
只使用action，多账户如何填写secrets

### ISSUE THREAD

**Issue by 2235283767** [happy888888/BiliExp#59]
大佬，这样填不行耶，该怎么填呀，还有填写一个账号的时候手动可以成功启动，但第二天自己12点启动就失败了
![image](https://user-images.githubusercontent.com/48860182/97772622-ce418c00-1b83-11eb-9bbb-aaac6c2f720d.png)
![image](https://user-images.githubusercontent.com/48860182/97772716-96871400-1b84-11eb-8e5e-b370434b4133.png)

**Comment by happy888888** [comment]
图片没了......
参照config/config.json文件

**Comment by 2235283767** [comment]
> 参照config/config.json文件，简单部署只支持单账号，复杂部署才支持多账号

解决了，谢谢大佬
