### ISSUE TITLE
多账号获取cookies问题

### ISSUE THREAD

**Issue by 2235283767** [happy888888/BiliExp#60]
大佬，chrome怎么获取两个账号的cookies还不失效呀？每次都是登完一个，另一个就失效了。。。。好像浏览器只能存储一个账号的cookies耶，找不到方法解决。

**Comment by 2235283767** [comment]
用两个不同的浏览器解决了。。。。这个问题可以关闭了

**Comment by happy888888** [comment]
你别退出就可以了，退出账号就会失效，直接清除浏览器缓存或者用无痕模式打开浏览器来清除账号

**Comment by happy888888** [comment]
firefox也有多账号模式
