### ISSUE TITLE
机器人UP主错误打不开

### ISSUE THREAD

**Issue by Azurlane-a** [happy888888/BiliExp#61]
\BiliExp-master\机器人up主>python mt.py
Traceback (most recent call last):
  File "mt.py", line 3, in <module>
    from BiliClient import Article
ModuleNotFoundError: No module named 'BiliClient'

pip install BiliClient = =没用。

**Comment by happy888888** [comment]
@Azurlane-a 
这个文件需要复制到上一层目录，也就是BiliExp-master目录，与BiliClient文件夹在同一级目录

**Comment by Azurlane-a** [comment]
> @Azurlane-a
> 这个文件需要复制到上一层目录，也就是BiliExp-master目录，与BiliClient文件夹在同一级目录

复制到BiliExp-master执行出现 No module named 'models'
pip install models = =没用

**Comment by happy888888** [comment]
已修复问题，请更新BiliClient文件夹下的文件

**Comment by Azurlane-a** [comment]
> 已修复问题，请更新BiliClient文件夹下的文件

已顺利打开，然后顺便问个这个，，，，

python mt.py
Traceback (most recent call last):
  File "mt.py", line 11, in <module>
    article = Article(configData["users"][0]["cookieDatas"], "每日美图") #创建B站专栏草稿,并设置标题
  File "C:\Users\Administrator\Desktop\BiliExp-master\BiliClient\Article.py", line 206, in __init__
    bili.login_by_cookie(self, cookieData)
  File "C:\Users\Administrator\Desktop\BiliExp-master\BiliClient\BiliApi.py", line 31, in login_by_cookie
    self._name = ret["data"]["uname"]
NameError: name 'ret' is not defined
Exception ignored in: <bound method Article.__del__ of <BiliClient.Article.Article object at 0x00000220FF907A58>>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\BiliExp-master\BiliClient\Article.py", line 280, in __del__
    bili.close(self)
AttributeError: type object 'BiliApi' has no attribute 'close'

pixiv的Cookie已更换

**Comment by Azurlane-a** [comment]
> 已修复问题，请更新BiliClient文件夹下的文件
启动每日一抽出现 登录验证id为____的账户失败
但启动BiliExp.py可正常运行。

**Comment by happy888888** [comment]
请再次更新BiliClient文件夹下的文件

**Comment by gy39830** [comment]
Exception ignored in: <function BiliApi.__del__ at 0x0000020238932158>
Traceback (most recent call last):
  File "D:\BiliExp-master\BiliClient\BiliApi.py", line 1058, in __del__
    self.close()
  File "D:\BiliExp-master\BiliClient\BiliApi.py", line 1055, in close
    self._session.close()
AttributeError: 'BiliApi' object has no attribute '_session'
登录验证id为******的账户失败，原因为__init__() takes 1 positional argument but 2 were given，跳过后续所有操作
Traceback (most recent call last):
  File "zl.py", line 100, in <module>
    main()
  File "zl.py", line 87, in main
    article = Article(configData["cookieDatas"][0], "互动抽奖系列--每日一抽") #创建B站专栏,并设置标题
KeyError: 'cookieDatas'

**Comment by happy888888** [comment]
> Exception ignored in: <function BiliApi.**del** at 0x0000020238932158>
> Traceback (most recent call last):
> File "D:\BiliExp-master\BiliClient\BiliApi.py", line 1058, in **del**
> self.close()
> File "D:\BiliExp-master\BiliClient\BiliApi.py", line 1055, in close
> self._session.close() AttributeError: 'BiliApi' object has no attribute '_session' 登录验证id为******的账户失败，原因为__init__() takes 1 positional argument but 2 were given，跳过后续所有操作
> Traceback (most recent call last):
> File "zl.py", line 100, in
> main()
> File "zl.py", line 87, in main
> article = Article(configData["cookieDatas"][0], "互动抽奖系列--每日一抽") #创建B站专栏,并设置标题
> KeyError: 'cookieDatas'

已修复相关问题，请更新至最新版代码
