### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by a449073718** [happy888888/BiliExp#68]
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/BiliExp.py\", line 93, in main\n    logfile = configData[\"log_file\"]\nKeyError: 'log_file'"}

**Comment by happy888888** [comment]
config/config.json 文件里面配置项log_file丢失，估计是配置文件的版本不对。

**Comment by a449073718** [comment]
搞定了，就是配置文件版本不对
