### ISSUE TITLE
配置加载异常，原因为Expecting ',' delimiter: line 154 column 27 (char 4506)，退出程序

### ISSUE THREAD

**Issue by qq1091851024** [happy888888/BiliExp#69]
配置加载异常，原因为Expecting ',' delimiter: line 154 column 27 (char 4506)，退出程序

**Comment by happy888888** [comment]
配置secrets错了吧
![](https://user-images.githubusercontent.com/67217225/95849036-77654580-0d81-11eb-8125-9adcd23ec25a.png)

这是默认配置，如果要自定义参数或者使用多账号请看首页说明

**Comment by qq1091851024** [comment]
已解决 谢谢~
