### ISSUE TITLE
一点点小问题？

### ISSUE THREAD

**Issue by wangmanv2** [happy888888/BiliExp#70]
1.是否支持直播获取小心心，或者以后会支持么？
2.以后会支持使用账号和密码自动登录的功能么？之前使用[bili2.0](https://github.com/yjqiang/bili2.0)有类似的功能实现。
3.多账号Actions部署是这样么？
```
SESSDATA（账号1）
bili_jct（账号1）
uid（账号1）
SESSDATA（账号2）
bili_jct（账号2）
uid（账号2）
```

**Comment by happy888888** [comment]
1. 小心心好像需要有粉丝牌并且连续观看才能获得(我不太清楚怎么获得小心心,本人不经常使用直播)，等明确了小心心获得方式后会支持的
2. 账号和密码自动登录我在其他issue也说过，可能导致异地登录的问题。我也确实搞不定B站的登录，非对称加密和验证码识别对我来说太难(当然抄别人代码简单)，所以我不打算实现账号密码登录的功能
3. 多账户需要配置config/config.json文件并复制到secrets `advconfig`，secrets `biliconfig`目前只支持单账户，这两个secrets分别给懂json和不懂json配置文件的人用的

**Comment by wangmanv2** [comment]
OK明白了。
1.如果cookie登录失效的话Server酱会进行提示的吧？
2.但是全部复制json的话会不会有些问题，我打算使用[pull](https://github.com/apps/pull)来对项目进行跟踪更新，如果项目更新了但是advconfig没有相应的更新会不会出现问题（主要看您的向下是否保持兼容，或许能在Server酱的推送中提示，需要更新advconfig？）

**Comment by happy888888** [comment]
1. 会提示
2. 配置文件目前已经比较稳定，一般不会做结构上的改变，功能是依靠配置文件动态加载的，如果新增加功能但是配置文件里面没有这一项那么新功能是不会加载的(在配置文件里面删除一个功能的配置项也能取消这一功能的加载)，在一定程度上能做到向后兼容

**Comment by wangmanv2** [comment]
您好，使用过程中发现了一个问题就是在获取Cookie的时候，可能是我的浏览器是FireFox在获取CooKie的时候，SESSDATA的值好像不会被转译成encodeURIComponent（主要是,不会被转译成%2C）。如果直接复制的话好像会有问题。
![FastStoneEditor1.jpg](https://i.loli.net/2020/11/08/ptVIFyl5n4TodPH.jpg)

**Comment by happy888888** [comment]
我的Firefox没这个问题，你用的是新版吗

![image](https://user-images.githubusercontent.com/67217225/98466277-8072f680-2209-11eb-9b74-0b00e90101b8.png)

**Comment by wangmanv2** [comment]
我才发现存储—Cookie中的SESSDATA是转译后的，但是在网络-任意请求中的请求Cookie是没转移的。我一直以为他们两个是一样的。

**Comment by happy888888** [comment]
@wangmanv2 

> 1.是否支持直播获取小心心，或者以后会支持么？
> 2.以后会支持使用账号和密码自动登录的功能么？之前使用[bili2.0](https://github.com/yjqiang/bili2.0)有类似的功能实现。
> 3.多账号Actions部署是这样么？
> 
> ```
> SESSDATA（账号1）
> bili_jct（账号1）
> uid（账号1）
> SESSDATA（账号2）
> bili_jct（账号2）
> uid（账号2）
> ```

1. 已支持直播挂机获取小心心(仅actions分支，每5分钟获得1个小心心，云函数版本因为运行时间限制不能启用)，不知道可不可以同时挂机多个直播间同时获取小心心，此功能默认不启用需要手动在配置文件中开启
3. 目前已支持这样的多账号配置方式，详情看首页说明

**Comment by wangmanv2** [comment]
> 
> 
> @wangmanv2
> 
> > 1.是否支持直播获取小心心，或者以后会支持么？
> > 2.以后会支持使用账号和密码自动登录的功能么？之前使用[bili2.0](https://github.com/yjqiang/bili2.0)有类似的功能实现。
> > 3.多账号Actions部署是这样么？
> > ```
> > SESSDATA（账号1）
> > bili_jct（账号1）
> > uid（账号1）
> > SESSDATA（账号2）
> > bili_jct（账号2）
> > uid（账号2）
> > ```
> 
>     1. 已支持直播挂机获取小心心(仅actions分支，每5分钟获得1个小心心，云函数版本因为运行时间限制不能启用)，不知道可不可以同时挂机多个直播间同时获取小心心，此功能默认不启用需要手动在配置文件中开启
> 
>     2. 目前已支持这样的多账号配置方式，详情看首页说明

太棒了！！我赶紧推荐给基友们！
