### ISSUE TITLE
大佬，可以添加自动同步上游吗？

### ISSUE THREAD

**Issue by happyzjhao** [happy888888/BiliExp#72]

**Comment by lance52587** [comment]
确实，happy888888可以参考这个添加一个.github/pull.yml文件。

参考地址：
https://github.com/lxk0301/scripts/blob/master/githubAction.md#%E8%87%AA%E5%8A%A8%E5%90%8C%E6%AD%A5fork%E5%90%8E%E7%9A%84%E4%BB%A3%E7%A0%81

**Comment by happy888888** [comment]
@lance52587  @happyzjhao 
有能让用户自己选择是否同步的actions吗，默认开启自动同步可能导致代码版本与配置文件版本不一致导致运行失败的问题，特别是使用Actions运行脚本而且自定义配置文件的人，更新后不手动使用新版本配置文件的人反而会导致运行失败。

**Comment by lance52587** [comment]
参考地址里面的方案B-    3. 将pull.yml里面的`mergeMethod: hardreset`修改为`mergeMethod: merge`保存。
好像就是这个意思？

**Comment by happyzjhao** [comment]
我试了happy888888大大的方案A、B，都失败了 方案C才成功

**Comment by happyzjhao** [comment]
@happy888888 方案C好像可以 不添加变量可以不运行

**Comment by happyzjhao** [comment]
我试了 方案A、B都失败了 只有C才成功

**Comment by happyzjhao** [comment]
A、B好像默认分支名字是master才可以成功

**Comment by happy888888** [comment]
会考虑在云函数分支添加自动同步，Actions分支不行，自定义配置与自动同步无论用什么方法合并都会出问题（只使用默认配置的用户除外），万一下个版本在配置文件添加了新参数，下游自动同步后使用自定义配置的人是没有这个参数的，那么无论是强制覆盖配置文件或者是不覆盖配置文件只更新代码都会导致下一次运行出错。

**Comment by happyzjhao** [comment]
好的 谢谢大佬

**Comment by happy888888** [comment]
> 我试了 方案A、B都失败了 只有C才成功

方案A和B必须改 base和upstream 两个参数才行，这个是上游改变才能同步，不能手动控制

**Comment by happyzjhao** [comment]
我当初改了 但是都不成功 没有反应

**Comment by happyzjhao** [comment]
方案C就成功了 我看lxk0301大大在yml里添加了条件判断 应该算手动决定要不要更新

**Comment by happy888888** [comment]
嗯，后面会加入可手动开关的定时同步方案的

**Comment by happyzjhao** [comment]
好的 谢谢大佬

**Comment by happy888888** [comment]
@lance52587 @happyzjhao
已经添加了同步，但不知道能否正常使用

**Comment by happyzjhao** [comment]
主分支可以正常运行，另一分支不确定是否可行

**Comment by happyzjhao** [comment]
> @lance52587 @happyzjhao
> 已经添加了同步，但不知道能否正常使用

**Comment by happyzjhao** [comment]
@happy888888 大大  经过这么多天的更新 这种同步方法只会同步master分支

**Comment by happy888888** [comment]
> @happy888888 大大 经过这么多天的更新 这种同步方法只会同步master分支

除了run BiliExp这个actions，还有一个auto_merge，你执行一下

**Comment by happyzjhao** [comment]
ok

**Comment by vay1314** [comment]
@happy888888 请教docker会自动同步新代码吗？还是现在能自动同步的只有Actions？

**Comment by happy888888** [comment]
> @happy888888 请教docker会自动同步新代码吗？还是现在能自动同步的只有Actions？

目前只有actions能自动同步
