### ISSUE TITLE
问题求助: 为什么github actions 没有run BiliExp? 只有这两项

### ISSUE THREAD

**Issue by fatFire** [happy888888/BiliExp#74]
![image](https://user-images.githubusercontent.com/33923314/98492092-c499e180-2271-11eb-8baa-aee00467a5be.png)

**Comment by happy888888** [comment]
你没有切换分支，master分支是给云函数用户使用的，切换分支的方法看首页说明

**Comment by fatFire** [comment]
> 你没有切换分支，master分支是给云函数用户使用的，切换分支的方法看首页说明

谢谢大佬
