### ISSUE TITLE
关于小心心获取功能的问题?

### ISSUE THREAD

**Issue by wangmanv2** [happy888888/BiliExp#75]
运行的时候提示`获取直播buvid异常，原因为'asyncBiliApi' object has no attribute 'get_buvid'，跳过直播心跳`
是否意味着要获取小心心的时候需要直播间在线呢？
像目前的Github Actions设置能保证获取到小心心么？（或许能关注bili音悦台？曲线救国？）
PS：运行代码中的用户名可以打码嘛？

**Comment by happy888888** [comment]
少了个文件，目前已修复该问题
获取小心心的时候需要直播间在线，程序会自动搜索在线且有勋章的直播间(未满足条件则退出)，也支持手动指定

**Comment by wangmanv2** [comment]
感谢，运行了几次没有发现任何问题，太棒了。

既然引出了小心心，那么还有另外一个需求，就是使用获得小心心去激活已经佩戴但是已经灰掉的直播牌子，不知道这个能否实现呢？

即：在小心心准备到期时候，先检测一下已经佩戴但是已经灰掉的直播牌子，先给每个送一个小心心，然后再将剩余的送给设定的用户。

**Comment by happy888888** [comment]
怎么得到已经灰掉的牌子呢，我现在没有，没办法判断
目前礼物是随机送的，需要添加一个手动指定的功能吗

**Comment by gy39830** [comment]
由于数据过于难看，破站已经改成有牌子的房间每日首次发弹幕自动点亮并活动100亲密度了，所以只要遍历勋章房间发条弹幕就好了

**Comment by wangmanv2** [comment]
这样嘛？很久没看了，也就是说只要做到每日每个牌子直播间遍历一遍随便发一些就可以了？

**Comment by happy888888** [comment]
不怎么用直播，发弹幕需要主播在线吗

**Comment by wangmanv2** [comment]
刚才尝试了一下，不需要主播在线也能获取到每日亲密度。

**Comment by happy888888** [comment]
> 刚才尝试了一下，不需要主播在线也能获取到每日亲密度。

已加入每次运行向所有有牌子的房间发送一次自定义消息，没定义消息则不发送

**Comment by wangmanv2** [comment]
好的，测试以后没啥问题，那我关闭了。
