### ISSUE TITLE
配置那个文件使用部分功能?

### ISSUE THREAD

**Issue by FairyWorld** [happy888888/BiliExp#79]
配置那个文件使用部分功能? 目前大号想要不开启部分功能, 如投币或者发动态抽奖之类的, 小号需要开启全部功能该如何配置?

**Comment by happy888888** [comment]
如果一个配置项同时在default和task里出现，会以task作为优先配置。在default里面的配置项下面的enable设置为true，在要关闭的用户的task下面复制这个配置项，enable设置为false就好了
