### ISSUE TITLE
使用复杂配置运行不了

### ISSUE THREAD

**Issue by FairyWorld** [happy888888/BiliExp#80]
auto_merge.yml不管启动第5,6行还是关闭都会报错

![image](https://user-images.githubusercontent.com/32956212/99153811-d520e080-26e5-11eb-9639-d62e180427a5.png)
![image](https://user-images.githubusercontent.com/32956212/99153819-dce08500-26e5-11eb-86df-ec47729dd2b9.png)

**Comment by happy888888** [comment]
仓库里面的配置文件被你删除了？
应该是json格式不对

**Comment by happy888888** [comment]
仓库里面的配置文件不能删除，这是模板文件，需要靠这个来生成配置。
一定要确定配置文件除了注释外是符合json规范的，不要把什么引号逗号的漏掉了

**Comment by happy888888** [comment]
我看了你第一次对仓库的修改，config.json文件第276行末尾多了一个逗号需要删掉，估计advconfig里面也是这个错误，但是仓库里的config.json文件必须存在，这个文件是不需要任何修改的

**Comment by FairyWorld** [comment]
> 仓库里面的配置文件被你删除了？
> 应该是json格式不对

谢谢了, 我记得json文件好像没有注释语法，我还以为py的json比较特殊可以通过/**/注释, 原来这个文件当做模板来用，现在应该上车成功了, 直播小星星好像要挺久的

**Comment by happy888888** [comment]
> > 仓库里面的配置文件被你删除了？
> > 应该是json格式不对
> 
> 谢谢了, 我记得json文件好像没有注释语法，我还以为py的json比较特殊可以通过/**/注释, 原来这个文件当做模板来用，现在应该上车成功了, 直播小星星好像要挺久的

json确实不支持注释，在程序执行前，secrets转配置文件时实际上把所有注释都给删除了。
小心心需要在拥有粉丝牌的直播间里面呆着，每5分钟获得一个，你可以去直播的背包里面看是否每5分钟增加一个小星星

**Comment by FairyWorld** [comment]
> > > 仓库里面的配置文件被你删除了？
> > > 应该是json格式不对
> > 
> > 
> > 谢谢了, 我记得json文件好像没有注释语法，我还以为py的json比较特殊可以通过/**/注释, 原来这个文件当做模板来用，现在应该上车成功了, 直播小星星好像要挺久的
> 
> json确实不支持注释，在程序执行前，secrets转配置文件时实际上把所有注释都给删除了。
> 小心心需要在拥有粉丝牌的直播间里面呆着，每5分钟获得一个，你可以去直播的背包里面看是否每5分钟增加一个小星星

感觉有点问题, 我再多测几天吧. 昨晚通宵的时候已经挂到了24个小心心并且已经送出去了, 今天9点多执行action, 还在获取小心心并且在日志里显示发送小心心, 昨晚应该获取完了并发送, 现在应该获取不了并且无法发送和日志显示的不一样
![image](https://user-images.githubusercontent.com/32956212/99161442-5fd8fe00-272d-11eb-9ecf-07e95bd5ca08.png)

**Comment by happy888888** [comment]
> > > > 仓库里面的配置文件被你删除了？
> > > > 应该是json格式不对
> > > 
> > > 
> > > 谢谢了, 我记得json文件好像没有注释语法，我还以为py的json比较特殊可以通过/**/注释, 原来这个文件当做模板来用，现在应该上车成功了, 直播小星星好像要挺久的
> > 
> > 
> > json确实不支持注释，在程序执行前，secrets转配置文件时实际上把所有注释都给删除了。
> > 小心心需要在拥有粉丝牌的直播间里面呆着，每5分钟获得一个，你可以去直播的背包里面看是否每5分钟增加一个小星星
> 
> 感觉有点问题, 我再多测几天吧. 昨晚通宵的时候已经挂到了24个小心心并且已经送出去了, 今天9点多执行action, 还在获取小心心并且在日志里显示发送小心心, 昨晚应该获取完了并发送, 现在应该获取不了并且无法发送和日志显示的不一样
> ![image](https://user-images.githubusercontent.com/32956212/99161442-5fd8fe00-272d-11eb-9ecf-07e95bd5ca08.png)

小心心不是获取的，是把直播挂机在哪里自动就有的。这是一个直播挂机的功能不是一个获取小心心的功能，只是只要挂机B站就给小心心
