### ISSUE TITLE
弹幕

### ISSUE THREAD

**Issue by gy39830** [happy888888/BiliExp#81]
看了一下日志，虽然发送弹幕成功，但只有第一条是生效的，可能弹幕发送太快？

**Comment by happy888888** [comment]
发送太快官方不会返回操作太频繁的提示吗，既然成功应该就是没问题的吧，我去检查一下

**Comment by wangmanv2** [comment]
+1 我也发现了一样的问题

**Comment by gy39830** [comment]
> 发送太快官方不会返回操作太频繁的提示吗，既然成功应该就是没问题的吧，我去检查一下

去直播间看了也没设定的发送弹幕，只有第一条发送的有，所以是没发送成功

**Comment by happy888888** [comment]
但是日志有每个房间的成功消息是吗？？

**Comment by gy39830** [comment]
> 但是日志有每个房间的成功消息是吗？？

是的，以前活动房间有过发弹幕的任务，也是一直发送成功实际没成功的，需要多次发送

**Comment by happy888888** [comment]
那怎么才能判断发送成功呢

**Comment by gy39830** [comment]
![image](https://user-images.githubusercontent.com/60922309/99224539-795b7200-2821-11eb-9fb3-80249b800518.png)
加个msg的判断，不为空就是失败的，1s的都是没发送成功的

**Comment by happy888888** [comment]
出现`msg in 1s`后重新发送会出现`msg repeat`

**Comment by gy39830** [comment]
> 出现`msg in 1s`后重新发送会出现`msg repeat`
> 
> 现在增加了重试3次，每次延时3秒

无论成功与否都等待3秒会比较好，成功率高，错误日志也会减少

**Comment by happy888888** [comment]
> > 出现`msg in 1s`后重新发送会出现`msg repeat`
> > 现在增加了重试3次，每次延时3秒
> 
> 无论成功与否都等待3秒会比较好，成功率高，错误日志也会减少

已加入等待，就是不知道这个接口是限制的是单个用户的发送速度还是单个ip的发送速度

**Comment by gy39830** [comment]
> > > 出现`msg in 1s`后重新发送会出现`msg repeat`
> > > 现在增加了重试3次，每次延时3秒
> > 
> > 
> > 无论成功与否都等待3秒会比较好，成功率高，错误日志也会减少
> 
> 已加入等待，就是不知道这个接口是限制的是单个用户的发送速度还是单个ip的发送速度

retry = 3
            while retry:
                try:
                    await asyncio.sleep(3)
                    ret = await biliapi.xliveMsgSend(roominfo[0], send_msg)
                except Exception as e:
                    logging.warning(f'{biliapi.name};点亮: {roominfo[0]}房间发弹幕异常({str(e)})')
                    retry -= 1
                else:
                    if ret["code"] == 0 and ret["message"] == '':
                        logging.info(f'{biliapi.name};点亮: {roominfo[0]}房间发送弹幕成功')
                        break
                    else:
                        logging.warning(f'{biliapi.name};点亮: {roominfo[0]}房间发送弹幕失败({ret["message"]}) 重试')
                        retry -= 1
![image](https://user-images.githubusercontent.com/60922309/99267303-bc880600-285e-11eb-95ee-a5c1775d13d9.png)
效果不错，只要不是房间屏蔽词或非法内容都能成功
