### ISSUE TITLE
投币失败，显示超过投币数量

### ISSUE THREAD

**Issue by fengguowhen** [happy888888/BiliExp#82]
查b站硬币管理发现并没有投币，config数量为5

**Comment by fengguowhen** [comment]
![2020-11-16 12-31-54](https://user-images.githubusercontent.com/62593111/99213146-cd595d00-2807-11eb-8013-fa872da1ae29.png)
![2020-11-16 12-32-8](https://user-images.githubusercontent.com/62593111/99213149-cfbbb700-2807-11eb-91c2-3fad41656991.png)

**Comment by fengguowhen** [comment]
![2020-11-16 12-33-16](https://user-images.githubusercontent.com/62593111/99213191-f0840c80-2807-11eb-9973-e6754ef0cc4a.png)

**Comment by happy888888** [comment]
看了一下你的日志，投的那几个视频都曾经投过币了，一个视频最多投2个币

建议修改config/config.json文件第32行`"do_task": [3]`修改为`"do_task": [1]`使用随机抽视频投币

**Comment by fengguowhen** [comment]
> @fengguowhen
> 看了一下你的日志，投的那几个视频都曾经投过币了，一个视频最多投2个币
> 
> 建议修改config/config.json文件第32行`"do_task": [3]`修改为`"do_task": [1]`使用随机抽视频投币。如果要优先投关注的人，也可以改成`do_task": [2]`

谢谢，已解决
