### ISSUE TITLE
加入直播抽奖后需要注意的一点

### ISSUE THREAD

**Issue by yun-Tong** [happy888888/BiliExp#86]
这次更新后加入直播抽奖，但是我在使用一次后，在第二天自动使用脚本时，邮件提示获取cookie失败，账号出现风控，再次登陆需要手机验证码，希望想开通这一功能的朋友注意这一点
ps.我是连开三个账号，一个账号开通这个功能可能会有所不同
![image](https://user-images.githubusercontent.com/57837738/99394820-77c1a500-291a-11eb-962d-5241317159a2.png)

**Comment by happy888888** [comment]
三个账号同时出现这样的情况吗？

**Comment by yun-Tong** [comment]
对的，三个账号同时出现这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "星辰"<notifications@github.com&gt;; 
发送时间: 2020年11月17日(星期二) 晚上9:36
收件人: "happy888888/BiliExp"<BiliExp@noreply.github.com&gt;; 
抄送: "云彤"<1640516241@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [happy888888/BiliExp] 加入直播抽奖后需要注意的一点 (#86)





 
三个账号同时出现这样的情况吗？

**Comment by happy888888** [comment]
暂时先关闭这个功能吧，可能B站对这种没有房间观看记录但是参与直播抽奖的行为比较敏感，还有actions在国外可能ip地址也比较敏感，后期增加进入房间事件的模拟和直播间心跳的模拟试试能不能规避这个问题
