### ISSUE TITLE
是否考虑将activity_task从config中分离出来？

### ISSUE THREAD

**Issue by ZhangSanMo** [happy888888/BiliExp#89]
**B站转盘抽奖活动**有时候需要更新，而这个与用户倾向没关系吧，~假定大家都想参加~，所以是否可以将这部分分离出来嘞？

~主要是更新的时候懒得去更新Github的Secret😂~

**Comment by happy888888** [comment]
目前发现有人是关闭了这个转盘抽奖功能或者自己增加或删除了部分活动的。

除了在activity_task下的activities参数中可以指定活动，额外增加一个file参数可以指定外部文件路径，加载外部文件里的转盘抽奖活动，这样可以吗

**Comment by ZhangSanMo** [comment]
**可以啊**，所以优先级上是 命令行/Secret 中的config和activity_task > 自带的config和activity_task文件；
***
~但是这样显得有点特别，是否可以弄成命令行/Secret的config> 自带的config，但是采用的方式不是**替代**（现在好像是替代的），而是采用**覆写**的方式。~

~但是，又会带来另一问题，覆写到哪一层级的问题😂，这样用起来又会不直观。~

~所以，如果整成**两套config**，一套default，一套user。在程序中判断应该取哪一套中的参数（如果user有，优先取user），这样避免在json层面上的合并给用户带来更多的思考负担。这样user需要写的~
***
才发现已经实现😂，所以可以将default和user参数分为两个文件么？这样作者你负责必要的default，使用者负责更新user部分，当作者你更新的时候也不会影响到使用者，同时享受到更新。

单独处理activity_task这样就不需要了，在user里面自己改写就OK了~

**Comment by happy888888** [comment]
目前是采用的user参数里的task参数大于default参数，task参数里面没有的参数用default代替，task里有的参数只能采用task里的。

default和user参数分为两个文件改动太大了，目前的配置文件是保持向后兼容的，即更新后的程序兼容老版本配置文件，以保持下游自动合并更新后能正常运行。

为了有些不会配置json文件的人，现在有三个secrets，biliconfig(存放多用户cookie)，push_message(存放邮件和微信SCKEY用于推送)，advconfig(存放配置文件，有前两个secrets以前两个为准，没有以本secrets为准)

除非有比现在配置文件和secrets更好的方案，否则不能更改配置文件的主要结构。如果你有更好的配置方案可以提供，但必须是全套方案。

最开始activity确实是单独的一个文件，config里面只有一个开关，之所以后面合并到config文件里是为了保持所有task模块的一致性和允许用户自己配置想参加的活动，我这里并不会很及时地更新，活动列表也不是本项目维护的范围，本人也找不全。

**Comment by happy888888** [comment]
@ZhangSanMo  已将活动列表分离成单独文件
