### ISSUE TITLE
阿里云账号的ACCOUNT_ID，ACCESS_KEY_ID，ACCESS_KEY_SECRET如何获得？

### ISSUE THREAD

**Issue by 2498966969** [happy888888/BiliExp#9]
如题

**Comment by happy888888** [comment]
开通云函数
https://www.aliyun.com/product/fc

查看账号id
https://account.console.aliyun.com/

创建ACCESS_KEY_ID和ACCESS_KEY_SECRET
https://ram.console.aliyun.com/manage/ak
不要用子账户
