### ISSUE TITLE
日志配置异常，原因为[Errno 30] Read-only file system: '/var/user/BiliExp.log'

### ISSUE THREAD

**Issue by kuilei0926** [happy888888/BiliExp#90]
![QQ截图20201119162456](https://user-images.githubusercontent.com/17094610/99640597-13baf000-2a84-11eb-9d40-1e488f20ceaa.png)

**Comment by happy888888** [comment]
日志配置异常没事，云函数环境是只读的，不能写出日志文件。

后面的异常是动态转发抽奖产生的，官方接口返回的数据中没有cards参数，可能是动态已经被枚举完了，目前已解决这个异常。
