### ISSUE TITLE
获取视频信息异常

### ISSUE THREAD

**Issue by 1244919208** [happy888888/BiliExp#92]
获取B站视频信息异常，原因为'count'，跳过投币
换了cookie也没用

**Comment by happy888888** [comment]
你是设置了给关注分组的up主投币吗

**Comment by 1244919208** [comment]
是的,是投币失败次数过多被拉黑了吗

**Comment by happy888888** [comment]
你访问一下这个网址呢`https://api.bilibili.com/x/relation/tags`

**Comment by 1244919208** [comment]
{"code":0,"message":"0","ttl":1,"data":[{"tagid":-10,"name":"特别关注","count":1,"tip":"第一时间收到该分组下用户更新稿件的通知"},{"tagid":0,"name":"默认分组","count":97,"tip":""}]}

**Comment by happy888888** [comment]
已修复此问题
