### ISSUE TITLE
直播挂机获取小心心问题

### ISSUE THREAD

**Issue by Lincest** [happy888888/BiliExp#93]
小心心获取设置为24, 前两次运行正常, 之后:

- actions运行20分钟左右会退出, log显示已经获得了24个小心心, 但实际只有4个 (手动指定直播间id)

-  会显示在当前并未开播的直播间挂机 (未手动指定直播间id的情况下)

![image](https://user-images.githubusercontent.com/43769667/99891137-9d93d480-2ca1-11eb-84e8-97ae682e0207.png)

**Comment by happy888888** [comment]
这是心跳次数不是获得的小心心数量，小心心是每5分钟获得一个，但是心跳不一定是每5分钟一次(每次的间隔由官方指定)，运行20分钟当然只有4个小心心，你加大心跳次数就行

**Comment by happy888888** [comment]
最新版本已支持通过时间来控制心跳次数，确保心跳到足够的时间
