### ISSUE TITLE
转发抽奖动态的小建议

### ISSUE THREAD

**Issue by co-ai** [happy888888/BiliExp#94]
有些抽奖需要带话题
这个可不可以实现,把动态里面除了#互动抽奖#以外的话题加到转发内容里边

**Comment by happy888888** [comment]
意思是原动态是带话题的，转发到字迹的动态也要带话题？

**Comment by co-ai** [comment]
![TIM截图20201123122131](https://user-images.githubusercontent.com/44060602/99929026-972b5880-2d86-11eb-9d4c-b827db2f0727.png)
你看这种就是

**Comment by happy888888** [comment]
已经添加转发附带标签和点赞
