### ISSUE TITLE
直播小心心部分发送失败

### ISSUE THREAD

**Issue by FairyWorld** [happy888888/BiliExp#96]
#### 异常:
我配置了两个账号, 而且把执行时间改成了每天12, 13, 14点等各执行一次, 防止风纪委员没有投完票, 理论上一天至少执行了很多轮代码, 第一个账号的直播小心心基本发送完毕, 但是第二个账号有部分小心心还保留在背包里, 只有部分发送成功

#### 感谢:
11.23号收到动物主题活动中奖通知, 一个月会员到手
![image](https://user-images.githubusercontent.com/32956212/100035861-08781380-2e3a-11eb-9dfe-e07aaadcd257.png)

**Comment by FairyWorld** [comment]
顺便问下腾讯云函数和github的action哪个好一点? 之前只知道腾讯云函数, 后来看到问题反馈里写到github运行时用国外的ip, 不知道哪个好用一点?

**Comment by happy888888** [comment]
只有背包中2天内过期的礼物才会被送出。

腾讯云函数确实在国内的，如果腾讯云函数有你所在地区当然是最好的，但是云函数每次运行最大时间为900秒，如果要开启花费时间较长的功能需要注意。小心心获取5分钟一个，只与时间有关系与心跳个数没有关系

actions在国外，但是每次可运行6小时，而且完全免费，腾讯云函数超过免费额度是收费的，不建议用来运行花费时间长的任务。
