### ISSUE TITLE
转发动态出错

### ISSUE THREAD

**Issue by co-ai** [happy888888/BiliExp#97]
![TIM截图20201124140401](https://user-images.githubusercontent.com/44060602/100055000-1770bd00-2e5e-11eb-8607-759c4aaac932.png)
转发能成功七八条,之后的都是失败,可以考虑一下加长操作之间的时延

**Comment by happy888888** [comment]
简单部署里不提供转发时延的选项，请使用复杂部署方式来精确调整运行参数，通过config.json配置文件能调整转发延时。
