### ISSUE TITLE
Actions部署失败

### ISSUE THREAD

**Issue by 2498966969** [happy888888/BiliExp#99]
![QQ截图20201128202111](https://user-images.githubusercontent.com/57282666/100515495-98f68100-31b7-11eb-943c-74f96ca8bef2.png)
![QQ截图20201128201913](https://user-images.githubusercontent.com/57282666/100515498-9f84f880-31b7-11eb-89ed-17a30eb35bfc.png)
如图，多次上传后仍失败

**Comment by happy888888** [comment]
获取 TENCENT_SECRET_ID，TENCENT_SECRET_KEY时是否使用的是子账户？？
[服务角色](https://console.cloud.tencent.com/cam/role)里是否有SCF_QcsRole、SLS_QcsRole？？

**Comment by 2498966969** [comment]
用的不是子账户，但有你说的那俩，请问怎么解决？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;星辰&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月28日(星期六) 晚上8:33
收件人:&nbsp;&quot;happy888888/BiliExp&quot;<BiliExp@noreply.github.com&gt;;
抄送:&nbsp;&quot;121W&quot;<2498966969@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [happy888888/BiliExp] Actions部署失败 (#99)

**Comment by happy888888** [comment]
1.在 [scf](https://cloud.tencent.com/product/scf) 看看是否开通了云函数
2. 在 [秘钥页面](https://console.cloud.tencent.com/cam/capi) 重新获取一次SECRET_ID和SECRET_KEY，注意不要使用子账户
![image](https://user-images.githubusercontent.com/67217225/100516371-669c5200-31be-11eb-960d-8e10397358f3.png)

**Comment by 2498966969** [comment]
问下怎么看是不是子账户？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "星辰"<notifications@github.com&gt;; 
发送时间: 2020年11月28日(星期六) 晚上9:13
收件人: "happy888888/BiliExp"<BiliExp@noreply.github.com&gt;; 
抄送: " "<2498966969@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [happy888888/BiliExp] Actions部署失败 (#99)





 
1.在 scf 看看是否开通了云函数
 2. 在 秘钥页面 重新获取一次SECRET_ID和SECRET_KEY，注意不要使用子账户

**Comment by happy888888** [comment]
> 问下怎么看是不是子账户？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "星辰"<notifications@github.com&gt;; 发送时间: 2020年11月28日(星期六) 晚上9:13 收件人: "happy888888/BiliExp"<BiliExp@noreply.github.com&gt;; 抄送: " "<2498966969@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [happy888888/BiliExp] Actions部署失败 (#99) 1.在 scf 看看是否开通了云函数 2. 在 秘钥页面 重新获取一次SECRET_ID和SECRET_KEY，注意不要使用子账户 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

看上图，创建秘钥时不要选择切换到子账户就行

**Comment by 2498966969** [comment]
好的，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "星辰"<notifications@github.com&gt;; 
发送时间: 2020年11月28日(星期六) 晚上9:20
收件人: "happy888888/BiliExp"<BiliExp@noreply.github.com&gt;; 
抄送: " "<2498966969@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [happy888888/BiliExp] Actions部署失败 (#99)





  
问下怎么看是不是子账户？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "星辰"<notifications@github.com&gt;; 发送时间: 2020年11月28日(星期六) 晚上9:13 收件人: "happy888888/BiliExp"<BiliExp@noreply.github.com&gt;; 抄送: " "<2498966969@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [happy888888/BiliExp] Actions部署失败 (#99) 1.在 scf 看看是否开通了云函数 2. 在 秘钥页面 重新获取一次SECRET_ID和SECRET_KEY，注意不要使用子账户 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
看上图，创建秘钥时不要选择切换到子账户就行

**Comment by 2498966969** [comment]
他怎么还是提示这个，跟原来一样

**Comment by happy888888** [comment]
> 他怎么还是提示这个，跟原来一样

重新获取了SECRET_ID和SECRET_KEY后也不行吗？

**Comment by happy888888** [comment]
如果不是非要使用云函数部署的话也可以直接使用actions来运行代码

**Comment by 2498966969** [comment]
嗯对------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;星辰&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月28日(星期六) 晚上9:30
收件人:&nbsp;&quot;happy888888/BiliExp&quot;<BiliExp@noreply.github.com&gt;;
抄送:&nbsp;&quot;121W&quot;<2498966969@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [happy888888/BiliExp] Actions部署失败 (#99)

**Comment by 2498966969** [comment]
主要觉得github不太稳------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;星辰&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月28日(星期六) 晚上9:45
收件人:&nbsp;&quot;happy888888/BiliExp&quot;<BiliExp@noreply.github.com&gt;;
抄送:&nbsp;&quot;121W&quot;<2498966969@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [happy888888/BiliExp] Actions部署失败 (#99)
